/* ============================================================
   SCRIPT MAESTRO ORACLE - MUEBLES DE LOS ALPES
   ORDENADO Y CONSTRAINTS ÚNICAS
   ============================================================ */

------------------------------------------------------------
-- 1) SEGURIDAD
------------------------------------------------------------
CREATE TABLE Rol (
  rol_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_nombre    VARCHAR2(60) NOT NULL,
  descripcion   VARCHAR2(200),
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  estado        VARCHAR2(20),
  CONSTRAINT uq_rol_nombre UNIQUE (rol_nombre),
  CONSTRAINT ck_rol_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Permiso (
  permiso_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        VARCHAR2(80) NOT NULL,
  descripcion   VARCHAR2(200) NOT NULL,
  modulo        VARCHAR2(60),
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  estado        VARCHAR2(20),
  CONSTRAINT uq_permiso_codigo UNIQUE (codigo),
  CONSTRAINT ck_permiso_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Rol_Permiso (
  rol_permiso_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id         NUMBER NOT NULL,
  permiso_id     NUMBER NOT NULL,
  es_permitido   NUMBER(1) DEFAULT 1 NOT NULL,
  created_at     TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  estado         VARCHAR2(20),
  CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (rol_id) REFERENCES Rol(rol_id),
  CONSTRAINT fk_rol_permiso_permiso FOREIGN KEY (permiso_id) REFERENCES Permiso(permiso_id),
  CONSTRAINT ck_rol_permiso_permitido CHECK (es_permitido IN (0,1)),
  CONSTRAINT ck_rol_permiso_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 2) RECURSOS HUMANOS (BASE)
------------------------------------------------------------
CREATE TABLE Departamento (
  depto_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(120) NOT NULL,
  descripcion  VARCHAR2(200),
  created_at   TIMESTAMP NOT NULL,
  updated_at   TIMESTAMP,
  estado       VARCHAR2(20),
  CONSTRAINT uq_departamento_nombre UNIQUE (nombre),
  CONSTRAINT ck_departamento_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Cargo (
  cargo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(120) NOT NULL,
  descripcion  VARCHAR2(200),
  created_at   TIMESTAMP NOT NULL,
  updated_at   TIMESTAMP,
  estado       VARCHAR2(20),
  CONSTRAINT uq_cargo_nombre UNIQUE (nombre),
  CONSTRAINT ck_cargo_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Rol_Empleado (
  rol_empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          VARCHAR2(120) NOT NULL,
  descripcion     VARCHAR2(200),
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT uq_rol_empleado_nombre UNIQUE (nombre),
  CONSTRAINT ck_rol_empleado_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Empleado (
  emp_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  depto_id         NUMBER NOT NULL,
  cargo_id         NUMBER NOT NULL,
  rol_empleado_id  NUMBER,
  nombres          VARCHAR2(120) NOT NULL,
  apellidos        VARCHAR2(120) NOT NULL,
  email            VARCHAR2(150),
  telefono         VARCHAR2(30),
  fecha_ingreso    DATE NOT NULL,
  salario_base     NUMBER(12,2),
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT uq_empleado_email UNIQUE (email),
  CONSTRAINT fk_empleado_departamento FOREIGN KEY (depto_id) REFERENCES Departamento(depto_id),
  CONSTRAINT fk_empleado_cargo FOREIGN KEY (cargo_id) REFERENCES Cargo(cargo_id),
  CONSTRAINT fk_empleado_rol_empleado FOREIGN KEY (rol_empleado_id) REFERENCES Rol_Empleado(rol_empleado_id),
  CONSTRAINT ck_empleado_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 3) CLIENTES
------------------------------------------------------------
CREATE TABLE Cliente (
  cli_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento VARCHAR2(30) NOT NULL,
  num_documento  VARCHAR2(30) NOT NULL,
  nit            VARCHAR2(30),
  nombres        VARCHAR2(120) NOT NULL,
  apellidos      VARCHAR2(120) NOT NULL,
  email          VARCHAR2(150) NOT NULL,
  tel_residencia VARCHAR2(30),
  tel_celular    VARCHAR2(30),
  direccion      VARCHAR2(250) NOT NULL,
  ciudad         VARCHAR2(80) NOT NULL,
  departamento   VARCHAR2(80) NOT NULL,
  pais           VARCHAR2(80) NOT NULL,
  profesion      VARCHAR2(80),
  created_at     TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  estado         VARCHAR2(20),
  CONSTRAINT uq_cliente_num_documento UNIQUE (num_documento),
  CONSTRAINT uq_cliente_nit UNIQUE (nit),
  CONSTRAINT uq_cliente_email UNIQUE (email),
  CONSTRAINT ck_cliente_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 4) PRODUCTOS E INVENTARIO (BASE)
------------------------------------------------------------
CREATE TABLE Unidad_Medida (
  unidad_medida_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo           VARCHAR2(20) NOT NULL,
  nombre           VARCHAR2(60) NOT NULL,
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT uq_unidad_medida_codigo UNIQUE (codigo),
  CONSTRAINT ck_unidad_medida_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Categoria (
  categoria_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre             VARCHAR2(120) NOT NULL,
  descripcion        VARCHAR2(400),
  categoria_padre_id NUMBER,
  created_at         TIMESTAMP NOT NULL,
  updated_at         TIMESTAMP,
  estado             VARCHAR2(20),
  CONSTRAINT uq_categoria_nombre UNIQUE (nombre),
  CONSTRAINT fk_categoria_padre FOREIGN KEY (categoria_padre_id) REFERENCES Categoria(categoria_id),
  CONSTRAINT ck_categoria_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Producto (
  producto_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referencia        VARCHAR2(60),
  nombre            VARCHAR2(150) NOT NULL,
  descripcion       VARCHAR2(1000),
  tipo              VARCHAR2(20) NOT NULL,
  material          VARCHAR2(120),
  alto_cm           NUMBER(10,2) NOT NULL,
  ancho_cm          NUMBER(10,2) NOT NULL,
  profundidad_cm    NUMBER(10,2) NOT NULL,
  color             VARCHAR2(60),
  peso_gramos       NUMBER NOT NULL,
  imagen_url        VARCHAR2(500),
  unidad_medida_id  NUMBER,
  categoria_id      NUMBER NOT NULL,
  lote_producto     VARCHAR2(60),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT uq_producto_referencia UNIQUE (referencia),
  CONSTRAINT fk_producto_unidad_medida FOREIGN KEY (unidad_medida_id) REFERENCES Unidad_Medida(unidad_medida_id),
  CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES Categoria(categoria_id),
  CONSTRAINT ck_producto_tipo CHECK (tipo IN ('INTERIOR','EXTERIOR')),
  CONSTRAINT ck_producto_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Inventario_Producto (
  inv_prod_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id      NUMBER NOT NULL,
  stock            NUMBER NOT NULL,
  stock_reservado  NUMBER DEFAULT 0 NOT NULL,
  stock_minimo     NUMBER,
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT fk_inventario_producto_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_inventario_producto_stock CHECK (stock >= 0 AND stock_reservado >= 0),
  CONSTRAINT ck_inventario_producto_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Movimiento_Inventario (
  mov_inv_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_prod_id    NUMBER NOT NULL,
  tipo_mov       VARCHAR2(20) NOT NULL,
  cantidad       NUMBER NOT NULL,
  motivo         VARCHAR2(200),
  referencia_id  NUMBER,
  mov_at         TIMESTAMP NOT NULL,
  created_at     TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  estado         VARCHAR2(20),
  CONSTRAINT fk_movimiento_inventario_inv_producto FOREIGN KEY (inv_prod_id) REFERENCES Inventario_Producto(inv_prod_id),
  CONSTRAINT ck_movimiento_inventario_tipo CHECK (tipo_mov IN ('ENTRADA','SALIDA','AJUSTE')),
  CONSTRAINT ck_movimiento_inventario_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Precio_Historico (
  precio_hist_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id      NUMBER NOT NULL,
  precio           NUMBER(12,2) NOT NULL,
  vigencia_inicio  DATE NOT NULL,
  vigencia_fin     DATE,
  motivo           VARCHAR2(200),
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT fk_precio_historico_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_precio_historico_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 5) PRODUCCIÓN
------------------------------------------------------------
CREATE TABLE Estado_Produccion (
  estado_produccion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo               VARCHAR2(30) NOT NULL,
  descripcion          VARCHAR2(200),
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT uq_estado_produccion_codigo UNIQUE (codigo),
  CONSTRAINT ck_estado_produccion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Materia_Prima (
  mp_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo           VARCHAR2(60) NOT NULL,
  nombre           VARCHAR2(150) NOT NULL,
  unidad_medida_id NUMBER NOT NULL,
  descripcion      VARCHAR2(500),
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT uq_materia_prima_codigo UNIQUE (codigo),
  CONSTRAINT fk_materia_prima_unidad_medida FOREIGN KEY (unidad_medida_id) REFERENCES Unidad_Medida(unidad_medida_id),
  CONSTRAINT ck_materia_prima_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Inventario_Materia_Prima (
  inv_mp_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mp_id         NUMBER NOT NULL,
  stock         NUMBER(12,3) NOT NULL,
  stock_minimo  NUMBER(12,3),
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  estado        VARCHAR2(20),
  CONSTRAINT fk_inventario_mp_materia_prima FOREIGN KEY (mp_id) REFERENCES Materia_Prima(mp_id),
  CONSTRAINT ck_inventario_mp_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Movimiento_Materia_Prima (
  mov_mp_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_mp_id    NUMBER NOT NULL,
  tipo_mov     VARCHAR2(20) NOT NULL,
  cantidad     NUMBER(12,3) NOT NULL,
  motivo       VARCHAR2(200),
  mov_at       TIMESTAMP NOT NULL,
  created_at   TIMESTAMP NOT NULL,
  updated_at   TIMESTAMP,
  estado       VARCHAR2(20),
  CONSTRAINT fk_movimiento_mp_inventario_mp FOREIGN KEY (inv_mp_id) REFERENCES Inventario_Materia_Prima(inv_mp_id),
  CONSTRAINT ck_movimiento_mp_tipo CHECK (tipo_mov IN ('ENTRADA','SALIDA','AJUSTE')),
  CONSTRAINT ck_movimiento_mp_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Plan_Produccion (
  plan_produccion_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id           NUMBER NOT NULL,
  cantidad              NUMBER NOT NULL,
  periodo_inicio        DATE NOT NULL,
  periodo_fin           DATE NOT NULL,
  tiempo_estimado_horas NUMBER(10,2),
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP,
  estado                VARCHAR2(20),
  CONSTRAINT fk_plan_produccion_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_plan_produccion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Orden_Produccion (
  orden_produccion_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  num_op               VARCHAR2(40) NOT NULL,
  producto_id          NUMBER NOT NULL,
  cantidad_planificada NUMBER NOT NULL,
  estado_produccion_id NUMBER NOT NULL,
  inicio_estimado      DATE,
  fin_estimado         DATE,
  inicio_real          DATE,
  fin_real             DATE,
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT uq_orden_produccion_num_op UNIQUE (num_op),
  CONSTRAINT fk_orden_produccion_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT fk_orden_produccion_estado FOREIGN KEY (estado_produccion_id) REFERENCES Estado_Produccion(estado_produccion_id),
  CONSTRAINT ck_orden_produccion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Lista_Materiales (
  lista_materiales_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id         NUMBER NOT NULL,
  version             VARCHAR2(20),
  vigencia_inicio     DATE,
  vigencia_fin        DATE,
  created_at          TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP,
  estado              VARCHAR2(20),
  CONSTRAINT fk_lista_materiales_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_lista_materiales_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Lista_Materiales_Detalle (
  lista_materiales_det_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lista_materiales_id     NUMBER NOT NULL,
  mp_id                   NUMBER NOT NULL,
  cantidad_requerida      NUMBER(12,3) NOT NULL,
  merma_pct               NUMBER(5,2),
  created_at              TIMESTAMP NOT NULL,
  updated_at              TIMESTAMP,
  estado                  VARCHAR2(20),
  CONSTRAINT fk_lm_detalle_lista_materiales FOREIGN KEY (lista_materiales_id) REFERENCES Lista_Materiales(lista_materiales_id),
  CONSTRAINT fk_lm_detalle_materia_prima FOREIGN KEY (mp_id) REFERENCES Materia_Prima(mp_id),
  CONSTRAINT ck_lm_detalle_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Herramienta (
  herramienta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo         VARCHAR2(60) NOT NULL,
  nombre         VARCHAR2(150) NOT NULL,
  descripcion    VARCHAR2(500),
  fecha_compra   DATE,
  created_at     TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  estado         VARCHAR2(20),
  CONSTRAINT uq_herramienta_codigo UNIQUE (codigo),
  CONSTRAINT ck_herramienta_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Mantenimiento_Herramienta (
  mantenimiento_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  herramienta_id      NUMBER NOT NULL,
  fecha_mantenimiento DATE NOT NULL,
  tipo                VARCHAR2(60),
  costo               NUMBER(12,2),
  observacion         VARCHAR2(500),
  created_at          TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP,
  estado              VARCHAR2(20),
  CONSTRAINT fk_mantenimiento_herramienta_herramienta FOREIGN KEY (herramienta_id) REFERENCES Herramienta(herramienta_id),
  CONSTRAINT ck_mantenimiento_herramienta_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Orden_Produccion_Tarea (
  op_tarea_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_produccion_id NUMBER NOT NULL,
  nombre_tarea        VARCHAR2(120) NOT NULL,
  orden               NUMBER DEFAULT 0,
  inicio_at           TIMESTAMP,
  fin_at              TIMESTAMP,
  emp_id_responsable  NUMBER,
  created_at          TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP,
  estado              VARCHAR2(20),
  CONSTRAINT fk_op_tarea_orden_produccion FOREIGN KEY (orden_produccion_id) REFERENCES Orden_Produccion(orden_produccion_id),
  CONSTRAINT fk_op_tarea_empleado_responsable FOREIGN KEY (emp_id_responsable) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_op_tarea_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Consumo_Materia_Prima (
  consumo_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_produccion_id NUMBER NOT NULL,
  mp_id               NUMBER NOT NULL,
  cantidad            NUMBER(12,3) NOT NULL,
  consumo_at          TIMESTAMP NOT NULL,
  created_at          TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP,
  estado              VARCHAR2(20),
  CONSTRAINT fk_consumo_mp_orden_produccion FOREIGN KEY (orden_produccion_id) REFERENCES Orden_Produccion(orden_produccion_id),
  CONSTRAINT fk_consumo_mp_materia_prima FOREIGN KEY (mp_id) REFERENCES Materia_Prima(mp_id),
  CONSTRAINT ck_consumo_mp_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Produccion_Resultados (
  resultado_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_produccion_id  NUMBER NOT NULL,
  unidades_buenas      NUMBER NOT NULL,
  unidades_merma       NUMBER DEFAULT 0 NOT NULL,
  registro_at          TIMESTAMP NOT NULL,
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT fk_produccion_resultados_orden FOREIGN KEY (orden_produccion_id) REFERENCES Orden_Produccion(orden_produccion_id),
  CONSTRAINT ck_produccion_resultados_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 6) COMPRAS A PROVEEDORES
------------------------------------------------------------
CREATE TABLE Proveedor (
  prov_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social  VARCHAR2(200) NOT NULL,
  nit           VARCHAR2(30) NOT NULL,
  email         VARCHAR2(150),
  telefono      VARCHAR2(30),
  direccion     VARCHAR2(250),
  ciudad        VARCHAR2(80),
  pais          VARCHAR2(80),
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  estado        VARCHAR2(20),
  CONSTRAINT uq_proveedor_nit UNIQUE (nit),
  CONSTRAINT uq_proveedor_email UNIQUE (email),
  CONSTRAINT ck_proveedor_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Estado_Orden_Compra (
  estado_oc_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        VARCHAR2(30) NOT NULL,
  descripcion   VARCHAR2(200),
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  estado        VARCHAR2(20),
  CONSTRAINT uq_estado_orden_compra_codigo UNIQUE (codigo),
  CONSTRAINT ck_estado_orden_compra_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Condicion_Pago (
  condicion_pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(80) NOT NULL,
  dias_credito      NUMBER DEFAULT 0 NOT NULL,
  descripcion       VARCHAR2(200),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT uq_condicion_pago_nombre UNIQUE (nombre),
  CONSTRAINT ck_condicion_pago_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Orden_Compra (
  orden_compra_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  num_oc             VARCHAR2(40),
  prov_id            NUMBER NOT NULL,
  estado_oc_id       NUMBER NOT NULL,
  condicion_pago_id  NUMBER NOT NULL,
  fecha_oc           DATE NOT NULL,
  subtotal           NUMBER(12,2) NOT NULL,
  impuesto           NUMBER(12,2) DEFAULT 0 NOT NULL,
  total              NUMBER(12,2) NOT NULL,
  observaciones      VARCHAR2(500),
  created_at         TIMESTAMP NOT NULL,
  updated_at         TIMESTAMP,
  estado             VARCHAR2(20),
  CONSTRAINT uq_orden_compra_num_oc UNIQUE (num_oc),
  CONSTRAINT fk_orden_compra_proveedor FOREIGN KEY (prov_id) REFERENCES Proveedor(prov_id),
  CONSTRAINT fk_orden_compra_estado FOREIGN KEY (estado_oc_id) REFERENCES Estado_Orden_Compra(estado_oc_id),
  CONSTRAINT fk_orden_compra_condicion_pago FOREIGN KEY (condicion_pago_id) REFERENCES Condicion_Pago(condicion_pago_id),
  CONSTRAINT ck_orden_compra_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Orden_Compra_Detalle (
  orden_compra_det_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_compra_id     NUMBER NOT NULL,
  mp_id               NUMBER NOT NULL,
  cantidad            NUMBER(12,3) NOT NULL,
  costo_unitario      NUMBER(12,2) NOT NULL,
  subtotal_linea      NUMBER(12,2) NOT NULL,
  created_at          TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP,
  estado              VARCHAR2(20),
  CONSTRAINT fk_oc_detalle_orden_compra FOREIGN KEY (orden_compra_id) REFERENCES Orden_Compra(orden_compra_id),
  CONSTRAINT fk_oc_detalle_materia_prima FOREIGN KEY (mp_id) REFERENCES Materia_Prima(mp_id),
  CONSTRAINT ck_oc_detalle_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Recepcion_Material (
  recepcion_material_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_compra_id       NUMBER NOT NULL,
  fecha_recepcion       DATE NOT NULL,
  emp_id_recibe         NUMBER,
  observaciones         VARCHAR2(500),
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP,
  estado                VARCHAR2(20),
  CONSTRAINT fk_recepcion_material_orden_compra FOREIGN KEY (orden_compra_id) REFERENCES Orden_Compra(orden_compra_id),
  CONSTRAINT fk_recepcion_material_empleado FOREIGN KEY (emp_id_recibe) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_recepcion_material_estado CHECK (estado IN ('ACTIVO','INACTIVO','RECIBIDO','PENDIENTE'))
);

CREATE TABLE Abastecimiento (
  abastecimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mp_id             NUMBER NOT NULL,
  cantidad_sugerida NUMBER(12,3) NOT NULL,
  motivo            VARCHAR2(200),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_abastecimiento_materia_prima FOREIGN KEY (mp_id) REFERENCES Materia_Prima(mp_id),
  CONSTRAINT ck_abastecimiento_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Cuenta_Pagar_Proveedor (
  cuenta_pagar_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prov_id           NUMBER NOT NULL,
  orden_compra_id   NUMBER NOT NULL,
  saldo             NUMBER(12,2) NOT NULL,
  fecha_vencimiento DATE,
  estado_cp         VARCHAR2(20),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_cxp_proveedor FOREIGN KEY (prov_id) REFERENCES Proveedor(prov_id),
  CONSTRAINT fk_cxp_orden_compra FOREIGN KEY (orden_compra_id) REFERENCES Orden_Compra(orden_compra_id),
  CONSTRAINT ck_cxp_estado_cp CHECK (estado_cp IN ('ABIERTA','CERRADA')),
  CONSTRAINT ck_cxp_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Pago_Proveedor (
  pago_proveedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuenta_pagar_id   NUMBER NOT NULL,
  monto             NUMBER(12,2) NOT NULL,
  fecha_pago        DATE NOT NULL,
  referencia        VARCHAR2(80),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_pago_proveedor_cuenta_pagar FOREIGN KEY (cuenta_pagar_id) REFERENCES Cuenta_Pagar_Proveedor(cuenta_pagar_id),
  CONSTRAINT ck_pago_proveedor_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Contrato_Proveedor (
  contrato_proveedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prov_id               NUMBER NOT NULL,
  titulo                VARCHAR2(120) NOT NULL,
  vigencia_inicio       DATE,
  vigencia_fin          DATE,
  url_documento         VARCHAR2(500),
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP,
  estado                VARCHAR2(20),
  CONSTRAINT fk_contrato_proveedor_proveedor FOREIGN KEY (prov_id) REFERENCES Proveedor(prov_id),
  CONSTRAINT ck_contrato_proveedor_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Expediente_Proveedor (
  expediente_proveedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prov_id                 NUMBER NOT NULL,
  tipo_documento          VARCHAR2(60) NOT NULL,
  url_documento           VARCHAR2(500) NOT NULL,
  fecha_documento         DATE,
  created_at              TIMESTAMP NOT NULL,
  updated_at              TIMESTAMP,
  estado                  VARCHAR2(20),
  CONSTRAINT fk_expediente_proveedor_proveedor FOREIGN KEY (prov_id) REFERENCES Proveedor(prov_id),
  CONSTRAINT ck_expediente_proveedor_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Historico_Precio_Materia_Prima_Proveedor (
  hist_mp_prov_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prov_id         NUMBER NOT NULL,
  mp_id           NUMBER NOT NULL,
  precio          NUMBER(12,2) NOT NULL,
  vigencia_inicio DATE NOT NULL,
  vigencia_fin    DATE,
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT fk_hist_precio_mp_proveedor FOREIGN KEY (prov_id) REFERENCES Proveedor(prov_id),
  CONSTRAINT fk_hist_precio_mp_materia_prima FOREIGN KEY (mp_id) REFERENCES Materia_Prima(mp_id),
  CONSTRAINT ck_hist_precio_mp_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Control_Calidad (
  control_calidad_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origen                VARCHAR2(30),
  orden_produccion_id   NUMBER,
  recepcion_material_id NUMBER,
  resultado             VARCHAR2(20),
  observacion           VARCHAR2(600),
  inspeccion_at         TIMESTAMP NOT NULL,
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP,
  estado                VARCHAR2(20),
  CONSTRAINT fk_control_calidad_orden_produccion FOREIGN KEY (orden_produccion_id) REFERENCES Orden_Produccion(orden_produccion_id),
  CONSTRAINT fk_control_calidad_recepcion_material FOREIGN KEY (recepcion_material_id) REFERENCES Recepcion_Material(recepcion_material_id),
  CONSTRAINT ck_control_calidad_origen CHECK (origen IN ('PRODUCCION','RECEPCION')),
  CONSTRAINT ck_control_calidad_resultado CHECK (resultado IN ('APROBADO','RECHAZADO')),
  CONSTRAINT ck_control_calidad_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 7) VENTAS
------------------------------------------------------------
CREATE TABLE Estado_Orden (
  estado_orden_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo          VARCHAR2(30) NOT NULL,
  descripcion     VARCHAR2(200),
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT uq_estado_orden_codigo UNIQUE (codigo),
  CONSTRAINT ck_estado_orden_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Metodo_Pago (
  metodo_pago_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre               VARCHAR2(60) NOT NULL,
  requiere_datos_extra NUMBER(1) DEFAULT 0 NOT NULL,
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT uq_metodo_pago_nombre UNIQUE (nombre),
  CONSTRAINT ck_metodo_pago_requiere_extra CHECK (requiere_datos_extra IN (0,1)),
  CONSTRAINT ck_metodo_pago_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Orden_Venta (
  orden_venta_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  num_orden                 VARCHAR2(40) NOT NULL,
  cli_id                    NUMBER NOT NULL,
  estado_orden_id           NUMBER NOT NULL,
  fecha_orden               TIMESTAMP NOT NULL,
  subtotal                  NUMBER(12,2) NOT NULL,
  descuento                 NUMBER(12,2) DEFAULT 0 NOT NULL,
  impuesto                  NUMBER(12,2) DEFAULT 0 NOT NULL,
  total                     NUMBER(12,2) NOT NULL,
  moneda                    VARCHAR2(10),
  direccion_envio_snapshot  VARCHAR2(250),
  observaciones             VARCHAR2(500),
  created_at                TIMESTAMP NOT NULL,
  updated_at                TIMESTAMP,
  estado                    VARCHAR2(20),
  CONSTRAINT uq_orden_venta_num_orden UNIQUE (num_orden),
  CONSTRAINT fk_orden_venta_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT fk_orden_venta_estado FOREIGN KEY (estado_orden_id) REFERENCES Estado_Orden(estado_orden_id),
  CONSTRAINT ck_orden_venta_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Orden_Venta_Detalle (
  orden_venta_det_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_venta_id           NUMBER NOT NULL,
  producto_id              NUMBER NOT NULL,
  cantidad                 NUMBER NOT NULL,
  precio_unitario_snapshot NUMBER(12,2) NOT NULL,
  subtotal_linea           NUMBER(12,2) NOT NULL,
  created_at               TIMESTAMP NOT NULL,
  updated_at               TIMESTAMP,
  estado                   VARCHAR2(20),
  CONSTRAINT fk_ov_detalle_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT fk_ov_detalle_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_ov_detalle_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_ov_detalle_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Pago (
  pago_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_venta_id  NUMBER NOT NULL,
  metodo_pago_id  NUMBER NOT NULL,
  monto           NUMBER(12,2) NOT NULL,
  estado_pago     VARCHAR2(20),
  referencia      VARCHAR2(80),
  pago_at         TIMESTAMP NOT NULL,
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT fk_pago_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT fk_pago_metodo_pago FOREIGN KEY (metodo_pago_id) REFERENCES Metodo_Pago(metodo_pago_id),
  CONSTRAINT ck_pago_estado_pago CHECK (estado_pago IN ('APROBADO','RECHAZADO','PENDIENTE')),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Cuotas_Pago (
  cuota_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pago_id            NUMBER NOT NULL,
  num_cuota          NUMBER NOT NULL,
  monto_cuota        NUMBER(12,2) NOT NULL,
  fecha_vencimiento  DATE,
  fecha_pago         DATE,
  created_at         TIMESTAMP NOT NULL,
  updated_at         TIMESTAMP,
  estado             VARCHAR2(20),
  CONSTRAINT fk_cuotas_pago_pago FOREIGN KEY (pago_id) REFERENCES Pago(pago_id),
  CONSTRAINT ck_cuotas_pago_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Factura (
  factura_id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_venta_id                 NUMBER NOT NULL,
  num_factura                    VARCHAR2(40) NOT NULL,
  fecha_emision                  DATE NOT NULL,
  nit_facturacion                VARCHAR2(30),
  direccion_facturacion_snapshot VARCHAR2(250),
  total_factura_snapshot         NUMBER(12,2) NOT NULL,
  created_at                     TIMESTAMP NOT NULL,
  updated_at                     TIMESTAMP,
  estado                         VARCHAR2(20),
  CONSTRAINT uq_factura_num_factura UNIQUE (num_factura),
  CONSTRAINT fk_factura_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT ck_factura_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Factura_Detalle (
  factura_det_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factura_id               NUMBER NOT NULL,
  producto_id              NUMBER NOT NULL,
  cantidad                 NUMBER NOT NULL,
  precio_unitario_snapshot NUMBER(12,2) NOT NULL,
  total_linea              NUMBER(12,2) NOT NULL,
  created_at               TIMESTAMP NOT NULL,
  updated_at               TIMESTAMP,
  estado                   VARCHAR2(20),
  CONSTRAINT fk_factura_detalle_factura FOREIGN KEY (factura_id) REFERENCES Factura(factura_id),
  CONSTRAINT fk_factura_detalle_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_factura_detalle_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Devolucion (
  devolucion_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_venta_id     NUMBER NOT NULL,
  cli_id             NUMBER NOT NULL,
  motivo             VARCHAR2(400) NOT NULL,
  estado_devolucion  VARCHAR2(20) NOT NULL,
  solicitud_at       TIMESTAMP NOT NULL,
  resolucion_at      TIMESTAMP,
  created_at         TIMESTAMP NOT NULL,
  updated_at         TIMESTAMP,
  estado             VARCHAR2(20),
  CONSTRAINT fk_devolucion_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT fk_devolucion_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT ck_devolucion_estado_devolucion CHECK (estado_devolucion IN ('SOLICITADA','APROBADA','RECHAZADA','RECIBIDA')),
  CONSTRAINT ck_devolucion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 8) CLIENTES / USUARIOS (DEPENDIENTES)
------------------------------------------------------------
CREATE TABLE Usuario (
  usu_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         VARCHAR2(100) NOT NULL,
  password_hash    VARCHAR2(255) NOT NULL,
  email            VARCHAR2(150),
  telefono         VARCHAR2(30),
  rol_id           NUMBER NOT NULL,
  cli_id           NUMBER,
  emp_id           NUMBER,
  ultimo_login_at  TIMESTAMP,
  bloqueado_hasta  TIMESTAMP,
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT uq_usuario_username UNIQUE (username),
  CONSTRAINT uq_usuario_email UNIQUE (email),
  CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES Rol(rol_id),
  CONSTRAINT fk_usuario_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT fk_usuario_empleado FOREIGN KEY (emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_usuario_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Sesion (
  sesion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usu_id      NUMBER NOT NULL,
  token_hash  VARCHAR2(255) NOT NULL,
  ip          VARCHAR2(45),
  user_agent  VARCHAR2(300),
  inicio_at   TIMESTAMP NOT NULL,
  fin_at      TIMESTAMP,
  created_at  TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP,
  CONSTRAINT uq_sesion_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_sesion_usuario FOREIGN KEY (usu_id) REFERENCES Usuario(usu_id)
);

CREATE TABLE Historial_Cambio_Contrasena (
  hc_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usu_id      NUMBER NOT NULL,
  cambio_at   TIMESTAMP NOT NULL,
  motivo      VARCHAR2(120),
  ip          VARCHAR2(45),
  created_at  TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP,
  CONSTRAINT fk_hist_contrasena_usuario FOREIGN KEY (usu_id) REFERENCES Usuario(usu_id)
);

CREATE TABLE Historial_Compra (
  hist_compra_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_id               NUMBER NOT NULL,
  orden_venta_id       NUMBER NOT NULL,
  compra_at            TIMESTAMP NOT NULL,
  monto_total_snapshot NUMBER(12,2) NOT NULL,
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT fk_historial_compra_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT fk_historial_compra_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT ck_historial_compra_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Preferencia_Cliente (
  pref_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_id            NUMBER NOT NULL,
  categoria_id      NUMBER NOT NULL,
  peso_preferencia  NUMBER(5,2) DEFAULT 1,
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_preferencia_cliente_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT fk_preferencia_cliente_categoria FOREIGN KEY (categoria_id) REFERENCES Categoria(categoria_id),
  CONSTRAINT ck_preferencia_cliente_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Carrito (
  carrito_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_id             NUMBER NOT NULL,
  estado_carrito     VARCHAR2(20),
  ultimo_calculo_at  TIMESTAMP,
  created_at         TIMESTAMP NOT NULL,
  updated_at         TIMESTAMP,
  estado             VARCHAR2(20),
  CONSTRAINT fk_carrito_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT ck_carrito_estado_carrito CHECK (estado_carrito IN ('ACTIVO','CONVERTIDO')),
  CONSTRAINT ck_carrito_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Carrito_Detalle (
  carrito_det_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrito_id               NUMBER NOT NULL,
  producto_id              NUMBER NOT NULL,
  cantidad                 NUMBER NOT NULL,
  precio_unitario_snapshot NUMBER(12,2),
  created_at               TIMESTAMP NOT NULL,
  updated_at               TIMESTAMP,
  estado                   VARCHAR2(20),
  CONSTRAINT fk_carrito_detalle_carrito FOREIGN KEY (carrito_id) REFERENCES Carrito(carrito_id),
  CONSTRAINT fk_carrito_detalle_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_carrito_detalle_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_carrito_detalle_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Lista_Deseos (
  lista_deseos_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_id          NUMBER NOT NULL,
  producto_id     NUMBER NOT NULL,
  nota            VARCHAR2(200),
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT fk_lista_deseos_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT fk_lista_deseos_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_lista_deseos_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Resena_Comentario (
  resena_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_id       NUMBER NOT NULL,
  producto_id  NUMBER NOT NULL,
  calificacion NUMBER,
  comentario   VARCHAR2(1000),
  resena_at    TIMESTAMP NOT NULL,
  created_at   TIMESTAMP NOT NULL,
  updated_at   TIMESTAMP,
  estado       VARCHAR2(20),
  CONSTRAINT fk_resena_cliente FOREIGN KEY (cli_id) REFERENCES Cliente(cli_id),
  CONSTRAINT fk_resena_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5),
  CONSTRAINT ck_resena_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE FAQ (
  faq_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pregunta    VARCHAR2(400) NOT NULL,
  respuesta   VARCHAR2(2000) NOT NULL,
  orden       NUMBER DEFAULT 0,
  created_at  TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP,
  estado      VARCHAR2(20),
  CONSTRAINT ck_faq_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 9) ENVÍOS Y LOGÍSTICA
------------------------------------------------------------
CREATE TABLE Estado_Envio (
  estado_envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo          VARCHAR2(30) NOT NULL,
  descripcion     VARCHAR2(200),
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT uq_estado_envio_codigo UNIQUE (codigo),
  CONSTRAINT ck_estado_envio_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Tipo_Entrega (
  tipo_entrega_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          VARCHAR2(60) NOT NULL,
  descripcion     VARCHAR2(200),
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT uq_tipo_entrega_nombre UNIQUE (nombre),
  CONSTRAINT ck_tipo_entrega_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Zona_Envio (
  zona_envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR2(80) NOT NULL,
  pais          VARCHAR2(80),
  departamento  VARCHAR2(80),
  ciudad        VARCHAR2(80),
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  estado        VARCHAR2(20),
  CONSTRAINT uq_zona_envio_nombre UNIQUE (nombre),
  CONSTRAINT ck_zona_envio_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Politica_Envio (
  politica_envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo            VARCHAR2(120) NOT NULL,
  descripcion       VARCHAR2(2000) NOT NULL,
  vigencia_inicio   DATE,
  vigencia_fin      DATE,
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT ck_politica_envio_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Regla_Envio_Gratis (
  regla_envio_gratis_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zona_envio_id         NUMBER NOT NULL,
  monto_minimo          NUMBER(12,2),
  peso_max_kg           NUMBER(10,2),
  vigencia_inicio       DATE,
  vigencia_fin          DATE,
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP,
  estado                VARCHAR2(20),
  CONSTRAINT fk_regla_envio_gratis_zona FOREIGN KEY (zona_envio_id) REFERENCES Zona_Envio(zona_envio_id),
  CONSTRAINT ck_regla_envio_gratis_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Tarifa_Envio (
  tarifa_envio_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zona_envio_id    NUMBER NOT NULL,
  tipo_entrega_id  NUMBER NOT NULL,
  peso_desde_kg    NUMBER(10,2) NOT NULL,
  peso_hasta_kg    NUMBER(10,2) NOT NULL,
  costo            NUMBER(12,2) NOT NULL,
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT fk_tarifa_envio_zona FOREIGN KEY (zona_envio_id) REFERENCES Zona_Envio(zona_envio_id),
  CONSTRAINT fk_tarifa_envio_tipo_entrega FOREIGN KEY (tipo_entrega_id) REFERENCES Tipo_Entrega(tipo_entrega_id),
  CONSTRAINT ck_tarifa_envio_peso CHECK (peso_desde_kg <= peso_hasta_kg),
  CONSTRAINT ck_tarifa_envio_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Vehiculo (
  vehiculo_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placa         VARCHAR2(20) NOT NULL,
  tipo          VARCHAR2(40),
  capacidad_kg  NUMBER(10,2),
  capacidad_m3  NUMBER(10,2),
  activo        NUMBER(1) DEFAULT 1 NOT NULL,
  created_at    TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_vehiculo_placa UNIQUE (placa),
  CONSTRAINT ck_vehiculo_activo CHECK (activo IN (0,1))
);

CREATE TABLE Ruta_Entrega (
  ruta_entrega_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehiculo_id     NUMBER NOT NULL,
  fecha_ruta      DATE NOT NULL,
  descripcion     VARCHAR2(200),
  estado_ruta     VARCHAR2(20),
  created_at      TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  estado          VARCHAR2(20),
  CONSTRAINT fk_ruta_entrega_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES Vehiculo(vehiculo_id),
  CONSTRAINT ck_ruta_entrega_estado_ruta CHECK (estado_ruta IN ('PLANIFICADA','EN_CURSO','CERRADA')),
  CONSTRAINT ck_ruta_entrega_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Envio (
  envio_id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_venta_id              NUMBER NOT NULL,
  estado_envio_id             NUMBER NOT NULL,
  tipo_entrega_id             NUMBER NOT NULL,
  zona_envio_id               NUMBER NOT NULL,
  ruta_entrega_id             NUMBER,
  direccion_entrega_snapshot  VARCHAR2(250) NOT NULL,
  costo_envio_snapshot        NUMBER(12,2) NOT NULL,
  fecha_envio                 DATE,
  fecha_entrega_estimada      DATE,
  fecha_entrega_real          DATE,
  tracking_codigo             VARCHAR2(60),
  created_at                  TIMESTAMP NOT NULL,
  updated_at                  TIMESTAMP,
  estado                      VARCHAR2(20),
  CONSTRAINT uq_envio_tracking_codigo UNIQUE (tracking_codigo),
  CONSTRAINT fk_envio_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT fk_envio_estado_envio FOREIGN KEY (estado_envio_id) REFERENCES Estado_Envio(estado_envio_id),
  CONSTRAINT fk_envio_tipo_entrega FOREIGN KEY (tipo_entrega_id) REFERENCES Tipo_Entrega(tipo_entrega_id),
  CONSTRAINT fk_envio_zona_envio FOREIGN KEY (zona_envio_id) REFERENCES Zona_Envio(zona_envio_id),
  CONSTRAINT fk_envio_ruta_entrega FOREIGN KEY (ruta_entrega_id) REFERENCES Ruta_Entrega(ruta_entrega_id),
  CONSTRAINT ck_envio_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Seguimiento_Envio (
  seg_envio_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id         NUMBER NOT NULL,
  estado_envio_id  NUMBER NOT NULL,
  evento_at        TIMESTAMP NOT NULL,
  ubicacion_texto  VARCHAR2(200),
  observacion      VARCHAR2(400),
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT fk_seguimiento_envio_envio FOREIGN KEY (envio_id) REFERENCES Envio(envio_id),
  CONSTRAINT fk_seguimiento_envio_estado FOREIGN KEY (estado_envio_id) REFERENCES Estado_Envio(estado_envio_id),
  CONSTRAINT ck_seguimiento_envio_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 10) MARKETING
------------------------------------------------------------
CREATE TABLE Tipo_Promocion (
  tipo_promocion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(80) NOT NULL,
  descripcion       VARCHAR2(200),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT uq_tipo_promocion_nombre UNIQUE (nombre),
  CONSTRAINT ck_tipo_promocion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Promocion (
  promocion_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_promocion_id NUMBER NOT NULL,
  nombre            VARCHAR2(120) NOT NULL,
  descripcion       VARCHAR2(500),
  vigencia_inicio   DATE NOT NULL,
  vigencia_fin      DATE NOT NULL,
  prioridad         NUMBER DEFAULT 0 NOT NULL,
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_promocion_tipo_promocion FOREIGN KEY (tipo_promocion_id) REFERENCES Tipo_Promocion(tipo_promocion_id),
  CONSTRAINT ck_promocion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Promocion_Producto (
  promocion_producto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promocion_id          NUMBER NOT NULL,
  producto_id           NUMBER NOT NULL,
  limite_unidades       NUMBER,
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP,
  estado                VARCHAR2(20),
  CONSTRAINT fk_promocion_producto_promocion FOREIGN KEY (promocion_id) REFERENCES Promocion(promocion_id),
  CONSTRAINT fk_promocion_producto_producto FOREIGN KEY (producto_id) REFERENCES Producto(producto_id),
  CONSTRAINT ck_promocion_producto_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Regla_Promocion (
  regla_promocion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promocion_id         NUMBER NOT NULL,
  min_compra           NUMBER(12,2),
  min_items            NUMBER,
  aplica_tipo_producto VARCHAR2(20),
  tope_descuento       NUMBER(12,2),
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT fk_regla_promocion_promocion FOREIGN KEY (promocion_id) REFERENCES Promocion(promocion_id),
  CONSTRAINT ck_regla_promocion_tipo_producto CHECK (aplica_tipo_producto IS NULL OR aplica_tipo_producto IN ('INTERIOR','EXTERIOR')),
  CONSTRAINT ck_regla_promocion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Campana_Marketing (
  campana_marketing_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre               VARCHAR2(120) NOT NULL,
  canal                VARCHAR2(60),
  presupuesto          NUMBER(12,2),
  inicio               DATE NOT NULL,
  fin                  DATE NOT NULL,
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT ck_campana_marketing_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Cupon (
  cupon_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo                 VARCHAR2(40) NOT NULL,
  descripcion            VARCHAR2(200),
  vigencia_inicio        DATE NOT NULL,
  vigencia_fin           DATE NOT NULL,
  limite_uso_total       NUMBER,
  limite_uso_por_cliente NUMBER,
  usos_actuales          NUMBER DEFAULT 0 NOT NULL,
  created_at             TIMESTAMP NOT NULL,
  updated_at             TIMESTAMP,
  estado                 VARCHAR2(20),
  CONSTRAINT uq_cupon_codigo UNIQUE (codigo),
  CONSTRAINT ck_cupon_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Historial_Promocion (
  historial_promocion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_venta_id           NUMBER NOT NULL,
  promocion_id             NUMBER NOT NULL,
  monto_descuento_snapshot NUMBER(12,2) NOT NULL,
  created_at               TIMESTAMP NOT NULL,
  updated_at               TIMESTAMP,
  estado                   VARCHAR2(20),
  CONSTRAINT fk_historial_promocion_orden_venta FOREIGN KEY (orden_venta_id) REFERENCES Orden_Venta(orden_venta_id),
  CONSTRAINT fk_historial_promocion_promocion FOREIGN KEY (promocion_id) REFERENCES Promocion(promocion_id),
  CONSTRAINT ck_historial_promocion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

------------------------------------------------------------
-- 11) RECURSOS HUMANOS (DEPENDIENTES)
------------------------------------------------------------
CREATE TABLE Historial_Laboral (
  historial_laboral_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id               NUMBER NOT NULL,
  fecha_cambio         DATE NOT NULL,
  tipo_cambio          VARCHAR2(60) NOT NULL,
  detalle              VARCHAR2(500),
  created_at           TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  estado               VARCHAR2(20),
  CONSTRAINT fk_historial_laboral_empleado FOREIGN KEY (emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_historial_laboral_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Expediente_Empleado (
  expediente_empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id                 NUMBER NOT NULL,
  tipo_documento         VARCHAR2(60) NOT NULL,
  url_documento          VARCHAR2(500) NOT NULL,
  fecha_documento        DATE,
  created_at             TIMESTAMP NOT NULL,
  updated_at             TIMESTAMP,
  estado                 VARCHAR2(20),
  CONSTRAINT fk_expediente_empleado_empleado FOREIGN KEY (emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_expediente_empleado_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Evaluacion (
  evaluacion_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id           NUMBER NOT NULL,
  evaluador_emp_id NUMBER,
  fecha_eval       DATE NOT NULL,
  puntuacion       NUMBER(5,2) NOT NULL,
  comentarios      VARCHAR2(800),
  created_at       TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  estado           VARCHAR2(20),
  CONSTRAINT fk_evaluacion_empleado FOREIGN KEY (emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT fk_evaluacion_evaluador FOREIGN KEY (evaluador_emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_evaluacion_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Nomina (
  nomina_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id         NUMBER NOT NULL,
  periodo_inicio DATE NOT NULL,
  periodo_fin    DATE NOT NULL,
  monto_bruto    NUMBER(12,2) NOT NULL,
  monto_neto     NUMBER(12,2) NOT NULL,
  fecha_pago     DATE NOT NULL,
  created_at     TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  estado         VARCHAR2(20),
  CONSTRAINT fk_nomina_empleado FOREIGN KEY (emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_nomina_estado CHECK (estado IN ('ACTIVO','INACTIVO','PENDIENTE','PAGADO'))
);

CREATE TABLE Nomina_Detalle (
  nomina_detalle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nomina_id         NUMBER NOT NULL,
  tipo              VARCHAR2(20) NOT NULL,
  concepto          VARCHAR2(120) NOT NULL,
  monto             NUMBER(12,2) NOT NULL,
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_nomina_detalle_nomina FOREIGN KEY (nomina_id) REFERENCES Nomina(nomina_id),
  CONSTRAINT ck_nomina_detalle_tipo CHECK (tipo IN ('DEDUCCION','BONO')),
  CONSTRAINT ck_nomina_detalle_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE Incidente_Laboral (
  incidente_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id            NUMBER NOT NULL,
  fecha_incidente   DATE NOT NULL,
  descripcion       VARCHAR2(800) NOT NULL,
  gravedad          VARCHAR2(20),
  acciones_tomadas  VARCHAR2(800),
  created_at        TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  estado            VARCHAR2(20),
  CONSTRAINT fk_incidente_laboral_empleado FOREIGN KEY (emp_id) REFERENCES Empleado(emp_id),
  CONSTRAINT ck_incidente_laboral_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);