CREATE OR REPLACE PACKAGE BODY PKG_FACTURA AS

  PROCEDURE SP_INSERTAR_FACTURA(
    P_ORDEN_VENTA_ID              IN  FACTURA.ORDEN_VENTA_ID%TYPE,
    P_NUM_FACTURA                 IN  FACTURA.NUM_FACTURA%TYPE,
    P_FECHA_EMISION               IN  FACTURA.FECHA_EMISION%TYPE,
    P_NIT_FACTURACION             IN  FACTURA.NIT_FACTURACION%TYPE,
    P_DIRECCION_FACTURACION_SNAPSHOT IN FACTURA.DIRECCION_FACTURACION_SNAPSHOT%TYPE,
    P_TOTAL_FACTURA_SNAPSHOT      IN  FACTURA.TOTAL_FACTURA_SNAPSHOT%TYPE,
    P_FACTURA_ID                  OUT FACTURA.FACTURA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO FACTURA (
      ORDEN_VENTA_ID,
      NUM_FACTURA,
      FECHA_EMISION,
      NIT_FACTURACION,
      DIRECCION_FACTURACION_SNAPSHOT,
      TOTAL_FACTURA_SNAPSHOT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_ORDEN_VENTA_ID,
      P_NUM_FACTURA,
      P_FECHA_EMISION,
      P_NIT_FACTURACION,
      P_DIRECCION_FACTURACION_SNAPSHOT,
      P_TOTAL_FACTURA_SNAPSHOT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING FACTURA_ID INTO P_FACTURA_ID;
  END SP_INSERTAR_FACTURA;

  PROCEDURE SP_ACTUALIZAR_FACTURA(
    P_FACTURA_ID                  IN  FACTURA.FACTURA_ID%TYPE,
    P_ORDEN_VENTA_ID              IN  FACTURA.ORDEN_VENTA_ID%TYPE,
    P_NUM_FACTURA                 IN  FACTURA.NUM_FACTURA%TYPE,
    P_FECHA_EMISION               IN  FACTURA.FECHA_EMISION%TYPE,
    P_NIT_FACTURACION             IN  FACTURA.NIT_FACTURACION%TYPE,
    P_DIRECCION_FACTURACION_SNAPSHOT IN FACTURA.DIRECCION_FACTURACION_SNAPSHOT%TYPE,
    P_TOTAL_FACTURA_SNAPSHOT      IN  FACTURA.TOTAL_FACTURA_SNAPSHOT%TYPE
  ) AS
  BEGIN
    UPDATE FACTURA
    SET ORDEN_VENTA_ID              = P_ORDEN_VENTA_ID,
        NUM_FACTURA                 = P_NUM_FACTURA,
        FECHA_EMISION               = P_FECHA_EMISION,
        NIT_FACTURACION             = P_NIT_FACTURACION,
        DIRECCION_FACTURACION_SNAPSHOT = P_DIRECCION_FACTURACION_SNAPSHOT,
        TOTAL_FACTURA_SNAPSHOT      = P_TOTAL_FACTURA_SNAPSHOT,
        UPDATED_AT                  = SYSTIMESTAMP
    WHERE FACTURA_ID = P_FACTURA_ID;
  END SP_ACTUALIZAR_FACTURA;

  PROCEDURE SP_ELIMINAR_FACTURA(
    P_FACTURA_ID IN FACTURA.FACTURA_ID%TYPE
  ) AS
  BEGIN
    UPDATE FACTURA
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE FACTURA_ID = P_FACTURA_ID;
  END SP_ELIMINAR_FACTURA;

  PROCEDURE SP_OBTENER_FACTURA(
    P_FACTURA_ID IN  FACTURA.FACTURA_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT FACTURA_ID,
             ORDEN_VENTA_ID,
             NUM_FACTURA,
             FECHA_EMISION,
             NIT_FACTURACION,
             DIRECCION_FACTURACION_SNAPSHOT,
             TOTAL_FACTURA_SNAPSHOT,
             ESTADO
      FROM FACTURA
      WHERE FACTURA_ID = P_FACTURA_ID;
  END SP_OBTENER_FACTURA;

  PROCEDURE SP_LISTAR_FACTURAS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT FACTURA_ID,
             NUM_FACTURA,
             ORDEN_VENTA_ID,
             FECHA_EMISION,
             TOTAL_FACTURA_SNAPSHOT,
             ESTADO
      FROM FACTURA
      WHERE ESTADO = 'ACTIVO'
      ORDER BY FECHA_EMISION DESC;
  END SP_LISTAR_FACTURAS;

  PROCEDURE SP_BUSCAR_FACTURAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT FACTURA_ID,
             NUM_FACTURA,
             ORDEN_VENTA_ID,
             FECHA_EMISION,
             TOTAL_FACTURA_SNAPSHOT,
             ESTADO
      FROM FACTURA
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'NUM_FACTURA'    AND UPPER(NUM_FACTURA) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'NIT_FACTURACION' AND UPPER(NIT_FACTURACION) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY FECHA_EMISION DESC;
  END SP_BUSCAR_FACTURAS;

END PKG_FACTURA;
/
