CREATE OR REPLACE PACKAGE PKG_FACTURA AS

  PROCEDURE SP_INSERTAR_FACTURA(
    P_ORDEN_VENTA_ID              IN  FACTURA.ORDEN_VENTA_ID%TYPE,
    P_NUM_FACTURA                 IN  FACTURA.NUM_FACTURA%TYPE,
    P_FECHA_EMISION               IN  FACTURA.FECHA_EMISION%TYPE,
    P_NIT_FACTURACION             IN  FACTURA.NIT_FACTURACION%TYPE,
    P_DIRECCION_FACTURACION_SNAPSHOT IN FACTURA.DIRECCION_FACTURACION_SNAPSHOT%TYPE,
    P_TOTAL_FACTURA_SNAPSHOT      IN  FACTURA.TOTAL_FACTURA_SNAPSHOT%TYPE,
    P_FACTURA_ID                  OUT FACTURA.FACTURA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_FACTURA(
    P_FACTURA_ID                  IN  FACTURA.FACTURA_ID%TYPE,
    P_ORDEN_VENTA_ID              IN  FACTURA.ORDEN_VENTA_ID%TYPE,
    P_NUM_FACTURA                 IN  FACTURA.NUM_FACTURA%TYPE,
    P_FECHA_EMISION               IN  FACTURA.FECHA_EMISION%TYPE,
    P_NIT_FACTURACION             IN  FACTURA.NIT_FACTURACION%TYPE,
    P_DIRECCION_FACTURACION_SNAPSHOT IN FACTURA.DIRECCION_FACTURACION_SNAPSHOT%TYPE,
    P_TOTAL_FACTURA_SNAPSHOT      IN  FACTURA.TOTAL_FACTURA_SNAPSHOT%TYPE
  );

  PROCEDURE SP_ELIMINAR_FACTURA(
    P_FACTURA_ID IN FACTURA.FACTURA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_FACTURA(
    P_FACTURA_ID IN  FACTURA.FACTURA_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_FACTURAS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_FACTURAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_FACTURA;
/
