/* ============================================
   PACKAGE SPEC
   ============================================ */

CREATE OR REPLACE PACKAGE PKG_CARGO AS

  PROCEDURE SP_INSERTAR_CARGO(
    P_NOMBRE IN CARGO.NOMBRE%TYPE,
    P_DESCRIPCION IN CARGO.DESCRIPCION%TYPE,
    P_CARGO_ID OUT CARGO.CARGO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CARGO(
    P_CARGO_ID IN CARGO.CARGO_ID%TYPE,
    P_NOMBRE IN CARGO.NOMBRE%TYPE,
    P_DESCRIPCION IN CARGO.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_CARGO(
    P_CARGO_ID IN CARGO.CARGO_ID%TYPE
  );

  PROCEDURE SP_LISTAR_CARGOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_OBTENER_CARGO(
    P_CARGO_ID IN CARGO.CARGO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_CARGO;
/


/* ============================================
   PACKAGE BODY
   ============================================ */

CREATE OR REPLACE PACKAGE BODY PKG_CARGO AS

  PROCEDURE SP_INSERTAR_CARGO(
    P_NOMBRE IN CARGO.NOMBRE%TYPE,
    P_DESCRIPCION IN CARGO.DESCRIPCION%TYPE,
    P_CARGO_ID OUT CARGO.CARGO_ID%TYPE
  ) AS
  BEGIN

    INSERT INTO CARGO(
      NOMBRE,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    )
    VALUES(
      P_NOMBRE,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CARGO_ID INTO P_CARGO_ID;

  END SP_INSERTAR_CARGO;


  PROCEDURE SP_ACTUALIZAR_CARGO(
    P_CARGO_ID IN CARGO.CARGO_ID%TYPE,
    P_NOMBRE IN CARGO.NOMBRE%TYPE,
    P_DESCRIPCION IN CARGO.DESCRIPCION%TYPE
  ) AS
  BEGIN

    UPDATE CARGO
       SET NOMBRE = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT = SYSTIMESTAMP
     WHERE CARGO_ID = P_CARGO_ID;

  END SP_ACTUALIZAR_CARGO;


  PROCEDURE SP_ELIMINAR_CARGO(
    P_CARGO_ID IN CARGO.CARGO_ID%TYPE
  ) AS
  BEGIN

    UPDATE CARGO
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE CARGO_ID = P_CARGO_ID;

  END SP_ELIMINAR_CARGO;


  PROCEDURE SP_LISTAR_CARGOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT CARGO_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM CARGO
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;

  END SP_LISTAR_CARGOS;


  PROCEDURE SP_OBTENER_CARGO(
    P_CARGO_ID IN CARGO.CARGO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT *
        FROM CARGO
       WHERE CARGO_ID = P_CARGO_ID;

  END SP_OBTENER_CARGO;

END PKG_CARGO;
/