CREATE OR REPLACE PACKAGE PKG_POLITICA_ENVIO AS

  PROCEDURE SP_INSERTAR_POLITICA_ENVIO(
    P_TITULO             IN POLITICA_ENVIO.TITULO%TYPE,
    P_DESCRIPCION        IN POLITICA_ENVIO.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO    IN POLITICA_ENVIO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN       IN POLITICA_ENVIO.VIGENCIA_FIN%TYPE,
    P_POLITICA_ENVIO_ID  OUT POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_POLITICA_ENVIO(
    P_POLITICA_ENVIO_ID  IN POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE,
    P_TITULO             IN POLITICA_ENVIO.TITULO%TYPE,
    P_DESCRIPCION        IN POLITICA_ENVIO.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO    IN POLITICA_ENVIO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN       IN POLITICA_ENVIO.VIGENCIA_FIN%TYPE
  );

  PROCEDURE SP_ELIMINAR_POLITICA_ENVIO(
    P_POLITICA_ENVIO_ID IN POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_POLITICA_ENVIO(
    P_POLITICA_ENVIO_ID IN POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE,
    P_CURSOR            OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_POLITICAS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_POLITICAS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_POLITICA_ENVIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_POLITICA_ENVIO AS

  PROCEDURE SP_INSERTAR_POLITICA_ENVIO(
    P_TITULO             IN POLITICA_ENVIO.TITULO%TYPE,
    P_DESCRIPCION        IN POLITICA_ENVIO.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO    IN POLITICA_ENVIO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN       IN POLITICA_ENVIO.VIGENCIA_FIN%TYPE,
    P_POLITICA_ENVIO_ID  OUT POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO POLITICA_ENVIO (
      TITULO,
      DESCRIPCION,
      VIGENCIA_INICIO,
      VIGENCIA_FIN,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_TITULO,
      P_DESCRIPCION,
      P_VIGENCIA_INICIO,
      P_VIGENCIA_FIN,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING POLITICA_ENVIO_ID INTO P_POLITICA_ENVIO_ID;
  END SP_INSERTAR_POLITICA_ENVIO;

  PROCEDURE SP_ACTUALIZAR_POLITICA_ENVIO(
    P_POLITICA_ENVIO_ID  IN POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE,
    P_TITULO             IN POLITICA_ENVIO.TITULO%TYPE,
    P_DESCRIPCION        IN POLITICA_ENVIO.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO    IN POLITICA_ENVIO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN       IN POLITICA_ENVIO.VIGENCIA_FIN%TYPE
  ) AS
  BEGIN
    UPDATE POLITICA_ENVIO
       SET TITULO          = P_TITULO,
           DESCRIPCION     = P_DESCRIPCION,
           VIGENCIA_INICIO = P_VIGENCIA_INICIO,
           VIGENCIA_FIN    = P_VIGENCIA_FIN,
           UPDATED_AT      = SYSTIMESTAMP
     WHERE POLITICA_ENVIO_ID = P_POLITICA_ENVIO_ID;
  END SP_ACTUALIZAR_POLITICA_ENVIO;

  PROCEDURE SP_ELIMINAR_POLITICA_ENVIO(
    P_POLITICA_ENVIO_ID IN POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE
  ) AS
  BEGIN
    UPDATE POLITICA_ENVIO
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE POLITICA_ENVIO_ID = P_POLITICA_ENVIO_ID;
  END SP_ELIMINAR_POLITICA_ENVIO;

  PROCEDURE SP_OBTENER_POLITICA_ENVIO(
    P_POLITICA_ENVIO_ID IN POLITICA_ENVIO.POLITICA_ENVIO_ID%TYPE,
    P_CURSOR            OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT POLITICA_ENVIO_ID,
             TITULO,
             DESCRIPCION,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             ESTADO
        FROM POLITICA_ENVIO
       WHERE POLITICA_ENVIO_ID = P_POLITICA_ENVIO_ID;
  END SP_OBTENER_POLITICA_ENVIO;

  PROCEDURE SP_LISTAR_POLITICAS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT POLITICA_ENVIO_ID,
             TITULO,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             ESTADO
        FROM POLITICA_ENVIO
       WHERE ESTADO = 'ACTIVO'
       ORDER BY TITULO;
  END SP_LISTAR_POLITICAS_ENVIO;

  PROCEDURE SP_BUSCAR_POLITICAS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT POLITICA_ENVIO_ID,
             TITULO,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             ESTADO
        FROM POLITICA_ENVIO
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'TITULO' AND UPPER(TITULO) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY TITULO;
  END SP_BUSCAR_POLITICAS_ENVIO;

END PKG_POLITICA_ENVIO;
/
