CREATE OR REPLACE PACKAGE PKG_CARRITO_DETALLE AS
  PROCEDURE SP_INSERTAR_CARRITO_DETALLE(
    P_CARRITO_ID IN CARRITO_DETALLE.CARRITO_ID%TYPE,
    P_PRODUCTO_ID IN CARRITO_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN CARRITO_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE,
    P_CARRITO_DET_ID OUT CARRITO_DETALLE.CARRITO_DET_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CARRITO_DETALLE(
    P_CARRITO_DET_ID IN CARRITO_DETALLE.CARRITO_DET_ID%TYPE,
    P_CARRITO_ID IN CARRITO_DETALLE.CARRITO_ID%TYPE,
    P_PRODUCTO_ID IN CARRITO_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN CARRITO_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE
  );

  PROCEDURE SP_ELIMINAR_CARRITO_DETALLE(
    P_CARRITO_DET_ID IN CARRITO_DETALLE.CARRITO_DET_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CARRITO_DETALLE(
    P_CARRITO_DET_ID IN  CARRITO_DETALLE.CARRITO_DET_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CARRITO_DETALLE(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CARRITO_DETALLE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CARRITO_DETALLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_CARRITO_DETALLE AS

  PROCEDURE SP_INSERTAR_CARRITO_DETALLE(
    P_CARRITO_ID IN CARRITO_DETALLE.CARRITO_ID%TYPE,
    P_PRODUCTO_ID IN CARRITO_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN CARRITO_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE,
    P_CARRITO_DET_ID OUT CARRITO_DETALLE.CARRITO_DET_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CARRITO_DETALLE (
      CARRITO_ID,
      PRODUCTO_ID,
      CANTIDAD,
      PRECIO_UNITARIO_SNAPSHOT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CARRITO_ID,
      P_PRODUCTO_ID,
      P_CANTIDAD,
      P_PRECIO_UNITARIO_SNAPSHOT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CARRITO_DET_ID INTO P_CARRITO_DET_ID;
  END SP_INSERTAR_CARRITO_DETALLE;

  PROCEDURE SP_ACTUALIZAR_CARRITO_DETALLE(
    P_CARRITO_DET_ID IN CARRITO_DETALLE.CARRITO_DET_ID%TYPE,
    P_CARRITO_ID IN CARRITO_DETALLE.CARRITO_ID%TYPE,
    P_PRODUCTO_ID IN CARRITO_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN CARRITO_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE
  ) AS
  BEGIN
    UPDATE CARRITO_DETALLE
    SET         CARRITO_ID = P_CARRITO_ID,
        PRODUCTO_ID = P_PRODUCTO_ID,
        CANTIDAD = P_CANTIDAD,
        PRECIO_UNITARIO_SNAPSHOT = P_PRECIO_UNITARIO_SNAPSHOT,
        UPDATED_AT = SYSTIMESTAMP
    WHERE CARRITO_DET_ID = P_CARRITO_DET_ID;
  END SP_ACTUALIZAR_CARRITO_DETALLE;

  PROCEDURE SP_ELIMINAR_CARRITO_DETALLE(
    P_CARRITO_DET_ID IN CARRITO_DETALLE.CARRITO_DET_ID%TYPE
  ) AS
  BEGIN
    UPDATE CARRITO_DETALLE
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE CARRITO_DET_ID = P_CARRITO_DET_ID;
  END SP_ELIMINAR_CARRITO_DETALLE;

  PROCEDURE SP_OBTENER_CARRITO_DETALLE(
    P_CARRITO_DET_ID IN  CARRITO_DETALLE.CARRITO_DET_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              CARRITO_DET_ID,
             CARRITO_ID,
             PRODUCTO_ID,
             CANTIDAD,
             PRECIO_UNITARIO_SNAPSHOT,
             ESTADO
      FROM CARRITO_DETALLE
      WHERE CARRITO_DET_ID = P_CARRITO_DET_ID;
  END SP_OBTENER_CARRITO_DETALLE;

  PROCEDURE SP_LISTAR_CARRITO_DETALLE(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              CARRITO_DET_ID,
             CARRITO_ID,
             PRODUCTO_ID,
             CANTIDAD,
             PRECIO_UNITARIO_SNAPSHOT,
             ESTADO
      FROM CARRITO_DETALLE
      WHERE ESTADO = 'ACTIVO'
      ORDER BY CARRITO_DET_ID;
  END SP_LISTAR_CARRITO_DETALLE;

  PROCEDURE SP_BUSCAR_CARRITO_DETALLE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              CARRITO_DET_ID,
             CARRITO_ID,
             PRODUCTO_ID,
             CANTIDAD,
             PRECIO_UNITARIO_SNAPSHOT,
             ESTADO
      FROM CARRITO_DETALLE
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'CARRITO_ID' AND UPPER(CAST(CARRITO_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'PRODUCTO_ID' AND UPPER(CAST(PRODUCTO_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY CARRITO_DET_ID;
  END SP_BUSCAR_CARRITO_DETALLE;

END PKG_CARRITO_DETALLE;
/
