CREATE OR REPLACE PACKAGE PKG_NOMINA_DETALLE AS

  PROCEDURE SP_INSERTAR_DETALLE(
    P_NOMINA_ID        IN NOMINA_DETALLE.NOMINA_ID%TYPE,
    P_CONCEPTO         IN NOMINA_DETALLE.CONCEPTO%TYPE,
    P_TIPO             IN NOMINA_DETALLE.TIPO%TYPE,
    P_MONTO            IN NOMINA_DETALLE.MONTO%TYPE,
    P_DETALLE_ID       OUT NOMINA_DETALLE.DETALLE_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_DETALLE(
    P_DETALLE_ID       IN NOMINA_DETALLE.DETALLE_ID%TYPE,
    P_CONCEPTO         IN NOMINA_DETALLE.CONCEPTO%TYPE,
    P_TIPO             IN NOMINA_DETALLE.TIPO%TYPE,
    P_MONTO            IN NOMINA_DETALLE.MONTO%TYPE
  );

  PROCEDURE SP_ELIMINAR_DETALLE(
    P_DETALLE_ID IN NOMINA_DETALLE.DETALLE_ID%TYPE
  );

  PROCEDURE SP_LISTAR_DETALLE_NOMINA(
    P_NOMINA_ID IN NOMINA_DETALLE.NOMINA_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_NOMINA_DETALLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_NOMINA_DETALLE AS

  PROCEDURE SP_INSERTAR_DETALLE(
    P_NOMINA_ID,
    P_CONCEPTO,
    P_TIPO,
    P_MONTO,
    P_DETALLE_ID
  ) AS
  BEGIN

    INSERT INTO NOMINA_DETALLE(
        NOMINA_ID,
        CONCEPTO,
        TIPO,
        MONTO,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_NOMINA_ID,
        P_CONCEPTO,
        P_TIPO,
        P_MONTO,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING DETALLE_ID INTO P_DETALLE_ID;

  END SP_INSERTAR_DETALLE;



  PROCEDURE SP_ACTUALIZAR_DETALLE(
    P_DETALLE_ID,
    P_CONCEPTO,
    P_TIPO,
    P_MONTO
  ) AS
  BEGIN

    UPDATE NOMINA_DETALLE
       SET CONCEPTO = P_CONCEPTO,
           TIPO = P_TIPO,
           MONTO = P_MONTO,
           UPDATED_AT = SYSTIMESTAMP
     WHERE DETALLE_ID = P_DETALLE_ID;

  END SP_ACTUALIZAR_DETALLE;



  PROCEDURE SP_ELIMINAR_DETALLE(
    P_DETALLE_ID
  ) AS
  BEGIN

    UPDATE NOMINA_DETALLE
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE DETALLE_ID = P_DETALLE_ID;

  END SP_ELIMINAR_DETALLE;



  PROCEDURE SP_LISTAR_DETALLE_NOMINA(
    P_NOMINA_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT DETALLE_ID,
             CONCEPTO,
             TIPO,
             MONTO
        FROM NOMINA_DETALLE
       WHERE NOMINA_ID = P_NOMINA_ID
       AND ESTADO = 'ACTIVO';

  END SP_LISTAR_DETALLE_NOMINA;

END PKG_NOMINA_DETALLE;
/