CREATE OR REPLACE PACKAGE PKG_HISTORIAL_LABORAL AS

  PROCEDURE SP_INSERTAR_HISTORIAL(
    P_EMPLEADO_ID        IN HISTORIAL_LABORAL.EMPLEADO_ID%TYPE,
    P_CARGO_ID           IN HISTORIAL_LABORAL.CARGO_ID%TYPE,
    P_DEPARTAMENTO_ID    IN HISTORIAL_LABORAL.DEPARTAMENTO_ID%TYPE,
    P_SALARIO            IN HISTORIAL_LABORAL.SALARIO%TYPE,
    P_FECHA_INICIO       IN HISTORIAL_LABORAL.FECHA_INICIO%TYPE,
    P_FECHA_FIN          IN HISTORIAL_LABORAL.FECHA_FIN%TYPE,
    P_HISTORIAL_ID       OUT HISTORIAL_LABORAL.HISTORIAL_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_HISTORIAL(
    P_HISTORIAL_ID       IN HISTORIAL_LABORAL.HISTORIAL_ID%TYPE,
    P_CARGO_ID           IN HISTORIAL_LABORAL.CARGO_ID%TYPE,
    P_DEPARTAMENTO_ID    IN HISTORIAL_LABORAL.DEPARTAMENTO_ID%TYPE,
    P_SALARIO            IN HISTORIAL_LABORAL.SALARIO%TYPE,
    P_FECHA_FIN          IN HISTORIAL_LABORAL.FECHA_FIN%TYPE
  );

  PROCEDURE SP_ELIMINAR_HISTORIAL(
    P_HISTORIAL_ID IN HISTORIAL_LABORAL.HISTORIAL_ID%TYPE
  );

  PROCEDURE SP_OBTENER_HISTORIAL(
    P_HISTORIAL_ID IN HISTORIAL_LABORAL.HISTORIAL_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_HISTORIAL(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_HISTORIAL_LABORAL;
/

CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_LABORAL AS

  PROCEDURE SP_INSERTAR_HISTORIAL(
    P_EMPLEADO_ID,
    P_CARGO_ID,
    P_DEPARTAMENTO_ID,
    P_SALARIO,
    P_FECHA_INICIO,
    P_FECHA_FIN,
    P_HISTORIAL_ID
  ) AS
  BEGIN

    INSERT INTO HISTORIAL_LABORAL(
        EMPLEADO_ID,
        CARGO_ID,
        DEPARTAMENTO_ID,
        SALARIO,
        FECHA_INICIO,
        FECHA_FIN,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_EMPLEADO_ID,
        P_CARGO_ID,
        P_DEPARTAMENTO_ID,
        P_SALARIO,
        P_FECHA_INICIO,
        P_FECHA_FIN,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING HISTORIAL_ID INTO P_HISTORIAL_ID;

  END SP_INSERTAR_HISTORIAL;



  PROCEDURE SP_ACTUALIZAR_HISTORIAL(
    P_HISTORIAL_ID,
    P_CARGO_ID,
    P_DEPARTAMENTO_ID,
    P_SALARIO,
    P_FECHA_FIN
  ) AS
  BEGIN

    UPDATE HISTORIAL_LABORAL
       SET CARGO_ID = P_CARGO_ID,
           DEPARTAMENTO_ID = P_DEPARTAMENTO_ID,
           SALARIO = P_SALARIO,
           FECHA_FIN = P_FECHA_FIN,
           UPDATED_AT = SYSTIMESTAMP
     WHERE HISTORIAL_ID = P_HISTORIAL_ID;

  END SP_ACTUALIZAR_HISTORIAL;



  PROCEDURE SP_ELIMINAR_HISTORIAL(
    P_HISTORIAL_ID
  ) AS
  BEGIN

    UPDATE HISTORIAL_LABORAL
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE HISTORIAL_ID = P_HISTORIAL_ID;

  END SP_ELIMINAR_HISTORIAL;



  PROCEDURE SP_OBTENER_HISTORIAL(
    P_HISTORIAL_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT H.HISTORIAL_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             C.NOMBRE AS CARGO,
             D.NOMBRE AS DEPARTAMENTO,
             H.SALARIO,
             H.FECHA_INICIO,
             H.FECHA_FIN
        FROM HISTORIAL_LABORAL H
        JOIN EMPLEADO E ON H.EMPLEADO_ID = E.EMPLEADO_ID
        JOIN CARGO C ON H.CARGO_ID = C.CARGO_ID
        JOIN DEPARTAMENTO D ON H.DEPARTAMENTO_ID = D.DEPTO_ID
       WHERE H.HISTORIAL_ID = P_HISTORIAL_ID;

  END SP_OBTENER_HISTORIAL;



  PROCEDURE SP_LISTAR_HISTORIAL(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT H.HISTORIAL_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             C.NOMBRE AS CARGO,
             D.NOMBRE AS DEPARTAMENTO,
             H.SALARIO,
             H.FECHA_INICIO,
             H.FECHA_FIN
        FROM HISTORIAL_LABORAL H
        JOIN EMPLEADO E ON H.EMPLEADO_ID = E.EMPLEADO_ID
        JOIN CARGO C ON H.CARGO_ID = C.CARGO_ID
        JOIN DEPARTAMENTO D ON H.DEPARTAMENTO_ID = D.DEPTO_ID
       WHERE H.ESTADO = 'ACTIVO'
       ORDER BY H.FECHA_INICIO DESC;

  END SP_LISTAR_HISTORIAL;

END PKG_HISTORIAL_LABORAL;
/