CREATE OR REPLACE PACKAGE PKG_TARIFA_ENVIO AS

  PROCEDURE SP_INSERTAR_TARIFA_ENVIO(
    P_ZONA_ENVIO_ID       IN TARIFA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID     IN TARIFA_ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_PESO_DESDE_KG       IN TARIFA_ENVIO.PESO_DESDE_KG%TYPE,
    P_PESO_HASTA_KG       IN TARIFA_ENVIO.PESO_HASTA_KG%TYPE,
    P_COSTO               IN TARIFA_ENVIO.COSTO%TYPE,
    P_TARIFA_ENVIO_ID     OUT TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_TARIFA_ENVIO(
    P_TARIFA_ENVIO_ID     IN TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE,
    P_ZONA_ENVIO_ID       IN TARIFA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID     IN TARIFA_ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_PESO_DESDE_KG       IN TARIFA_ENVIO.PESO_DESDE_KG%TYPE,
    P_PESO_HASTA_KG       IN TARIFA_ENVIO.PESO_HASTA_KG%TYPE,
    P_COSTO               IN TARIFA_ENVIO.COSTO%TYPE
  );

  PROCEDURE SP_ELIMINAR_TARIFA_ENVIO(
    P_TARIFA_ENVIO_ID IN TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_TARIFA_ENVIO(
    P_TARIFA_ENVIO_ID IN TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_TARIFAS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_TARIFAS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_TARIFA_ENVIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_TARIFA_ENVIO AS

  PROCEDURE SP_INSERTAR_TARIFA_ENVIO(
    P_ZONA_ENVIO_ID       IN TARIFA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID     IN TARIFA_ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_PESO_DESDE_KG       IN TARIFA_ENVIO.PESO_DESDE_KG%TYPE,
    P_PESO_HASTA_KG       IN TARIFA_ENVIO.PESO_HASTA_KG%TYPE,
    P_COSTO               IN TARIFA_ENVIO.COSTO%TYPE,
    P_TARIFA_ENVIO_ID     OUT TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO TARIFA_ENVIO (
      ZONA_ENVIO_ID,
      TIPO_ENTREGA_ID,
      PESO_DESDE_KG,
      PESO_HASTA_KG,
      COSTO,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_ZONA_ENVIO_ID,
      P_TIPO_ENTREGA_ID,
      P_PESO_DESDE_KG,
      P_PESO_HASTA_KG,
      P_COSTO,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING TARIFA_ENVIO_ID INTO P_TARIFA_ENVIO_ID;
  END SP_INSERTAR_TARIFA_ENVIO;

  PROCEDURE SP_ACTUALIZAR_TARIFA_ENVIO(
    P_TARIFA_ENVIO_ID     IN TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE,
    P_ZONA_ENVIO_ID       IN TARIFA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID     IN TARIFA_ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_PESO_DESDE_KG       IN TARIFA_ENVIO.PESO_DESDE_KG%TYPE,
    P_PESO_HASTA_KG       IN TARIFA_ENVIO.PESO_HASTA_KG%TYPE,
    P_COSTO               IN TARIFA_ENVIO.COSTO%TYPE
  ) AS
  BEGIN
    UPDATE TARIFA_ENVIO
       SET ZONA_ENVIO_ID   = P_ZONA_ENVIO_ID,
           TIPO_ENTREGA_ID = P_TIPO_ENTREGA_ID,
           PESO_DESDE_KG   = P_PESO_DESDE_KG,
           PESO_HASTA_KG   = P_PESO_HASTA_KG,
           COSTO           = P_COSTO,
           UPDATED_AT      = SYSTIMESTAMP
     WHERE TARIFA_ENVIO_ID = P_TARIFA_ENVIO_ID;
  END SP_ACTUALIZAR_TARIFA_ENVIO;

  PROCEDURE SP_ELIMINAR_TARIFA_ENVIO(
    P_TARIFA_ENVIO_ID IN TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE
  ) AS
  BEGIN
    UPDATE TARIFA_ENVIO
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE TARIFA_ENVIO_ID = P_TARIFA_ENVIO_ID;
  END SP_ELIMINAR_TARIFA_ENVIO;

  PROCEDURE SP_OBTENER_TARIFA_ENVIO(
    P_TARIFA_ENVIO_ID IN TARIFA_ENVIO.TARIFA_ENVIO_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT T.TARIFA_ENVIO_ID,
             T.ZONA_ENVIO_ID,
             Z.NOMBRE AS ZONA_ENVIO,
             T.TIPO_ENTREGA_ID,
             TE.NOMBRE AS TIPO_ENTREGA,
             T.PESO_DESDE_KG,
             T.PESO_HASTA_KG,
             T.COSTO,
             T.ESTADO
        FROM TARIFA_ENVIO T
        JOIN ZONA_ENVIO Z
          ON Z.ZONA_ENVIO_ID = T.ZONA_ENVIO_ID
        JOIN TIPO_ENTREGA TE
          ON TE.TIPO_ENTREGA_ID = T.TIPO_ENTREGA_ID
       WHERE T.TARIFA_ENVIO_ID = P_TARIFA_ENVIO_ID;
  END SP_OBTENER_TARIFA_ENVIO;

  PROCEDURE SP_LISTAR_TARIFAS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT T.TARIFA_ENVIO_ID,
             Z.NOMBRE AS ZONA_ENVIO,
             TE.NOMBRE AS TIPO_ENTREGA,
             T.PESO_DESDE_KG,
             T.PESO_HASTA_KG,
             T.COSTO,
             T.ESTADO
        FROM TARIFA_ENVIO T
        JOIN ZONA_ENVIO Z
          ON Z.ZONA_ENVIO_ID = T.ZONA_ENVIO_ID
        JOIN TIPO_ENTREGA TE
          ON TE.TIPO_ENTREGA_ID = T.TIPO_ENTREGA_ID
       WHERE T.ESTADO = 'ACTIVO'
       ORDER BY Z.NOMBRE, TE.NOMBRE, T.PESO_DESDE_KG;
  END SP_LISTAR_TARIFAS_ENVIO;

  PROCEDURE SP_BUSCAR_TARIFAS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT T.TARIFA_ENVIO_ID,
             Z.NOMBRE AS ZONA_ENVIO,
             TE.NOMBRE AS TIPO_ENTREGA,
             T.PESO_DESDE_KG,
             T.PESO_HASTA_KG,
             T.COSTO,
             T.ESTADO
        FROM TARIFA_ENVIO T
        JOIN ZONA_ENVIO Z
          ON Z.ZONA_ENVIO_ID = T.ZONA_ENVIO_ID
        JOIN TIPO_ENTREGA TE
          ON TE.TIPO_ENTREGA_ID = T.TIPO_ENTREGA_ID
       WHERE T.ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'ZONA' AND UPPER(Z.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'TIPO_ENTREGA' AND UPPER(TE.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY Z.NOMBRE, TE.NOMBRE, T.PESO_DESDE_KG;
  END SP_BUSCAR_TARIFAS_ENVIO;

END PKG_TARIFA_ENVIO;
/
