/* ============================================
   PACKAGE SPEC
   ============================================ */

CREATE OR REPLACE PACKAGE PKG_ROL_EMPLEADO AS

  PROCEDURE SP_INSERTAR_ROL(
    P_NOMBRE        IN ROL_EMPLEADO.NOMBRE%TYPE,
    P_DESCRIPCION   IN ROL_EMPLEADO.DESCRIPCION%TYPE,
    P_ROL_ID        OUT ROL_EMPLEADO.ROL_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ROL(
    P_ROL_ID        IN ROL_EMPLEADO.ROL_ID%TYPE,
    P_NOMBRE        IN ROL_EMPLEADO.NOMBRE%TYPE,
    P_DESCRIPCION   IN ROL_EMPLEADO.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_ROL(
    P_ROL_ID IN ROL_EMPLEADO.ROL_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ROL(
    P_ROL_ID IN ROL_EMPLEADO.ROL_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ROLES(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_ROL_EMPLEADO;
/

/* ============================================
   PACKAGE BODY
   ============================================ */

CREATE OR REPLACE PACKAGE BODY PKG_ROL_EMPLEADO AS

  PROCEDURE SP_INSERTAR_ROL(
    P_NOMBRE        IN ROL_EMPLEADO.NOMBRE%TYPE,
    P_DESCRIPCION   IN ROL_EMPLEADO.DESCRIPCION%TYPE,
    P_ROL_ID        OUT ROL_EMPLEADO.ROL_ID%TYPE
  ) AS
  BEGIN

    INSERT INTO ROL_EMPLEADO(
      NOMBRE,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    )
    VALUES(
      P_NOMBRE,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING ROL_ID INTO P_ROL_ID;

  END SP_INSERTAR_ROL;


  PROCEDURE SP_ACTUALIZAR_ROL(
    P_ROL_ID        IN ROL_EMPLEADO.ROL_ID%TYPE,
    P_NOMBRE        IN ROL_EMPLEADO.NOMBRE%TYPE,
    P_DESCRIPCION   IN ROL_EMPLEADO.DESCRIPCION%TYPE
  ) AS
  BEGIN

    UPDATE ROL_EMPLEADO
       SET NOMBRE = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT = SYSTIMESTAMP
     WHERE ROL_ID = P_ROL_ID;

  END SP_ACTUALIZAR_ROL;


  PROCEDURE SP_ELIMINAR_ROL(
    P_ROL_ID IN ROL_EMPLEADO.ROL_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN

    /* Validar si el rol está siendo usado por empleados */

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM EMPLEADO
     WHERE ROL_ID = P_ROL_ID;

    IF V_EXISTE > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'No se puede eliminar el rol porque está asignado a empleados.'
        );
    END IF;

    UPDATE ROL_EMPLEADO
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE ROL_ID = P_ROL_ID;

  END SP_ELIMINAR_ROL;


  PROCEDURE SP_OBTENER_ROL(
    P_ROL_ID IN ROL_EMPLEADO.ROL_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT ROL_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM ROL_EMPLEADO
       WHERE ROL_ID = P_ROL_ID;

  END SP_OBTENER_ROL;


  PROCEDURE SP_LISTAR_ROLES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT ROL_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM ROL_EMPLEADO
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;

  END SP_LISTAR_ROLES;

END PKG_ROL_EMPLEADO;
/