CREATE OR REPLACE PACKAGE PKG_HERRAMIENTA AS

  PROCEDURE SP_INSERTAR_HERRAMIENTA(
    P_CODIGO_HERRAMIENTA IN HERRAMIENTA.CODIGO_HERRAMIENTA%TYPE,
    P_NOMBRE             IN HERRAMIENTA.NOMBRE%TYPE,
    P_DESCRIPCION        IN HERRAMIENTA.DESCRIPCION%TYPE,
    P_ESTADO             IN HERRAMIENTA.ESTADO%TYPE,
    P_HERR_ID            OUT HERRAMIENTA.HERR_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_HERRAMIENTA(
    P_HERR_ID            IN HERRAMIENTA.HERR_ID%TYPE,
    P_CODIGO_HERRAMIENTA IN HERRAMIENTA.CODIGO_HERRAMIENTA%TYPE,
    P_NOMBRE             IN HERRAMIENTA.NOMBRE%TYPE,
    P_DESCRIPCION        IN HERRAMIENTA.DESCRIPCION%TYPE,
    P_ESTADO             IN HERRAMIENTA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_HERRAMIENTA(
    P_HERR_ID IN HERRAMIENTA.HERR_ID%TYPE
  );

  PROCEDURE SP_OBTENER_HERRAMIENTA(
    P_HERR_ID IN HERRAMIENTA.HERR_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_HERRAMIENTAS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_HERRAMIENTAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_HERRAMIENTA;
/

CREATE OR REPLACE PACKAGE BODY PKG_HERRAMIENTA AS

  PROCEDURE SP_INSERTAR_HERRAMIENTA(
    P_CODIGO_HERRAMIENTA IN HERRAMIENTA.CODIGO_HERRAMIENTA%TYPE,
    P_NOMBRE             IN HERRAMIENTA.NOMBRE%TYPE,
    P_DESCRIPCION        IN HERRAMIENTA.DESCRIPCION%TYPE,
    P_ESTADO             IN HERRAMIENTA.ESTADO%TYPE,
    P_HERR_ID            OUT HERRAMIENTA.HERR_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO HERRAMIENTA (
      CODIGO_HERRAMIENTA,
      NOMBRE,
      DESCRIPCION,
      ESTADO,
      CREATED_AT
    )
    VALUES (
      P_CODIGO_HERRAMIENTA,
      P_NOMBRE,
      P_DESCRIPCION,
      P_ESTADO,
      SYSTIMESTAMP
    )
    RETURNING HERR_ID INTO P_HERR_ID;
  END SP_INSERTAR_HERRAMIENTA;


  PROCEDURE SP_ACTUALIZAR_HERRAMIENTA(
    P_HERR_ID            IN HERRAMIENTA.HERR_ID%TYPE,
    P_CODIGO_HERRAMIENTA IN HERRAMIENTA.CODIGO_HERRAMIENTA%TYPE,
    P_NOMBRE             IN HERRAMIENTA.NOMBRE%TYPE,
    P_DESCRIPCION        IN HERRAMIENTA.DESCRIPCION%TYPE,
    P_ESTADO             IN HERRAMIENTA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE HERRAMIENTA
       SET CODIGO_HERRAMIENTA = P_CODIGO_HERRAMIENTA,
           NOMBRE             = P_NOMBRE,
           DESCRIPCION        = P_DESCRIPCION,
           ESTADO             = P_ESTADO,
           UPDATED_AT         = SYSTIMESTAMP
     WHERE HERR_ID = P_HERR_ID;
  END SP_ACTUALIZAR_HERRAMIENTA;


  PROCEDURE SP_ELIMINAR_HERRAMIENTA(
    P_HERR_ID IN HERRAMIENTA.HERR_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM MANTENIMIENTO_HERRAMIENTA
     WHERE HERR_ID = P_HERR_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la herramienta porque tiene mantenimientos registrados.');
    END IF;

    DELETE FROM HERRAMIENTA
     WHERE HERR_ID = P_HERR_ID;

  END SP_ELIMINAR_HERRAMIENTA;


  PROCEDURE SP_OBTENER_HERRAMIENTA(
    P_HERR_ID IN HERRAMIENTA.HERR_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT HERR_ID,
             CODIGO_HERRAMIENTA,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM HERRAMIENTA
       WHERE HERR_ID = P_HERR_ID;
  END SP_OBTENER_HERRAMIENTA;


  PROCEDURE SP_LISTAR_HERRAMIENTAS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT HERR_ID,
             CODIGO_HERRAMIENTA,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM HERRAMIENTA
       ORDER BY NOMBRE;
  END SP_LISTAR_HERRAMIENTAS;


  PROCEDURE SP_BUSCAR_HERRAMIENTAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT HERR_ID,
             CODIGO_HERRAMIENTA,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM HERRAMIENTA
       WHERE (
             (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO_HERRAMIENTA) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY NOMBRE;

  END SP_BUSCAR_HERRAMIENTAS;

END PKG_HERRAMIENTA;
/