CREATE OR REPLACE PACKAGE PKG_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_MATERIA_PRIMA(
    P_CODIGO          IN MATERIA_PRIMA.CODIGO%TYPE,
    P_NOMBRE          IN MATERIA_PRIMA.NOMBRE%TYPE,
    P_DESCRIPCION     IN MATERIA_PRIMA.DESCRIPCION%TYPE,
    P_UNIDAD_MEDIDA   IN MATERIA_PRIMA.UNIDAD_MEDIDA%TYPE,
    P_STOCK_MINIMO    IN MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_STOCK_ACTUAL    IN MATERIA_PRIMA.STOCK_ACTUAL%TYPE,
    P_ESTADO          IN MATERIA_PRIMA.ESTADO%TYPE,
    P_MP_ID           OUT MATERIA_PRIMA.MP_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_MATERIA_PRIMA(
    P_MP_ID           IN MATERIA_PRIMA.MP_ID%TYPE,
    P_CODIGO          IN MATERIA_PRIMA.CODIGO%TYPE,
    P_NOMBRE          IN MATERIA_PRIMA.NOMBRE%TYPE,
    P_DESCRIPCION     IN MATERIA_PRIMA.DESCRIPCION%TYPE,
    P_UNIDAD_MEDIDA   IN MATERIA_PRIMA.UNIDAD_MEDIDA%TYPE,
    P_STOCK_MINIMO    IN MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_STOCK_ACTUAL    IN MATERIA_PRIMA.STOCK_ACTUAL%TYPE,
    P_ESTADO          IN MATERIA_PRIMA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_MATERIA_PRIMA(
    P_MP_ID IN MATERIA_PRIMA.MP_ID%TYPE
  );

  PROCEDURE SP_OBTENER_MATERIA_PRIMA(
    P_MP_ID  IN MATERIA_PRIMA.MP_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_MATERIAS_PRIMAS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_MATERIAS_PRIMAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_MATERIA_PRIMA;
/

CREATE OR REPLACE PACKAGE BODY PKG_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_MATERIA_PRIMA(
    P_CODIGO          IN MATERIA_PRIMA.CODIGO%TYPE,
    P_NOMBRE          IN MATERIA_PRIMA.NOMBRE%TYPE,
    P_DESCRIPCION     IN MATERIA_PRIMA.DESCRIPCION%TYPE,
    P_UNIDAD_MEDIDA   IN MATERIA_PRIMA.UNIDAD_MEDIDA%TYPE,
    P_STOCK_MINIMO    IN MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_STOCK_ACTUAL    IN MATERIA_PRIMA.STOCK_ACTUAL%TYPE,
    P_ESTADO          IN MATERIA_PRIMA.ESTADO%TYPE,
    P_MP_ID           OUT MATERIA_PRIMA.MP_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO MATERIA_PRIMA (
      CODIGO,
      NOMBRE,
      DESCRIPCION,
      UNIDAD_MEDIDA,
      STOCK_MINIMO,
      STOCK_ACTUAL,
      ESTADO,
      CREATED_AT
    )
    VALUES (
      P_CODIGO,
      P_NOMBRE,
      P_DESCRIPCION,
      P_UNIDAD_MEDIDA,
      P_STOCK_MINIMO,
      P_STOCK_ACTUAL,
      P_ESTADO,
      SYSTIMESTAMP
    )
    RETURNING MP_ID INTO P_MP_ID;
  END SP_INSERTAR_MATERIA_PRIMA;


  PROCEDURE SP_ACTUALIZAR_MATERIA_PRIMA(
    P_MP_ID           IN MATERIA_PRIMA.MP_ID%TYPE,
    P_CODIGO          IN MATERIA_PRIMA.CODIGO%TYPE,
    P_NOMBRE          IN MATERIA_PRIMA.NOMBRE%TYPE,
    P_DESCRIPCION     IN MATERIA_PRIMA.DESCRIPCION%TYPE,
    P_UNIDAD_MEDIDA   IN MATERIA_PRIMA.UNIDAD_MEDIDA%TYPE,
    P_STOCK_MINIMO    IN MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_STOCK_ACTUAL    IN MATERIA_PRIMA.STOCK_ACTUAL%TYPE,
    P_ESTADO          IN MATERIA_PRIMA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE MATERIA_PRIMA
       SET CODIGO        = P_CODIGO,
           NOMBRE        = P_NOMBRE,
           DESCRIPCION   = P_DESCRIPCION,
           UNIDAD_MEDIDA = P_UNIDAD_MEDIDA,
           STOCK_MINIMO  = P_STOCK_MINIMO,
           STOCK_ACTUAL  = P_STOCK_ACTUAL,
           ESTADO        = P_ESTADO,
           UPDATED_AT    = SYSTIMESTAMP
     WHERE MP_ID = P_MP_ID;
  END SP_ACTUALIZAR_MATERIA_PRIMA;


  PROCEDURE SP_ELIMINAR_MATERIA_PRIMA(
    P_MP_ID IN MATERIA_PRIMA.MP_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM INVENTARIO_MATERIA_PRIMA
     WHERE MP_ID = P_MP_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la materia prima porque tiene registros en inventario.');
    END IF;

    DELETE FROM MATERIA_PRIMA
     WHERE MP_ID = P_MP_ID;
  END SP_ELIMINAR_MATERIA_PRIMA;


  PROCEDURE SP_OBTENER_MATERIA_PRIMA(
    P_MP_ID  IN MATERIA_PRIMA.MP_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MP_ID,
             CODIGO,
             NOMBRE,
             DESCRIPCION,
             UNIDAD_MEDIDA,
             STOCK_MINIMO,
             STOCK_ACTUAL,
             ESTADO
        FROM MATERIA_PRIMA
       WHERE MP_ID = P_MP_ID;
  END SP_OBTENER_MATERIA_PRIMA;


  PROCEDURE SP_LISTAR_MATERIAS_PRIMAS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MP_ID,
             CODIGO,
             NOMBRE,
             UNIDAD_MEDIDA,
             STOCK_MINIMO,
             STOCK_ACTUAL,
             ESTADO
        FROM MATERIA_PRIMA
       ORDER BY NOMBRE;
  END SP_LISTAR_MATERIAS_PRIMAS;


  PROCEDURE SP_BUSCAR_MATERIAS_PRIMAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MP_ID,
             CODIGO,
             NOMBRE,
             UNIDAD_MEDIDA,
             STOCK_MINIMO,
             STOCK_ACTUAL,
             ESTADO
        FROM MATERIA_PRIMA
       WHERE (
             (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY NOMBRE;
  END SP_BUSCAR_MATERIAS_PRIMAS;

END PKG_MATERIA_PRIMA;
/