CREATE OR REPLACE PACKAGE PKG_PRODUCCION_RESULTADOS AS

  PROCEDURE SP_INSERTAR_PRODUCCION_RESULTADOS(
    P_ORDEN_PRODUCCION_ID IN PRODUCCION_RESULTADOS.ORDEN_PRODUCCION_ID%TYPE,
    P_UNIDADES_BUENAS     IN PRODUCCION_RESULTADOS.UNIDADES_BUENAS%TYPE,
    P_UNIDADES_MERMA      IN PRODUCCION_RESULTADOS.UNIDADES_MERMA%TYPE,
    P_REGISTRO_AT         IN PRODUCCION_RESULTADOS.REGISTRO_AT%TYPE,
    P_ESTADO              IN PRODUCCION_RESULTADOS.ESTADO%TYPE,
    P_RESULTADO_ID        OUT PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PRODUCCION_RESULTADOS(
    P_RESULTADO_ID        IN PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE,
    P_ORDEN_PRODUCCION_ID IN PRODUCCION_RESULTADOS.ORDEN_PRODUCCION_ID%TYPE,
    P_UNIDADES_BUENAS     IN PRODUCCION_RESULTADOS.UNIDADES_BUENAS%TYPE,
    P_UNIDADES_MERMA      IN PRODUCCION_RESULTADOS.UNIDADES_MERMA%TYPE,
    P_REGISTRO_AT         IN PRODUCCION_RESULTADOS.REGISTRO_AT%TYPE,
    P_ESTADO              IN PRODUCCION_RESULTADOS.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_PRODUCCION_RESULTADOS(
    P_RESULTADO_ID IN PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PRODUCCION_RESULTADOS(
    P_RESULTADO_ID IN PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PRODUCCION_RESULTADOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PRODUCCION_RESULTADOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PRODUCCION_RESULTADOS;
/
CREATE OR REPLACE PACKAGE BODY PKG_PRODUCCION_RESULTADOS AS

  PROCEDURE SP_INSERTAR_PRODUCCION_RESULTADOS(
    P_ORDEN_PRODUCCION_ID IN PRODUCCION_RESULTADOS.ORDEN_PRODUCCION_ID%TYPE,
    P_UNIDADES_BUENAS     IN PRODUCCION_RESULTADOS.UNIDADES_BUENAS%TYPE,
    P_UNIDADES_MERMA      IN PRODUCCION_RESULTADOS.UNIDADES_MERMA%TYPE,
    P_REGISTRO_AT         IN PRODUCCION_RESULTADOS.REGISTRO_AT%TYPE,
    P_ESTADO              IN PRODUCCION_RESULTADOS.ESTADO%TYPE,
    P_RESULTADO_ID        OUT PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PRODUCCION_RESULTADOS (
      ORDEN_PRODUCCION_ID,
      UNIDADES_BUENAS,
      UNIDADES_MERMA,
      REGISTRO_AT,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_ORDEN_PRODUCCION_ID,
      P_UNIDADES_BUENAS,
      P_UNIDADES_MERMA,
      P_REGISTRO_AT,
      SYSTIMESTAMP,
      P_ESTADO
    )
    RETURNING RESULTADO_ID INTO P_RESULTADO_ID;
  END SP_INSERTAR_PRODUCCION_RESULTADOS;

  PROCEDURE SP_ACTUALIZAR_PRODUCCION_RESULTADOS(
    P_RESULTADO_ID        IN PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE,
    P_ORDEN_PRODUCCION_ID IN PRODUCCION_RESULTADOS.ORDEN_PRODUCCION_ID%TYPE,
    P_UNIDADES_BUENAS     IN PRODUCCION_RESULTADOS.UNIDADES_BUENAS%TYPE,
    P_UNIDADES_MERMA      IN PRODUCCION_RESULTADOS.UNIDADES_MERMA%TYPE,
    P_REGISTRO_AT         IN PRODUCCION_RESULTADOS.REGISTRO_AT%TYPE,
    P_ESTADO              IN PRODUCCION_RESULTADOS.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE PRODUCCION_RESULTADOS
       SET ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID,
           UNIDADES_BUENAS     = P_UNIDADES_BUENAS,
           UNIDADES_MERMA      = P_UNIDADES_MERMA,
           REGISTRO_AT         = P_REGISTRO_AT,
           UPDATED_AT          = SYSTIMESTAMP,
           ESTADO              = P_ESTADO
     WHERE RESULTADO_ID = P_RESULTADO_ID;
  END SP_ACTUALIZAR_PRODUCCION_RESULTADOS;

  PROCEDURE SP_ELIMINAR_PRODUCCION_RESULTADOS(
    P_RESULTADO_ID IN PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE
  ) AS
  BEGIN
    UPDATE PRODUCCION_RESULTADOS
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE RESULTADO_ID = P_RESULTADO_ID;
  END SP_ELIMINAR_PRODUCCION_RESULTADOS;

  PROCEDURE SP_OBTENER_PRODUCCION_RESULTADOS(
    P_RESULTADO_ID IN PRODUCCION_RESULTADOS.RESULTADO_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RESULTADO_ID,
             ORDEN_PRODUCCION_ID,
             UNIDADES_BUENAS,
             UNIDADES_MERMA,
             REGISTRO_AT,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM PRODUCCION_RESULTADOS
       WHERE RESULTADO_ID = P_RESULTADO_ID;
  END SP_OBTENER_PRODUCCION_RESULTADOS;

  PROCEDURE SP_LISTAR_PRODUCCION_RESULTADOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RESULTADO_ID,
             ORDEN_PRODUCCION_ID,
             UNIDADES_BUENAS,
             UNIDADES_MERMA,
             REGISTRO_AT,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM PRODUCCION_RESULTADOS
       ORDER BY REGISTRO_AT DESC, RESULTADO_ID DESC;
  END SP_LISTAR_PRODUCCION_RESULTADOS;

  PROCEDURE SP_BUSCAR_PRODUCCION_RESULTADOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RESULTADO_ID,
             ORDEN_PRODUCCION_ID,
             UNIDADES_BUENAS,
             UNIDADES_MERMA,
             REGISTRO_AT,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM PRODUCCION_RESULTADOS
       WHERE (
             (UPPER(P_CRITERIO) = 'RESULTADO_ID' AND TO_CHAR(RESULTADO_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ORDEN_PRODUCCION_ID' AND TO_CHAR(ORDEN_PRODUCCION_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY REGISTRO_AT DESC, RESULTADO_ID DESC;
  END SP_BUSCAR_PRODUCCION_RESULTADOS;

END PKG_PRODUCCION_RESULTADOS;
/
