CREATE OR REPLACE PACKAGE PKG_HISTORIAL_COMPRA AS
  PROCEDURE SP_INSERTAR_HISTORIAL_COMPRA(
    P_CLI_ID IN HISTORIAL_COMPRA.CLI_ID%TYPE,
    P_ORDEN_VENTA_ID IN HISTORIAL_COMPRA.ORDEN_VENTA_ID%TYPE,
    P_COMPRA_AT IN HISTORIAL_COMPRA.COMPRA_AT%TYPE,
    P_MONTO_TOTAL_SNAPSHOT IN HISTORIAL_COMPRA.MONTO_TOTAL_SNAPSHOT%TYPE,
    P_HIST_COMPRA_ID OUT HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_HISTORIAL_COMPRA(
    P_HIST_COMPRA_ID IN HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE,
    P_CLI_ID IN HISTORIAL_COMPRA.CLI_ID%TYPE,
    P_ORDEN_VENTA_ID IN HISTORIAL_COMPRA.ORDEN_VENTA_ID%TYPE,
    P_COMPRA_AT IN HISTORIAL_COMPRA.COMPRA_AT%TYPE,
    P_MONTO_TOTAL_SNAPSHOT IN HISTORIAL_COMPRA.MONTO_TOTAL_SNAPSHOT%TYPE
  );

  PROCEDURE SP_ELIMINAR_HISTORIAL_COMPRA(
    P_HIST_COMPRA_ID IN HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_HISTORIAL_COMPRA(
    P_HIST_COMPRA_ID IN  HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_HISTORIAL_COMPRA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_HISTORIAL_COMPRA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_HISTORIAL_COMPRA;
/


CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_COMPRA AS

  PROCEDURE SP_INSERTAR_HISTORIAL_COMPRA(
    P_CLI_ID IN HISTORIAL_COMPRA.CLI_ID%TYPE,
    P_ORDEN_VENTA_ID IN HISTORIAL_COMPRA.ORDEN_VENTA_ID%TYPE,
    P_COMPRA_AT IN HISTORIAL_COMPRA.COMPRA_AT%TYPE,
    P_MONTO_TOTAL_SNAPSHOT IN HISTORIAL_COMPRA.MONTO_TOTAL_SNAPSHOT%TYPE,
    P_HIST_COMPRA_ID OUT HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO HISTORIAL_COMPRA (
      CLI_ID,
      ORDEN_VENTA_ID,
      COMPRA_AT,
      MONTO_TOTAL_SNAPSHOT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CLI_ID,
      P_ORDEN_VENTA_ID,
      P_COMPRA_AT,
      P_MONTO_TOTAL_SNAPSHOT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING HIST_COMPRA_ID INTO P_HIST_COMPRA_ID;
  END SP_INSERTAR_HISTORIAL_COMPRA;

  PROCEDURE SP_ACTUALIZAR_HISTORIAL_COMPRA(
    P_HIST_COMPRA_ID IN HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE,
    P_CLI_ID IN HISTORIAL_COMPRA.CLI_ID%TYPE,
    P_ORDEN_VENTA_ID IN HISTORIAL_COMPRA.ORDEN_VENTA_ID%TYPE,
    P_COMPRA_AT IN HISTORIAL_COMPRA.COMPRA_AT%TYPE,
    P_MONTO_TOTAL_SNAPSHOT IN HISTORIAL_COMPRA.MONTO_TOTAL_SNAPSHOT%TYPE
  ) AS
  BEGIN
    UPDATE HISTORIAL_COMPRA
    SET         CLI_ID = P_CLI_ID,
        ORDEN_VENTA_ID = P_ORDEN_VENTA_ID,
        COMPRA_AT = P_COMPRA_AT,
        MONTO_TOTAL_SNAPSHOT = P_MONTO_TOTAL_SNAPSHOT,
        UPDATED_AT = SYSTIMESTAMP
    WHERE HIST_COMPRA_ID = P_HIST_COMPRA_ID;
  END SP_ACTUALIZAR_HISTORIAL_COMPRA;

  PROCEDURE SP_ELIMINAR_HISTORIAL_COMPRA(
    P_HIST_COMPRA_ID IN HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE
  ) AS
  BEGIN
    UPDATE HISTORIAL_COMPRA
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE HIST_COMPRA_ID = P_HIST_COMPRA_ID;
  END SP_ELIMINAR_HISTORIAL_COMPRA;

  PROCEDURE SP_OBTENER_HISTORIAL_COMPRA(
    P_HIST_COMPRA_ID IN  HISTORIAL_COMPRA.HIST_COMPRA_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              HIST_COMPRA_ID,
             CLI_ID,
             ORDEN_VENTA_ID,
             COMPRA_AT,
             MONTO_TOTAL_SNAPSHOT,
             ESTADO
      FROM HISTORIAL_COMPRA
      WHERE HIST_COMPRA_ID = P_HIST_COMPRA_ID;
  END SP_OBTENER_HISTORIAL_COMPRA;

  PROCEDURE SP_LISTAR_HISTORIAL_COMPRA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              HIST_COMPRA_ID,
             CLI_ID,
             ORDEN_VENTA_ID,
             COMPRA_AT,
             MONTO_TOTAL_SNAPSHOT,
             ESTADO
      FROM HISTORIAL_COMPRA
      WHERE ESTADO = 'ACTIVO'
      ORDER BY COMPRA_AT DESC;
  END SP_LISTAR_HISTORIAL_COMPRA;

  PROCEDURE SP_BUSCAR_HISTORIAL_COMPRA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              HIST_COMPRA_ID,
             CLI_ID,
             ORDEN_VENTA_ID,
             COMPRA_AT,
             MONTO_TOTAL_SNAPSHOT,
             ESTADO
      FROM HISTORIAL_COMPRA
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'CLI_ID' AND UPPER(CAST(CLI_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'ORDEN_VENTA_ID' AND UPPER(CAST(ORDEN_VENTA_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY COMPRA_AT DESC;
  END SP_BUSCAR_HISTORIAL_COMPRA;

END PKG_HISTORIAL_COMPRA;
/
