CREATE OR REPLACE PACKAGE PKG_TIPO_PROMOCION AS

  PROCEDURE SP_INSERTAR_TIPO_PROMOCION(
    P_NOMBRE            IN TIPO_PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_PROMOCION.DESCRIPCION%TYPE,
    P_TIPO_PROMOCION_ID OUT TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_TIPO_PROMOCION(
    P_TIPO_PROMOCION_ID IN TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_NOMBRE            IN TIPO_PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_PROMOCION.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_TIPO_PROMOCION(
    P_TIPO_PROMOCION_ID IN TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_TIPO_PROMOCION(
    P_TIPO_PROMOCION_ID IN TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_CURSOR            OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_TIPO_PROMOCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_TIPO_PROMOCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_TIPO_PROMOCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_TIPO_PROMOCION AS

  PROCEDURE SP_INSERTAR_TIPO_PROMOCION(
    P_NOMBRE            IN TIPO_PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_PROMOCION.DESCRIPCION%TYPE,
    P_TIPO_PROMOCION_ID OUT TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO TIPO_PROMOCION (
      NOMBRE,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_NOMBRE,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING TIPO_PROMOCION_ID INTO P_TIPO_PROMOCION_ID;
  END SP_INSERTAR_TIPO_PROMOCION;

  PROCEDURE SP_ACTUALIZAR_TIPO_PROMOCION(
    P_TIPO_PROMOCION_ID IN TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_NOMBRE            IN TIPO_PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_PROMOCION.DESCRIPCION%TYPE
  ) AS
  BEGIN
    UPDATE TIPO_PROMOCION
       SET NOMBRE      = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT  = SYSTIMESTAMP
     WHERE TIPO_PROMOCION_ID = P_TIPO_PROMOCION_ID;
  END SP_ACTUALIZAR_TIPO_PROMOCION;

  PROCEDURE SP_ELIMINAR_TIPO_PROMOCION(
    P_TIPO_PROMOCION_ID IN TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM PROMOCION
     WHERE TIPO_PROMOCION_ID = P_TIPO_PROMOCION_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el tipo de promoción porque tiene promociones asociadas.');
    END IF;

    UPDATE TIPO_PROMOCION
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE TIPO_PROMOCION_ID = P_TIPO_PROMOCION_ID;
  END SP_ELIMINAR_TIPO_PROMOCION;

  PROCEDURE SP_OBTENER_TIPO_PROMOCION(
    P_TIPO_PROMOCION_ID IN TIPO_PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_CURSOR            OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT TIPO_PROMOCION_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM TIPO_PROMOCION
       WHERE TIPO_PROMOCION_ID = P_TIPO_PROMOCION_ID;
  END SP_OBTENER_TIPO_PROMOCION;

  PROCEDURE SP_LISTAR_TIPO_PROMOCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT TIPO_PROMOCION_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM TIPO_PROMOCION
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;
  END SP_LISTAR_TIPO_PROMOCION;

  PROCEDURE SP_BUSCAR_TIPO_PROMOCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT TIPO_PROMOCION_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM TIPO_PROMOCION
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY NOMBRE;
  END SP_BUSCAR_TIPO_PROMOCION;

END PKG_TIPO_PROMOCION;
/
