CREATE OR REPLACE PACKAGE PKG_REGLA_ENVIO_GRATIS AS

  PROCEDURE SP_INSERTAR_REGLA_ENVIO_GRATIS(
    P_ZONA_ENVIO_ID            IN REGLA_ENVIO_GRATIS.ZONA_ENVIO_ID%TYPE,
    P_MONTO_MINIMO             IN REGLA_ENVIO_GRATIS.MONTO_MINIMO%TYPE,
    P_PESO_MAX_KG              IN REGLA_ENVIO_GRATIS.PESO_MAX_KG%TYPE,
    P_VIGENCIA_INICIO          IN REGLA_ENVIO_GRATIS.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN             IN REGLA_ENVIO_GRATIS.VIGENCIA_FIN%TYPE,
    P_REGLA_ENVIO_GRATIS_ID    OUT REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_REGLA_ENVIO_GRATIS(
    P_REGLA_ENVIO_GRATIS_ID    IN REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE,
    P_ZONA_ENVIO_ID            IN REGLA_ENVIO_GRATIS.ZONA_ENVIO_ID%TYPE,
    P_MONTO_MINIMO             IN REGLA_ENVIO_GRATIS.MONTO_MINIMO%TYPE,
    P_PESO_MAX_KG              IN REGLA_ENVIO_GRATIS.PESO_MAX_KG%TYPE,
    P_VIGENCIA_INICIO          IN REGLA_ENVIO_GRATIS.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN             IN REGLA_ENVIO_GRATIS.VIGENCIA_FIN%TYPE
  );

  PROCEDURE SP_ELIMINAR_REGLA_ENVIO_GRATIS(
    P_REGLA_ENVIO_GRATIS_ID IN REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE
  );

  PROCEDURE SP_OBTENER_REGLA_ENVIO_GRATIS(
    P_REGLA_ENVIO_GRATIS_ID IN REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE,
    P_CURSOR                OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_REGLAS_ENVIO_GRATIS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_REGLAS_ENVIO_GRATIS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_REGLA_ENVIO_GRATIS;
/

CREATE OR REPLACE PACKAGE BODY PKG_REGLA_ENVIO_GRATIS AS

  PROCEDURE SP_INSERTAR_REGLA_ENVIO_GRATIS(
    P_ZONA_ENVIO_ID            IN REGLA_ENVIO_GRATIS.ZONA_ENVIO_ID%TYPE,
    P_MONTO_MINIMO             IN REGLA_ENVIO_GRATIS.MONTO_MINIMO%TYPE,
    P_PESO_MAX_KG              IN REGLA_ENVIO_GRATIS.PESO_MAX_KG%TYPE,
    P_VIGENCIA_INICIO          IN REGLA_ENVIO_GRATIS.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN             IN REGLA_ENVIO_GRATIS.VIGENCIA_FIN%TYPE,
    P_REGLA_ENVIO_GRATIS_ID    OUT REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO REGLA_ENVIO_GRATIS (
      ZONA_ENVIO_ID,
      MONTO_MINIMO,
      PESO_MAX_KG,
      VIGENCIA_INICIO,
      VIGENCIA_FIN,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_ZONA_ENVIO_ID,
      P_MONTO_MINIMO,
      P_PESO_MAX_KG,
      P_VIGENCIA_INICIO,
      P_VIGENCIA_FIN,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING REGLA_ENVIO_GRATIS_ID INTO P_REGLA_ENVIO_GRATIS_ID;
  END SP_INSERTAR_REGLA_ENVIO_GRATIS;

  PROCEDURE SP_ACTUALIZAR_REGLA_ENVIO_GRATIS(
    P_REGLA_ENVIO_GRATIS_ID    IN REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE,
    P_ZONA_ENVIO_ID            IN REGLA_ENVIO_GRATIS.ZONA_ENVIO_ID%TYPE,
    P_MONTO_MINIMO             IN REGLA_ENVIO_GRATIS.MONTO_MINIMO%TYPE,
    P_PESO_MAX_KG              IN REGLA_ENVIO_GRATIS.PESO_MAX_KG%TYPE,
    P_VIGENCIA_INICIO          IN REGLA_ENVIO_GRATIS.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN             IN REGLA_ENVIO_GRATIS.VIGENCIA_FIN%TYPE
  ) AS
  BEGIN
    UPDATE REGLA_ENVIO_GRATIS
       SET ZONA_ENVIO_ID   = P_ZONA_ENVIO_ID,
           MONTO_MINIMO    = P_MONTO_MINIMO,
           PESO_MAX_KG     = P_PESO_MAX_KG,
           VIGENCIA_INICIO = P_VIGENCIA_INICIO,
           VIGENCIA_FIN    = P_VIGENCIA_FIN,
           UPDATED_AT      = SYSTIMESTAMP
     WHERE REGLA_ENVIO_GRATIS_ID = P_REGLA_ENVIO_GRATIS_ID;
  END SP_ACTUALIZAR_REGLA_ENVIO_GRATIS;

  PROCEDURE SP_ELIMINAR_REGLA_ENVIO_GRATIS(
    P_REGLA_ENVIO_GRATIS_ID IN REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE
  ) AS
  BEGIN
    UPDATE REGLA_ENVIO_GRATIS
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE REGLA_ENVIO_GRATIS_ID = P_REGLA_ENVIO_GRATIS_ID;
  END SP_ELIMINAR_REGLA_ENVIO_GRATIS;

  PROCEDURE SP_OBTENER_REGLA_ENVIO_GRATIS(
    P_REGLA_ENVIO_GRATIS_ID IN REGLA_ENVIO_GRATIS.REGLA_ENVIO_GRATIS_ID%TYPE,
    P_CURSOR                OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT REG.REGLA_ENVIO_GRATIS_ID,
             REG.ZONA_ENVIO_ID,
             Z.NOMBRE AS ZONA_ENVIO,
             REG.MONTO_MINIMO,
             REG.PESO_MAX_KG,
             REG.VIGENCIA_INICIO,
             REG.VIGENCIA_FIN,
             REG.ESTADO
        FROM REGLA_ENVIO_GRATIS REG
        JOIN ZONA_ENVIO Z
          ON Z.ZONA_ENVIO_ID = REG.ZONA_ENVIO_ID
       WHERE REG.REGLA_ENVIO_GRATIS_ID = P_REGLA_ENVIO_GRATIS_ID;
  END SP_OBTENER_REGLA_ENVIO_GRATIS;

  PROCEDURE SP_LISTAR_REGLAS_ENVIO_GRATIS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT REG.REGLA_ENVIO_GRATIS_ID,
             Z.NOMBRE AS ZONA_ENVIO,
             REG.MONTO_MINIMO,
             REG.PESO_MAX_KG,
             REG.VIGENCIA_INICIO,
             REG.VIGENCIA_FIN,
             REG.ESTADO
        FROM REGLA_ENVIO_GRATIS REG
        JOIN ZONA_ENVIO Z
          ON Z.ZONA_ENVIO_ID = REG.ZONA_ENVIO_ID
       WHERE REG.ESTADO = 'ACTIVO'
       ORDER BY Z.NOMBRE, REG.REGLA_ENVIO_GRATIS_ID;
  END SP_LISTAR_REGLAS_ENVIO_GRATIS;

  PROCEDURE SP_BUSCAR_REGLAS_ENVIO_GRATIS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT REG.REGLA_ENVIO_GRATIS_ID,
             Z.NOMBRE AS ZONA_ENVIO,
             REG.MONTO_MINIMO,
             REG.PESO_MAX_KG,
             REG.VIGENCIA_INICIO,
             REG.VIGENCIA_FIN,
             REG.ESTADO
        FROM REGLA_ENVIO_GRATIS REG
        JOIN ZONA_ENVIO Z
          ON Z.ZONA_ENVIO_ID = REG.ZONA_ENVIO_ID
       WHERE REG.ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'ZONA' AND UPPER(Z.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'PAIS' AND UPPER(Z.PAIS) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY Z.NOMBRE, REG.REGLA_ENVIO_GRATIS_ID;
  END SP_BUSCAR_REGLAS_ENVIO_GRATIS;

END PKG_REGLA_ENVIO_GRATIS;
/
