CREATE OR REPLACE PACKAGE PKG_CUOTAS_PAGO AS

  PROCEDURE SP_INSERTAR(
      P_PAGO_ID          IN CUOTAS_PAGO.PAGO_ID%TYPE,
      P_NUMERO_CUOTA     IN CUOTAS_PAGO.NUMERO_CUOTA%TYPE,
      P_MONTO            IN CUOTAS_PAGO.MONTO%TYPE,
      P_FECHA_VENCIMIENTO IN CUOTAS_PAGO.FECHA_VENCIMIENTO%TYPE,
      P_ID               OUT CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR(
      P_ID               IN CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE,
      P_PAGO_ID          IN CUOTAS_PAGO.PAGO_ID%TYPE,
      P_NUMERO_CUOTA     IN CUOTAS_PAGO.NUMERO_CUOTA%TYPE,
      P_MONTO            IN CUOTAS_PAGO.MONTO%TYPE,
      P_FECHA_VENCIMIENTO IN CUOTAS_PAGO.FECHA_VENCIMIENTO%TYPE
  );

  PROCEDURE SP_ELIMINAR(
      P_ID IN CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE
  );

  PROCEDURE SP_OBTENER(
      P_ID     IN CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE,
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR(
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR(
      P_PAGO_ID IN NUMBER,
      P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_CUOTAS_PAGO;
/

CREATE OR REPLACE PACKAGE BODY PKG_CUOTAS_PAGO AS


PROCEDURE SP_INSERTAR(
    P_PAGO_ID          IN CUOTAS_PAGO.PAGO_ID%TYPE,
    P_NUMERO_CUOTA     IN CUOTAS_PAGO.NUMERO_CUOTA%TYPE,
    P_MONTO            IN CUOTAS_PAGO.MONTO%TYPE,
    P_FECHA_VENCIMIENTO IN CUOTAS_PAGO.FECHA_VENCIMIENTO%TYPE,
    P_ID               OUT CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE
) AS
BEGIN

    INSERT INTO CUOTAS_PAGO
    (
        PAGO_ID,
        NUMERO_CUOTA,
        MONTO,
        FECHA_VENCIMIENTO,
        ESTADO
    )
    VALUES
    (
        P_PAGO_ID,
        P_NUMERO_CUOTA,
        P_MONTO,
        P_FECHA_VENCIMIENTO,
        'A'
    )
    RETURNING CUOTAS_PAGO_ID INTO P_ID;

END SP_INSERTAR;



PROCEDURE SP_ACTUALIZAR(
    P_ID               IN CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE,
    P_PAGO_ID          IN CUOTAS_PAGO.PAGO_ID%TYPE,
    P_NUMERO_CUOTA     IN CUOTAS_PAGO.NUMERO_CUOTA%TYPE,
    P_MONTO            IN CUOTAS_PAGO.MONTO%TYPE,
    P_FECHA_VENCIMIENTO IN CUOTAS_PAGO.FECHA_VENCIMIENTO%TYPE
) AS
BEGIN

    UPDATE CUOTAS_PAGO
    SET
        PAGO_ID = P_PAGO_ID,
        NUMERO_CUOTA = P_NUMERO_CUOTA,
        MONTO = P_MONTO,
        FECHA_VENCIMIENTO = P_FECHA_VENCIMIENTO
    WHERE CUOTAS_PAGO_ID = P_ID;

END SP_ACTUALIZAR;



PROCEDURE SP_ELIMINAR(
    P_ID IN CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE
) AS
BEGIN

    UPDATE CUOTAS_PAGO
    SET ESTADO = 'I'
    WHERE CUOTAS_PAGO_ID = P_ID;

END SP_ELIMINAR;



PROCEDURE SP_OBTENER(
    P_ID     IN CUOTAS_PAGO.CUOTAS_PAGO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            CUOTAS_PAGO_ID,
            PAGO_ID,
            NUMERO_CUOTA,
            MONTO,
            FECHA_VENCIMIENTO,
            ESTADO
        FROM CUOTAS_PAGO
        WHERE CUOTAS_PAGO_ID = P_ID;

END SP_OBTENER;



PROCEDURE SP_LISTAR(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            CUOTAS_PAGO_ID,
            PAGO_ID,
            NUMERO_CUOTA,
            MONTO,
            FECHA_VENCIMIENTO,
            ESTADO
        FROM CUOTAS_PAGO
        WHERE ESTADO = 'A'
        ORDER BY FECHA_VENCIMIENTO;

END SP_LISTAR;



PROCEDURE SP_BUSCAR(
    P_PAGO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            CUOTAS_PAGO_ID,
            PAGO_ID,
            NUMERO_CUOTA,
            MONTO,
            FECHA_VENCIMIENTO,
            ESTADO
        FROM CUOTAS_PAGO
        WHERE PAGO_ID = P_PAGO_ID
        AND ESTADO = 'A';

END SP_BUSCAR;


END PKG_CUOTAS_PAGO;
/