CREATE OR REPLACE PACKAGE PKG_RUTA_ENTREGA AS

  PROCEDURE SP_INSERTAR_RUTA_ENTREGA(
    P_VEHICULO_ID      IN  RUTA_ENTREGA.VEHICULO_ID%TYPE,
    P_FECHA_RUTA       IN  RUTA_ENTREGA.FECHA_RUTA%TYPE,
    P_DESCRIPCION      IN  RUTA_ENTREGA.DESCRIPCION%TYPE,
    P_ESTADO_RUTA      IN  RUTA_ENTREGA.ESTADO_RUTA%TYPE,
    P_RUTA_ENTREGA_ID  OUT RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_RUTA_ENTREGA(
    P_RUTA_ENTREGA_ID  IN  RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE,
    P_VEHICULO_ID      IN  RUTA_ENTREGA.VEHICULO_ID%TYPE,
    P_FECHA_RUTA       IN  RUTA_ENTREGA.FECHA_RUTA%TYPE,
    P_DESCRIPCION      IN  RUTA_ENTREGA.DESCRIPCION%TYPE,
    P_ESTADO_RUTA      IN  RUTA_ENTREGA.ESTADO_RUTA%TYPE
  );

  PROCEDURE SP_ELIMINAR_RUTA_ENTREGA(
    P_RUTA_ENTREGA_ID IN RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_RUTA_ENTREGA(
    P_RUTA_ENTREGA_ID IN  RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_RUTA_ENTREGA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_RUTA_ENTREGA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_RUTA_ENTREGA;
/

CREATE OR REPLACE PACKAGE BODY PKG_RUTA_ENTREGA AS

  PROCEDURE SP_INSERTAR_RUTA_ENTREGA(
    P_VEHICULO_ID      IN  RUTA_ENTREGA.VEHICULO_ID%TYPE,
    P_FECHA_RUTA       IN  RUTA_ENTREGA.FECHA_RUTA%TYPE,
    P_DESCRIPCION      IN  RUTA_ENTREGA.DESCRIPCION%TYPE,
    P_ESTADO_RUTA      IN  RUTA_ENTREGA.ESTADO_RUTA%TYPE,
    P_RUTA_ENTREGA_ID  OUT RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO RUTA_ENTREGA (
      VEHICULO_ID,
      FECHA_RUTA,
      DESCRIPCION,
      ESTADO_RUTA,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_VEHICULO_ID,
      P_FECHA_RUTA,
      P_DESCRIPCION,
      P_ESTADO_RUTA,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING RUTA_ENTREGA_ID INTO P_RUTA_ENTREGA_ID;
  END SP_INSERTAR_RUTA_ENTREGA;

  PROCEDURE SP_ACTUALIZAR_RUTA_ENTREGA(
    P_RUTA_ENTREGA_ID  IN  RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE,
    P_VEHICULO_ID      IN  RUTA_ENTREGA.VEHICULO_ID%TYPE,
    P_FECHA_RUTA       IN  RUTA_ENTREGA.FECHA_RUTA%TYPE,
    P_DESCRIPCION      IN  RUTA_ENTREGA.DESCRIPCION%TYPE,
    P_ESTADO_RUTA      IN  RUTA_ENTREGA.ESTADO_RUTA%TYPE
  ) AS
  BEGIN
    UPDATE RUTA_ENTREGA
    SET VEHICULO_ID  = P_VEHICULO_ID,
        FECHA_RUTA   = P_FECHA_RUTA,
        DESCRIPCION  = P_DESCRIPCION,
        ESTADO_RUTA  = P_ESTADO_RUTA,
        UPDATED_AT   = SYSTIMESTAMP
    WHERE RUTA_ENTREGA_ID = P_RUTA_ENTREGA_ID;
  END SP_ACTUALIZAR_RUTA_ENTREGA;

  PROCEDURE SP_ELIMINAR_RUTA_ENTREGA(
    P_RUTA_ENTREGA_ID IN RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM ENVIO
    WHERE RUTA_ENTREGA_ID = P_RUTA_ENTREGA_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la ruta de entrega porque tiene envios asociados.');
    END IF;

    UPDATE RUTA_ENTREGA
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE RUTA_ENTREGA_ID = P_RUTA_ENTREGA_ID;
  END SP_ELIMINAR_RUTA_ENTREGA;

  PROCEDURE SP_OBTENER_RUTA_ENTREGA(
    P_RUTA_ENTREGA_ID IN  RUTA_ENTREGA.RUTA_ENTREGA_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RUTA_ENTREGA_ID,
             VEHICULO_ID,
             FECHA_RUTA,
             DESCRIPCION,
             ESTADO_RUTA,
             ESTADO
      FROM RUTA_ENTREGA
      WHERE RUTA_ENTREGA_ID = P_RUTA_ENTREGA_ID;
  END SP_OBTENER_RUTA_ENTREGA;

  PROCEDURE SP_LISTAR_RUTA_ENTREGA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RE.RUTA_ENTREGA_ID,
             RE.VEHICULO_ID,
             V.PLACA AS PLACA_VEHICULO,
             RE.FECHA_RUTA,
             RE.DESCRIPCION,
             RE.ESTADO_RUTA,
             RE.ESTADO
      FROM RUTA_ENTREGA RE
      JOIN VEHICULO V ON V.VEHICULO_ID = RE.VEHICULO_ID
      WHERE RE.ESTADO = 'ACTIVO'
      ORDER BY RE.FECHA_RUTA DESC;
  END SP_LISTAR_RUTA_ENTREGA;

  PROCEDURE SP_BUSCAR_RUTA_ENTREGA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RE.RUTA_ENTREGA_ID,
             RE.VEHICULO_ID,
             V.PLACA AS PLACA_VEHICULO,
             RE.FECHA_RUTA,
             RE.DESCRIPCION,
             RE.ESTADO_RUTA,
             RE.ESTADO
      FROM RUTA_ENTREGA RE
      JOIN VEHICULO V ON V.VEHICULO_ID = RE.VEHICULO_ID
      WHERE RE.ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'PLACA'       AND UPPER(V.PLACA)       LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'ESTADO_RUTA' AND UPPER(RE.ESTADO_RUTA) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(RE.DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY RE.FECHA_RUTA DESC;
  END SP_BUSCAR_RUTA_ENTREGA;

END PKG_RUTA_ENTREGA;
/
