CREATE OR REPLACE PACKAGE PKG_UNIDAD_MEDIDA AS

  PROCEDURE SP_INSERTAR_UNIDAD_MEDIDA(
    P_CODIGO          IN  UNIDAD_MEDIDA.CODIGO%TYPE,
    P_NOMBRE          IN  UNIDAD_MEDIDA.NOMBRE%TYPE,
    P_UNIDAD_MEDIDA_ID OUT UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_UNIDAD_MEDIDA(
    P_UNIDAD_MEDIDA_ID IN  UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE,
    P_CODIGO           IN  UNIDAD_MEDIDA.CODIGO%TYPE,
    P_NOMBRE           IN  UNIDAD_MEDIDA.NOMBRE%TYPE
  );

  PROCEDURE SP_ELIMINAR_UNIDAD_MEDIDA(
    P_UNIDAD_MEDIDA_ID IN UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_UNIDAD_MEDIDA(
    P_UNIDAD_MEDIDA_ID IN  UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE,
    P_CURSOR           OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_UNIDAD_MEDIDA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_UNIDAD_MEDIDA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_UNIDAD_MEDIDA;
/

CREATE OR REPLACE PACKAGE BODY PKG_UNIDAD_MEDIDA AS

  PROCEDURE SP_INSERTAR_UNIDAD_MEDIDA(
    P_CODIGO           IN  UNIDAD_MEDIDA.CODIGO%TYPE,
    P_NOMBRE           IN  UNIDAD_MEDIDA.NOMBRE%TYPE,
    P_UNIDAD_MEDIDA_ID OUT UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO UNIDAD_MEDIDA (
      CODIGO,
      NOMBRE,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CODIGO,
      P_NOMBRE,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING UNIDAD_MEDIDA_ID INTO P_UNIDAD_MEDIDA_ID;
  END SP_INSERTAR_UNIDAD_MEDIDA;

  PROCEDURE SP_ACTUALIZAR_UNIDAD_MEDIDA(
    P_UNIDAD_MEDIDA_ID IN  UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE,
    P_CODIGO           IN  UNIDAD_MEDIDA.CODIGO%TYPE,
    P_NOMBRE           IN  UNIDAD_MEDIDA.NOMBRE%TYPE
  ) AS
  BEGIN
    UPDATE UNIDAD_MEDIDA
    SET CODIGO     = P_CODIGO,
        NOMBRE     = P_NOMBRE,
        UPDATED_AT = SYSTIMESTAMP
    WHERE UNIDAD_MEDIDA_ID = P_UNIDAD_MEDIDA_ID;
  END SP_ACTUALIZAR_UNIDAD_MEDIDA;

  PROCEDURE SP_ELIMINAR_UNIDAD_MEDIDA(
    P_UNIDAD_MEDIDA_ID IN UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM PRODUCTO
    WHERE UNIDAD_MEDIDA_ID = P_UNIDAD_MEDIDA_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la unidad de medida porque tiene productos asociados.');
    END IF;

    UPDATE UNIDAD_MEDIDA
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE UNIDAD_MEDIDA_ID = P_UNIDAD_MEDIDA_ID;
  END SP_ELIMINAR_UNIDAD_MEDIDA;

  PROCEDURE SP_OBTENER_UNIDAD_MEDIDA(
    P_UNIDAD_MEDIDA_ID IN  UNIDAD_MEDIDA.UNIDAD_MEDIDA_ID%TYPE,
    P_CURSOR           OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT UNIDAD_MEDIDA_ID,
             CODIGO,
             NOMBRE,
             ESTADO
      FROM UNIDAD_MEDIDA
      WHERE UNIDAD_MEDIDA_ID = P_UNIDAD_MEDIDA_ID;
  END SP_OBTENER_UNIDAD_MEDIDA;

  PROCEDURE SP_LISTAR_UNIDAD_MEDIDA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT UNIDAD_MEDIDA_ID,
             CODIGO,
             NOMBRE,
             ESTADO
      FROM UNIDAD_MEDIDA
      WHERE ESTADO = 'ACTIVO'
      ORDER BY NOMBRE;
  END SP_LISTAR_UNIDAD_MEDIDA;

  PROCEDURE SP_BUSCAR_UNIDAD_MEDIDA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT UNIDAD_MEDIDA_ID,
             CODIGO,
             NOMBRE,
             ESTADO
      FROM UNIDAD_MEDIDA
      WHERE ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY NOMBRE;
  END SP_BUSCAR_UNIDAD_MEDIDA;

END PKG_UNIDAD_MEDIDA;
/

