CREATE OR REPLACE PACKAGE PKG_PROMOCION AS

  PROCEDURE SP_INSERTAR_PROMOCION(
    P_TIPO_PROMOCION_ID IN PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_NOMBRE            IN PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN PROMOCION.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO   IN PROMOCION.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN      IN PROMOCION.VIGENCIA_FIN%TYPE,
    P_PRIORIDAD         IN PROMOCION.PRIORIDAD%TYPE,
    P_PROMOCION_ID      OUT PROMOCION.PROMOCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PROMOCION(
    P_PROMOCION_ID      IN PROMOCION.PROMOCION_ID%TYPE,
    P_TIPO_PROMOCION_ID IN PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_NOMBRE            IN PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN PROMOCION.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO   IN PROMOCION.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN      IN PROMOCION.VIGENCIA_FIN%TYPE,
    P_PRIORIDAD         IN PROMOCION.PRIORIDAD%TYPE
  );

  PROCEDURE SP_ELIMINAR_PROMOCION(
    P_PROMOCION_ID IN PROMOCION.PROMOCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PROMOCION(
    P_PROMOCION_ID IN PROMOCION.PROMOCION_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PROMOCIONES(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PROMOCIONES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PROMOCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_PROMOCION AS

  PROCEDURE SP_INSERTAR_PROMOCION(
    P_TIPO_PROMOCION_ID IN PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_NOMBRE            IN PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN PROMOCION.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO   IN PROMOCION.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN      IN PROMOCION.VIGENCIA_FIN%TYPE,
    P_PRIORIDAD         IN PROMOCION.PRIORIDAD%TYPE,
    P_PROMOCION_ID      OUT PROMOCION.PROMOCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PROMOCION (
      TIPO_PROMOCION_ID,
      NOMBRE,
      DESCRIPCION,
      VIGENCIA_INICIO,
      VIGENCIA_FIN,
      PRIORIDAD,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_TIPO_PROMOCION_ID,
      P_NOMBRE,
      P_DESCRIPCION,
      P_VIGENCIA_INICIO,
      P_VIGENCIA_FIN,
      P_PRIORIDAD,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING PROMOCION_ID INTO P_PROMOCION_ID;
  END SP_INSERTAR_PROMOCION;

  PROCEDURE SP_ACTUALIZAR_PROMOCION(
    P_PROMOCION_ID      IN PROMOCION.PROMOCION_ID%TYPE,
    P_TIPO_PROMOCION_ID IN PROMOCION.TIPO_PROMOCION_ID%TYPE,
    P_NOMBRE            IN PROMOCION.NOMBRE%TYPE,
    P_DESCRIPCION       IN PROMOCION.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO   IN PROMOCION.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN      IN PROMOCION.VIGENCIA_FIN%TYPE,
    P_PRIORIDAD         IN PROMOCION.PRIORIDAD%TYPE
  ) AS
  BEGIN
    UPDATE PROMOCION
       SET TIPO_PROMOCION_ID = P_TIPO_PROMOCION_ID,
           NOMBRE            = P_NOMBRE,
           DESCRIPCION       = P_DESCRIPCION,
           VIGENCIA_INICIO   = P_VIGENCIA_INICIO,
           VIGENCIA_FIN      = P_VIGENCIA_FIN,
           PRIORIDAD         = P_PRIORIDAD,
           UPDATED_AT        = SYSTIMESTAMP
     WHERE PROMOCION_ID = P_PROMOCION_ID;
  END SP_ACTUALIZAR_PROMOCION;

  PROCEDURE SP_ELIMINAR_PROMOCION(
    P_PROMOCION_ID IN PROMOCION.PROMOCION_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM (
        SELECT PROMOCION_ID FROM PROMOCION_PRODUCTO WHERE PROMOCION_ID = P_PROMOCION_ID
        UNION ALL
        SELECT PROMOCION_ID FROM REGLA_PROMOCION WHERE PROMOCION_ID = P_PROMOCION_ID
        UNION ALL
        SELECT PROMOCION_ID FROM HISTORIAL_PROMOCION WHERE PROMOCION_ID = P_PROMOCION_ID
      );

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la promoción porque tiene registros asociados.');
    END IF;

    UPDATE PROMOCION
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE PROMOCION_ID = P_PROMOCION_ID;
  END SP_ELIMINAR_PROMOCION;

  PROCEDURE SP_OBTENER_PROMOCION(
    P_PROMOCION_ID IN PROMOCION.PROMOCION_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT P.PROMOCION_ID,
             P.TIPO_PROMOCION_ID,
             TP.NOMBRE AS TIPO_PROMOCION,
             P.NOMBRE,
             P.DESCRIPCION,
             P.VIGENCIA_INICIO,
             P.VIGENCIA_FIN,
             P.PRIORIDAD,
             P.ESTADO
        FROM PROMOCION P
        JOIN TIPO_PROMOCION TP
          ON TP.TIPO_PROMOCION_ID = P.TIPO_PROMOCION_ID
       WHERE P.PROMOCION_ID = P_PROMOCION_ID;
  END SP_OBTENER_PROMOCION;

  PROCEDURE SP_LISTAR_PROMOCIONES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT P.PROMOCION_ID,
             TP.NOMBRE AS TIPO_PROMOCION,
             P.NOMBRE,
             P.VIGENCIA_INICIO,
             P.VIGENCIA_FIN,
             P.PRIORIDAD,
             P.ESTADO
        FROM PROMOCION P
        JOIN TIPO_PROMOCION TP
          ON TP.TIPO_PROMOCION_ID = P.TIPO_PROMOCION_ID
       WHERE P.ESTADO = 'ACTIVO'
       ORDER BY P.PRIORIDAD DESC, P.NOMBRE;
  END SP_LISTAR_PROMOCIONES;

  PROCEDURE SP_BUSCAR_PROMOCIONES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT P.PROMOCION_ID,
             TP.NOMBRE AS TIPO_PROMOCION,
             P.NOMBRE,
             P.VIGENCIA_INICIO,
             P.VIGENCIA_FIN,
             P.PRIORIDAD,
             P.ESTADO
        FROM PROMOCION P
        JOIN TIPO_PROMOCION TP
          ON TP.TIPO_PROMOCION_ID = P.TIPO_PROMOCION_ID
       WHERE P.ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(P.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'TIPO' AND UPPER(TP.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(P.DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY P.PRIORIDAD DESC, P.NOMBRE;
  END SP_BUSCAR_PROMOCIONES;

END PKG_PROMOCION;
/
