CREATE OR REPLACE PACKAGE PKG_CAMPANA_MARKETING AS

  PROCEDURE SP_INSERTAR_CAMPANA_MARKETING(
    P_NOMBRE                IN CAMPANA_MARKETING.NOMBRE%TYPE,
    P_CANAL                 IN CAMPANA_MARKETING.CANAL%TYPE,
    P_PRESUPUESTO           IN CAMPANA_MARKETING.PRESUPUESTO%TYPE,
    P_INICIO                IN CAMPANA_MARKETING.INICIO%TYPE,
    P_FIN                   IN CAMPANA_MARKETING.FIN%TYPE,
    P_CAMPANA_MARKETING_ID  OUT CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CAMPANA_MARKETING(
    P_CAMPANA_MARKETING_ID  IN CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE,
    P_NOMBRE                IN CAMPANA_MARKETING.NOMBRE%TYPE,
    P_CANAL                 IN CAMPANA_MARKETING.CANAL%TYPE,
    P_PRESUPUESTO           IN CAMPANA_MARKETING.PRESUPUESTO%TYPE,
    P_INICIO                IN CAMPANA_MARKETING.INICIO%TYPE,
    P_FIN                   IN CAMPANA_MARKETING.FIN%TYPE
  );

  PROCEDURE SP_ELIMINAR_CAMPANA_MARKETING(
    P_CAMPANA_MARKETING_ID IN CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CAMPANA_MARKETING(
    P_CAMPANA_MARKETING_ID IN CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE,
    P_CURSOR               OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CAMPANA_MARKETING(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CAMPANA_MARKETING(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CAMPANA_MARKETING;
/

CREATE OR REPLACE PACKAGE BODY PKG_CAMPANA_MARKETING AS

  PROCEDURE SP_INSERTAR_CAMPANA_MARKETING(
    P_NOMBRE                IN CAMPANA_MARKETING.NOMBRE%TYPE,
    P_CANAL                 IN CAMPANA_MARKETING.CANAL%TYPE,
    P_PRESUPUESTO           IN CAMPANA_MARKETING.PRESUPUESTO%TYPE,
    P_INICIO                IN CAMPANA_MARKETING.INICIO%TYPE,
    P_FIN                   IN CAMPANA_MARKETING.FIN%TYPE,
    P_CAMPANA_MARKETING_ID  OUT CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CAMPANA_MARKETING (
      NOMBRE,
      CANAL,
      PRESUPUESTO,
      INICIO,
      FIN,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_NOMBRE,
      P_CANAL,
      P_PRESUPUESTO,
      P_INICIO,
      P_FIN,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CAMPANA_MARKETING_ID INTO P_CAMPANA_MARKETING_ID;
  END SP_INSERTAR_CAMPANA_MARKETING;

  PROCEDURE SP_ACTUALIZAR_CAMPANA_MARKETING(
    P_CAMPANA_MARKETING_ID  IN CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE,
    P_NOMBRE                IN CAMPANA_MARKETING.NOMBRE%TYPE,
    P_CANAL                 IN CAMPANA_MARKETING.CANAL%TYPE,
    P_PRESUPUESTO           IN CAMPANA_MARKETING.PRESUPUESTO%TYPE,
    P_INICIO                IN CAMPANA_MARKETING.INICIO%TYPE,
    P_FIN                   IN CAMPANA_MARKETING.FIN%TYPE
  ) AS
  BEGIN
    UPDATE CAMPANA_MARKETING
       SET NOMBRE      = P_NOMBRE,
           CANAL       = P_CANAL,
           PRESUPUESTO = P_PRESUPUESTO,
           INICIO      = P_INICIO,
           FIN         = P_FIN,
           UPDATED_AT  = SYSTIMESTAMP
     WHERE CAMPANA_MARKETING_ID = P_CAMPANA_MARKETING_ID;
  END SP_ACTUALIZAR_CAMPANA_MARKETING;

  PROCEDURE SP_ELIMINAR_CAMPANA_MARKETING(
    P_CAMPANA_MARKETING_ID IN CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE
  ) AS
  BEGIN
    UPDATE CAMPANA_MARKETING
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE CAMPANA_MARKETING_ID = P_CAMPANA_MARKETING_ID;
  END SP_ELIMINAR_CAMPANA_MARKETING;

  PROCEDURE SP_OBTENER_CAMPANA_MARKETING(
    P_CAMPANA_MARKETING_ID IN CAMPANA_MARKETING.CAMPANA_MARKETING_ID%TYPE,
    P_CURSOR               OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CAMPANA_MARKETING_ID,
             NOMBRE,
             CANAL,
             PRESUPUESTO,
             INICIO,
             FIN,
             ESTADO
        FROM CAMPANA_MARKETING
       WHERE CAMPANA_MARKETING_ID = P_CAMPANA_MARKETING_ID;
  END SP_OBTENER_CAMPANA_MARKETING;

  PROCEDURE SP_LISTAR_CAMPANA_MARKETING(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CAMPANA_MARKETING_ID,
             NOMBRE,
             CANAL,
             PRESUPUESTO,
             INICIO,
             FIN,
             ESTADO
        FROM CAMPANA_MARKETING
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;
  END SP_LISTAR_CAMPANA_MARKETING;

  PROCEDURE SP_BUSCAR_CAMPANA_MARKETING(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CAMPANA_MARKETING_ID,
             NOMBRE,
             CANAL,
             PRESUPUESTO,
             INICIO,
             FIN,
             ESTADO
        FROM CAMPANA_MARKETING
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'CANAL' AND UPPER(CANAL) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY NOMBRE;
  END SP_BUSCAR_CAMPANA_MARKETING;

END PKG_CAMPANA_MARKETING;
/
