CREATE OR REPLACE PACKAGE PKG_MOVIMIENTO_INVENTARIO AS

  PROCEDURE SP_INSERTAR_MOVIMIENTO_INVENTARIO(
    P_INV_PROD_ID    IN  MOVIMIENTO_INVENTARIO.INV_PROD_ID%TYPE,
    P_TIPO_MOV       IN  MOVIMIENTO_INVENTARIO.TIPO_MOV%TYPE,
    P_CANTIDAD       IN  MOVIMIENTO_INVENTARIO.CANTIDAD%TYPE,
    P_MOTIVO         IN  MOVIMIENTO_INVENTARIO.MOTIVO%TYPE,
    P_REFERENCIA_ID  IN  MOVIMIENTO_INVENTARIO.REFERENCIA_ID%TYPE,
    P_MOV_AT         IN  MOVIMIENTO_INVENTARIO.MOV_AT%TYPE,
    P_MOV_INV_ID     OUT MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_MOVIMIENTO_INVENTARIO(
    P_MOV_INV_ID     IN  MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE,
    P_INV_PROD_ID    IN  MOVIMIENTO_INVENTARIO.INV_PROD_ID%TYPE,
    P_TIPO_MOV       IN  MOVIMIENTO_INVENTARIO.TIPO_MOV%TYPE,
    P_CANTIDAD       IN  MOVIMIENTO_INVENTARIO.CANTIDAD%TYPE,
    P_MOTIVO         IN  MOVIMIENTO_INVENTARIO.MOTIVO%TYPE,
    P_REFERENCIA_ID  IN  MOVIMIENTO_INVENTARIO.REFERENCIA_ID%TYPE,
    P_MOV_AT         IN  MOVIMIENTO_INVENTARIO.MOV_AT%TYPE
  );

  PROCEDURE SP_ELIMINAR_MOVIMIENTO_INVENTARIO(
    P_MOV_INV_ID IN MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE
  );

  PROCEDURE SP_OBTENER_MOVIMIENTO_INVENTARIO(
    P_MOV_INV_ID IN  MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_MOVIMIENTO_INVENTARIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_MOVIMIENTO_INVENTARIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_MOVIMIENTO_INVENTARIO;
/


CREATE OR REPLACE PACKAGE BODY PKG_MOVIMIENTO_INVENTARIO AS

  PROCEDURE SP_INSERTAR_MOVIMIENTO_INVENTARIO(
    P_INV_PROD_ID    IN  MOVIMIENTO_INVENTARIO.INV_PROD_ID%TYPE,
    P_TIPO_MOV       IN  MOVIMIENTO_INVENTARIO.TIPO_MOV%TYPE,
    P_CANTIDAD       IN  MOVIMIENTO_INVENTARIO.CANTIDAD%TYPE,
    P_MOTIVO         IN  MOVIMIENTO_INVENTARIO.MOTIVO%TYPE,
    P_REFERENCIA_ID  IN  MOVIMIENTO_INVENTARIO.REFERENCIA_ID%TYPE,
    P_MOV_AT         IN  MOVIMIENTO_INVENTARIO.MOV_AT%TYPE,
    P_MOV_INV_ID     OUT MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO MOVIMIENTO_INVENTARIO (
      INV_PROD_ID,
      TIPO_MOV,
      CANTIDAD,
      MOTIVO,
      REFERENCIA_ID,
      MOV_AT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_INV_PROD_ID,
      P_TIPO_MOV,
      P_CANTIDAD,
      P_MOTIVO,
      P_REFERENCIA_ID,
      P_MOV_AT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING MOV_INV_ID INTO P_MOV_INV_ID;
  END SP_INSERTAR_MOVIMIENTO_INVENTARIO;

  PROCEDURE SP_ACTUALIZAR_MOVIMIENTO_INVENTARIO(
    P_MOV_INV_ID     IN  MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE,
    P_INV_PROD_ID    IN  MOVIMIENTO_INVENTARIO.INV_PROD_ID%TYPE,
    P_TIPO_MOV       IN  MOVIMIENTO_INVENTARIO.TIPO_MOV%TYPE,
    P_CANTIDAD       IN  MOVIMIENTO_INVENTARIO.CANTIDAD%TYPE,
    P_MOTIVO         IN  MOVIMIENTO_INVENTARIO.MOTIVO%TYPE,
    P_REFERENCIA_ID  IN  MOVIMIENTO_INVENTARIO.REFERENCIA_ID%TYPE,
    P_MOV_AT         IN  MOVIMIENTO_INVENTARIO.MOV_AT%TYPE
  ) AS
  BEGIN
    UPDATE MOVIMIENTO_INVENTARIO
    SET INV_PROD_ID   = P_INV_PROD_ID,
        TIPO_MOV      = P_TIPO_MOV,
        CANTIDAD      = P_CANTIDAD,
        MOTIVO        = P_MOTIVO,
        REFERENCIA_ID = P_REFERENCIA_ID,
        MOV_AT        = P_MOV_AT,
        UPDATED_AT    = SYSTIMESTAMP
    WHERE MOV_INV_ID = P_MOV_INV_ID;
  END SP_ACTUALIZAR_MOVIMIENTO_INVENTARIO;

  PROCEDURE SP_ELIMINAR_MOVIMIENTO_INVENTARIO(
    P_MOV_INV_ID IN MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE
  ) AS
  BEGIN
    UPDATE MOVIMIENTO_INVENTARIO
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE MOV_INV_ID = P_MOV_INV_ID;
  END SP_ELIMINAR_MOVIMIENTO_INVENTARIO;

  PROCEDURE SP_OBTENER_MOVIMIENTO_INVENTARIO(
    P_MOV_INV_ID IN  MOVIMIENTO_INVENTARIO.MOV_INV_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MOV_INV_ID,
             INV_PROD_ID,
             TIPO_MOV,
             CANTIDAD,
             MOTIVO,
             REFERENCIA_ID,
             MOV_AT,
             ESTADO
      FROM MOVIMIENTO_INVENTARIO
      WHERE MOV_INV_ID = P_MOV_INV_ID;
  END SP_OBTENER_MOVIMIENTO_INVENTARIO;

  PROCEDURE SP_LISTAR_MOVIMIENTO_INVENTARIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MOV_INV_ID,
             INV_PROD_ID,
             TIPO_MOV,
             CANTIDAD,
             MOV_AT,
             ESTADO
      FROM MOVIMIENTO_INVENTARIO
      WHERE ESTADO = 'ACTIVO'
      ORDER BY MOV_AT DESC;
  END SP_LISTAR_MOVIMIENTO_INVENTARIO;

  PROCEDURE SP_BUSCAR_MOVIMIENTO_INVENTARIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MOV_INV_ID,
             INV_PROD_ID,
             TIPO_MOV,
             CANTIDAD,
             MOV_AT,
             ESTADO
      FROM MOVIMIENTO_INVENTARIO
      WHERE ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'TIPO_MOV' AND UPPER(TIPO_MOV) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'MOTIVO'   AND UPPER(MOTIVO)   LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY MOV_AT DESC;
  END SP_BUSCAR_MOVIMIENTO_INVENTARIO;

END PKG_MOVIMIENTO_INVENTARIO;
/
