CREATE OR REPLACE PACKAGE PKG_CATEGORIA AS

  PROCEDURE SP_INSERTAR_CATEGORIA(
    P_NOMBRE             IN  CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION        IN  CATEGORIA.DESCRIPCION%TYPE,
    P_CATEGORIA_PADRE_ID IN  CATEGORIA.CATEGORIA_PADRE_ID%TYPE,
    P_CATEGORIA_ID       OUT CATEGORIA.CATEGORIA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CATEGORIA(
    P_CATEGORIA_ID       IN  CATEGORIA.CATEGORIA_ID%TYPE,
    P_NOMBRE             IN  CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION        IN  CATEGORIA.DESCRIPCION%TYPE,
    P_CATEGORIA_PADRE_ID IN  CATEGORIA.CATEGORIA_PADRE_ID%TYPE
  );

  PROCEDURE SP_ELIMINAR_CATEGORIA(
    P_CATEGORIA_ID IN CATEGORIA.CATEGORIA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CATEGORIA(
    P_CATEGORIA_ID IN  CATEGORIA.CATEGORIA_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CATEGORIAS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CATEGORIAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CATEGORIA;
/


CREATE OR REPLACE PACKAGE BODY PKG_CATEGORIA AS

  PROCEDURE SP_INSERTAR_CATEGORIA(
    P_NOMBRE             IN  CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION        IN  CATEGORIA.DESCRIPCION%TYPE,
    P_CATEGORIA_PADRE_ID IN  CATEGORIA.CATEGORIA_PADRE_ID%TYPE,
    P_CATEGORIA_ID       OUT CATEGORIA.CATEGORIA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CATEGORIA (
      NOMBRE,
      DESCRIPCION,
      CATEGORIA_PADRE_ID,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_NOMBRE,
      P_DESCRIPCION,
      P_CATEGORIA_PADRE_ID,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CATEGORIA_ID INTO P_CATEGORIA_ID;
  END SP_INSERTAR_CATEGORIA;

  PROCEDURE SP_ACTUALIZAR_CATEGORIA(
    P_CATEGORIA_ID       IN  CATEGORIA.CATEGORIA_ID%TYPE,
    P_NOMBRE             IN  CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION        IN  CATEGORIA.DESCRIPCION%TYPE,
    P_CATEGORIA_PADRE_ID IN  CATEGORIA.CATEGORIA_PADRE_ID%TYPE
  ) AS
  BEGIN
    UPDATE CATEGORIA
    SET NOMBRE             = P_NOMBRE,
        DESCRIPCION        = P_DESCRIPCION,
        CATEGORIA_PADRE_ID = P_CATEGORIA_PADRE_ID,
        UPDATED_AT         = SYSTIMESTAMP
    WHERE CATEGORIA_ID = P_CATEGORIA_ID;
  END SP_ACTUALIZAR_CATEGORIA;

  PROCEDURE SP_ELIMINAR_CATEGORIA(
    P_CATEGORIA_ID IN CATEGORIA.CATEGORIA_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM PRODUCTO
    WHERE CATEGORIA_ID = P_CATEGORIA_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la categoria porque tiene productos asociados.');
    END IF;

    UPDATE CATEGORIA
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE CATEGORIA_ID = P_CATEGORIA_ID;
  END SP_ELIMINAR_CATEGORIA;

  PROCEDURE SP_OBTENER_CATEGORIA(
    P_CATEGORIA_ID IN  CATEGORIA.CATEGORIA_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CATEGORIA_ID,
             NOMBRE,
             DESCRIPCION,
             CATEGORIA_PADRE_ID,
             ESTADO
      FROM CATEGORIA
      WHERE CATEGORIA_ID = P_CATEGORIA_ID;
  END SP_OBTENER_CATEGORIA;

  PROCEDURE SP_LISTAR_CATEGORIAS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CATEGORIA_ID,
             NOMBRE,
             DESCRIPCION,
             CATEGORIA_PADRE_ID,
             ESTADO
      FROM CATEGORIA
      WHERE ESTADO = 'ACTIVO'
      ORDER BY NOMBRE;
  END SP_LISTAR_CATEGORIAS;

  PROCEDURE SP_BUSCAR_CATEGORIAS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CATEGORIA_ID,
             NOMBRE,
             DESCRIPCION,
             CATEGORIA_PADRE_ID,
             ESTADO
      FROM CATEGORIA
      WHERE ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'NOMBRE'      AND UPPER(NOMBRE)      LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY NOMBRE;
  END SP_BUSCAR_CATEGORIAS;

END PKG_CATEGORIA;
/
