CREATE OR REPLACE PACKAGE PKG_PLAN_PRODUCCION AS

  PROCEDURE SP_INSERTAR_PLAN_PRODUCCION(
    P_PRODUCTO_ID           IN  PLAN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD              IN  PLAN_PRODUCCION.CANTIDAD%TYPE,
    P_PERIODO_INICIO        IN  PLAN_PRODUCCION.PERIODO_INICIO%TYPE,
    P_PERIODO_FIN           IN  PLAN_PRODUCCION.PERIODO_FIN%TYPE,
    P_TIEMPO_ESTIMADO_HORAS IN  PLAN_PRODUCCION.TIEMPO_ESTIMADO_HORAS%TYPE,
    P_PLAN_PRODUCCION_ID    OUT PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PLAN_PRODUCCION(
    P_PLAN_PRODUCCION_ID    IN  PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE,
    P_PRODUCTO_ID           IN  PLAN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD              IN  PLAN_PRODUCCION.CANTIDAD%TYPE,
    P_PERIODO_INICIO        IN  PLAN_PRODUCCION.PERIODO_INICIO%TYPE,
    P_PERIODO_FIN           IN  PLAN_PRODUCCION.PERIODO_FIN%TYPE,
    P_TIEMPO_ESTIMADO_HORAS IN  PLAN_PRODUCCION.TIEMPO_ESTIMADO_HORAS%TYPE
  );

  PROCEDURE SP_ELIMINAR_PLAN_PRODUCCION(
    P_PLAN_PRODUCCION_ID IN PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PLAN_PRODUCCION(
    P_PLAN_PRODUCCION_ID IN  PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE,
    P_CURSOR             OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PLAN_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PLAN_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PLAN_PRODUCCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_PLAN_PRODUCCION AS

  PROCEDURE SP_INSERTAR_PLAN_PRODUCCION(
    P_PRODUCTO_ID           IN  PLAN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD              IN  PLAN_PRODUCCION.CANTIDAD%TYPE,
    P_PERIODO_INICIO        IN  PLAN_PRODUCCION.PERIODO_INICIO%TYPE,
    P_PERIODO_FIN           IN  PLAN_PRODUCCION.PERIODO_FIN%TYPE,
    P_TIEMPO_ESTIMADO_HORAS IN  PLAN_PRODUCCION.TIEMPO_ESTIMADO_HORAS%TYPE,
    P_PLAN_PRODUCCION_ID    OUT PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PLAN_PRODUCCION (
      PRODUCTO_ID,
      CANTIDAD,
      PERIODO_INICIO,
      PERIODO_FIN,
      TIEMPO_ESTIMADO_HORAS,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_PRODUCTO_ID,
      P_CANTIDAD,
      P_PERIODO_INICIO,
      P_PERIODO_FIN,
      P_TIEMPO_ESTIMADO_HORAS,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING PLAN_PRODUCCION_ID INTO P_PLAN_PRODUCCION_ID;
  END SP_INSERTAR_PLAN_PRODUCCION;

  PROCEDURE SP_ACTUALIZAR_PLAN_PRODUCCION(
    P_PLAN_PRODUCCION_ID    IN  PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE,
    P_PRODUCTO_ID           IN  PLAN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD              IN  PLAN_PRODUCCION.CANTIDAD%TYPE,
    P_PERIODO_INICIO        IN  PLAN_PRODUCCION.PERIODO_INICIO%TYPE,
    P_PERIODO_FIN           IN  PLAN_PRODUCCION.PERIODO_FIN%TYPE,
    P_TIEMPO_ESTIMADO_HORAS IN  PLAN_PRODUCCION.TIEMPO_ESTIMADO_HORAS%TYPE
  ) AS
  BEGIN
    UPDATE PLAN_PRODUCCION
    SET PRODUCTO_ID           = P_PRODUCTO_ID,
        CANTIDAD              = P_CANTIDAD,
        PERIODO_INICIO        = P_PERIODO_INICIO,
        PERIODO_FIN           = P_PERIODO_FIN,
        TIEMPO_ESTIMADO_HORAS = P_TIEMPO_ESTIMADO_HORAS,
        UPDATED_AT            = SYSTIMESTAMP
    WHERE PLAN_PRODUCCION_ID = P_PLAN_PRODUCCION_ID;
  END SP_ACTUALIZAR_PLAN_PRODUCCION;

  PROCEDURE SP_ELIMINAR_PLAN_PRODUCCION(
    P_PLAN_PRODUCCION_ID IN PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE
  ) AS
  BEGIN
    UPDATE PLAN_PRODUCCION
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE PLAN_PRODUCCION_ID = P_PLAN_PRODUCCION_ID;
  END SP_ELIMINAR_PLAN_PRODUCCION;

  PROCEDURE SP_OBTENER_PLAN_PRODUCCION(
    P_PLAN_PRODUCCION_ID IN  PLAN_PRODUCCION.PLAN_PRODUCCION_ID%TYPE,
    P_CURSOR             OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PLAN_PRODUCCION_ID,
             PRODUCTO_ID,
             CANTIDAD,
             PERIODO_INICIO,
             PERIODO_FIN,
             TIEMPO_ESTIMADO_HORAS,
             ESTADO
      FROM PLAN_PRODUCCION
      WHERE PLAN_PRODUCCION_ID = P_PLAN_PRODUCCION_ID;
  END SP_OBTENER_PLAN_PRODUCCION;

  PROCEDURE SP_LISTAR_PLAN_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PP.PLAN_PRODUCCION_ID,
             PP.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             PP.CANTIDAD,
             PP.PERIODO_INICIO,
             PP.PERIODO_FIN,
             PP.TIEMPO_ESTIMADO_HORAS,
             PP.ESTADO
      FROM PLAN_PRODUCCION PP
      JOIN PRODUCTO P ON P.PRODUCTO_ID = PP.PRODUCTO_ID
      WHERE PP.ESTADO = 'ACTIVO'
      ORDER BY PP.PERIODO_INICIO DESC;
  END SP_LISTAR_PLAN_PRODUCCION;

  PROCEDURE SP_BUSCAR_PLAN_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PP.PLAN_PRODUCCION_ID,
             PP.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             PP.CANTIDAD,
             PP.PERIODO_INICIO,
             PP.PERIODO_FIN,
             PP.TIEMPO_ESTIMADO_HORAS,
             PP.ESTADO
      FROM PLAN_PRODUCCION PP
      JOIN PRODUCTO P ON P.PRODUCTO_ID = PP.PRODUCTO_ID
      WHERE PP.ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'PRODUCTO' AND UPPER(P.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'PERIODO'  AND TO_CHAR(PP.PERIODO_INICIO, 'YYYY-MM-DD') LIKE '%' || P_VALOR || '%')
      )
      ORDER BY PP.PERIODO_INICIO DESC;
  END SP_BUSCAR_PLAN_PRODUCCION;

END PKG_PLAN_PRODUCCION;
/
