CREATE OR REPLACE PACKAGE PKG_SEGUIMIENTO_ENVIO AS

  PROCEDURE SP_INSERTAR_SEGUIMIENTO_ENVIO(
    P_ENVIO_ID          IN  SEGUIMIENTO_ENVIO.ENVIO_ID%TYPE,
    P_ESTADO_ENVIO_ID   IN  SEGUIMIENTO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_EVENTO_AT         IN  SEGUIMIENTO_ENVIO.EVENTO_AT%TYPE,
    P_UBICACION_TEXTO   IN  SEGUIMIENTO_ENVIO.UBICACION_TEXTO%TYPE,
    P_OBSERVACION       IN  SEGUIMIENTO_ENVIO.OBSERVACION%TYPE,
    P_SEG_ENVIO_ID      OUT SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_SEGUIMIENTO_ENVIO(
    P_SEG_ENVIO_ID      IN  SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE,
    P_ENVIO_ID          IN  SEGUIMIENTO_ENVIO.ENVIO_ID%TYPE,
    P_ESTADO_ENVIO_ID   IN  SEGUIMIENTO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_EVENTO_AT         IN  SEGUIMIENTO_ENVIO.EVENTO_AT%TYPE,
    P_UBICACION_TEXTO   IN  SEGUIMIENTO_ENVIO.UBICACION_TEXTO%TYPE,
    P_OBSERVACION       IN  SEGUIMIENTO_ENVIO.OBSERVACION%TYPE
  );

  PROCEDURE SP_ELIMINAR_SEGUIMIENTO_ENVIO(
    P_SEG_ENVIO_ID IN SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_SEGUIMIENTO_ENVIO(
    P_SEG_ENVIO_ID IN  SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_SEGUIMIENTO_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_SEGUIMIENTO_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_SEGUIMIENTO_ENVIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_SEGUIMIENTO_ENVIO AS

  PROCEDURE SP_INSERTAR_SEGUIMIENTO_ENVIO(
    P_ENVIO_ID          IN  SEGUIMIENTO_ENVIO.ENVIO_ID%TYPE,
    P_ESTADO_ENVIO_ID   IN  SEGUIMIENTO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_EVENTO_AT         IN  SEGUIMIENTO_ENVIO.EVENTO_AT%TYPE,
    P_UBICACION_TEXTO   IN  SEGUIMIENTO_ENVIO.UBICACION_TEXTO%TYPE,
    P_OBSERVACION       IN  SEGUIMIENTO_ENVIO.OBSERVACION%TYPE,
    P_SEG_ENVIO_ID      OUT SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO SEGUIMIENTO_ENVIO (
      ENVIO_ID,
      ESTADO_ENVIO_ID,
      EVENTO_AT,
      UBICACION_TEXTO,
      OBSERVACION,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_ENVIO_ID,
      P_ESTADO_ENVIO_ID,
      P_EVENTO_AT,
      P_UBICACION_TEXTO,
      P_OBSERVACION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING SEG_ENVIO_ID INTO P_SEG_ENVIO_ID;
  END SP_INSERTAR_SEGUIMIENTO_ENVIO;

  PROCEDURE SP_ACTUALIZAR_SEGUIMIENTO_ENVIO(
    P_SEG_ENVIO_ID      IN  SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE,
    P_ENVIO_ID          IN  SEGUIMIENTO_ENVIO.ENVIO_ID%TYPE,
    P_ESTADO_ENVIO_ID   IN  SEGUIMIENTO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_EVENTO_AT         IN  SEGUIMIENTO_ENVIO.EVENTO_AT%TYPE,
    P_UBICACION_TEXTO   IN  SEGUIMIENTO_ENVIO.UBICACION_TEXTO%TYPE,
    P_OBSERVACION       IN  SEGUIMIENTO_ENVIO.OBSERVACION%TYPE
  ) AS
  BEGIN
    UPDATE SEGUIMIENTO_ENVIO
    SET ENVIO_ID        = P_ENVIO_ID,
        ESTADO_ENVIO_ID = P_ESTADO_ENVIO_ID,
        EVENTO_AT       = P_EVENTO_AT,
        UBICACION_TEXTO = P_UBICACION_TEXTO,
        OBSERVACION     = P_OBSERVACION,
        UPDATED_AT      = SYSTIMESTAMP
    WHERE SEG_ENVIO_ID = P_SEG_ENVIO_ID;
  END SP_ACTUALIZAR_SEGUIMIENTO_ENVIO;

  PROCEDURE SP_ELIMINAR_SEGUIMIENTO_ENVIO(
    P_SEG_ENVIO_ID IN SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE
  ) AS
  BEGIN
    UPDATE SEGUIMIENTO_ENVIO
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE SEG_ENVIO_ID = P_SEG_ENVIO_ID;
  END SP_ELIMINAR_SEGUIMIENTO_ENVIO;

  PROCEDURE SP_OBTENER_SEGUIMIENTO_ENVIO(
    P_SEG_ENVIO_ID IN  SEGUIMIENTO_ENVIO.SEG_ENVIO_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT SEG_ENVIO_ID,
             ENVIO_ID,
             ESTADO_ENVIO_ID,
             EVENTO_AT,
             UBICACION_TEXTO,
             OBSERVACION,
             ESTADO
      FROM SEGUIMIENTO_ENVIO
      WHERE SEG_ENVIO_ID = P_SEG_ENVIO_ID;
  END SP_OBTENER_SEGUIMIENTO_ENVIO;

  PROCEDURE SP_LISTAR_SEGUIMIENTO_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT SEG_ENVIO_ID,
             ENVIO_ID,
             ESTADO_ENVIO_ID,
             EVENTO_AT,
             UBICACION_TEXTO,
             ESTADO
      FROM SEGUIMIENTO_ENVIO
      WHERE ESTADO = 'ACTIVO'
      ORDER BY EVENTO_AT DESC;
  END SP_LISTAR_SEGUIMIENTO_ENVIO;

  PROCEDURE SP_BUSCAR_SEGUIMIENTO_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT SEG_ENVIO_ID,
             ENVIO_ID,
             ESTADO_ENVIO_ID,
             EVENTO_AT,
             UBICACION_TEXTO,
             ESTADO
      FROM SEGUIMIENTO_ENVIO
      WHERE ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'ENVIO_ID'        AND TO_CHAR(ENVIO_ID) LIKE '%' || P_VALOR || '%')
        OR
        (UPPER(P_CRITERIO) = 'UBICACION'       AND UPPER(UBICACION_TEXTO) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'OBSERVACION'     AND UPPER(OBSERVACION) LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY EVENTO_AT DESC;
  END SP_BUSCAR_SEGUIMIENTO_ENVIO;

END PKG_SEGUIMIENTO_ENVIO;
/
