CREATE OR REPLACE PACKAGE PKG_FACTURA_DETALLE AS
  PROCEDURE SP_INSERTAR_FACTURA_DETALLE(
    P_FACTURA_ID IN FACTURA_DETALLE.FACTURA_ID%TYPE,
    P_PRODUCTO_ID IN FACTURA_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN FACTURA_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN FACTURA_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE,
    P_TOTAL_LINEA IN FACTURA_DETALLE.TOTAL_LINEA%TYPE,
    P_FACTURA_DET_ID OUT FACTURA_DETALLE.FACTURA_DET_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_FACTURA_DETALLE(
    P_FACTURA_DET_ID IN FACTURA_DETALLE.FACTURA_DET_ID%TYPE,
    P_FACTURA_ID IN FACTURA_DETALLE.FACTURA_ID%TYPE,
    P_PRODUCTO_ID IN FACTURA_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN FACTURA_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN FACTURA_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE,
    P_TOTAL_LINEA IN FACTURA_DETALLE.TOTAL_LINEA%TYPE
  );

  PROCEDURE SP_ELIMINAR_FACTURA_DETALLE(
    P_FACTURA_DET_ID IN FACTURA_DETALLE.FACTURA_DET_ID%TYPE
  );

  PROCEDURE SP_OBTENER_FACTURA_DETALLE(
    P_FACTURA_DET_ID IN  FACTURA_DETALLE.FACTURA_DET_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_FACTURA_DETALLE(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_FACTURA_DETALLE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_FACTURA_DETALLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_FACTURA_DETALLE AS

  PROCEDURE SP_INSERTAR_FACTURA_DETALLE(
    P_FACTURA_ID IN FACTURA_DETALLE.FACTURA_ID%TYPE,
    P_PRODUCTO_ID IN FACTURA_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN FACTURA_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN FACTURA_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE,
    P_TOTAL_LINEA IN FACTURA_DETALLE.TOTAL_LINEA%TYPE,
    P_FACTURA_DET_ID OUT FACTURA_DETALLE.FACTURA_DET_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO FACTURA_DETALLE (
      FACTURA_ID,
      PRODUCTO_ID,
      CANTIDAD,
      PRECIO_UNITARIO_SNAPSHOT,
      TOTAL_LINEA,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_FACTURA_ID,
      P_PRODUCTO_ID,
      P_CANTIDAD,
      P_PRECIO_UNITARIO_SNAPSHOT,
      P_TOTAL_LINEA,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING FACTURA_DET_ID INTO P_FACTURA_DET_ID;
  END SP_INSERTAR_FACTURA_DETALLE;

  PROCEDURE SP_ACTUALIZAR_FACTURA_DETALLE(
    P_FACTURA_DET_ID IN FACTURA_DETALLE.FACTURA_DET_ID%TYPE,
    P_FACTURA_ID IN FACTURA_DETALLE.FACTURA_ID%TYPE,
    P_PRODUCTO_ID IN FACTURA_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD IN FACTURA_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO_SNAPSHOT IN FACTURA_DETALLE.PRECIO_UNITARIO_SNAPSHOT%TYPE,
    P_TOTAL_LINEA IN FACTURA_DETALLE.TOTAL_LINEA%TYPE
  ) AS
  BEGIN
    UPDATE FACTURA_DETALLE
    SET         FACTURA_ID = P_FACTURA_ID,
        PRODUCTO_ID = P_PRODUCTO_ID,
        CANTIDAD = P_CANTIDAD,
        PRECIO_UNITARIO_SNAPSHOT = P_PRECIO_UNITARIO_SNAPSHOT,
        TOTAL_LINEA = P_TOTAL_LINEA,
        UPDATED_AT = SYSTIMESTAMP
    WHERE FACTURA_DET_ID = P_FACTURA_DET_ID;
  END SP_ACTUALIZAR_FACTURA_DETALLE;

  PROCEDURE SP_ELIMINAR_FACTURA_DETALLE(
    P_FACTURA_DET_ID IN FACTURA_DETALLE.FACTURA_DET_ID%TYPE
  ) AS
  BEGIN
    UPDATE FACTURA_DETALLE
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE FACTURA_DET_ID = P_FACTURA_DET_ID;
  END SP_ELIMINAR_FACTURA_DETALLE;

  PROCEDURE SP_OBTENER_FACTURA_DETALLE(
    P_FACTURA_DET_ID IN  FACTURA_DETALLE.FACTURA_DET_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              FACTURA_DET_ID,
             FACTURA_ID,
             PRODUCTO_ID,
             CANTIDAD,
             TOTAL_LINEA,
             ESTADO
      FROM FACTURA_DETALLE
      WHERE FACTURA_DET_ID = P_FACTURA_DET_ID;
  END SP_OBTENER_FACTURA_DETALLE;

  PROCEDURE SP_LISTAR_FACTURA_DETALLE(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              FACTURA_DET_ID,
             FACTURA_ID,
             PRODUCTO_ID,
             CANTIDAD,
             TOTAL_LINEA,
             ESTADO
      FROM FACTURA_DETALLE
      WHERE ESTADO = 'ACTIVO'
      ORDER BY FACTURA_ID;
  END SP_LISTAR_FACTURA_DETALLE;

  PROCEDURE SP_BUSCAR_FACTURA_DETALLE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              FACTURA_DET_ID,
             FACTURA_ID,
             PRODUCTO_ID,
             CANTIDAD,
             TOTAL_LINEA,
             ESTADO
      FROM FACTURA_DETALLE
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'FACTURA_ID' AND UPPER(CAST(FACTURA_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY FACTURA_ID;
  END SP_BUSCAR_FACTURA_DETALLE;

END PKG_FACTURA_DETALLE;
/
