CREATE OR REPLACE PACKAGE PKG_ESTADO_ORDEN AS

  PROCEDURE SP_INSERTAR(
      P_NOMBRE        IN ESTADO_ORDEN.NOMBRE%TYPE,
      P_DESCRIPCION   IN ESTADO_ORDEN.DESCRIPCION%TYPE,
      P_ID            OUT ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR(
      P_ID            IN ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE,
      P_NOMBRE        IN ESTADO_ORDEN.NOMBRE%TYPE,
      P_DESCRIPCION   IN ESTADO_ORDEN.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR(
      P_ID IN ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE
  );

  PROCEDURE SP_OBTENER(
      P_ID     IN ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE,
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR(
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR(
      P_NOMBRE IN VARCHAR2,
      P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_ESTADO_ORDEN;
/

CREATE OR REPLACE PACKAGE BODY PKG_ESTADO_ORDEN AS


PROCEDURE SP_INSERTAR(
    P_NOMBRE        IN ESTADO_ORDEN.NOMBRE%TYPE,
    P_DESCRIPCION   IN ESTADO_ORDEN.DESCRIPCION%TYPE,
    P_ID            OUT ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE
) AS
BEGIN

    INSERT INTO ESTADO_ORDEN
    (
        NOMBRE,
        DESCRIPCION,
        ESTADO
    )
    VALUES
    (
        P_NOMBRE,
        P_DESCRIPCION,
        'A'
    )
    RETURNING ESTADO_ORDEN_ID INTO P_ID;

END SP_INSERTAR;



PROCEDURE SP_ACTUALIZAR(
    P_ID            IN ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE,
    P_NOMBRE        IN ESTADO_ORDEN.NOMBRE%TYPE,
    P_DESCRIPCION   IN ESTADO_ORDEN.DESCRIPCION%TYPE
) AS
BEGIN

    UPDATE ESTADO_ORDEN
    SET
        NOMBRE = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION
    WHERE ESTADO_ORDEN_ID = P_ID;

END SP_ACTUALIZAR;



PROCEDURE SP_ELIMINAR(
    P_ID IN ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE
) AS
BEGIN

    UPDATE ESTADO_ORDEN
    SET ESTADO = 'I'
    WHERE ESTADO_ORDEN_ID = P_ID;

END SP_ELIMINAR;



PROCEDURE SP_OBTENER(
    P_ID     IN ESTADO_ORDEN.ESTADO_ORDEN_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ESTADO_ORDEN_ID,
            NOMBRE,
            DESCRIPCION,
            ESTADO
        FROM ESTADO_ORDEN
        WHERE ESTADO_ORDEN_ID = P_ID;

END SP_OBTENER;



PROCEDURE SP_LISTAR(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ESTADO_ORDEN_ID,
            NOMBRE,
            DESCRIPCION,
            ESTADO
        FROM ESTADO_ORDEN
        WHERE ESTADO = 'A'
        ORDER BY NOMBRE;

END SP_LISTAR;



PROCEDURE SP_BUSCAR(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ESTADO_ORDEN_ID,
            NOMBRE,
            DESCRIPCION,
            ESTADO
        FROM ESTADO_ORDEN
        WHERE UPPER(NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%'
        AND ESTADO = 'A'
        ORDER BY NOMBRE;

END SP_BUSCAR;


END PKG_ESTADO_ORDEN;
/