CREATE OR REPLACE PACKAGE PKG_MANTENIMIENTO_HERRAMIENTA AS

  PROCEDURE SP_INSERTAR_MANTENIMIENTO_HERRAMIENTA(
    P_HERR_ID              IN MANTENIMIENTO_HERRAMIENTA.HERR_ID%TYPE,
    P_FECHA_MANTENIMIENTO  IN MANTENIMIENTO_HERRAMIENTA.FECHA_MANTENIMIENTO%TYPE,
    P_TIPO_MANTENIMIENTO   IN MANTENIMIENTO_HERRAMIENTA.TIPO_MANTENIMIENTO%TYPE,
    P_DESCRIPCION          IN MANTENIMIENTO_HERRAMIENTA.DESCRIPCION%TYPE,
    P_RESPONSABLE          IN MANTENIMIENTO_HERRAMIENTA.RESPONSABLE%TYPE,
    P_ESTADO               IN MANTENIMIENTO_HERRAMIENTA.ESTADO%TYPE,
    P_MANT_HERR_ID         OUT MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_MANTENIMIENTO_HERRAMIENTA(
    P_MANT_HERR_ID         IN MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE,
    P_HERR_ID              IN MANTENIMIENTO_HERRAMIENTA.HERR_ID%TYPE,
    P_FECHA_MANTENIMIENTO  IN MANTENIMIENTO_HERRAMIENTA.FECHA_MANTENIMIENTO%TYPE,
    P_TIPO_MANTENIMIENTO   IN MANTENIMIENTO_HERRAMIENTA.TIPO_MANTENIMIENTO%TYPE,
    P_DESCRIPCION          IN MANTENIMIENTO_HERRAMIENTA.DESCRIPCION%TYPE,
    P_RESPONSABLE          IN MANTENIMIENTO_HERRAMIENTA.RESPONSABLE%TYPE,
    P_ESTADO               IN MANTENIMIENTO_HERRAMIENTA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_MANTENIMIENTO_HERRAMIENTA(
    P_MANT_HERR_ID IN MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE
  );

  PROCEDURE SP_OBTENER_MANTENIMIENTO_HERRAMIENTA(
    P_MANT_HERR_ID IN MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_MANTENIMIENTOS_HERRAMIENTA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_MANTENIMIENTOS_HERRAMIENTA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_MANTENIMIENTO_HERRAMIENTA;
/

CREATE OR REPLACE PACKAGE BODY PKG_MANTENIMIENTO_HERRAMIENTA AS

  PROCEDURE SP_INSERTAR_MANTENIMIENTO_HERRAMIENTA(
    P_HERR_ID              IN MANTENIMIENTO_HERRAMIENTA.HERR_ID%TYPE,
    P_FECHA_MANTENIMIENTO  IN MANTENIMIENTO_HERRAMIENTA.FECHA_MANTENIMIENTO%TYPE,
    P_TIPO_MANTENIMIENTO   IN MANTENIMIENTO_HERRAMIENTA.TIPO_MANTENIMIENTO%TYPE,
    P_DESCRIPCION          IN MANTENIMIENTO_HERRAMIENTA.DESCRIPCION%TYPE,
    P_RESPONSABLE          IN MANTENIMIENTO_HERRAMIENTA.RESPONSABLE%TYPE,
    P_ESTADO               IN MANTENIMIENTO_HERRAMIENTA.ESTADO%TYPE,
    P_MANT_HERR_ID         OUT MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO MANTENIMIENTO_HERRAMIENTA (
      HERR_ID,
      FECHA_MANTENIMIENTO,
      TIPO_MANTENIMIENTO,
      DESCRIPCION,
      RESPONSABLE,
      ESTADO,
      CREATED_AT
    )
    VALUES (
      P_HERR_ID,
      P_FECHA_MANTENIMIENTO,
      P_TIPO_MANTENIMIENTO,
      P_DESCRIPCION,
      P_RESPONSABLE,
      P_ESTADO,
      SYSTIMESTAMP
    )
    RETURNING MANT_HERR_ID INTO P_MANT_HERR_ID;
  END SP_INSERTAR_MANTENIMIENTO_HERRAMIENTA;


  PROCEDURE SP_ACTUALIZAR_MANTENIMIENTO_HERRAMIENTA(
    P_MANT_HERR_ID         IN MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE,
    P_HERR_ID              IN MANTENIMIENTO_HERRAMIENTA.HERR_ID%TYPE,
    P_FECHA_MANTENIMIENTO  IN MANTENIMIENTO_HERRAMIENTA.FECHA_MANTENIMIENTO%TYPE,
    P_TIPO_MANTENIMIENTO   IN MANTENIMIENTO_HERRAMIENTA.TIPO_MANTENIMIENTO%TYPE,
    P_DESCRIPCION          IN MANTENIMIENTO_HERRAMIENTA.DESCRIPCION%TYPE,
    P_RESPONSABLE          IN MANTENIMIENTO_HERRAMIENTA.RESPONSABLE%TYPE,
    P_ESTADO               IN MANTENIMIENTO_HERRAMIENTA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE MANTENIMIENTO_HERRAMIENTA
       SET HERR_ID             = P_HERR_ID,
           FECHA_MANTENIMIENTO = P_FECHA_MANTENIMIENTO,
           TIPO_MANTENIMIENTO  = P_TIPO_MANTENIMIENTO,
           DESCRIPCION         = P_DESCRIPCION,
           RESPONSABLE         = P_RESPONSABLE,
           ESTADO              = P_ESTADO,
           UPDATED_AT          = SYSTIMESTAMP
     WHERE MANT_HERR_ID = P_MANT_HERR_ID;
  END SP_ACTUALIZAR_MANTENIMIENTO_HERRAMIENTA;


  PROCEDURE SP_ELIMINAR_MANTENIMIENTO_HERRAMIENTA(
    P_MANT_HERR_ID IN MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM MANTENIMIENTO_HERRAMIENTA
     WHERE MANT_HERR_ID = P_MANT_HERR_ID;
  END SP_ELIMINAR_MANTENIMIENTO_HERRAMIENTA;


  PROCEDURE SP_OBTENER_MANTENIMIENTO_HERRAMIENTA(
    P_MANT_HERR_ID IN MANTENIMIENTO_HERRAMIENTA.MANT_HERR_ID%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MANT_HERR_ID,
             HERR_ID,
             FECHA_MANTENIMIENTO,
             TIPO_MANTENIMIENTO,
             DESCRIPCION,
             RESPONSABLE,
             ESTADO
        FROM MANTENIMIENTO_HERRAMIENTA
       WHERE MANT_HERR_ID = P_MANT_HERR_ID;
  END SP_OBTENER_MANTENIMIENTO_HERRAMIENTA;


  PROCEDURE SP_LISTAR_MANTENIMIENTOS_HERRAMIENTA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MANT_HERR_ID,
             HERR_ID,
             FECHA_MANTENIMIENTO,
             TIPO_MANTENIMIENTO,
             DESCRIPCION,
             RESPONSABLE,
             ESTADO
        FROM MANTENIMIENTO_HERRAMIENTA
       ORDER BY FECHA_MANTENIMIENTO DESC, MANT_HERR_ID DESC;
  END SP_LISTAR_MANTENIMIENTOS_HERRAMIENTA;


  PROCEDURE SP_BUSCAR_MANTENIMIENTOS_HERRAMIENTA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MANT_HERR_ID,
             HERR_ID,
             FECHA_MANTENIMIENTO,
             TIPO_MANTENIMIENTO,
             DESCRIPCION,
             RESPONSABLE,
             ESTADO
        FROM MANTENIMIENTO_HERRAMIENTA
       WHERE (
             (UPPER(P_CRITERIO) = 'TIPO' AND UPPER(TIPO_MANTENIMIENTO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'RESPONSABLE' AND UPPER(RESPONSABLE) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'HERR_ID' AND TO_CHAR(HERR_ID) LIKE '%' || P_VALOR || '%')
       )
       ORDER BY FECHA_MANTENIMIENTO DESC, MANT_HERR_ID DESC;
  END SP_BUSCAR_MANTENIMIENTOS_HERRAMIENTA;

END PKG_MANTENIMIENTO_HERRAMIENTA;
/