CREATE OR REPLACE PACKAGE PKG_ROL_PERMISO AS

  PROCEDURE SP_ASIGNAR_PERMISO(
    P_ROL_ID     IN ROL_PERMISO.ROL_ID%TYPE,
    P_PERMISO_ID IN ROL_PERMISO.PERMISO_ID%TYPE
  );

  PROCEDURE SP_ELIMINAR_PERMISO_ROL(
    P_ROL_ID     IN ROL_PERMISO.ROL_ID%TYPE,
    P_PERMISO_ID IN ROL_PERMISO.PERMISO_ID%TYPE
  );

  PROCEDURE SP_PERMISOS_POR_ROL(
    P_ROL_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_ROLES_POR_PERMISO(
    P_PERMISO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_ROL_PERMISO;
/

CREATE OR REPLACE PACKAGE BODY PKG_ROL_PERMISO AS


  PROCEDURE SP_ASIGNAR_PERMISO(
    P_ROL_ID     IN ROL_PERMISO.ROL_ID%TYPE,
    P_PERMISO_ID IN ROL_PERMISO.PERMISO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN

    SELECT COUNT(*)
    INTO V_EXISTE
    FROM ROL_PERMISO
    WHERE ROL_ID = P_ROL_ID
    AND PERMISO_ID = P_PERMISO_ID;

    IF V_EXISTE > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'El permiso ya está asignado a este rol'
        );
    END IF;

    INSERT INTO ROL_PERMISO(
        ROL_ID,
        PERMISO_ID,
        CREATED_AT
    )
    VALUES(
        P_ROL_ID,
        P_PERMISO_ID,
        SYSTIMESTAMP
    );

  END SP_ASIGNAR_PERMISO;



  PROCEDURE SP_ELIMINAR_PERMISO_ROL(
    P_ROL_ID     IN ROL_PERMISO.ROL_ID%TYPE,
    P_PERMISO_ID IN ROL_PERMISO.PERMISO_ID%TYPE
  ) AS
  BEGIN

    DELETE FROM ROL_PERMISO
    WHERE ROL_ID = P_ROL_ID
    AND PERMISO_ID = P_PERMISO_ID;

  END SP_ELIMINAR_PERMISO_ROL;



  PROCEDURE SP_PERMISOS_POR_ROL(
    P_ROL_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            P.PERMISO_ID,
            P.NOMBRE,
            P.DESCRIPCION
        FROM PERMISO P
        INNER JOIN ROL_PERMISO RP
            ON P.PERMISO_ID = RP.PERMISO_ID
        WHERE RP.ROL_ID = P_ROL_ID
        ORDER BY P.NOMBRE;

  END SP_PERMISOS_POR_ROL;



  PROCEDURE SP_ROLES_POR_PERMISO(
    P_PERMISO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            R.ROL_ID,
            R.NOMBRE,
            R.DESCRIPCION
        FROM ROL R
        INNER JOIN ROL_PERMISO RP
            ON R.ROL_ID = RP.ROL_ID
        WHERE RP.PERMISO_ID = P_PERMISO_ID
        ORDER BY R.NOMBRE;

  END SP_ROLES_POR_PERMISO;


END PKG_ROL_PERMISO;
/

