CREATE OR REPLACE PACKAGE PKG_PREFERENCIA_CLIENTE AS
  PROCEDURE SP_INSERTAR_PREFERENCIA_CLIENTE(
    P_CLI_ID IN PREFERENCIA_CLIENTE.CLI_ID%TYPE,
    P_CATEGORIA_ID IN PREFERENCIA_CLIENTE.CATEGORIA_ID%TYPE,
    P_PESO_PREFERENCIA IN PREFERENCIA_CLIENTE.PESO_PREFERENCIA%TYPE,
    P_PREF_ID OUT PREFERENCIA_CLIENTE.PREF_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PREFERENCIA_CLIENTE(
    P_PREF_ID IN PREFERENCIA_CLIENTE.PREF_ID%TYPE,
    P_CLI_ID IN PREFERENCIA_CLIENTE.CLI_ID%TYPE,
    P_CATEGORIA_ID IN PREFERENCIA_CLIENTE.CATEGORIA_ID%TYPE,
    P_PESO_PREFERENCIA IN PREFERENCIA_CLIENTE.PESO_PREFERENCIA%TYPE
  );

  PROCEDURE SP_ELIMINAR_PREFERENCIA_CLIENTE(
    P_PREF_ID IN PREFERENCIA_CLIENTE.PREF_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PREFERENCIA_CLIENTE(
    P_PREF_ID IN  PREFERENCIA_CLIENTE.PREF_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PREFERENCIA_CLIENTE(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PREFERENCIA_CLIENTE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PREFERENCIA_CLIENTE;
/

CREATE OR REPLACE PACKAGE BODY PKG_PREFERENCIA_CLIENTE AS

  PROCEDURE SP_INSERTAR_PREFERENCIA_CLIENTE(
    P_CLI_ID IN PREFERENCIA_CLIENTE.CLI_ID%TYPE,
    P_CATEGORIA_ID IN PREFERENCIA_CLIENTE.CATEGORIA_ID%TYPE,
    P_PESO_PREFERENCIA IN PREFERENCIA_CLIENTE.PESO_PREFERENCIA%TYPE,
    P_PREF_ID OUT PREFERENCIA_CLIENTE.PREF_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PREFERENCIA_CLIENTE (
      CLI_ID,
      CATEGORIA_ID,
      PESO_PREFERENCIA,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CLI_ID,
      P_CATEGORIA_ID,
      P_PESO_PREFERENCIA,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING PREF_ID INTO P_PREF_ID;
  END SP_INSERTAR_PREFERENCIA_CLIENTE;

  PROCEDURE SP_ACTUALIZAR_PREFERENCIA_CLIENTE(
    P_PREF_ID IN PREFERENCIA_CLIENTE.PREF_ID%TYPE,
    P_CLI_ID IN PREFERENCIA_CLIENTE.CLI_ID%TYPE,
    P_CATEGORIA_ID IN PREFERENCIA_CLIENTE.CATEGORIA_ID%TYPE,
    P_PESO_PREFERENCIA IN PREFERENCIA_CLIENTE.PESO_PREFERENCIA%TYPE
  ) AS
  BEGIN
    UPDATE PREFERENCIA_CLIENTE
    SET         CLI_ID = P_CLI_ID,
        CATEGORIA_ID = P_CATEGORIA_ID,
        PESO_PREFERENCIA = P_PESO_PREFERENCIA,
        UPDATED_AT = SYSTIMESTAMP
    WHERE PREF_ID = P_PREF_ID;
  END SP_ACTUALIZAR_PREFERENCIA_CLIENTE;

  PROCEDURE SP_ELIMINAR_PREFERENCIA_CLIENTE(
    P_PREF_ID IN PREFERENCIA_CLIENTE.PREF_ID%TYPE
  ) AS
  BEGIN
    UPDATE PREFERENCIA_CLIENTE
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE PREF_ID = P_PREF_ID;
  END SP_ELIMINAR_PREFERENCIA_CLIENTE;

  PROCEDURE SP_OBTENER_PREFERENCIA_CLIENTE(
    P_PREF_ID IN  PREFERENCIA_CLIENTE.PREF_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              PREF_ID,
             CLI_ID,
             CATEGORIA_ID,
             PESO_PREFERENCIA,
             ESTADO
      FROM PREFERENCIA_CLIENTE
      WHERE PREF_ID = P_PREF_ID;
  END SP_OBTENER_PREFERENCIA_CLIENTE;

  PROCEDURE SP_LISTAR_PREFERENCIA_CLIENTE(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              PREF_ID,
             CLI_ID,
             CATEGORIA_ID,
             PESO_PREFERENCIA,
             ESTADO
      FROM PREFERENCIA_CLIENTE
      WHERE ESTADO = 'ACTIVO'
      ORDER BY PREF_ID;
  END SP_LISTAR_PREFERENCIA_CLIENTE;

  PROCEDURE SP_BUSCAR_PREFERENCIA_CLIENTE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              PREF_ID,
             CLI_ID,
             CATEGORIA_ID,
             PESO_PREFERENCIA,
             ESTADO
      FROM PREFERENCIA_CLIENTE
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'CLI_ID' AND UPPER(CAST(CLI_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'CATEGORIA_ID' AND UPPER(CAST(CATEGORIA_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY PREF_ID;
  END SP_BUSCAR_PREFERENCIA_CLIENTE;

END PKG_PREFERENCIA_CLIENTE;
/

