CREATE OR REPLACE PACKAGE PKG_PRECIO_HISTORICO AS

  PROCEDURE SP_INSERTAR_PRECIO_HISTORICO(
    P_PRODUCTO_ID      IN  PRECIO_HISTORICO.PRODUCTO_ID%TYPE,
    P_PRECIO           IN  PRECIO_HISTORICO.PRECIO%TYPE,
    P_VIGENCIA_INICIO  IN  PRECIO_HISTORICO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN     IN  PRECIO_HISTORICO.VIGENCIA_FIN%TYPE,
    P_MOTIVO           IN  PRECIO_HISTORICO.MOTIVO%TYPE,
    P_PRECIO_HIST_ID   OUT PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PRECIO_HISTORICO(
    P_PRECIO_HIST_ID   IN  PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE,
    P_PRODUCTO_ID      IN  PRECIO_HISTORICO.PRODUCTO_ID%TYPE,
    P_PRECIO           IN  PRECIO_HISTORICO.PRECIO%TYPE,
    P_VIGENCIA_INICIO  IN  PRECIO_HISTORICO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN     IN  PRECIO_HISTORICO.VIGENCIA_FIN%TYPE,
    P_MOTIVO           IN  PRECIO_HISTORICO.MOTIVO%TYPE
  );

  PROCEDURE SP_ELIMINAR_PRECIO_HISTORICO(
    P_PRECIO_HIST_ID IN PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PRECIO_HISTORICO(
    P_PRECIO_HIST_ID IN  PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PRECIO_HISTORICO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PRECIO_HISTORICO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PRECIO_HISTORICO;
/

CREATE OR REPLACE PACKAGE BODY PKG_PRECIO_HISTORICO AS

  PROCEDURE SP_INSERTAR_PRECIO_HISTORICO(
    P_PRODUCTO_ID      IN  PRECIO_HISTORICO.PRODUCTO_ID%TYPE,
    P_PRECIO           IN  PRECIO_HISTORICO.PRECIO%TYPE,
    P_VIGENCIA_INICIO  IN  PRECIO_HISTORICO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN     IN  PRECIO_HISTORICO.VIGENCIA_FIN%TYPE,
    P_MOTIVO           IN  PRECIO_HISTORICO.MOTIVO%TYPE,
    P_PRECIO_HIST_ID   OUT PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PRECIO_HISTORICO (
      PRODUCTO_ID,
      PRECIO,
      VIGENCIA_INICIO,
      VIGENCIA_FIN,
      MOTIVO,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_PRODUCTO_ID,
      P_PRECIO,
      P_VIGENCIA_INICIO,
      P_VIGENCIA_FIN,
      P_MOTIVO,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING PRECIO_HIST_ID INTO P_PRECIO_HIST_ID;
  END SP_INSERTAR_PRECIO_HISTORICO;

  PROCEDURE SP_ACTUALIZAR_PRECIO_HISTORICO(
    P_PRECIO_HIST_ID   IN  PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE,
    P_PRODUCTO_ID      IN  PRECIO_HISTORICO.PRODUCTO_ID%TYPE,
    P_PRECIO           IN  PRECIO_HISTORICO.PRECIO%TYPE,
    P_VIGENCIA_INICIO  IN  PRECIO_HISTORICO.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN     IN  PRECIO_HISTORICO.VIGENCIA_FIN%TYPE,
    P_MOTIVO           IN  PRECIO_HISTORICO.MOTIVO%TYPE
  ) AS
  BEGIN
    UPDATE PRECIO_HISTORICO
    SET PRODUCTO_ID     = P_PRODUCTO_ID,
        PRECIO          = P_PRECIO,
        VIGENCIA_INICIO = P_VIGENCIA_INICIO,
        VIGENCIA_FIN    = P_VIGENCIA_FIN,
        MOTIVO          = P_MOTIVO,
        UPDATED_AT      = SYSTIMESTAMP
    WHERE PRECIO_HIST_ID = P_PRECIO_HIST_ID;
  END SP_ACTUALIZAR_PRECIO_HISTORICO;

  PROCEDURE SP_ELIMINAR_PRECIO_HISTORICO(
    P_PRECIO_HIST_ID IN PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE
  ) AS
  BEGIN
    UPDATE PRECIO_HISTORICO
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE PRECIO_HIST_ID = P_PRECIO_HIST_ID;
  END SP_ELIMINAR_PRECIO_HISTORICO;

  PROCEDURE SP_OBTENER_PRECIO_HISTORICO(
    P_PRECIO_HIST_ID IN  PRECIO_HISTORICO.PRECIO_HIST_ID%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PRECIO_HIST_ID,
             PRODUCTO_ID,
             PRECIO,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             MOTIVO,
             ESTADO
      FROM PRECIO_HISTORICO
      WHERE PRECIO_HIST_ID = P_PRECIO_HIST_ID;
  END SP_OBTENER_PRECIO_HISTORICO;

  PROCEDURE SP_LISTAR_PRECIO_HISTORICO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PH.PRECIO_HIST_ID,
             PH.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             PH.PRECIO,
             PH.VIGENCIA_INICIO,
             PH.VIGENCIA_FIN,
             PH.ESTADO
      FROM PRECIO_HISTORICO PH
      JOIN PRODUCTO P ON P.PRODUCTO_ID = PH.PRODUCTO_ID
      WHERE PH.ESTADO = 'ACTIVO'
      ORDER BY PH.VIGENCIA_INICIO DESC;
  END SP_LISTAR_PRECIO_HISTORICO;

  PROCEDURE SP_BUSCAR_PRECIO_HISTORICO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PH.PRECIO_HIST_ID,
             PH.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             PH.PRECIO,
             PH.VIGENCIA_INICIO,
             PH.VIGENCIA_FIN,
             PH.ESTADO
      FROM PRECIO_HISTORICO PH
      JOIN PRODUCTO P ON P.PRODUCTO_ID = PH.PRODUCTO_ID
      WHERE PH.ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'PRODUCTO' AND UPPER(P.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'MOTIVO'   AND UPPER(PH.MOTIVO) LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY PH.VIGENCIA_INICIO DESC;
  END SP_BUSCAR_PRECIO_HISTORICO;

END PKG_PRECIO_HISTORICO;
/
