CREATE OR REPLACE PACKAGE PKG_CONTROL_CALIDAD AS

  PROCEDURE SP_INSERTAR_CONTROL_CALIDAD(
    P_OP_ID               IN CONTROL_CALIDAD.OP_ID%TYPE,
    P_FECHA_CONTROL       IN CONTROL_CALIDAD.FECHA_CONTROL%TYPE,
    P_RESULTADO           IN CONTROL_CALIDAD.RESULTADO%TYPE,
    P_OBSERVACIONES       IN CONTROL_CALIDAD.OBSERVACIONES%TYPE,
    P_RESPONSABLE         IN CONTROL_CALIDAD.RESPONSABLE%TYPE,
    P_CC_ID               OUT CONTROL_CALIDAD.CC_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CONTROL_CALIDAD(
    P_CC_ID               IN CONTROL_CALIDAD.CC_ID%TYPE,
    P_OP_ID               IN CONTROL_CALIDAD.OP_ID%TYPE,
    P_FECHA_CONTROL       IN CONTROL_CALIDAD.FECHA_CONTROL%TYPE,
    P_RESULTADO           IN CONTROL_CALIDAD.RESULTADO%TYPE,
    P_OBSERVACIONES       IN CONTROL_CALIDAD.OBSERVACIONES%TYPE,
    P_RESPONSABLE         IN CONTROL_CALIDAD.RESPONSABLE%TYPE
  );

  PROCEDURE SP_ELIMINAR_CONTROL_CALIDAD(
    P_CC_ID IN CONTROL_CALIDAD.CC_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CONTROL_CALIDAD(
    P_CC_ID  IN CONTROL_CALIDAD.CC_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CONTROLES_CALIDAD(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CONTROLES_CALIDAD(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CONTROL_CALIDAD;
/

CREATE OR REPLACE PACKAGE BODY PKG_CONTROL_CALIDAD AS

  PROCEDURE SP_INSERTAR_CONTROL_CALIDAD(
    P_OP_ID               IN CONTROL_CALIDAD.OP_ID%TYPE,
    P_FECHA_CONTROL       IN CONTROL_CALIDAD.FECHA_CONTROL%TYPE,
    P_RESULTADO           IN CONTROL_CALIDAD.RESULTADO%TYPE,
    P_OBSERVACIONES       IN CONTROL_CALIDAD.OBSERVACIONES%TYPE,
    P_RESPONSABLE         IN CONTROL_CALIDAD.RESPONSABLE%TYPE,
    P_CC_ID               OUT CONTROL_CALIDAD.CC_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CONTROL_CALIDAD (
      OP_ID,
      FECHA_CONTROL,
      RESULTADO,
      OBSERVACIONES,
      RESPONSABLE,
      CREATED_AT
    )
    VALUES (
      P_OP_ID,
      P_FECHA_CONTROL,
      P_RESULTADO,
      P_OBSERVACIONES,
      P_RESPONSABLE,
      SYSTIMESTAMP
    )
    RETURNING CC_ID INTO P_CC_ID;
  END SP_INSERTAR_CONTROL_CALIDAD;


  PROCEDURE SP_ACTUALIZAR_CONTROL_CALIDAD(
    P_CC_ID               IN CONTROL_CALIDAD.CC_ID%TYPE,
    P_OP_ID               IN CONTROL_CALIDAD.OP_ID%TYPE,
    P_FECHA_CONTROL       IN CONTROL_CALIDAD.FECHA_CONTROL%TYPE,
    P_RESULTADO           IN CONTROL_CALIDAD.RESULTADO%TYPE,
    P_OBSERVACIONES       IN CONTROL_CALIDAD.OBSERVACIONES%TYPE,
    P_RESPONSABLE         IN CONTROL_CALIDAD.RESPONSABLE%TYPE
  ) AS
  BEGIN
    UPDATE CONTROL_CALIDAD
       SET OP_ID         = P_OP_ID,
           FECHA_CONTROL = P_FECHA_CONTROL,
           RESULTADO     = P_RESULTADO,
           OBSERVACIONES = P_OBSERVACIONES,
           RESPONSABLE   = P_RESPONSABLE,
           UPDATED_AT    = SYSTIMESTAMP
     WHERE CC_ID = P_CC_ID;
  END SP_ACTUALIZAR_CONTROL_CALIDAD;


  PROCEDURE SP_ELIMINAR_CONTROL_CALIDAD(
    P_CC_ID IN CONTROL_CALIDAD.CC_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM CONTROL_CALIDAD
     WHERE CC_ID = P_CC_ID;
  END SP_ELIMINAR_CONTROL_CALIDAD;


  PROCEDURE SP_OBTENER_CONTROL_CALIDAD(
    P_CC_ID  IN CONTROL_CALIDAD.CC_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CC_ID,
             OP_ID,
             FECHA_CONTROL,
             RESULTADO,
             OBSERVACIONES,
             RESPONSABLE
        FROM CONTROL_CALIDAD
       WHERE CC_ID = P_CC_ID;
  END SP_OBTENER_CONTROL_CALIDAD;


  PROCEDURE SP_LISTAR_CONTROLES_CALIDAD(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CC_ID,
             OP_ID,
             FECHA_CONTROL,
             RESULTADO,
             OBSERVACIONES,
             RESPONSABLE
        FROM CONTROL_CALIDAD
       ORDER BY FECHA_CONTROL DESC, CC_ID DESC;
  END SP_LISTAR_CONTROLES_CALIDAD;


  PROCEDURE SP_BUSCAR_CONTROLES_CALIDAD(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CC_ID,
             OP_ID,
             FECHA_CONTROL,
             RESULTADO,
             OBSERVACIONES,
             RESPONSABLE
        FROM CONTROL_CALIDAD
       WHERE (
             (UPPER(P_CRITERIO) = 'OP_ID' AND TO_CHAR(OP_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'RESULTADO' AND UPPER(RESULTADO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'RESPONSABLE' AND UPPER(RESPONSABLE) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY FECHA_CONTROL DESC, CC_ID DESC;
  END SP_BUSCAR_CONTROLES_CALIDAD;

END PKG_CONTROL_CALIDAD;
/