CREATE OR REPLACE PACKAGE PKG_TIPO_ENTREGA AS

  PROCEDURE SP_INSERTAR_TIPO_ENTREGA(
    P_NOMBRE            IN TIPO_ENTREGA.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_ENTREGA.DESCRIPCION%TYPE,
    P_TIPO_ENTREGA_ID   OUT TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_TIPO_ENTREGA(
    P_TIPO_ENTREGA_ID   IN TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE,
    P_NOMBRE            IN TIPO_ENTREGA.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_ENTREGA.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_TIPO_ENTREGA(
    P_TIPO_ENTREGA_ID IN TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_TIPO_ENTREGA(
    P_TIPO_ENTREGA_ID IN TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_TIPO_ENTREGA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_TIPO_ENTREGA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_TIPO_ENTREGA;
/

CREATE OR REPLACE PACKAGE BODY PKG_TIPO_ENTREGA AS

  PROCEDURE SP_INSERTAR_TIPO_ENTREGA(
    P_NOMBRE            IN TIPO_ENTREGA.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_ENTREGA.DESCRIPCION%TYPE,
    P_TIPO_ENTREGA_ID   OUT TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO TIPO_ENTREGA (
      NOMBRE,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_NOMBRE,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING TIPO_ENTREGA_ID INTO P_TIPO_ENTREGA_ID;
  END SP_INSERTAR_TIPO_ENTREGA;

  PROCEDURE SP_ACTUALIZAR_TIPO_ENTREGA(
    P_TIPO_ENTREGA_ID   IN TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE,
    P_NOMBRE            IN TIPO_ENTREGA.NOMBRE%TYPE,
    P_DESCRIPCION       IN TIPO_ENTREGA.DESCRIPCION%TYPE
  ) AS
  BEGIN
    UPDATE TIPO_ENTREGA
       SET NOMBRE      = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT  = SYSTIMESTAMP
     WHERE TIPO_ENTREGA_ID = P_TIPO_ENTREGA_ID;
  END SP_ACTUALIZAR_TIPO_ENTREGA;

  PROCEDURE SP_ELIMINAR_TIPO_ENTREGA(
    P_TIPO_ENTREGA_ID IN TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM (
        SELECT TIPO_ENTREGA_ID FROM TARIFA_ENVIO WHERE TIPO_ENTREGA_ID = P_TIPO_ENTREGA_ID
        UNION ALL
        SELECT TIPO_ENTREGA_ID FROM ENVIO WHERE TIPO_ENTREGA_ID = P_TIPO_ENTREGA_ID
      );

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el tipo de entrega porque tiene registros asociados.');
    END IF;

    UPDATE TIPO_ENTREGA
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE TIPO_ENTREGA_ID = P_TIPO_ENTREGA_ID;
  END SP_ELIMINAR_TIPO_ENTREGA;

  PROCEDURE SP_OBTENER_TIPO_ENTREGA(
    P_TIPO_ENTREGA_ID IN TIPO_ENTREGA.TIPO_ENTREGA_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT TIPO_ENTREGA_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM TIPO_ENTREGA
       WHERE TIPO_ENTREGA_ID = P_TIPO_ENTREGA_ID;
  END SP_OBTENER_TIPO_ENTREGA;

  PROCEDURE SP_LISTAR_TIPO_ENTREGA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT TIPO_ENTREGA_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM TIPO_ENTREGA
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;
  END SP_LISTAR_TIPO_ENTREGA;

  PROCEDURE SP_BUSCAR_TIPO_ENTREGA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT TIPO_ENTREGA_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM TIPO_ENTREGA
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY NOMBRE;
  END SP_BUSCAR_TIPO_ENTREGA;

END PKG_TIPO_ENTREGA;
/
