CREATE OR REPLACE PACKAGE PKG_EMPLEADO AS

  PROCEDURE SP_INSERTAR_EMPLEADO(
    P_NOMBRES        IN EMPLEADO.NOMBRES%TYPE,
    P_APELLIDOS      IN EMPLEADO.APELLIDOS%TYPE,
    P_EMAIL          IN EMPLEADO.EMAIL%TYPE,
    P_TELEFONO       IN EMPLEADO.TELEFONO%TYPE,
    P_DIRECCION      IN EMPLEADO.DIRECCION%TYPE,
    P_DEPARTAMENTO_ID IN EMPLEADO.DEPARTAMENTO_ID%TYPE,
    P_CARGO_ID       IN EMPLEADO.CARGO_ID%TYPE,
    P_ROL_ID         IN EMPLEADO.ROL_ID%TYPE,
    P_EMPLEADO_ID    OUT EMPLEADO.EMPLEADO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_EMPLEADO(
    P_EMPLEADO_ID     IN EMPLEADO.EMPLEADO_ID%TYPE,
    P_NOMBRES         IN EMPLEADO.NOMBRES%TYPE,
    P_APELLIDOS       IN EMPLEADO.APELLIDOS%TYPE,
    P_EMAIL           IN EMPLEADO.EMAIL%TYPE,
    P_TELEFONO        IN EMPLEADO.TELEFONO%TYPE,
    P_DIRECCION       IN EMPLEADO.DIRECCION%TYPE,
    P_DEPARTAMENTO_ID IN EMPLEADO.DEPARTAMENTO_ID%TYPE,
    P_CARGO_ID        IN EMPLEADO.CARGO_ID%TYPE,
    P_ROL_ID          IN EMPLEADO.ROL_ID%TYPE
  );

  PROCEDURE SP_ELIMINAR_EMPLEADO(
    P_EMPLEADO_ID IN EMPLEADO.EMPLEADO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_EMPLEADO(
    P_EMPLEADO_ID IN EMPLEADO.EMPLEADO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_EMPLEADOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_EMPLEADO;
/

CREATE OR REPLACE PACKAGE BODY PKG_EMPLEADO AS

  PROCEDURE SP_INSERTAR_EMPLEADO(
    P_NOMBRES,
    P_APELLIDOS,
    P_EMAIL,
    P_TELEFONO,
    P_DIRECCION,
    P_DEPARTAMENTO_ID,
    P_CARGO_ID,
    P_ROL_ID,
    P_EMPLEADO_ID
  ) AS
  BEGIN

    INSERT INTO EMPLEADO(
        NOMBRES,
        APELLIDOS,
        EMAIL,
        TELEFONO,
        DIRECCION,
        DEPARTAMENTO_ID,
        CARGO_ID,
        ROL_ID,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_NOMBRES,
        P_APELLIDOS,
        P_EMAIL,
        P_TELEFONO,
        P_DIRECCION,
        P_DEPARTAMENTO_ID,
        P_CARGO_ID,
        P_ROL_ID,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING EMPLEADO_ID INTO P_EMPLEADO_ID;

  END SP_INSERTAR_EMPLEADO;


  PROCEDURE SP_ACTUALIZAR_EMPLEADO(
    P_EMPLEADO_ID,
    P_NOMBRES,
    P_APELLIDOS,
    P_EMAIL,
    P_TELEFONO,
    P_DIRECCION,
    P_DEPARTAMENTO_ID,
    P_CARGO_ID,
    P_ROL_ID
  ) AS
  BEGIN

    UPDATE EMPLEADO
       SET NOMBRES = P_NOMBRES,
           APELLIDOS = P_APELLIDOS,
           EMAIL = P_EMAIL,
           TELEFONO = P_TELEFONO,
           DIRECCION = P_DIRECCION,
           DEPARTAMENTO_ID = P_DEPARTAMENTO_ID,
           CARGO_ID = P_CARGO_ID,
           ROL_ID = P_ROL_ID,
           UPDATED_AT = SYSTIMESTAMP
     WHERE EMPLEADO_ID = P_EMPLEADO_ID;

  END SP_ACTUALIZAR_EMPLEADO;


  PROCEDURE SP_ELIMINAR_EMPLEADO(
    P_EMPLEADO_ID IN EMPLEADO.EMPLEADO_ID%TYPE
  ) AS
  BEGIN

    UPDATE EMPLEADO
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE EMPLEADO_ID = P_EMPLEADO_ID;

  END SP_ELIMINAR_EMPLEADO;


  PROCEDURE SP_OBTENER_EMPLEADO(
    P_EMPLEADO_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT E.EMPLEADO_ID,
             E.NOMBRES,
             E.APELLIDOS,
             E.EMAIL,
             E.TELEFONO,
             E.DIRECCION,
             D.NOMBRE AS DEPARTAMENTO,
             C.NOMBRE AS CARGO,
             R.NOMBRE AS ROL,
             E.ESTADO
        FROM EMPLEADO E
        JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.DEPTO_ID
        JOIN CARGO C ON E.CARGO_ID = C.CARGO_ID
        JOIN ROL_EMPLEADO R ON E.ROL_ID = R.ROL_ID
       WHERE E.EMPLEADO_ID = P_EMPLEADO_ID;

  END SP_OBTENER_EMPLEADO;


  PROCEDURE SP_LISTAR_EMPLEADOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT E.EMPLEADO_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS NOMBRE_COMPLETO,
             E.EMAIL,
             D.NOMBRE AS DEPARTAMENTO,
             C.NOMBRE AS CARGO,
             R.NOMBRE AS ROL,
             E.ESTADO
        FROM EMPLEADO E
        JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.DEPTO_ID
        JOIN CARGO C ON E.CARGO_ID = C.CARGO_ID
        JOIN ROL_EMPLEADO R ON E.ROL_ID = R.ROL_ID
       WHERE E.ESTADO = 'ACTIVO'
       ORDER BY NOMBRES;

  END SP_LISTAR_EMPLEADOS;

END PKG_EMPLEADO;
/