CREATE OR REPLACE PACKAGE PKG_HISTORIAL_PRECIO_MP_PROV AS

  PROCEDURE SP_INSERTAR_HISTORIAL_PRECIO(
    P_PROVEEDOR_ID        IN HISTORIAL_PRECIO_MP_PROV.PROVEEDOR_ID%TYPE,
    P_MATERIA_PRIMA_ID    IN HISTORIAL_PRECIO_MP_PROV.MATERIA_PRIMA_ID%TYPE,
    P_PRECIO              IN HISTORIAL_PRECIO_MP_PROV.PRECIO%TYPE,
    P_FECHA               IN HISTORIAL_PRECIO_MP_PROV.FECHA%TYPE,
    P_HISTORIAL_ID        OUT HISTORIAL_PRECIO_MP_PROV.HISTORIAL_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_HISTORIAL_PRECIO(
    P_HISTORIAL_ID        IN HISTORIAL_PRECIO_MP_PROV.HISTORIAL_ID%TYPE,
    P_PRECIO              IN HISTORIAL_PRECIO_MP_PROV.PRECIO%TYPE
  );

  PROCEDURE SP_ELIMINAR_HISTORIAL_PRECIO(
    P_HISTORIAL_ID IN HISTORIAL_PRECIO_MP_PROV.HISTORIAL_ID%TYPE
  );

  PROCEDURE SP_LISTAR_HISTORIAL_PRECIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_HISTORIAL_PRECIO_MP_PROV;
/

CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_PRECIO_MP_PROV AS

  PROCEDURE SP_INSERTAR_HISTORIAL_PRECIO(
    P_PROVEEDOR_ID,
    P_MATERIA_PRIMA_ID,
    P_PRECIO,
    P_FECHA,
    P_HISTORIAL_ID
  ) AS
  BEGIN

    INSERT INTO HISTORIAL_PRECIO_MP_PROV(
        PROVEEDOR_ID,
        MATERIA_PRIMA_ID,
        PRECIO,
        FECHA,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_PROVEEDOR_ID,
        P_MATERIA_PRIMA_ID,
        P_PRECIO,
        P_FECHA,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING HISTORIAL_ID INTO P_HISTORIAL_ID;

  END SP_INSERTAR_HISTORIAL_PRECIO;



  PROCEDURE SP_ACTUALIZAR_HISTORIAL_PRECIO(
    P_HISTORIAL_ID,
    P_PRECIO
  ) AS
  BEGIN

    UPDATE HISTORIAL_PRECIO_MP_PROV
       SET PRECIO = P_PRECIO,
           UPDATED_AT = SYSTIMESTAMP
     WHERE HISTORIAL_ID = P_HISTORIAL_ID;

  END SP_ACTUALIZAR_HISTORIAL_PRECIO;



  PROCEDURE SP_ELIMINAR_HISTORIAL_PRECIO(
    P_HISTORIAL_ID
  ) AS
  BEGIN

    UPDATE HISTORIAL_PRECIO_MP_PROV
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE HISTORIAL_ID = P_HISTORIAL_ID;

  END SP_ELIMINAR_HISTORIAL_PRECIO;



  PROCEDURE SP_LISTAR_HISTORIAL_PRECIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT H.HISTORIAL_ID,
             P.NOMBRE AS PROVEEDOR,
             M.NOMBRE AS MATERIA_PRIMA,
             H.PRECIO,
             H.FECHA
        FROM HISTORIAL_PRECIO_MP_PROV H
        JOIN PROVEEDOR P ON H.PROVEEDOR_ID = P.PROVEEDOR_ID
        JOIN MATERIA_PRIMA M ON H.MATERIA_PRIMA_ID = M.MATERIA_PRIMA_ID
       WHERE H.ESTADO = 'ACTIVO'
       ORDER BY H.FECHA DESC;

  END SP_LISTAR_HISTORIAL_PRECIO;

END PKG_HISTORIAL_PRECIO_MP_PROV;
/