CREATE OR REPLACE PACKAGE PKG_METODO_PAGO AS

  PROCEDURE SP_INSERTAR(
      P_NOMBRE        IN METODO_PAGO.NOMBRE%TYPE,
      P_DESCRIPCION   IN METODO_PAGO.DESCRIPCION%TYPE,
      P_ID            OUT METODO_PAGO.METODO_PAGO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR(
      P_ID            IN METODO_PAGO.METODO_PAGO_ID%TYPE,
      P_NOMBRE        IN METODO_PAGO.NOMBRE%TYPE,
      P_DESCRIPCION   IN METODO_PAGO.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR(
      P_ID IN METODO_PAGO.METODO_PAGO_ID%TYPE
  );

  PROCEDURE SP_OBTENER(
      P_ID     IN METODO_PAGO.METODO_PAGO_ID%TYPE,
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR(
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR(
      P_NOMBRE IN VARCHAR2,
      P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_METODO_PAGO;
/

CREATE OR REPLACE PACKAGE BODY PKG_METODO_PAGO AS


PROCEDURE SP_INSERTAR(
    P_NOMBRE        IN METODO_PAGO.NOMBRE%TYPE,
    P_DESCRIPCION   IN METODO_PAGO.DESCRIPCION%TYPE,
    P_ID            OUT METODO_PAGO.METODO_PAGO_ID%TYPE
) AS
BEGIN

    INSERT INTO METODO_PAGO
    (
        NOMBRE,
        DESCRIPCION,
        ESTADO
    )
    VALUES
    (
        P_NOMBRE,
        P_DESCRIPCION,
        'A'
    )
    RETURNING METODO_PAGO_ID INTO P_ID;

END SP_INSERTAR;



PROCEDURE SP_ACTUALIZAR(
    P_ID            IN METODO_PAGO.METODO_PAGO_ID%TYPE,
    P_NOMBRE        IN METODO_PAGO.NOMBRE%TYPE,
    P_DESCRIPCION   IN METODO_PAGO.DESCRIPCION%TYPE
) AS
BEGIN

    UPDATE METODO_PAGO
    SET
        NOMBRE = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION
    WHERE METODO_PAGO_ID = P_ID;

END SP_ACTUALIZAR;



PROCEDURE SP_ELIMINAR(
    P_ID IN METODO_PAGO.METODO_PAGO_ID%TYPE
) AS
BEGIN

    UPDATE METODO_PAGO
    SET ESTADO = 'I'
    WHERE METODO_PAGO_ID = P_ID;

END SP_ELIMINAR;



PROCEDURE SP_OBTENER(
    P_ID     IN METODO_PAGO.METODO_PAGO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            METODO_PAGO_ID,
            NOMBRE,
            DESCRIPCION,
            ESTADO
        FROM METODO_PAGO
        WHERE METODO_PAGO_ID = P_ID;

END SP_OBTENER;



PROCEDURE SP_LISTAR(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            METODO_PAGO_ID,
            NOMBRE,
            DESCRIPCION,
            ESTADO
        FROM METODO_PAGO
        WHERE ESTADO = 'A'
        ORDER BY NOMBRE;

END SP_LISTAR;



PROCEDURE SP_BUSCAR(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            METODO_PAGO_ID,
            NOMBRE,
            DESCRIPCION,
            ESTADO
        FROM METODO_PAGO
        WHERE UPPER(NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%'
        AND ESTADO = 'A'
        ORDER BY NOMBRE;

END SP_BUSCAR;


END PKG_METODO_PAGO;
/