CREATE OR REPLACE PACKAGE PKG_ORDEN_PRODUCCION AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION(
    P_CODIGO_ORDEN        IN ORDEN_PRODUCCION.CODIGO_ORDEN%TYPE,
    P_PRODUCTO_ID         IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PROGRAMADA IN ORDEN_PRODUCCION.CANTIDAD_PROGRAMADA%TYPE,
    P_FECHA_INICIO        IN ORDEN_PRODUCCION.FECHA_INICIO%TYPE,
    P_FECHA_FIN           IN ORDEN_PRODUCCION.FECHA_FIN%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION.ESTADO%TYPE,
    P_OBSERVACIONES       IN ORDEN_PRODUCCION.OBSERVACIONES%TYPE,
    P_OP_ID               OUT ORDEN_PRODUCCION.OP_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION(
    P_OP_ID               IN ORDEN_PRODUCCION.OP_ID%TYPE,
    P_CODIGO_ORDEN        IN ORDEN_PRODUCCION.CODIGO_ORDEN%TYPE,
    P_PRODUCTO_ID         IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PROGRAMADA IN ORDEN_PRODUCCION.CANTIDAD_PROGRAMADA%TYPE,
    P_FECHA_INICIO        IN ORDEN_PRODUCCION.FECHA_INICIO%TYPE,
    P_FECHA_FIN           IN ORDEN_PRODUCCION.FECHA_FIN%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION.ESTADO%TYPE,
    P_OBSERVACIONES       IN ORDEN_PRODUCCION.OBSERVACIONES%TYPE
  );

  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION(
    P_OP_ID IN ORDEN_PRODUCCION.OP_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION(
    P_OP_ID   IN ORDEN_PRODUCCION.OP_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ORDENES_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ORDENES_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ORDEN_PRODUCCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_ORDEN_PRODUCCION AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION(
    P_CODIGO_ORDEN        IN ORDEN_PRODUCCION.CODIGO_ORDEN%TYPE,
    P_PRODUCTO_ID         IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PROGRAMADA IN ORDEN_PRODUCCION.CANTIDAD_PROGRAMADA%TYPE,
    P_FECHA_INICIO        IN ORDEN_PRODUCCION.FECHA_INICIO%TYPE,
    P_FECHA_FIN           IN ORDEN_PRODUCCION.FECHA_FIN%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION.ESTADO%TYPE,
    P_OBSERVACIONES       IN ORDEN_PRODUCCION.OBSERVACIONES%TYPE,
    P_OP_ID               OUT ORDEN_PRODUCCION.OP_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ORDEN_PRODUCCION (
      CODIGO_ORDEN,
      PRODUCTO_ID,
      CANTIDAD_PROGRAMADA,
      FECHA_INICIO,
      FECHA_FIN,
      ESTADO,
      OBSERVACIONES,
      CREATED_AT
    )
    VALUES (
      P_CODIGO_ORDEN,
      P_PRODUCTO_ID,
      P_CANTIDAD_PROGRAMADA,
      P_FECHA_INICIO,
      P_FECHA_FIN,
      P_ESTADO,
      P_OBSERVACIONES,
      SYSTIMESTAMP
    )
    RETURNING OP_ID INTO P_OP_ID;
  END SP_INSERTAR_ORDEN_PRODUCCION;


  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION(
    P_OP_ID               IN ORDEN_PRODUCCION.OP_ID%TYPE,
    P_CODIGO_ORDEN        IN ORDEN_PRODUCCION.CODIGO_ORDEN%TYPE,
    P_PRODUCTO_ID         IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PROGRAMADA IN ORDEN_PRODUCCION.CANTIDAD_PROGRAMADA%TYPE,
    P_FECHA_INICIO        IN ORDEN_PRODUCCION.FECHA_INICIO%TYPE,
    P_FECHA_FIN           IN ORDEN_PRODUCCION.FECHA_FIN%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION.ESTADO%TYPE,
    P_OBSERVACIONES       IN ORDEN_PRODUCCION.OBSERVACIONES%TYPE
  ) AS
  BEGIN
    UPDATE ORDEN_PRODUCCION
       SET CODIGO_ORDEN        = P_CODIGO_ORDEN,
           PRODUCTO_ID         = P_PRODUCTO_ID,
           CANTIDAD_PROGRAMADA = P_CANTIDAD_PROGRAMADA,
           FECHA_INICIO        = P_FECHA_INICIO,
           FECHA_FIN           = P_FECHA_FIN,
           ESTADO              = P_ESTADO,
           OBSERVACIONES       = P_OBSERVACIONES,
           UPDATED_AT          = SYSTIMESTAMP
     WHERE OP_ID = P_OP_ID;
  END SP_ACTUALIZAR_ORDEN_PRODUCCION;


  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION(
    P_OP_ID IN ORDEN_PRODUCCION.OP_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM ORDEN_PRODUCCION_TAREA
     WHERE OP_ID = P_OP_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la orden de producción porque tiene tareas asociadas.');
    END IF;

    DELETE FROM ORDEN_PRODUCCION
     WHERE OP_ID = P_OP_ID;
  END SP_ELIMINAR_ORDEN_PRODUCCION;


  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION(
    P_OP_ID   IN ORDEN_PRODUCCION.OP_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OP_ID,
             CODIGO_ORDEN,
             PRODUCTO_ID,
             CANTIDAD_PROGRAMADA,
             FECHA_INICIO,
             FECHA_FIN,
             ESTADO,
             OBSERVACIONES
        FROM ORDEN_PRODUCCION
       WHERE OP_ID = P_OP_ID;
  END SP_OBTENER_ORDEN_PRODUCCION;


  PROCEDURE SP_LISTAR_ORDENES_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OP_ID,
             CODIGO_ORDEN,
             PRODUCTO_ID,
             CANTIDAD_PROGRAMADA,
             FECHA_INICIO,
             FECHA_FIN,
             ESTADO,
             OBSERVACIONES
        FROM ORDEN_PRODUCCION
       ORDER BY OP_ID DESC;
  END SP_LISTAR_ORDENES_PRODUCCION;


  PROCEDURE SP_BUSCAR_ORDENES_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OP_ID,
             CODIGO_ORDEN,
             PRODUCTO_ID,
             CANTIDAD_PROGRAMADA,
             FECHA_INICIO,
             FECHA_FIN,
             ESTADO,
             OBSERVACIONES
        FROM ORDEN_PRODUCCION
       WHERE (
             (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO_ORDEN) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'PRODUCTO_ID' AND TO_CHAR(PRODUCTO_ID) LIKE '%' || P_VALOR || '%')
       )
       ORDER BY OP_ID DESC;
  END SP_BUSCAR_ORDENES_PRODUCCION;

END PKG_ORDEN_PRODUCCION;
/