CREATE OR REPLACE PACKAGE PKG_VEHICULO AS

  PROCEDURE SP_INSERTAR_VEHICULO(
    P_PLACA         IN  VEHICULO.PLACA%TYPE,
    P_TIPO          IN  VEHICULO.TIPO%TYPE,
    P_CAPACIDAD_KG  IN  VEHICULO.CAPACIDAD_KG%TYPE,
    P_CAPACIDAD_M3  IN  VEHICULO.CAPACIDAD_M3%TYPE,
    P_ACTIVO        IN  VEHICULO.ACTIVO%TYPE,
    P_VEHICULO_ID   OUT VEHICULO.VEHICULO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_VEHICULO(
    P_VEHICULO_ID   IN  VEHICULO.VEHICULO_ID%TYPE,
    P_PLACA         IN  VEHICULO.PLACA%TYPE,
    P_TIPO          IN  VEHICULO.TIPO%TYPE,
    P_CAPACIDAD_KG  IN  VEHICULO.CAPACIDAD_KG%TYPE,
    P_CAPACIDAD_M3  IN  VEHICULO.CAPACIDAD_M3%TYPE,
    P_ACTIVO        IN  VEHICULO.ACTIVO%TYPE
  );

  PROCEDURE SP_ELIMINAR_VEHICULO(
    P_VEHICULO_ID IN VEHICULO.VEHICULO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_VEHICULO(
    P_VEHICULO_ID IN  VEHICULO.VEHICULO_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_VEHICULOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_VEHICULOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_VEHICULO;
/

CREATE OR REPLACE PACKAGE BODY PKG_VEHICULO AS

  PROCEDURE SP_INSERTAR_VEHICULO(
    P_PLACA         IN  VEHICULO.PLACA%TYPE,
    P_TIPO          IN  VEHICULO.TIPO%TYPE,
    P_CAPACIDAD_KG  IN  VEHICULO.CAPACIDAD_KG%TYPE,
    P_CAPACIDAD_M3  IN  VEHICULO.CAPACIDAD_M3%TYPE,
    P_ACTIVO        IN  VEHICULO.ACTIVO%TYPE,
    P_VEHICULO_ID   OUT VEHICULO.VEHICULO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO VEHICULO (
      PLACA,
      TIPO,
      CAPACIDAD_KG,
      CAPACIDAD_M3,
      ACTIVO,
      CREATED_AT
    ) VALUES (
      P_PLACA,
      P_TIPO,
      P_CAPACIDAD_KG,
      P_CAPACIDAD_M3,
      P_ACTIVO,
      SYSTIMESTAMP
    )
    RETURNING VEHICULO_ID INTO P_VEHICULO_ID;
  END SP_INSERTAR_VEHICULO;

  PROCEDURE SP_ACTUALIZAR_VEHICULO(
    P_VEHICULO_ID   IN  VEHICULO.VEHICULO_ID%TYPE,
    P_PLACA         IN  VEHICULO.PLACA%TYPE,
    P_TIPO          IN  VEHICULO.TIPO%TYPE,
    P_CAPACIDAD_KG  IN  VEHICULO.CAPACIDAD_KG%TYPE,
    P_CAPACIDAD_M3  IN  VEHICULO.CAPACIDAD_M3%TYPE,
    P_ACTIVO        IN  VEHICULO.ACTIVO%TYPE
  ) AS
  BEGIN
    UPDATE VEHICULO
    SET PLACA        = P_PLACA,
        TIPO         = P_TIPO,
        CAPACIDAD_KG = P_CAPACIDAD_KG,
        CAPACIDAD_M3 = P_CAPACIDAD_M3,
        ACTIVO       = P_ACTIVO,
        UPDATED_AT   = SYSTIMESTAMP
    WHERE VEHICULO_ID = P_VEHICULO_ID;
  END SP_ACTUALIZAR_VEHICULO;

  PROCEDURE SP_ELIMINAR_VEHICULO(
    P_VEHICULO_ID IN VEHICULO.VEHICULO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM RUTA_ENTREGA
    WHERE VEHICULO_ID = P_VEHICULO_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el vehiculo porque tiene rutas de entrega asociadas.');
    END IF;

    UPDATE VEHICULO
    SET ACTIVO     = 0,
        UPDATED_AT = SYSTIMESTAMP
    WHERE VEHICULO_ID = P_VEHICULO_ID;
  END SP_ELIMINAR_VEHICULO;

  PROCEDURE SP_OBTENER_VEHICULO(
    P_VEHICULO_ID IN  VEHICULO.VEHICULO_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT VEHICULO_ID,
             PLACA,
             TIPO,
             CAPACIDAD_KG,
             CAPACIDAD_M3,
             ACTIVO
      FROM VEHICULO
      WHERE VEHICULO_ID = P_VEHICULO_ID;
  END SP_OBTENER_VEHICULO;

  PROCEDURE SP_LISTAR_VEHICULOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT VEHICULO_ID,
             PLACA,
             TIPO,
             CAPACIDAD_KG,
             CAPACIDAD_M3,
             ACTIVO
      FROM VEHICULO
      WHERE ACTIVO = 1
      ORDER BY PLACA;
  END SP_LISTAR_VEHICULOS;

  PROCEDURE SP_BUSCAR_VEHICULOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT VEHICULO_ID,
             PLACA,
             TIPO,
             CAPACIDAD_KG,
             CAPACIDAD_M3,
             ACTIVO
      FROM VEHICULO
      WHERE ACTIVO = 1
      AND (
        (UPPER(P_CRITERIO) = 'PLACA' AND UPPER(PLACA) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'TIPO'  AND UPPER(TIPO)  LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY PLACA;
  END SP_BUSCAR_VEHICULOS;

END PKG_VEHICULO;
/
