
 
CREATE OR REPLACE PACKAGE PKG_USUARIO AS

  PROCEDURE SP_INSERTAR_USUARIO(
    P_NOMBRE        IN USUARIO.NOMBRE%TYPE,
    P_EMAIL         IN USUARIO.EMAIL%TYPE,
    P_PASSWORD      IN USUARIO.PASSWORD%TYPE,
    P_ROL_ID        IN USUARIO.ROL_ID%TYPE,
    P_USUARIO_ID    OUT USUARIO.USUARIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_USUARIO(
    P_USUARIO_ID IN USUARIO.USUARIO_ID%TYPE,
    P_NOMBRE     IN USUARIO.NOMBRE%TYPE,
    P_EMAIL      IN USUARIO.EMAIL%TYPE,
    P_ROL_ID     IN USUARIO.ROL_ID%TYPE
  );

  PROCEDURE SP_ELIMINAR_USUARIO(
    P_USUARIO_ID IN USUARIO.USUARIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_USUARIO(
    P_USUARIO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_USUARIOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_USUARIO(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LOGIN(
    P_EMAIL    IN VARCHAR2,
    P_PASSWORD IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_USUARIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_USUARIO AS


  PROCEDURE SP_INSERTAR_USUARIO(
    P_NOMBRE        IN USUARIO.NOMBRE%TYPE,
    P_EMAIL         IN USUARIO.EMAIL%TYPE,
    P_PASSWORD      IN USUARIO.PASSWORD%TYPE,
    P_ROL_ID        IN USUARIO.ROL_ID%TYPE,
    P_USUARIO_ID    OUT USUARIO.USUARIO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN

    SELECT COUNT(*)
    INTO V_EXISTE
    FROM USUARIO
    WHERE EMAIL = P_EMAIL;

    IF V_EXISTE > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'El correo ya está registrado'
        );
    END IF;

    INSERT INTO USUARIO(
        NOMBRE,
        EMAIL,
        PASSWORD,
        ROL_ID,
        CREATED_AT
    )
    VALUES(
        P_NOMBRE,
        P_EMAIL,
        P_PASSWORD,
        P_ROL_ID,
        SYSTIMESTAMP
    )
    RETURNING USUARIO_ID INTO P_USUARIO_ID;

  END SP_INSERTAR_USUARIO;



  PROCEDURE SP_ACTUALIZAR_USUARIO(
    P_USUARIO_ID IN USUARIO.USUARIO_ID%TYPE,
    P_NOMBRE     IN USUARIO.NOMBRE%TYPE,
    P_EMAIL      IN USUARIO.EMAIL%TYPE,
    P_ROL_ID     IN USUARIO.ROL_ID%TYPE
  ) AS
  BEGIN

    UPDATE USUARIO
       SET NOMBRE = P_NOMBRE,
           EMAIL = P_EMAIL,
           ROL_ID = P_ROL_ID,
           UPDATED_AT = SYSTIMESTAMP
     WHERE USUARIO_ID = P_USUARIO_ID;

  END SP_ACTUALIZAR_USUARIO;



  PROCEDURE SP_ELIMINAR_USUARIO(
    P_USUARIO_ID IN USUARIO.USUARIO_ID%TYPE
  ) AS
  BEGIN

    DELETE FROM USUARIO
    WHERE USUARIO_ID = P_USUARIO_ID;

  END SP_ELIMINAR_USUARIO;



  PROCEDURE SP_OBTENER_USUARIO(
    P_USUARIO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            U.USUARIO_ID,
            U.NOMBRE,
            U.EMAIL,
            R.NOMBRE AS ROL
        FROM USUARIO U
        INNER JOIN ROL R
        ON U.ROL_ID = R.ROL_ID
        WHERE U.USUARIO_ID = P_USUARIO_ID;

  END SP_OBTENER_USUARIO;



  PROCEDURE SP_LISTAR_USUARIOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            U.USUARIO_ID,
            U.NOMBRE,
            U.EMAIL,
            R.NOMBRE AS ROL
        FROM USUARIO U
        INNER JOIN ROL R
        ON U.ROL_ID = R.ROL_ID
        ORDER BY U.NOMBRE;

  END SP_LISTAR_USUARIOS;



  PROCEDURE SP_BUSCAR_USUARIO(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            U.USUARIO_ID,
            U.NOMBRE,
            U.EMAIL,
            R.NOMBRE AS ROL
        FROM USUARIO U
        INNER JOIN ROL R
        ON U.ROL_ID = R.ROL_ID
        WHERE UPPER(U.NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%';

  END SP_BUSCAR_USUARIO;



  PROCEDURE SP_LOGIN(
    P_EMAIL    IN VARCHAR2,
    P_PASSWORD IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            USUARIO_ID,
            NOMBRE,
            EMAIL,
            ROL_ID
        FROM USUARIO
        WHERE EMAIL = P_EMAIL
        AND PASSWORD = P_PASSWORD;

  END SP_LOGIN;


END PKG_USUARIO;
/