CREATE OR REPLACE PACKAGE PKG_PERMISO AS

  PROCEDURE SP_INSERTAR_PERMISO(
    P_NOMBRE      IN PERMISO.NOMBRE%TYPE,
    P_DESCRIPCION IN PERMISO.DESCRIPCION%TYPE,
    P_PERMISO_ID  OUT PERMISO.PERMISO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PERMISO(
    P_PERMISO_ID  IN PERMISO.PERMISO_ID%TYPE,
    P_NOMBRE      IN PERMISO.NOMBRE%TYPE,
    P_DESCRIPCION IN PERMISO.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_PERMISO(
    P_PERMISO_ID IN PERMISO.PERMISO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PERMISO(
    P_PERMISO_ID IN PERMISO.PERMISO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PERMISOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PERMISO(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_PERMISO;
/

CREATE OR REPLACE PACKAGE BODY PKG_PERMISO AS


  PROCEDURE SP_INSERTAR_PERMISO(
    P_NOMBRE      IN PERMISO.NOMBRE%TYPE,
    P_DESCRIPCION IN PERMISO.DESCRIPCION%TYPE,
    P_PERMISO_ID  OUT PERMISO.PERMISO_ID%TYPE
  ) AS
  BEGIN

    INSERT INTO PERMISO(
        NOMBRE,
        DESCRIPCION,
        CREATED_AT
    )
    VALUES(
        P_NOMBRE,
        P_DESCRIPCION,
        SYSTIMESTAMP
    )
    RETURNING PERMISO_ID INTO P_PERMISO_ID;

  END SP_INSERTAR_PERMISO;



  PROCEDURE SP_ACTUALIZAR_PERMISO(
    P_PERMISO_ID  IN PERMISO.PERMISO_ID%TYPE,
    P_NOMBRE      IN PERMISO.NOMBRE%TYPE,
    P_DESCRIPCION IN PERMISO.DESCRIPCION%TYPE
  ) AS
  BEGIN

    UPDATE PERMISO
       SET NOMBRE = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT = SYSTIMESTAMP
     WHERE PERMISO_ID = P_PERMISO_ID;

  END SP_ACTUALIZAR_PERMISO;



  PROCEDURE SP_ELIMINAR_PERMISO(
    P_PERMISO_ID IN PERMISO.PERMISO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM ROL_PERMISO
     WHERE PERMISO_ID = P_PERMISO_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(
        -20001,
        'No se puede eliminar el permiso porque está asignado a un rol.'
      );
    END IF;

    DELETE FROM PERMISO
     WHERE PERMISO_ID = P_PERMISO_ID;

  END SP_ELIMINAR_PERMISO;



  PROCEDURE SP_OBTENER_PERMISO(
    P_PERMISO_ID IN PERMISO.PERMISO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            PERMISO_ID,
            NOMBRE,
            DESCRIPCION
        FROM PERMISO
        WHERE PERMISO_ID = P_PERMISO_ID;

  END SP_OBTENER_PERMISO;



  PROCEDURE SP_LISTAR_PERMISOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            PERMISO_ID,
            NOMBRE,
            DESCRIPCION
        FROM PERMISO
        ORDER BY NOMBRE;

  END SP_LISTAR_PERMISOS;



  PROCEDURE SP_BUSCAR_PERMISO(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            PERMISO_ID,
            NOMBRE,
            DESCRIPCION
        FROM PERMISO
        WHERE UPPER(NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%'
        ORDER BY NOMBRE;

  END SP_BUSCAR_PERMISO;


END PKG_PERMISO;
/
