CREATE OR REPLACE PACKAGE PKG_PRODUCCION_RESULTADOS AS

  PROCEDURE SP_INSERTAR_PRODUCCION_RESULTADOS(
    P_OP_ID                 IN PRODUCCION_RESULTADOS.OP_ID%TYPE,
    P_CANTIDAD_PRODUCIDA    IN PRODUCCION_RESULTADOS.CANTIDAD_PRODUCIDA%TYPE,
    P_CANTIDAD_DEFECTUOSA   IN PRODUCCION_RESULTADOS.CANTIDAD_DEFECTUOSA%TYPE,
    P_FECHA_RESULTADO       IN PRODUCCION_RESULTADOS.FECHA_RESULTADO%TYPE,
    P_OBSERVACIONES         IN PRODUCCION_RESULTADOS.OBSERVACIONES%TYPE,
    P_PR_ID                 OUT PRODUCCION_RESULTADOS.PR_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PRODUCCION_RESULTADOS(
    P_PR_ID                 IN PRODUCCION_RESULTADOS.PR_ID%TYPE,
    P_OP_ID                 IN PRODUCCION_RESULTADOS.OP_ID%TYPE,
    P_CANTIDAD_PRODUCIDA    IN PRODUCCION_RESULTADOS.CANTIDAD_PRODUCIDA%TYPE,
    P_CANTIDAD_DEFECTUOSA   IN PRODUCCION_RESULTADOS.CANTIDAD_DEFECTUOSA%TYPE,
    P_FECHA_RESULTADO       IN PRODUCCION_RESULTADOS.FECHA_RESULTADO%TYPE,
    P_OBSERVACIONES         IN PRODUCCION_RESULTADOS.OBSERVACIONES%TYPE
  );

  PROCEDURE SP_ELIMINAR_PRODUCCION_RESULTADOS(
    P_PR_ID IN PRODUCCION_RESULTADOS.PR_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PRODUCCION_RESULTADOS(
    P_PR_ID  IN PRODUCCION_RESULTADOS.PR_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PRODUCCION_RESULTADOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PRODUCCION_RESULTADOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PRODUCCION_RESULTADOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_PRODUCCION_RESULTADOS AS

  PROCEDURE SP_INSERTAR_PRODUCCION_RESULTADOS(
    P_OP_ID                 IN PRODUCCION_RESULTADOS.OP_ID%TYPE,
    P_CANTIDAD_PRODUCIDA    IN PRODUCCION_RESULTADOS.CANTIDAD_PRODUCIDA%TYPE,
    P_CANTIDAD_DEFECTUOSA   IN PRODUCCION_RESULTADOS.CANTIDAD_DEFECTUOSA%TYPE,
    P_FECHA_RESULTADO       IN PRODUCCION_RESULTADOS.FECHA_RESULTADO%TYPE,
    P_OBSERVACIONES         IN PRODUCCION_RESULTADOS.OBSERVACIONES%TYPE,
    P_PR_ID                 OUT PRODUCCION_RESULTADOS.PR_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PRODUCCION_RESULTADOS (
      OP_ID,
      CANTIDAD_PRODUCIDA,
      CANTIDAD_DEFECTUOSA,
      FECHA_RESULTADO,
      OBSERVACIONES,
      CREATED_AT
    )
    VALUES (
      P_OP_ID,
      P_CANTIDAD_PRODUCIDA,
      P_CANTIDAD_DEFECTUOSA,
      P_FECHA_RESULTADO,
      P_OBSERVACIONES,
      SYSTIMESTAMP
    )
    RETURNING PR_ID INTO P_PR_ID;
  END SP_INSERTAR_PRODUCCION_RESULTADOS;


  PROCEDURE SP_ACTUALIZAR_PRODUCCION_RESULTADOS(
    P_PR_ID                 IN PRODUCCION_RESULTADOS.PR_ID%TYPE,
    P_OP_ID                 IN PRODUCCION_RESULTADOS.OP_ID%TYPE,
    P_CANTIDAD_PRODUCIDA    IN PRODUCCION_RESULTADOS.CANTIDAD_PRODUCIDA%TYPE,
    P_CANTIDAD_DEFECTUOSA   IN PRODUCCION_RESULTADOS.CANTIDAD_DEFECTUOSA%TYPE,
    P_FECHA_RESULTADO       IN PRODUCCION_RESULTADOS.FECHA_RESULTADO%TYPE,
    P_OBSERVACIONES         IN PRODUCCION_RESULTADOS.OBSERVACIONES%TYPE
  ) AS
  BEGIN
    UPDATE PRODUCCION_RESULTADOS
       SET OP_ID               = P_OP_ID,
           CANTIDAD_PRODUCIDA  = P_CANTIDAD_PRODUCIDA,
           CANTIDAD_DEFECTUOSA = P_CANTIDAD_DEFECTUOSA,
           FECHA_RESULTADO     = P_FECHA_RESULTADO,
           OBSERVACIONES       = P_OBSERVACIONES,
           UPDATED_AT          = SYSTIMESTAMP
     WHERE PR_ID = P_PR_ID;
  END SP_ACTUALIZAR_PRODUCCION_RESULTADOS;


  PROCEDURE SP_ELIMINAR_PRODUCCION_RESULTADOS(
    P_PR_ID IN PRODUCCION_RESULTADOS.PR_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM PRODUCCION_RESULTADOS
     WHERE PR_ID = P_PR_ID;
  END SP_ELIMINAR_PRODUCCION_RESULTADOS;


  PROCEDURE SP_OBTENER_PRODUCCION_RESULTADOS(
    P_PR_ID  IN PRODUCCION_RESULTADOS.PR_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PR_ID,
             OP_ID,
             CANTIDAD_PRODUCIDA,
             CANTIDAD_DEFECTUOSA,
             FECHA_RESULTADO,
             OBSERVACIONES
        FROM PRODUCCION_RESULTADOS
       WHERE PR_ID = P_PR_ID;
  END SP_OBTENER_PRODUCCION_RESULTADOS;


  PROCEDURE SP_LISTAR_PRODUCCION_RESULTADOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PR_ID,
             OP_ID,
             CANTIDAD_PRODUCIDA,
             CANTIDAD_DEFECTUOSA,
             FECHA_RESULTADO,
             OBSERVACIONES
        FROM PRODUCCION_RESULTADOS
       ORDER BY FECHA_RESULTADO DESC, PR_ID DESC;
  END SP_LISTAR_PRODUCCION_RESULTADOS;


  PROCEDURE SP_BUSCAR_PRODUCCION_RESULTADOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PR_ID,
             OP_ID,
             CANTIDAD_PRODUCIDA,
             CANTIDAD_DEFECTUOSA,
             FECHA_RESULTADO,
             OBSERVACIONES
        FROM PRODUCCION_RESULTADOS
       WHERE (
             (UPPER(P_CRITERIO) = 'OP_ID' AND TO_CHAR(OP_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'OBSERVACIONES' AND UPPER(OBSERVACIONES) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY FECHA_RESULTADO DESC, PR_ID DESC;
  END SP_BUSCAR_PRODUCCION_RESULTADOS;

END PKG_PRODUCCION_RESULTADOS;
/