CREATE OR REPLACE PACKAGE PKG_CONSUMO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_CONSUMO_MATERIA_PRIMA(
    P_ORDEN_PRODUCCION_ID IN CONSUMO_MATERIA_PRIMA.ORDEN_PRODUCCION_ID%TYPE,
    P_MP_ID               IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD            IN CONSUMO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_CONSUMO_AT          IN CONSUMO_MATERIA_PRIMA.CONSUMO_AT%TYPE,
    P_ESTADO              IN CONSUMO_MATERIA_PRIMA.ESTADO%TYPE,
    P_CONSUMO_ID          OUT CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CONSUMO_MATERIA_PRIMA(
    P_CONSUMO_ID          IN CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE,
    P_ORDEN_PRODUCCION_ID IN CONSUMO_MATERIA_PRIMA.ORDEN_PRODUCCION_ID%TYPE,
    P_MP_ID               IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD            IN CONSUMO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_CONSUMO_AT          IN CONSUMO_MATERIA_PRIMA.CONSUMO_AT%TYPE,
    P_ESTADO              IN CONSUMO_MATERIA_PRIMA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_CONSUMO_MATERIA_PRIMA(
    P_CONSUMO_ID IN CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CONSUMO_MATERIA_PRIMA(
    P_CONSUMO_ID IN CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CONSUMO_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CONSUMO_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CONSUMO_MATERIA_PRIMA;
/
CREATE OR REPLACE PACKAGE BODY PKG_CONSUMO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_CONSUMO_MATERIA_PRIMA(
    P_ORDEN_PRODUCCION_ID IN CONSUMO_MATERIA_PRIMA.ORDEN_PRODUCCION_ID%TYPE,
    P_MP_ID               IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD            IN CONSUMO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_CONSUMO_AT          IN CONSUMO_MATERIA_PRIMA.CONSUMO_AT%TYPE,
    P_ESTADO              IN CONSUMO_MATERIA_PRIMA.ESTADO%TYPE,
    P_CONSUMO_ID          OUT CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CONSUMO_MATERIA_PRIMA (
      ORDEN_PRODUCCION_ID,
      MP_ID,
      CANTIDAD,
      CONSUMO_AT,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_ORDEN_PRODUCCION_ID,
      P_MP_ID,
      P_CANTIDAD,
      P_CONSUMO_AT,
      SYSTIMESTAMP,
      P_ESTADO
    )
    RETURNING CONSUMO_ID INTO P_CONSUMO_ID;
  END SP_INSERTAR_CONSUMO_MATERIA_PRIMA;

  PROCEDURE SP_ACTUALIZAR_CONSUMO_MATERIA_PRIMA(
    P_CONSUMO_ID          IN CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE,
    P_ORDEN_PRODUCCION_ID IN CONSUMO_MATERIA_PRIMA.ORDEN_PRODUCCION_ID%TYPE,
    P_MP_ID               IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD            IN CONSUMO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_CONSUMO_AT          IN CONSUMO_MATERIA_PRIMA.CONSUMO_AT%TYPE,
    P_ESTADO              IN CONSUMO_MATERIA_PRIMA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE CONSUMO_MATERIA_PRIMA
       SET ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID,
           MP_ID               = P_MP_ID,
           CANTIDAD            = P_CANTIDAD,
           CONSUMO_AT          = P_CONSUMO_AT,
           UPDATED_AT          = SYSTIMESTAMP,
           ESTADO              = P_ESTADO
     WHERE CONSUMO_ID = P_CONSUMO_ID;
  END SP_ACTUALIZAR_CONSUMO_MATERIA_PRIMA;

  PROCEDURE SP_ELIMINAR_CONSUMO_MATERIA_PRIMA(
    P_CONSUMO_ID IN CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE
  ) AS
  BEGIN
    UPDATE CONSUMO_MATERIA_PRIMA
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE CONSUMO_ID = P_CONSUMO_ID;
  END SP_ELIMINAR_CONSUMO_MATERIA_PRIMA;

  PROCEDURE SP_OBTENER_CONSUMO_MATERIA_PRIMA(
    P_CONSUMO_ID IN CONSUMO_MATERIA_PRIMA.CONSUMO_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CONSUMO_ID,
             ORDEN_PRODUCCION_ID,
             MP_ID,
             CANTIDAD,
             CONSUMO_AT,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM CONSUMO_MATERIA_PRIMA
       WHERE CONSUMO_ID = P_CONSUMO_ID;
  END SP_OBTENER_CONSUMO_MATERIA_PRIMA;

  PROCEDURE SP_LISTAR_CONSUMO_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CONSUMO_ID,
             ORDEN_PRODUCCION_ID,
             MP_ID,
             CANTIDAD,
             CONSUMO_AT,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM CONSUMO_MATERIA_PRIMA
       ORDER BY CONSUMO_AT DESC, CONSUMO_ID DESC;
  END SP_LISTAR_CONSUMO_MATERIA_PRIMA;

  PROCEDURE SP_BUSCAR_CONSUMO_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CONSUMO_ID,
             ORDEN_PRODUCCION_ID,
             MP_ID,
             CANTIDAD,
             CONSUMO_AT,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM CONSUMO_MATERIA_PRIMA
       WHERE (
             (UPPER(P_CRITERIO) = 'CONSUMO_ID' AND TO_CHAR(CONSUMO_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ORDEN_PRODUCCION_ID' AND TO_CHAR(ORDEN_PRODUCCION_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'MP_ID' AND TO_CHAR(MP_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY CONSUMO_AT DESC, CONSUMO_ID DESC;
  END SP_BUSCAR_CONSUMO_MATERIA_PRIMA;

END PKG_CONSUMO_MATERIA_PRIMA;
/
