CREATE OR REPLACE PACKAGE PKG_REGLA_PROMOCION AS

  PROCEDURE SP_INSERTAR_REGLA_PROMOCION(
    P_PROMOCION_ID        IN REGLA_PROMOCION.PROMOCION_ID%TYPE,
    P_MIN_COMPRA          IN REGLA_PROMOCION.MIN_COMPRA%TYPE,
    P_MIN_ITEMS           IN REGLA_PROMOCION.MIN_ITEMS%TYPE,
    P_APLICA_TIPO_PRODUCTO IN REGLA_PROMOCION.APLICA_TIPO_PRODUCTO%TYPE,
    P_TOPE_DESCUENTO      IN REGLA_PROMOCION.TOPE_DESCUENTO%TYPE,
    P_REGLA_PROMOCION_ID  OUT REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_REGLA_PROMOCION(
    P_REGLA_PROMOCION_ID   IN REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE,
    P_PROMOCION_ID         IN REGLA_PROMOCION.PROMOCION_ID%TYPE,
    P_MIN_COMPRA           IN REGLA_PROMOCION.MIN_COMPRA%TYPE,
    P_MIN_ITEMS            IN REGLA_PROMOCION.MIN_ITEMS%TYPE,
    P_APLICA_TIPO_PRODUCTO IN REGLA_PROMOCION.APLICA_TIPO_PRODUCTO%TYPE,
    P_TOPE_DESCUENTO       IN REGLA_PROMOCION.TOPE_DESCUENTO%TYPE
  );

  PROCEDURE SP_ELIMINAR_REGLA_PROMOCION(
    P_REGLA_PROMOCION_ID IN REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_REGLA_PROMOCION(
    P_REGLA_PROMOCION_ID IN REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE,
    P_CURSOR             OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_REGLAS_PROMOCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_REGLAS_PROMOCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_REGLA_PROMOCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_REGLA_PROMOCION AS

  PROCEDURE SP_INSERTAR_REGLA_PROMOCION(
    P_PROMOCION_ID         IN REGLA_PROMOCION.PROMOCION_ID%TYPE,
    P_MIN_COMPRA           IN REGLA_PROMOCION.MIN_COMPRA%TYPE,
    P_MIN_ITEMS            IN REGLA_PROMOCION.MIN_ITEMS%TYPE,
    P_APLICA_TIPO_PRODUCTO IN REGLA_PROMOCION.APLICA_TIPO_PRODUCTO%TYPE,
    P_TOPE_DESCUENTO       IN REGLA_PROMOCION.TOPE_DESCUENTO%TYPE,
    P_REGLA_PROMOCION_ID   OUT REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO REGLA_PROMOCION (
      PROMOCION_ID,
      MIN_COMPRA,
      MIN_ITEMS,
      APLICA_TIPO_PRODUCTO,
      TOPE_DESCUENTO,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_PROMOCION_ID,
      P_MIN_COMPRA,
      P_MIN_ITEMS,
      P_APLICA_TIPO_PRODUCTO,
      P_TOPE_DESCUENTO,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING REGLA_PROMOCION_ID INTO P_REGLA_PROMOCION_ID;
  END SP_INSERTAR_REGLA_PROMOCION;

  PROCEDURE SP_ACTUALIZAR_REGLA_PROMOCION(
    P_REGLA_PROMOCION_ID   IN REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE,
    P_PROMOCION_ID         IN REGLA_PROMOCION.PROMOCION_ID%TYPE,
    P_MIN_COMPRA           IN REGLA_PROMOCION.MIN_COMPRA%TYPE,
    P_MIN_ITEMS            IN REGLA_PROMOCION.MIN_ITEMS%TYPE,
    P_APLICA_TIPO_PRODUCTO IN REGLA_PROMOCION.APLICA_TIPO_PRODUCTO%TYPE,
    P_TOPE_DESCUENTO       IN REGLA_PROMOCION.TOPE_DESCUENTO%TYPE
  ) AS
  BEGIN
    UPDATE REGLA_PROMOCION
       SET PROMOCION_ID         = P_PROMOCION_ID,
           MIN_COMPRA           = P_MIN_COMPRA,
           MIN_ITEMS            = P_MIN_ITEMS,
           APLICA_TIPO_PRODUCTO = P_APLICA_TIPO_PRODUCTO,
           TOPE_DESCUENTO       = P_TOPE_DESCUENTO,
           UPDATED_AT           = SYSTIMESTAMP
     WHERE REGLA_PROMOCION_ID = P_REGLA_PROMOCION_ID;
  END SP_ACTUALIZAR_REGLA_PROMOCION;

  PROCEDURE SP_ELIMINAR_REGLA_PROMOCION(
    P_REGLA_PROMOCION_ID IN REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE
  ) AS
  BEGIN
    UPDATE REGLA_PROMOCION
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE REGLA_PROMOCION_ID = P_REGLA_PROMOCION_ID;
  END SP_ELIMINAR_REGLA_PROMOCION;

  PROCEDURE SP_OBTENER_REGLA_PROMOCION(
    P_REGLA_PROMOCION_ID IN REGLA_PROMOCION.REGLA_PROMOCION_ID%TYPE,
    P_CURSOR             OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RP.REGLA_PROMOCION_ID,
             RP.PROMOCION_ID,
             P.NOMBRE AS PROMOCION,
             RP.MIN_COMPRA,
             RP.MIN_ITEMS,
             RP.APLICA_TIPO_PRODUCTO,
             RP.TOPE_DESCUENTO,
             RP.ESTADO
        FROM REGLA_PROMOCION RP
        JOIN PROMOCION P
          ON P.PROMOCION_ID = RP.PROMOCION_ID
       WHERE RP.REGLA_PROMOCION_ID = P_REGLA_PROMOCION_ID;
  END SP_OBTENER_REGLA_PROMOCION;

  PROCEDURE SP_LISTAR_REGLAS_PROMOCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RP.REGLA_PROMOCION_ID,
             P.NOMBRE AS PROMOCION,
             RP.MIN_COMPRA,
             RP.MIN_ITEMS,
             RP.APLICA_TIPO_PRODUCTO,
             RP.TOPE_DESCUENTO,
             RP.ESTADO
        FROM REGLA_PROMOCION RP
        JOIN PROMOCION P
          ON P.PROMOCION_ID = RP.PROMOCION_ID
       WHERE RP.ESTADO = 'ACTIVO'
       ORDER BY P.NOMBRE, RP.REGLA_PROMOCION_ID;
  END SP_LISTAR_REGLAS_PROMOCION;

  PROCEDURE SP_BUSCAR_REGLAS_PROMOCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT RP.REGLA_PROMOCION_ID,
             P.NOMBRE AS PROMOCION,
             RP.MIN_COMPRA,
             RP.MIN_ITEMS,
             RP.APLICA_TIPO_PRODUCTO,
             RP.TOPE_DESCUENTO,
             RP.ESTADO
        FROM REGLA_PROMOCION RP
        JOIN PROMOCION P
          ON P.PROMOCION_ID = RP.PROMOCION_ID
       WHERE RP.ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'PROMOCION' AND UPPER(P.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'TIPO_PRODUCTO' AND UPPER(RP.APLICA_TIPO_PRODUCTO) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY P.NOMBRE, RP.REGLA_PROMOCION_ID;
  END SP_BUSCAR_REGLAS_PROMOCION;

END PKG_REGLA_PROMOCION;
/
