CREATE OR REPLACE PACKAGE PKG_CONSUMO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_CONSUMO_MATERIA_PRIMA(
    P_OP_ID            IN CONSUMO_MATERIA_PRIMA.OP_ID%TYPE,
    P_MP_ID            IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_CONSUMIDA IN CONSUMO_MATERIA_PRIMA.CANTIDAD_CONSUMIDA%TYPE,
    P_FECHA_CONSUMO    IN CONSUMO_MATERIA_PRIMA.FECHA_CONSUMO%TYPE,
    P_USUARIO_REGISTRO IN CONSUMO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE,
    P_CONS_MP_ID       OUT CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CONSUMO_MATERIA_PRIMA(
    P_CONS_MP_ID       IN CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE,
    P_OP_ID            IN CONSUMO_MATERIA_PRIMA.OP_ID%TYPE,
    P_MP_ID            IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_CONSUMIDA IN CONSUMO_MATERIA_PRIMA.CANTIDAD_CONSUMIDA%TYPE,
    P_FECHA_CONSUMO    IN CONSUMO_MATERIA_PRIMA.FECHA_CONSUMO%TYPE,
    P_USUARIO_REGISTRO IN CONSUMO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE
  );

  PROCEDURE SP_ELIMINAR_CONSUMO_MATERIA_PRIMA(
    P_CONS_MP_ID IN CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CONSUMO_MATERIA_PRIMA(
    P_CONS_MP_ID IN CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CONSUMOS_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CONSUMOS_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CONSUMO_MATERIA_PRIMA;
/

CREATE OR REPLACE PACKAGE BODY PKG_CONSUMO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_CONSUMO_MATERIA_PRIMA(
    P_OP_ID            IN CONSUMO_MATERIA_PRIMA.OP_ID%TYPE,
    P_MP_ID            IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_CONSUMIDA IN CONSUMO_MATERIA_PRIMA.CANTIDAD_CONSUMIDA%TYPE,
    P_FECHA_CONSUMO    IN CONSUMO_MATERIA_PRIMA.FECHA_CONSUMO%TYPE,
    P_USUARIO_REGISTRO IN CONSUMO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE,
    P_CONS_MP_ID       OUT CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CONSUMO_MATERIA_PRIMA (
      OP_ID,
      MP_ID,
      CANTIDAD_CONSUMIDA,
      FECHA_CONSUMO,
      USUARIO_REGISTRO,
      CREATED_AT
    )
    VALUES (
      P_OP_ID,
      P_MP_ID,
      P_CANTIDAD_CONSUMIDA,
      P_FECHA_CONSUMO,
      P_USUARIO_REGISTRO,
      SYSTIMESTAMP
    )
    RETURNING CONS_MP_ID INTO P_CONS_MP_ID;
  END SP_INSERTAR_CONSUMO_MATERIA_PRIMA;


  PROCEDURE SP_ACTUALIZAR_CONSUMO_MATERIA_PRIMA(
    P_CONS_MP_ID       IN CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE,
    P_OP_ID            IN CONSUMO_MATERIA_PRIMA.OP_ID%TYPE,
    P_MP_ID            IN CONSUMO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_CONSUMIDA IN CONSUMO_MATERIA_PRIMA.CANTIDAD_CONSUMIDA%TYPE,
    P_FECHA_CONSUMO    IN CONSUMO_MATERIA_PRIMA.FECHA_CONSUMO%TYPE,
    P_USUARIO_REGISTRO IN CONSUMO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE
  ) AS
  BEGIN
    UPDATE CONSUMO_MATERIA_PRIMA
       SET OP_ID             = P_OP_ID,
           MP_ID             = P_MP_ID,
           CANTIDAD_CONSUMIDA = P_CANTIDAD_CONSUMIDA,
           FECHA_CONSUMO     = P_FECHA_CONSUMO,
           USUARIO_REGISTRO  = P_USUARIO_REGISTRO,
           UPDATED_AT        = SYSTIMESTAMP
     WHERE CONS_MP_ID = P_CONS_MP_ID;
  END SP_ACTUALIZAR_CONSUMO_MATERIA_PRIMA;


  PROCEDURE SP_ELIMINAR_CONSUMO_MATERIA_PRIMA(
    P_CONS_MP_ID IN CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM CONSUMO_MATERIA_PRIMA
     WHERE CONS_MP_ID = P_CONS_MP_ID;
  END SP_ELIMINAR_CONSUMO_MATERIA_PRIMA;


  PROCEDURE SP_OBTENER_CONSUMO_MATERIA_PRIMA(
    P_CONS_MP_ID IN CONSUMO_MATERIA_PRIMA.CONS_MP_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CONS_MP_ID,
             OP_ID,
             MP_ID,
             CANTIDAD_CONSUMIDA,
             FECHA_CONSUMO,
             USUARIO_REGISTRO
        FROM CONSUMO_MATERIA_PRIMA
       WHERE CONS_MP_ID = P_CONS_MP_ID;
  END SP_OBTENER_CONSUMO_MATERIA_PRIMA;


  PROCEDURE SP_LISTAR_CONSUMOS_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CONS_MP_ID,
             OP_ID,
             MP_ID,
             CANTIDAD_CONSUMIDA,
             FECHA_CONSUMO,
             USUARIO_REGISTRO
        FROM CONSUMO_MATERIA_PRIMA
       ORDER BY FECHA_CONSUMO DESC;
  END SP_LISTAR_CONSUMOS_MATERIA_PRIMA;


  PROCEDURE SP_BUSCAR_CONSUMOS_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CONS_MP_ID,
             OP_ID,
             MP_ID,
             CANTIDAD_CONSUMIDA,
             FECHA_CONSUMO,
             USUARIO_REGISTRO
        FROM CONSUMO_MATERIA_PRIMA
       WHERE (
             (UPPER(P_CRITERIO) = 'OP_ID' AND TO_CHAR(OP_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'MP_ID' AND TO_CHAR(MP_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'USUARIO' AND UPPER(USUARIO_REGISTRO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY FECHA_CONSUMO DESC;
  END SP_BUSCAR_CONSUMOS_MATERIA_PRIMA;

END PKG_CONSUMO_MATERIA_PRIMA;
/