CREATE OR REPLACE PACKAGE PKG_ORDEN_PRODUCCION_TAREA AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION_TAREA(
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION_TAREA.ORDEN_PRODUCCION_ID%TYPE,
    P_NOMBRE_TAREA        IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_ORDEN               IN ORDEN_PRODUCCION_TAREA.ORDEN%TYPE,
    P_INICIO_AT           IN ORDEN_PRODUCCION_TAREA.INICIO_AT%TYPE,
    P_FIN_AT              IN ORDEN_PRODUCCION_TAREA.FIN_AT%TYPE,
    P_EMP_ID_RESPONSABLE  IN ORDEN_PRODUCCION_TAREA.EMP_ID_RESPONSABLE%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE,
    P_OP_TAREA_ID         OUT ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION_TAREA(
    P_OP_TAREA_ID         IN ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE,
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION_TAREA.ORDEN_PRODUCCION_ID%TYPE,
    P_NOMBRE_TAREA        IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_ORDEN               IN ORDEN_PRODUCCION_TAREA.ORDEN%TYPE,
    P_INICIO_AT           IN ORDEN_PRODUCCION_TAREA.INICIO_AT%TYPE,
    P_FIN_AT              IN ORDEN_PRODUCCION_TAREA.FIN_AT%TYPE,
    P_EMP_ID_RESPONSABLE  IN ORDEN_PRODUCCION_TAREA.EMP_ID_RESPONSABLE%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION_TAREA(
    P_OP_TAREA_ID IN ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION_TAREA(
    P_OP_TAREA_ID IN ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ORDEN_PRODUCCION_TAREA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ORDEN_PRODUCCION_TAREA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ORDEN_PRODUCCION_TAREA;
/
CREATE OR REPLACE PACKAGE BODY PKG_ORDEN_PRODUCCION_TAREA AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION_TAREA(
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION_TAREA.ORDEN_PRODUCCION_ID%TYPE,
    P_NOMBRE_TAREA        IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_ORDEN               IN ORDEN_PRODUCCION_TAREA.ORDEN%TYPE,
    P_INICIO_AT           IN ORDEN_PRODUCCION_TAREA.INICIO_AT%TYPE,
    P_FIN_AT              IN ORDEN_PRODUCCION_TAREA.FIN_AT%TYPE,
    P_EMP_ID_RESPONSABLE  IN ORDEN_PRODUCCION_TAREA.EMP_ID_RESPONSABLE%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE,
    P_OP_TAREA_ID         OUT ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ORDEN_PRODUCCION_TAREA (
      ORDEN_PRODUCCION_ID,
      NOMBRE_TAREA,
      ORDEN,
      INICIO_AT,
      FIN_AT,
      EMP_ID_RESPONSABLE,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_ORDEN_PRODUCCION_ID,
      P_NOMBRE_TAREA,
      P_ORDEN,
      P_INICIO_AT,
      P_FIN_AT,
      P_EMP_ID_RESPONSABLE,
      SYSTIMESTAMP,
      P_ESTADO
    )
    RETURNING OP_TAREA_ID INTO P_OP_TAREA_ID;
  END SP_INSERTAR_ORDEN_PRODUCCION_TAREA;

  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION_TAREA(
    P_OP_TAREA_ID         IN ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE,
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION_TAREA.ORDEN_PRODUCCION_ID%TYPE,
    P_NOMBRE_TAREA        IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_ORDEN               IN ORDEN_PRODUCCION_TAREA.ORDEN%TYPE,
    P_INICIO_AT           IN ORDEN_PRODUCCION_TAREA.INICIO_AT%TYPE,
    P_FIN_AT              IN ORDEN_PRODUCCION_TAREA.FIN_AT%TYPE,
    P_EMP_ID_RESPONSABLE  IN ORDEN_PRODUCCION_TAREA.EMP_ID_RESPONSABLE%TYPE,
    P_ESTADO              IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE ORDEN_PRODUCCION_TAREA
       SET ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID,
           NOMBRE_TAREA        = P_NOMBRE_TAREA,
           ORDEN               = P_ORDEN,
           INICIO_AT           = P_INICIO_AT,
           FIN_AT              = P_FIN_AT,
           EMP_ID_RESPONSABLE  = P_EMP_ID_RESPONSABLE,
           UPDATED_AT          = SYSTIMESTAMP,
           ESTADO              = P_ESTADO
     WHERE OP_TAREA_ID = P_OP_TAREA_ID;
  END SP_ACTUALIZAR_ORDEN_PRODUCCION_TAREA;

  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION_TAREA(
    P_OP_TAREA_ID IN ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE
  ) AS
  BEGIN
    UPDATE ORDEN_PRODUCCION_TAREA
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE OP_TAREA_ID = P_OP_TAREA_ID;
  END SP_ELIMINAR_ORDEN_PRODUCCION_TAREA;

  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION_TAREA(
    P_OP_TAREA_ID IN ORDEN_PRODUCCION_TAREA.OP_TAREA_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OP_TAREA_ID,
             ORDEN_PRODUCCION_ID,
             NOMBRE_TAREA,
             ORDEN,
             INICIO_AT,
             FIN_AT,
             EMP_ID_RESPONSABLE,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ORDEN_PRODUCCION_TAREA
       WHERE OP_TAREA_ID = P_OP_TAREA_ID;
  END SP_OBTENER_ORDEN_PRODUCCION_TAREA;

  PROCEDURE SP_LISTAR_ORDEN_PRODUCCION_TAREA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OP_TAREA_ID,
             ORDEN_PRODUCCION_ID,
             NOMBRE_TAREA,
             ORDEN,
             INICIO_AT,
             FIN_AT,
             EMP_ID_RESPONSABLE,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ORDEN_PRODUCCION_TAREA
       ORDER BY OP_TAREA_ID DESC;
  END SP_LISTAR_ORDEN_PRODUCCION_TAREA;

  PROCEDURE SP_BUSCAR_ORDEN_PRODUCCION_TAREA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OP_TAREA_ID,
             ORDEN_PRODUCCION_ID,
             NOMBRE_TAREA,
             ORDEN,
             INICIO_AT,
             FIN_AT,
             EMP_ID_RESPONSABLE,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ORDEN_PRODUCCION_TAREA
       WHERE (
             (UPPER(P_CRITERIO) = 'OP_TAREA_ID' AND TO_CHAR(OP_TAREA_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ORDEN_PRODUCCION_ID' AND TO_CHAR(ORDEN_PRODUCCION_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'NOMBRE_TAREA' AND UPPER(NOMBRE_TAREA) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'EMP_ID_RESPONSABLE' AND TO_CHAR(EMP_ID_RESPONSABLE) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY OP_TAREA_ID DESC;
  END SP_BUSCAR_ORDEN_PRODUCCION_TAREA;

END PKG_ORDEN_PRODUCCION_TAREA;
/
