CREATE OR REPLACE PACKAGE PKG_NOMINA AS

  PROCEDURE SP_INSERTAR_NOMINA(
    P_EMPLEADO_ID      IN NOMINA.EMPLEADO_ID%TYPE,
    P_FECHA_PAGO       IN NOMINA.FECHA_PAGO%TYPE,
    P_SALARIO_BASE     IN NOMINA.SALARIO_BASE%TYPE,
    P_TOTAL_DEDUCCION  IN NOMINA.TOTAL_DEDUCCION%TYPE,
    P_TOTAL_PAGO       IN NOMINA.TOTAL_PAGO%TYPE,
    P_NOMINA_ID        OUT NOMINA.NOMINA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_NOMINA(
    P_NOMINA_ID        IN NOMINA.NOMINA_ID%TYPE,
    P_SALARIO_BASE     IN NOMINA.SALARIO_BASE%TYPE,
    P_TOTAL_DEDUCCION  IN NOMINA.TOTAL_DEDUCCION%TYPE,
    P_TOTAL_PAGO       IN NOMINA.TOTAL_PAGO%TYPE
  );

  PROCEDURE SP_ELIMINAR_NOMINA(
    P_NOMINA_ID IN NOMINA.NOMINA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_NOMINA(
    P_NOMINA_ID IN NOMINA.NOMINA_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_NOMINAS(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_NOMINA;
/

CREATE OR REPLACE PACKAGE BODY PKG_NOMINA AS

  PROCEDURE SP_INSERTAR_NOMINA(
    P_EMPLEADO_ID,
    P_FECHA_PAGO,
    P_SALARIO_BASE,
    P_TOTAL_DEDUCCION,
    P_TOTAL_PAGO,
    P_NOMINA_ID
  ) AS
  BEGIN

    INSERT INTO NOMINA(
        EMPLEADO_ID,
        FECHA_PAGO,
        SALARIO_BASE,
        TOTAL_DEDUCCION,
        TOTAL_PAGO,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_EMPLEADO_ID,
        P_FECHA_PAGO,
        P_SALARIO_BASE,
        P_TOTAL_DEDUCCION,
        P_TOTAL_PAGO,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING NOMINA_ID INTO P_NOMINA_ID;

  END SP_INSERTAR_NOMINA;



  PROCEDURE SP_ACTUALIZAR_NOMINA(
    P_NOMINA_ID,
    P_SALARIO_BASE,
    P_TOTAL_DEDUCCION,
    P_TOTAL_PAGO
  ) AS
  BEGIN

    UPDATE NOMINA
       SET SALARIO_BASE = P_SALARIO_BASE,
           TOTAL_DEDUCCION = P_TOTAL_DEDUCCION,
           TOTAL_PAGO = P_TOTAL_PAGO,
           UPDATED_AT = SYSTIMESTAMP
     WHERE NOMINA_ID = P_NOMINA_ID;

  END SP_ACTUALIZAR_NOMINA;



  PROCEDURE SP_ELIMINAR_NOMINA(
    P_NOMINA_ID
  ) AS
  BEGIN

    UPDATE NOMINA
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE NOMINA_ID = P_NOMINA_ID;

  END SP_ELIMINAR_NOMINA;



  PROCEDURE SP_OBTENER_NOMINA(
    P_NOMINA_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT N.NOMINA_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             N.FECHA_PAGO,
             N.SALARIO_BASE,
             N.TOTAL_DEDUCCION,
             N.TOTAL_PAGO
        FROM NOMINA N
        JOIN EMPLEADO E ON N.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE N.NOMINA_ID = P_NOMINA_ID;

  END SP_OBTENER_NOMINA;



  PROCEDURE SP_LISTAR_NOMINAS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT N.NOMINA_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             N.FECHA_PAGO,
             N.SALARIO_BASE,
             N.TOTAL_DEDUCCION,
             N.TOTAL_PAGO
        FROM NOMINA N
        JOIN EMPLEADO E ON N.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE N.ESTADO = 'ACTIVO'
       ORDER BY N.FECHA_PAGO DESC;

  END SP_LISTAR_NOMINAS;

END PKG_NOMINA;
/