CREATE OR REPLACE PACKAGE PKG_ESTADO_ENVIO AS

  PROCEDURE SP_INSERTAR_ESTADO_ENVIO(
    P_CODIGO           IN ESTADO_ENVIO.CODIGO%TYPE,
    P_DESCRIPCION      IN ESTADO_ENVIO.DESCRIPCION%TYPE,
    P_ESTADO_ENVIO_ID  OUT ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ESTADO_ENVIO(
    P_ESTADO_ENVIO_ID  IN ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_CODIGO           IN ESTADO_ENVIO.CODIGO%TYPE,
    P_DESCRIPCION      IN ESTADO_ENVIO.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_ESTADO_ENVIO(
    P_ESTADO_ENVIO_ID IN ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ESTADO_ENVIO(
    P_ESTADO_ENVIO_ID IN ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ESTADOS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ESTADOS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ESTADO_ENVIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_ESTADO_ENVIO AS

  PROCEDURE SP_INSERTAR_ESTADO_ENVIO(
    P_CODIGO           IN ESTADO_ENVIO.CODIGO%TYPE,
    P_DESCRIPCION      IN ESTADO_ENVIO.DESCRIPCION%TYPE,
    P_ESTADO_ENVIO_ID  OUT ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ESTADO_ENVIO (
      CODIGO,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_CODIGO,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING ESTADO_ENVIO_ID INTO P_ESTADO_ENVIO_ID;
  END SP_INSERTAR_ESTADO_ENVIO;

  PROCEDURE SP_ACTUALIZAR_ESTADO_ENVIO(
    P_ESTADO_ENVIO_ID  IN ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_CODIGO           IN ESTADO_ENVIO.CODIGO%TYPE,
    P_DESCRIPCION      IN ESTADO_ENVIO.DESCRIPCION%TYPE
  ) AS
  BEGIN
    UPDATE ESTADO_ENVIO
       SET CODIGO      = P_CODIGO,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT  = SYSTIMESTAMP
     WHERE ESTADO_ENVIO_ID = P_ESTADO_ENVIO_ID;
  END SP_ACTUALIZAR_ESTADO_ENVIO;

  PROCEDURE SP_ELIMINAR_ESTADO_ENVIO(
    P_ESTADO_ENVIO_ID IN ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM (
        SELECT ESTADO_ENVIO_ID FROM ENVIO WHERE ESTADO_ENVIO_ID = P_ESTADO_ENVIO_ID
        UNION ALL
        SELECT ESTADO_ENVIO_ID FROM SEGUIMIENTO_ENVIO WHERE ESTADO_ENVIO_ID = P_ESTADO_ENVIO_ID
      );

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el estado de envío porque tiene registros asociados.');
    END IF;

    UPDATE ESTADO_ENVIO
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE ESTADO_ENVIO_ID = P_ESTADO_ENVIO_ID;
  END SP_ELIMINAR_ESTADO_ENVIO;

  PROCEDURE SP_OBTENER_ESTADO_ENVIO(
    P_ESTADO_ENVIO_ID IN ESTADO_ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ESTADO_ENVIO_ID,
             CODIGO,
             DESCRIPCION,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ESTADO_ENVIO
       WHERE ESTADO_ENVIO_ID = P_ESTADO_ENVIO_ID;
  END SP_OBTENER_ESTADO_ENVIO;

  PROCEDURE SP_LISTAR_ESTADOS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ESTADO_ENVIO_ID,
             CODIGO,
             DESCRIPCION,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ESTADO_ENVIO
       WHERE ESTADO = 'ACTIVO'
       ORDER BY CODIGO;
  END SP_LISTAR_ESTADOS_ENVIO;

  PROCEDURE SP_BUSCAR_ESTADOS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ESTADO_ENVIO_ID,
             CODIGO,
             DESCRIPCION,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ESTADO_ENVIO
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY CODIGO;
  END SP_BUSCAR_ESTADOS_ENVIO;

END PKG_ESTADO_ENVIO;
/
