CREATE OR REPLACE PACKAGE PKG_ORDEN_PRODUCCION AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION(
    P_NUM_OP               IN ORDEN_PRODUCCION.NUM_OP%TYPE,
    P_PRODUCTO_ID          IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PLANIFICADA IN ORDEN_PRODUCCION.CANTIDAD_PLANIFICADA%TYPE,
    P_ESTADO_PRODUCCION_ID IN ORDEN_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_INICIO_ESTIMADO      IN ORDEN_PRODUCCION.INICIO_ESTIMADO%TYPE,
    P_FIN_ESTIMADO         IN ORDEN_PRODUCCION.FIN_ESTIMADO%TYPE,
    P_INICIO_REAL          IN ORDEN_PRODUCCION.INICIO_REAL%TYPE,
    P_FIN_REAL             IN ORDEN_PRODUCCION.FIN_REAL%TYPE,
    P_ESTADO               IN ORDEN_PRODUCCION.ESTADO%TYPE,
    P_ORDEN_PRODUCCION_ID  OUT ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION(
    P_ORDEN_PRODUCCION_ID  IN ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE,
    P_NUM_OP               IN ORDEN_PRODUCCION.NUM_OP%TYPE,
    P_PRODUCTO_ID          IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PLANIFICADA IN ORDEN_PRODUCCION.CANTIDAD_PLANIFICADA%TYPE,
    P_ESTADO_PRODUCCION_ID IN ORDEN_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_INICIO_ESTIMADO      IN ORDEN_PRODUCCION.INICIO_ESTIMADO%TYPE,
    P_FIN_ESTIMADO         IN ORDEN_PRODUCCION.FIN_ESTIMADO%TYPE,
    P_INICIO_REAL          IN ORDEN_PRODUCCION.INICIO_REAL%TYPE,
    P_FIN_REAL             IN ORDEN_PRODUCCION.FIN_REAL%TYPE,
    P_ESTADO               IN ORDEN_PRODUCCION.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION(
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION(
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE,
    P_CURSOR              OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ORDEN_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ORDEN_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ORDEN_PRODUCCION;
/
CREATE OR REPLACE PACKAGE BODY PKG_ORDEN_PRODUCCION AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION(
    P_NUM_OP               IN ORDEN_PRODUCCION.NUM_OP%TYPE,
    P_PRODUCTO_ID          IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PLANIFICADA IN ORDEN_PRODUCCION.CANTIDAD_PLANIFICADA%TYPE,
    P_ESTADO_PRODUCCION_ID IN ORDEN_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_INICIO_ESTIMADO      IN ORDEN_PRODUCCION.INICIO_ESTIMADO%TYPE,
    P_FIN_ESTIMADO         IN ORDEN_PRODUCCION.FIN_ESTIMADO%TYPE,
    P_INICIO_REAL          IN ORDEN_PRODUCCION.INICIO_REAL%TYPE,
    P_FIN_REAL             IN ORDEN_PRODUCCION.FIN_REAL%TYPE,
    P_ESTADO               IN ORDEN_PRODUCCION.ESTADO%TYPE,
    P_ORDEN_PRODUCCION_ID  OUT ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ORDEN_PRODUCCION (
      NUM_OP,
      PRODUCTO_ID,
      CANTIDAD_PLANIFICADA,
      ESTADO_PRODUCCION_ID,
      INICIO_ESTIMADO,
      FIN_ESTIMADO,
      INICIO_REAL,
      FIN_REAL,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_NUM_OP,
      P_PRODUCTO_ID,
      P_CANTIDAD_PLANIFICADA,
      P_ESTADO_PRODUCCION_ID,
      P_INICIO_ESTIMADO,
      P_FIN_ESTIMADO,
      P_INICIO_REAL,
      P_FIN_REAL,
      SYSTIMESTAMP,
      P_ESTADO
    )
    RETURNING ORDEN_PRODUCCION_ID INTO P_ORDEN_PRODUCCION_ID;
  END SP_INSERTAR_ORDEN_PRODUCCION;

  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION(
    P_ORDEN_PRODUCCION_ID  IN ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE,
    P_NUM_OP               IN ORDEN_PRODUCCION.NUM_OP%TYPE,
    P_PRODUCTO_ID          IN ORDEN_PRODUCCION.PRODUCTO_ID%TYPE,
    P_CANTIDAD_PLANIFICADA IN ORDEN_PRODUCCION.CANTIDAD_PLANIFICADA%TYPE,
    P_ESTADO_PRODUCCION_ID IN ORDEN_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_INICIO_ESTIMADO      IN ORDEN_PRODUCCION.INICIO_ESTIMADO%TYPE,
    P_FIN_ESTIMADO         IN ORDEN_PRODUCCION.FIN_ESTIMADO%TYPE,
    P_INICIO_REAL          IN ORDEN_PRODUCCION.INICIO_REAL%TYPE,
    P_FIN_REAL             IN ORDEN_PRODUCCION.FIN_REAL%TYPE,
    P_ESTADO               IN ORDEN_PRODUCCION.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE ORDEN_PRODUCCION
       SET NUM_OP               = P_NUM_OP,
           PRODUCTO_ID          = P_PRODUCTO_ID,
           CANTIDAD_PLANIFICADA = P_CANTIDAD_PLANIFICADA,
           ESTADO_PRODUCCION_ID = P_ESTADO_PRODUCCION_ID,
           INICIO_ESTIMADO      = P_INICIO_ESTIMADO,
           FIN_ESTIMADO         = P_FIN_ESTIMADO,
           INICIO_REAL          = P_INICIO_REAL,
           FIN_REAL             = P_FIN_REAL,
           UPDATED_AT           = SYSTIMESTAMP,
           ESTADO               = P_ESTADO
     WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID;
  END SP_ACTUALIZAR_ORDEN_PRODUCCION;

  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION(
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE
  ) AS
    V_EXISTE_TAREAS      NUMBER;
    V_EXISTE_RESULTADOS  NUMBER;
    V_EXISTE_CONSUMO     NUMBER;
  BEGIN
    SELECT COUNT(*) INTO V_EXISTE_TAREAS
      FROM ORDEN_PRODUCCION_TAREA
     WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID
       AND NVL(ESTADO, 'ACTIVO') <> 'INACTIVO';

    SELECT COUNT(*) INTO V_EXISTE_RESULTADOS
      FROM PRODUCCION_RESULTADOS
     WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID
       AND NVL(ESTADO, 'ACTIVO') <> 'INACTIVO';

    SELECT COUNT(*) INTO V_EXISTE_CONSUMO
      FROM CONSUMO_MATERIA_PRIMA
     WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID
       AND NVL(ESTADO, 'ACTIVO') <> 'INACTIVO';

    IF V_EXISTE_TAREAS > 0 OR V_EXISTE_RESULTADOS > 0 OR V_EXISTE_CONSUMO > 0 THEN
      UPDATE ORDEN_PRODUCCION
         SET ESTADO = 'INACTIVO',
             UPDATED_AT = SYSTIMESTAMP
       WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID;
    ELSE
      DELETE FROM ORDEN_PRODUCCION
       WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID;
    END IF;
  END SP_ELIMINAR_ORDEN_PRODUCCION;

  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION(
    P_ORDEN_PRODUCCION_ID IN ORDEN_PRODUCCION.ORDEN_PRODUCCION_ID%TYPE,
    P_CURSOR              OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ORDEN_PRODUCCION_ID,
             NUM_OP,
             PRODUCTO_ID,
             CANTIDAD_PLANIFICADA,
             ESTADO_PRODUCCION_ID,
             INICIO_ESTIMADO,
             FIN_ESTIMADO,
             INICIO_REAL,
             FIN_REAL,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ORDEN_PRODUCCION
       WHERE ORDEN_PRODUCCION_ID = P_ORDEN_PRODUCCION_ID;
  END SP_OBTENER_ORDEN_PRODUCCION;

  PROCEDURE SP_LISTAR_ORDEN_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ORDEN_PRODUCCION_ID,
             NUM_OP,
             PRODUCTO_ID,
             CANTIDAD_PLANIFICADA,
             ESTADO_PRODUCCION_ID,
             INICIO_ESTIMADO,
             FIN_ESTIMADO,
             INICIO_REAL,
             FIN_REAL,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ORDEN_PRODUCCION
       ORDER BY ORDEN_PRODUCCION_ID DESC;
  END SP_LISTAR_ORDEN_PRODUCCION;

  PROCEDURE SP_BUSCAR_ORDEN_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ORDEN_PRODUCCION_ID,
             NUM_OP,
             PRODUCTO_ID,
             CANTIDAD_PLANIFICADA,
             ESTADO_PRODUCCION_ID,
             INICIO_ESTIMADO,
             FIN_ESTIMADO,
             INICIO_REAL,
             FIN_REAL,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
        FROM ORDEN_PRODUCCION
       WHERE (
             (UPPER(P_CRITERIO) = 'ORDEN_PRODUCCION_ID' AND TO_CHAR(ORDEN_PRODUCCION_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'NUM_OP' AND UPPER(NUM_OP) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'PRODUCTO_ID' AND TO_CHAR(PRODUCTO_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO_PRODUCCION_ID' AND TO_CHAR(ESTADO_PRODUCCION_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY ORDEN_PRODUCCION_ID DESC;
  END SP_BUSCAR_ORDEN_PRODUCCION;

END PKG_ORDEN_PRODUCCION;
/
