CREATE OR REPLACE PACKAGE PKG_EXPEDIENTE_EMPLEADO AS

  PROCEDURE SP_INSERTAR_EXPEDIENTE(
    P_EMPLEADO_ID        IN EXPEDIENTE_EMPLEADO.EMPLEADO_ID%TYPE,
    P_DESCRIPCION        IN EXPEDIENTE_EMPLEADO.DESCRIPCION%TYPE,
    P_OBSERVACIONES      IN EXPEDIENTE_EMPLEADO.OBSERVACIONES%TYPE,
    P_EXPEDIENTE_ID      OUT EXPEDIENTE_EMPLEADO.EXPEDIENTE_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_EXPEDIENTE(
    P_EXPEDIENTE_ID      IN EXPEDIENTE_EMPLEADO.EXPEDIENTE_ID%TYPE,
    P_DESCRIPCION        IN EXPEDIENTE_EMPLEADO.DESCRIPCION%TYPE,
    P_OBSERVACIONES      IN EXPEDIENTE_EMPLEADO.OBSERVACIONES%TYPE
  );

  PROCEDURE SP_ELIMINAR_EXPEDIENTE(
    P_EXPEDIENTE_ID IN EXPEDIENTE_EMPLEADO.EXPEDIENTE_ID%TYPE
  );

  PROCEDURE SP_OBTENER_EXPEDIENTE(
    P_EXPEDIENTE_ID IN EXPEDIENTE_EMPLEADO.EXPEDIENTE_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_EXPEDIENTES(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_EXPEDIENTE_EMPLEADO;
/

CREATE OR REPLACE PACKAGE BODY PKG_EXPEDIENTE_EMPLEADO AS

  PROCEDURE SP_INSERTAR_EXPEDIENTE(
    P_EMPLEADO_ID,
    P_DESCRIPCION,
    P_OBSERVACIONES,
    P_EXPEDIENTE_ID
  ) AS
  BEGIN

    INSERT INTO EXPEDIENTE_EMPLEADO(
        EMPLEADO_ID,
        DESCRIPCION,
        OBSERVACIONES,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_EMPLEADO_ID,
        P_DESCRIPCION,
        P_OBSERVACIONES,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING EXPEDIENTE_ID INTO P_EXPEDIENTE_ID;

  END SP_INSERTAR_EXPEDIENTE;


  PROCEDURE SP_ACTUALIZAR_EXPEDIENTE(
    P_EXPEDIENTE_ID,
    P_DESCRIPCION,
    P_OBSERVACIONES
  ) AS
  BEGIN

    UPDATE EXPEDIENTE_EMPLEADO
       SET DESCRIPCION = P_DESCRIPCION,
           OBSERVACIONES = P_OBSERVACIONES,
           UPDATED_AT = SYSTIMESTAMP
     WHERE EXPEDIENTE_ID = P_EXPEDIENTE_ID;

  END SP_ACTUALIZAR_EXPEDIENTE;


  PROCEDURE SP_ELIMINAR_EXPEDIENTE(
    P_EXPEDIENTE_ID
  ) AS
  BEGIN

    UPDATE EXPEDIENTE_EMPLEADO
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE EXPEDIENTE_ID = P_EXPEDIENTE_ID;

  END SP_ELIMINAR_EXPEDIENTE;


  PROCEDURE SP_OBTENER_EXPEDIENTE(
    P_EXPEDIENTE_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT EX.EXPEDIENTE_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             EX.DESCRIPCION,
             EX.OBSERVACIONES,
             EX.ESTADO
        FROM EXPEDIENTE_EMPLEADO EX
        JOIN EMPLEADO E ON EX.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE EX.EXPEDIENTE_ID = P_EXPEDIENTE_ID;

  END SP_OBTENER_EXPEDIENTE;


  PROCEDURE SP_LISTAR_EXPEDIENTES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT EX.EXPEDIENTE_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             EX.DESCRIPCION,
             EX.ESTADO
        FROM EXPEDIENTE_EMPLEADO EX
        JOIN EMPLEADO E ON EX.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE EX.ESTADO = 'ACTIVO'
       ORDER BY EX.EXPEDIENTE_ID DESC;

  END SP_LISTAR_EXPEDIENTES;

END PKG_EXPEDIENTE_EMPLEADO;
/