CREATE OR REPLACE PACKAGE PKG_PAGO AS

  PROCEDURE SP_INSERTAR(
      P_ORDEN_VENTA_ID   IN PAGO.ORDEN_VENTA_ID%TYPE,
      P_METODO_PAGO_ID   IN PAGO.METODO_PAGO_ID%TYPE,
      P_FECHA_PAGO       IN PAGO.FECHA_PAGO%TYPE,
      P_MONTO            IN PAGO.MONTO%TYPE,
      P_ID               OUT PAGO.PAGO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR(
      P_ID               IN PAGO.PAGO_ID%TYPE,
      P_ORDEN_VENTA_ID   IN PAGO.ORDEN_VENTA_ID%TYPE,
      P_METODO_PAGO_ID   IN PAGO.METODO_PAGO_ID%TYPE,
      P_FECHA_PAGO       IN PAGO.FECHA_PAGO%TYPE,
      P_MONTO            IN PAGO.MONTO%TYPE
  );

  PROCEDURE SP_ELIMINAR(
      P_ID IN PAGO.PAGO_ID%TYPE
  );

  PROCEDURE SP_OBTENER(
      P_ID     IN PAGO.PAGO_ID%TYPE,
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR(
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR(
      P_ORDEN_VENTA_ID IN NUMBER,
      P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_PAGO;
/

CREATE OR REPLACE PACKAGE BODY PKG_PAGO AS


PROCEDURE SP_INSERTAR(
    P_ORDEN_VENTA_ID   IN PAGO.ORDEN_VENTA_ID%TYPE,
    P_METODO_PAGO_ID   IN PAGO.METODO_PAGO_ID%TYPE,
    P_FECHA_PAGO       IN PAGO.FECHA_PAGO%TYPE,
    P_MONTO            IN PAGO.MONTO%TYPE,
    P_ID               OUT PAGO.PAGO_ID%TYPE
) AS
BEGIN

    INSERT INTO PAGO
    (
        ORDEN_VENTA_ID,
        METODO_PAGO_ID,
        FECHA_PAGO,
        MONTO,
        ESTADO
    )
    VALUES
    (
        P_ORDEN_VENTA_ID,
        P_METODO_PAGO_ID,
        P_FECHA_PAGO,
        P_MONTO,
        'A'
    )
    RETURNING PAGO_ID INTO P_ID;

END SP_INSERTAR;



PROCEDURE SP_ACTUALIZAR(
    P_ID               IN PAGO.PAGO_ID%TYPE,
    P_ORDEN_VENTA_ID   IN PAGO.ORDEN_VENTA_ID%TYPE,
    P_METODO_PAGO_ID   IN PAGO.METODO_PAGO_ID%TYPE,
    P_FECHA_PAGO       IN PAGO.FECHA_PAGO%TYPE,
    P_MONTO            IN PAGO.MONTO%TYPE
) AS
BEGIN

    UPDATE PAGO
    SET
        ORDEN_VENTA_ID = P_ORDEN_VENTA_ID,
        METODO_PAGO_ID = P_METODO_PAGO_ID,
        FECHA_PAGO = P_FECHA_PAGO,
        MONTO = P_MONTO
    WHERE PAGO_ID = P_ID;

END SP_ACTUALIZAR;



PROCEDURE SP_ELIMINAR(
    P_ID IN PAGO.PAGO_ID%TYPE
) AS
BEGIN

    UPDATE PAGO
    SET ESTADO = 'I'
    WHERE PAGO_ID = P_ID;

END SP_ELIMINAR;



PROCEDURE SP_OBTENER(
    P_ID     IN PAGO.PAGO_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            PAGO_ID,
            ORDEN_VENTA_ID,
            METODO_PAGO_ID,
            FECHA_PAGO,
            MONTO,
            ESTADO
        FROM PAGO
        WHERE PAGO_ID = P_ID;

END SP_OBTENER;



PROCEDURE SP_LISTAR(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            PAGO_ID,
            ORDEN_VENTA_ID,
            METODO_PAGO_ID,
            FECHA_PAGO,
            MONTO,
            ESTADO
        FROM PAGO
        WHERE ESTADO = 'A'
        ORDER BY FECHA_PAGO DESC;

END SP_LISTAR;



PROCEDURE SP_BUSCAR(
    P_ORDEN_VENTA_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            PAGO_ID,
            ORDEN_VENTA_ID,
            METODO_PAGO_ID,
            FECHA_PAGO,
            MONTO,
            ESTADO
        FROM PAGO
        WHERE ORDEN_VENTA_ID = P_ORDEN_VENTA_ID
        AND ESTADO = 'A';

END SP_BUSCAR;


END PKG_PAGO;
/