CREATE OR REPLACE PACKAGE PKG_HISTORIAL_PASSWORD AS

  PROCEDURE SP_REGISTRAR_CAMBIO(
    P_USUARIO_ID        IN HISTORIAL_CAMBIO_CONTRASENA.USUARIO_ID%TYPE,
    P_PASSWORD_ANTERIOR IN HISTORIAL_CAMBIO_CONTRASENA.PASSWORD_ANTERIOR%TYPE
  );

  PROCEDURE SP_HISTORIAL_USUARIO(
    P_USUARIO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_VERIFICAR_PASSWORD(
    P_USUARIO_ID IN NUMBER,
    P_PASSWORD   IN VARCHAR2,
    P_EXISTE     OUT NUMBER
  );

END PKG_HISTORIAL_PASSWORD;
/

CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_PASSWORD AS


  PROCEDURE SP_REGISTRAR_CAMBIO(
    P_USUARIO_ID        IN HISTORIAL_CAMBIO_CONTRASENA.USUARIO_ID%TYPE,
    P_PASSWORD_ANTERIOR IN HISTORIAL_CAMBIO_CONTRASENA.PASSWORD_ANTERIOR%TYPE
  ) AS
  BEGIN

    INSERT INTO HISTORIAL_CAMBIO_CONTRASENA(
        USUARIO_ID,
        PASSWORD_ANTERIOR,
        FECHA_CAMBIO
    )
    VALUES(
        P_USUARIO_ID,
        P_PASSWORD_ANTERIOR,
        SYSTIMESTAMP
    );

  END SP_REGISTRAR_CAMBIO;



  PROCEDURE SP_HISTORIAL_USUARIO(
    P_USUARIO_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            HISTORIAL_ID,
            USUARIO_ID,
            PASSWORD_ANTERIOR,
            FECHA_CAMBIO
        FROM HISTORIAL_CAMBIO_CONTRASENA
        WHERE USUARIO_ID = P_USUARIO_ID
        ORDER BY FECHA_CAMBIO DESC;

  END SP_HISTORIAL_USUARIO;



  PROCEDURE SP_VERIFICAR_PASSWORD(
    P_USUARIO_ID IN NUMBER,
    P_PASSWORD   IN VARCHAR2,
    P_EXISTE     OUT NUMBER
  ) AS
  BEGIN

    SELECT COUNT(*)
    INTO P_EXISTE
    FROM HISTORIAL_CAMBIO_CONTRASENA
    WHERE USUARIO_ID = P_USUARIO_ID
    AND PASSWORD_ANTERIOR = P_PASSWORD;

  END SP_VERIFICAR_PASSWORD;


END PKG_HISTORIAL_PASSWORD;
/