CREATE OR REPLACE PACKAGE PKG_CUPON AS

  PROCEDURE SP_INSERTAR_CUPON(
    P_CODIGO                  IN CUPON.CODIGO%TYPE,
    P_DESCRIPCION             IN CUPON.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO         IN CUPON.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN            IN CUPON.VIGENCIA_FIN%TYPE,
    P_LIMITE_USO_TOTAL        IN CUPON.LIMITE_USO_TOTAL%TYPE,
    P_LIMITE_USO_POR_CLIENTE  IN CUPON.LIMITE_USO_POR_CLIENTE%TYPE,
    P_USOS_ACTUALES           IN CUPON.USOS_ACTUALES%TYPE,
    P_CUPON_ID                OUT CUPON.CUPON_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CUPON(
    P_CUPON_ID                IN CUPON.CUPON_ID%TYPE,
    P_CODIGO                  IN CUPON.CODIGO%TYPE,
    P_DESCRIPCION             IN CUPON.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO         IN CUPON.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN            IN CUPON.VIGENCIA_FIN%TYPE,
    P_LIMITE_USO_TOTAL        IN CUPON.LIMITE_USO_TOTAL%TYPE,
    P_LIMITE_USO_POR_CLIENTE  IN CUPON.LIMITE_USO_POR_CLIENTE%TYPE,
    P_USOS_ACTUALES           IN CUPON.USOS_ACTUALES%TYPE
  );

  PROCEDURE SP_ELIMINAR_CUPON(
    P_CUPON_ID IN CUPON.CUPON_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CUPON(
    P_CUPON_ID IN CUPON.CUPON_ID%TYPE,
    P_CURSOR   OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CUPONES(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CUPONES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CUPON;
/

CREATE OR REPLACE PACKAGE BODY PKG_CUPON AS

  PROCEDURE SP_INSERTAR_CUPON(
    P_CODIGO                  IN CUPON.CODIGO%TYPE,
    P_DESCRIPCION             IN CUPON.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO         IN CUPON.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN            IN CUPON.VIGENCIA_FIN%TYPE,
    P_LIMITE_USO_TOTAL        IN CUPON.LIMITE_USO_TOTAL%TYPE,
    P_LIMITE_USO_POR_CLIENTE  IN CUPON.LIMITE_USO_POR_CLIENTE%TYPE,
    P_USOS_ACTUALES           IN CUPON.USOS_ACTUALES%TYPE,
    P_CUPON_ID                OUT CUPON.CUPON_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CUPON (
      CODIGO,
      DESCRIPCION,
      VIGENCIA_INICIO,
      VIGENCIA_FIN,
      LIMITE_USO_TOTAL,
      LIMITE_USO_POR_CLIENTE,
      USOS_ACTUALES,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_CODIGO,
      P_DESCRIPCION,
      P_VIGENCIA_INICIO,
      P_VIGENCIA_FIN,
      P_LIMITE_USO_TOTAL,
      P_LIMITE_USO_POR_CLIENTE,
      P_USOS_ACTUALES,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CUPON_ID INTO P_CUPON_ID;
  END SP_INSERTAR_CUPON;

  PROCEDURE SP_ACTUALIZAR_CUPON(
    P_CUPON_ID                IN CUPON.CUPON_ID%TYPE,
    P_CODIGO                  IN CUPON.CODIGO%TYPE,
    P_DESCRIPCION             IN CUPON.DESCRIPCION%TYPE,
    P_VIGENCIA_INICIO         IN CUPON.VIGENCIA_INICIO%TYPE,
    P_VIGENCIA_FIN            IN CUPON.VIGENCIA_FIN%TYPE,
    P_LIMITE_USO_TOTAL        IN CUPON.LIMITE_USO_TOTAL%TYPE,
    P_LIMITE_USO_POR_CLIENTE  IN CUPON.LIMITE_USO_POR_CLIENTE%TYPE,
    P_USOS_ACTUALES           IN CUPON.USOS_ACTUALES%TYPE
  ) AS
  BEGIN
    UPDATE CUPON
       SET CODIGO                 = P_CODIGO,
           DESCRIPCION            = P_DESCRIPCION,
           VIGENCIA_INICIO        = P_VIGENCIA_INICIO,
           VIGENCIA_FIN           = P_VIGENCIA_FIN,
           LIMITE_USO_TOTAL       = P_LIMITE_USO_TOTAL,
           LIMITE_USO_POR_CLIENTE = P_LIMITE_USO_POR_CLIENTE,
           USOS_ACTUALES          = P_USOS_ACTUALES,
           UPDATED_AT             = SYSTIMESTAMP
     WHERE CUPON_ID = P_CUPON_ID;
  END SP_ACTUALIZAR_CUPON;

  PROCEDURE SP_ELIMINAR_CUPON(
    P_CUPON_ID IN CUPON.CUPON_ID%TYPE
  ) AS
  BEGIN
    UPDATE CUPON
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE CUPON_ID = P_CUPON_ID;
  END SP_ELIMINAR_CUPON;

  PROCEDURE SP_OBTENER_CUPON(
    P_CUPON_ID IN CUPON.CUPON_ID%TYPE,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CUPON_ID,
             CODIGO,
             DESCRIPCION,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             LIMITE_USO_TOTAL,
             LIMITE_USO_POR_CLIENTE,
             USOS_ACTUALES,
             ESTADO
        FROM CUPON
       WHERE CUPON_ID = P_CUPON_ID;
  END SP_OBTENER_CUPON;

  PROCEDURE SP_LISTAR_CUPONES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CUPON_ID,
             CODIGO,
             DESCRIPCION,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             LIMITE_USO_TOTAL,
             LIMITE_USO_POR_CLIENTE,
             USOS_ACTUALES,
             ESTADO
        FROM CUPON
       WHERE ESTADO = 'ACTIVO'
       ORDER BY CODIGO;
  END SP_LISTAR_CUPONES;

  PROCEDURE SP_BUSCAR_CUPONES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CUPON_ID,
             CODIGO,
             DESCRIPCION,
             VIGENCIA_INICIO,
             VIGENCIA_FIN,
             LIMITE_USO_TOTAL,
             LIMITE_USO_POR_CLIENTE,
             USOS_ACTUALES,
             ESTADO
        FROM CUPON
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY CODIGO;
  END SP_BUSCAR_CUPONES;

END PKG_CUPON;
/
