CREATE OR REPLACE PACKAGE PKG_CARRITO AS
  PROCEDURE SP_INSERTAR_CARRITO(
    P_CLI_ID IN CARRITO.CLI_ID%TYPE,
    P_ESTADO_CARRITO IN CARRITO.ESTADO_CARRITO%TYPE,
    P_ULTIMO_CALCULO_AT IN CARRITO.ULTIMO_CALCULO_AT%TYPE,
    P_CARRITO_ID OUT CARRITO.CARRITO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CARRITO(
    P_CARRITO_ID IN CARRITO.CARRITO_ID%TYPE,
    P_CLI_ID IN CARRITO.CLI_ID%TYPE,
    P_ESTADO_CARRITO IN CARRITO.ESTADO_CARRITO%TYPE,
    P_ULTIMO_CALCULO_AT IN CARRITO.ULTIMO_CALCULO_AT%TYPE
  );

  PROCEDURE SP_ELIMINAR_CARRITO(
    P_CARRITO_ID IN CARRITO.CARRITO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CARRITO(
    P_CARRITO_ID IN  CARRITO.CARRITO_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CARRITO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CARRITO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CARRITO;
/

CREATE OR REPLACE PACKAGE BODY PKG_CARRITO AS

  PROCEDURE SP_INSERTAR_CARRITO(
    P_CLI_ID IN CARRITO.CLI_ID%TYPE,
    P_ESTADO_CARRITO IN CARRITO.ESTADO_CARRITO%TYPE,
    P_ULTIMO_CALCULO_AT IN CARRITO.ULTIMO_CALCULO_AT%TYPE,
    P_CARRITO_ID OUT CARRITO.CARRITO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CARRITO (
      CLI_ID,
      ESTADO_CARRITO,
      ULTIMO_CALCULO_AT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CLI_ID,
      P_ESTADO_CARRITO,
      P_ULTIMO_CALCULO_AT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CARRITO_ID INTO P_CARRITO_ID;
  END SP_INSERTAR_CARRITO;

  PROCEDURE SP_ACTUALIZAR_CARRITO(
    P_CARRITO_ID IN CARRITO.CARRITO_ID%TYPE,
    P_CLI_ID IN CARRITO.CLI_ID%TYPE,
    P_ESTADO_CARRITO IN CARRITO.ESTADO_CARRITO%TYPE,
    P_ULTIMO_CALCULO_AT IN CARRITO.ULTIMO_CALCULO_AT%TYPE
  ) AS
  BEGIN
    UPDATE CARRITO
    SET         CLI_ID = P_CLI_ID,
        ESTADO_CARRITO = P_ESTADO_CARRITO,
        ULTIMO_CALCULO_AT = P_ULTIMO_CALCULO_AT,
        UPDATED_AT = SYSTIMESTAMP
    WHERE CARRITO_ID = P_CARRITO_ID;
  END SP_ACTUALIZAR_CARRITO;

  PROCEDURE SP_ELIMINAR_CARRITO(
    P_CARRITO_ID IN CARRITO.CARRITO_ID%TYPE
  ) AS
  BEGIN
    UPDATE CARRITO
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE CARRITO_ID = P_CARRITO_ID;
  END SP_ELIMINAR_CARRITO;

  PROCEDURE SP_OBTENER_CARRITO(
    P_CARRITO_ID IN  CARRITO.CARRITO_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              CARRITO_ID,
             CLI_ID,
             ESTADO_CARRITO,
             ULTIMO_CALCULO_AT,
             ESTADO
      FROM CARRITO
      WHERE CARRITO_ID = P_CARRITO_ID;
  END SP_OBTENER_CARRITO;

  PROCEDURE SP_LISTAR_CARRITO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              CARRITO_ID,
             CLI_ID,
             ESTADO_CARRITO,
             ULTIMO_CALCULO_AT,
             ESTADO
      FROM CARRITO
      WHERE ESTADO = 'ACTIVO'
      ORDER BY CARRITO_ID DESC;
  END SP_LISTAR_CARRITO;

  PROCEDURE SP_BUSCAR_CARRITO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              CARRITO_ID,
             CLI_ID,
             ESTADO_CARRITO,
             ULTIMO_CALCULO_AT,
             ESTADO
      FROM CARRITO
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'CLI_ID' AND UPPER(CAST(CLI_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'ESTADO_CARRITO' AND UPPER(CAST(ESTADO_CARRITO AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY CARRITO_ID DESC;
  END SP_BUSCAR_CARRITO;

END PKG_CARRITO;
/
