CREATE OR REPLACE PACKAGE PKG_FAQ AS
  PROCEDURE SP_INSERTAR_FAQ(
    P_PREGUNTA IN FAQ.PREGUNTA%TYPE,
    P_RESPUESTA IN FAQ.RESPUESTA%TYPE,
    P_ORDEN IN FAQ.ORDEN%TYPE,
    P_FAQ_ID OUT FAQ.FAQ_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_FAQ(
    P_FAQ_ID IN FAQ.FAQ_ID%TYPE,
    P_PREGUNTA IN FAQ.PREGUNTA%TYPE,
    P_RESPUESTA IN FAQ.RESPUESTA%TYPE,
    P_ORDEN IN FAQ.ORDEN%TYPE
  );

  PROCEDURE SP_ELIMINAR_FAQ(
    P_FAQ_ID IN FAQ.FAQ_ID%TYPE
  );

  PROCEDURE SP_OBTENER_FAQ(
    P_FAQ_ID IN  FAQ.FAQ_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_FAQ(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_FAQ(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_FAQ;
/

CREATE OR REPLACE PACKAGE BODY PKG_FAQ AS

  PROCEDURE SP_INSERTAR_FAQ(
    P_PREGUNTA IN FAQ.PREGUNTA%TYPE,
    P_RESPUESTA IN FAQ.RESPUESTA%TYPE,
    P_ORDEN IN FAQ.ORDEN%TYPE,
    P_FAQ_ID OUT FAQ.FAQ_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO FAQ (
      PREGUNTA,
      RESPUESTA,
      ORDEN,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_PREGUNTA,
      P_RESPUESTA,
      P_ORDEN,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING FAQ_ID INTO P_FAQ_ID;
  END SP_INSERTAR_FAQ;

  PROCEDURE SP_ACTUALIZAR_FAQ(
    P_FAQ_ID IN FAQ.FAQ_ID%TYPE,
    P_PREGUNTA IN FAQ.PREGUNTA%TYPE,
    P_RESPUESTA IN FAQ.RESPUESTA%TYPE,
    P_ORDEN IN FAQ.ORDEN%TYPE
  ) AS
  BEGIN
    UPDATE FAQ
    SET         PREGUNTA = P_PREGUNTA,
        RESPUESTA = P_RESPUESTA,
        ORDEN = P_ORDEN,
        UPDATED_AT = SYSTIMESTAMP
    WHERE FAQ_ID = P_FAQ_ID;
  END SP_ACTUALIZAR_FAQ;

  PROCEDURE SP_ELIMINAR_FAQ(
    P_FAQ_ID IN FAQ.FAQ_ID%TYPE
  ) AS
  BEGIN
    UPDATE FAQ
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE FAQ_ID = P_FAQ_ID;
  END SP_ELIMINAR_FAQ;

  PROCEDURE SP_OBTENER_FAQ(
    P_FAQ_ID IN  FAQ.FAQ_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              FAQ_ID,
             PREGUNTA,
             ORDEN,
             ESTADO
      FROM FAQ
      WHERE FAQ_ID = P_FAQ_ID;
  END SP_OBTENER_FAQ;

  PROCEDURE SP_LISTAR_FAQ(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              FAQ_ID,
             PREGUNTA,
             ORDEN,
             ESTADO
      FROM FAQ
      WHERE ESTADO = 'ACTIVO'
      ORDER BY ORDEN;
  END SP_LISTAR_FAQ;

  PROCEDURE SP_BUSCAR_FAQ(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              FAQ_ID,
             PREGUNTA,
             ORDEN,
             ESTADO
      FROM FAQ
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'PREGUNTA' AND UPPER(CAST(PREGUNTA AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'RESPUESTA' AND UPPER(CAST(RESPUESTA AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY ORDEN;
  END SP_BUSCAR_FAQ;

END PKG_FAQ;
/
