CREATE OR REPLACE PACKAGE PKG_INCIDENTE_LABORAL AS

  PROCEDURE SP_INSERTAR_INCIDENTE(
    P_EMPLEADO_ID      IN INCIDENTE_LABORAL.EMPLEADO_ID%TYPE,
    P_TIPO_INCIDENTE   IN INCIDENTE_LABORAL.TIPO_INCIDENTE%TYPE,
    P_DESCRIPCION      IN INCIDENTE_LABORAL.DESCRIPCION%TYPE,
    P_FECHA_INCIDENTE  IN INCIDENTE_LABORAL.FECHA_INCIDENTE%TYPE,
    P_INCIDENTE_ID     OUT INCIDENTE_LABORAL.INCIDENTE_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_INCIDENTE(
    P_INCIDENTE_ID     IN INCIDENTE_LABORAL.INCIDENTE_ID%TYPE,
    P_TIPO_INCIDENTE   IN INCIDENTE_LABORAL.TIPO_INCIDENTE%TYPE,
    P_DESCRIPCION      IN INCIDENTE_LABORAL.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_INCIDENTE(
    P_INCIDENTE_ID IN INCIDENTE_LABORAL.INCIDENTE_ID%TYPE
  );

  PROCEDURE SP_OBTENER_INCIDENTE(
    P_INCIDENTE_ID IN INCIDENTE_LABORAL.INCIDENTE_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_INCIDENTES(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_INCIDENTE_LABORAL;
/

CREATE OR REPLACE PACKAGE BODY PKG_INCIDENTE_LABORAL AS

  PROCEDURE SP_INSERTAR_INCIDENTE(
    P_EMPLEADO_ID,
    P_TIPO_INCIDENTE,
    P_DESCRIPCION,
    P_FECHA_INCIDENTE,
    P_INCIDENTE_ID
  ) AS
  BEGIN

    INSERT INTO INCIDENTE_LABORAL(
        EMPLEADO_ID,
        TIPO_INCIDENTE,
        DESCRIPCION,
        FECHA_INCIDENTE,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_EMPLEADO_ID,
        P_TIPO_INCIDENTE,
        P_DESCRIPCION,
        P_FECHA_INCIDENTE,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING INCIDENTE_ID INTO P_INCIDENTE_ID;

  END SP_INSERTAR_INCIDENTE;



  PROCEDURE SP_ACTUALIZAR_INCIDENTE(
    P_INCIDENTE_ID,
    P_TIPO_INCIDENTE,
    P_DESCRIPCION
  ) AS
  BEGIN

    UPDATE INCIDENTE_LABORAL
       SET TIPO_INCIDENTE = P_TIPO_INCIDENTE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT = SYSTIMESTAMP
     WHERE INCIDENTE_ID = P_INCIDENTE_ID;

  END SP_ACTUALIZAR_INCIDENTE;



  PROCEDURE SP_ELIMINAR_INCIDENTE(
    P_INCIDENTE_ID
  ) AS
  BEGIN

    UPDATE INCIDENTE_LABORAL
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE INCIDENTE_ID = P_INCIDENTE_ID;

  END SP_ELIMINAR_INCIDENTE;



  PROCEDURE SP_OBTENER_INCIDENTE(
    P_INCIDENTE_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT I.INCIDENTE_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             I.TIPO_INCIDENTE,
             I.DESCRIPCION,
             I.FECHA_INCIDENTE
        FROM INCIDENTE_LABORAL I
        JOIN EMPLEADO E ON I.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE I.INCIDENTE_ID = P_INCIDENTE_ID;

  END SP_OBTENER_INCIDENTE;



  PROCEDURE SP_LISTAR_INCIDENTES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT I.INCIDENTE_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             I.TIPO_INCIDENTE,
             I.FECHA_INCIDENTE,
             I.ESTADO
        FROM INCIDENTE_LABORAL I
        JOIN EMPLEADO E ON I.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE I.ESTADO = 'ACTIVO'
       ORDER BY I.FECHA_INCIDENTE DESC;

  END SP_LISTAR_INCIDENTES;

END PKG_INCIDENTE_LABORAL;
/