CREATE OR REPLACE PACKAGE PKG_EVALUACION AS

  PROCEDURE SP_INSERTAR_EVALUACION(
    P_EMPLEADO_ID     IN EVALUACION.EMPLEADO_ID%TYPE,
    P_FECHA_EVAL      IN EVALUACION.FECHA_EVAL%TYPE,
    P_CALIFICACION    IN EVALUACION.CALIFICACION%TYPE,
    P_COMENTARIOS     IN EVALUACION.COMENTARIOS%TYPE,
    P_EVALUACION_ID   OUT EVALUACION.EVALUACION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_EVALUACION(
    P_EVALUACION_ID   IN EVALUACION.EVALUACION_ID%TYPE,
    P_FECHA_EVAL      IN EVALUACION.FECHA_EVAL%TYPE,
    P_CALIFICACION    IN EVALUACION.CALIFICACION%TYPE,
    P_COMENTARIOS     IN EVALUACION.COMENTARIOS%TYPE
  );

  PROCEDURE SP_ELIMINAR_EVALUACION(
    P_EVALUACION_ID IN EVALUACION.EVALUACION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_EVALUACION(
    P_EVALUACION_ID IN EVALUACION.EVALUACION_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_EVALUACIONES(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_EVALUACION;
/

CREATE OR REPLACE PACKAGE BODY PKG_EVALUACION AS

  PROCEDURE SP_INSERTAR_EVALUACION(
    P_EMPLEADO_ID,
    P_FECHA_EVAL,
    P_CALIFICACION,
    P_COMENTARIOS,
    P_EVALUACION_ID
  ) AS
  BEGIN

    INSERT INTO EVALUACION(
        EMPLEADO_ID,
        FECHA_EVAL,
        CALIFICACION,
        COMENTARIOS,
        CREATED_AT,
        ESTADO
    )
    VALUES(
        P_EMPLEADO_ID,
        P_FECHA_EVAL,
        P_CALIFICACION,
        P_COMENTARIOS,
        SYSTIMESTAMP,
        'ACTIVO'
    )
    RETURNING EVALUACION_ID INTO P_EVALUACION_ID;

  END SP_INSERTAR_EVALUACION;


  PROCEDURE SP_ACTUALIZAR_EVALUACION(
    P_EVALUACION_ID,
    P_FECHA_EVAL,
    P_CALIFICACION,
    P_COMENTARIOS
  ) AS
  BEGIN

    UPDATE EVALUACION
       SET FECHA_EVAL = P_FECHA_EVAL,
           CALIFICACION = P_CALIFICACION,
           COMENTARIOS = P_COMENTARIOS,
           UPDATED_AT = SYSTIMESTAMP
     WHERE EVALUACION_ID = P_EVALUACION_ID;

  END SP_ACTUALIZAR_EVALUACION;


  PROCEDURE SP_ELIMINAR_EVALUACION(
    P_EVALUACION_ID IN EVALUACION.EVALUACION_ID%TYPE
  ) AS
  BEGIN

    UPDATE EVALUACION
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE EVALUACION_ID = P_EVALUACION_ID;

  END SP_ELIMINAR_EVALUACION;


  PROCEDURE SP_OBTENER_EVALUACION(
    P_EVALUACION_ID,
    P_CURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT EV.EVALUACION_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             EV.FECHA_EVAL,
             EV.CALIFICACION,
             EV.COMENTARIOS,
             EV.ESTADO
        FROM EVALUACION EV
        JOIN EMPLEADO E ON EV.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE EV.EVALUACION_ID = P_EVALUACION_ID;

  END SP_OBTENER_EVALUACION;


  PROCEDURE SP_LISTAR_EVALUACIONES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT EV.EVALUACION_ID,
             E.NOMBRES || ' ' || E.APELLIDOS AS EMPLEADO,
             EV.FECHA_EVAL,
             EV.CALIFICACION,
             EV.ESTADO
        FROM EVALUACION EV
        JOIN EMPLEADO E ON EV.EMPLEADO_ID = E.EMPLEADO_ID
       WHERE EV.ESTADO = 'ACTIVO'
       ORDER BY EV.FECHA_EVAL DESC;

  END SP_LISTAR_EVALUACIONES;

END PKG_EVALUACION;
/