CREATE OR REPLACE PACKAGE PKG_ORDEN_VENTA_DETALLE AS

  PROCEDURE SP_INSERTAR(
      P_ORDEN_VENTA_ID   IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_ID%TYPE,
      P_PRODUCTO_ID      IN ORDEN_VENTA_DETALLE.PRODUCTO_ID%TYPE,
      P_CANTIDAD         IN ORDEN_VENTA_DETALLE.CANTIDAD%TYPE,
      P_PRECIO_UNITARIO  IN ORDEN_VENTA_DETALLE.PRECIO_UNITARIO%TYPE,
      P_SUBTOTAL         IN ORDEN_VENTA_DETALLE.SUBTOTAL%TYPE,
      P_ID               OUT ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR(
      P_ID               IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE,
      P_ORDEN_VENTA_ID   IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_ID%TYPE,
      P_PRODUCTO_ID      IN ORDEN_VENTA_DETALLE.PRODUCTO_ID%TYPE,
      P_CANTIDAD         IN ORDEN_VENTA_DETALLE.CANTIDAD%TYPE,
      P_PRECIO_UNITARIO  IN ORDEN_VENTA_DETALLE.PRECIO_UNITARIO%TYPE,
      P_SUBTOTAL         IN ORDEN_VENTA_DETALLE.SUBTOTAL%TYPE
  );

  PROCEDURE SP_ELIMINAR(
      P_ID IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE
  );

  PROCEDURE SP_OBTENER(
      P_ID     IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE,
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR(
      P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR(
      P_ORDEN_VENTA_ID IN NUMBER,
      P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_ORDEN_VENTA_DETALLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_ORDEN_VENTA_DETALLE AS


PROCEDURE SP_INSERTAR(
    P_ORDEN_VENTA_ID   IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_ID%TYPE,
    P_PRODUCTO_ID      IN ORDEN_VENTA_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD         IN ORDEN_VENTA_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO  IN ORDEN_VENTA_DETALLE.PRECIO_UNITARIO%TYPE,
    P_SUBTOTAL         IN ORDEN_VENTA_DETALLE.SUBTOTAL%TYPE,
    P_ID               OUT ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE
) AS
BEGIN

    INSERT INTO ORDEN_VENTA_DETALLE
    (
        ORDEN_VENTA_ID,
        PRODUCTO_ID,
        CANTIDAD,
        PRECIO_UNITARIO,
        SUBTOTAL,
        ESTADO
    )
    VALUES
    (
        P_ORDEN_VENTA_ID,
        P_PRODUCTO_ID,
        P_CANTIDAD,
        P_PRECIO_UNITARIO,
        P_SUBTOTAL,
        'A'
    )
    RETURNING ORDEN_VENTA_DETALLE_ID INTO P_ID;

END SP_INSERTAR;



PROCEDURE SP_ACTUALIZAR(
    P_ID               IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE,
    P_ORDEN_VENTA_ID   IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_ID%TYPE,
    P_PRODUCTO_ID      IN ORDEN_VENTA_DETALLE.PRODUCTO_ID%TYPE,
    P_CANTIDAD         IN ORDEN_VENTA_DETALLE.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO  IN ORDEN_VENTA_DETALLE.PRECIO_UNITARIO%TYPE,
    P_SUBTOTAL         IN ORDEN_VENTA_DETALLE.SUBTOTAL%TYPE
) AS
BEGIN

    UPDATE ORDEN_VENTA_DETALLE
    SET
        ORDEN_VENTA_ID = P_ORDEN_VENTA_ID,
        PRODUCTO_ID = P_PRODUCTO_ID,
        CANTIDAD = P_CANTIDAD,
        PRECIO_UNITARIO = P_PRECIO_UNITARIO,
        SUBTOTAL = P_SUBTOTAL
    WHERE ORDEN_VENTA_DETALLE_ID = P_ID;

END SP_ACTUALIZAR;



PROCEDURE SP_ELIMINAR(
    P_ID IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE
) AS
BEGIN

    UPDATE ORDEN_VENTA_DETALLE
    SET ESTADO = 'I'
    WHERE ORDEN_VENTA_DETALLE_ID = P_ID;

END SP_ELIMINAR;



PROCEDURE SP_OBTENER(
    P_ID     IN ORDEN_VENTA_DETALLE.ORDEN_VENTA_DETALLE_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ORDEN_VENTA_DETALLE_ID,
            ORDEN_VENTA_ID,
            PRODUCTO_ID,
            CANTIDAD,
            PRECIO_UNITARIO,
            SUBTOTAL,
            ESTADO
        FROM ORDEN_VENTA_DETALLE
        WHERE ORDEN_VENTA_DETALLE_ID = P_ID;

END SP_OBTENER;



PROCEDURE SP_LISTAR(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ORDEN_VENTA_DETALLE_ID,
            ORDEN_VENTA_ID,
            PRODUCTO_ID,
            CANTIDAD,
            PRECIO_UNITARIO,
            SUBTOTAL,
            ESTADO
        FROM ORDEN_VENTA_DETALLE
        WHERE ESTADO = 'A'
        ORDER BY ORDEN_VENTA_ID;

END SP_LISTAR;



PROCEDURE SP_BUSCAR(
    P_ORDEN_VENTA_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ORDEN_VENTA_DETALLE_ID,
            ORDEN_VENTA_ID,
            PRODUCTO_ID,
            CANTIDAD,
            PRECIO_UNITARIO,
            SUBTOTAL,
            ESTADO
        FROM ORDEN_VENTA_DETALLE
        WHERE ORDEN_VENTA_ID = P_ORDEN_VENTA_ID
        AND ESTADO = 'A';

END SP_BUSCAR;


END PKG_ORDEN_VENTA_DETALLE;
/