CREATE OR REPLACE PACKAGE PKG_HISTORIAL_PROMOCION AS
  PROCEDURE SP_INSERTAR_HISTORIAL_PROMOCION(
    P_ORDEN_VENTA_ID IN HISTORIAL_PROMOCION.ORDEN_VENTA_ID%TYPE,
    P_PROMOCION_ID IN HISTORIAL_PROMOCION.PROMOCION_ID%TYPE,
    P_MONTO_DESCUENTO_SNAPSHOT IN HISTORIAL_PROMOCION.MONTO_DESCUENTO_SNAPSHOT%TYPE,
    P_HISTORIAL_PROMOCION_ID OUT HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_HISTORIAL_PROMOCION(
    P_HISTORIAL_PROMOCION_ID IN HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE,
    P_ORDEN_VENTA_ID IN HISTORIAL_PROMOCION.ORDEN_VENTA_ID%TYPE,
    P_PROMOCION_ID IN HISTORIAL_PROMOCION.PROMOCION_ID%TYPE,
    P_MONTO_DESCUENTO_SNAPSHOT IN HISTORIAL_PROMOCION.MONTO_DESCUENTO_SNAPSHOT%TYPE
  );

  PROCEDURE SP_ELIMINAR_HISTORIAL_PROMOCION(
    P_HISTORIAL_PROMOCION_ID IN HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_HISTORIAL_PROMOCION(
    P_HISTORIAL_PROMOCION_ID IN  HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_HISTORIAL_PROMOCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_HISTORIAL_PROMOCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_HISTORIAL_PROMOCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_PROMOCION AS

  PROCEDURE SP_INSERTAR_HISTORIAL_PROMOCION(
    P_ORDEN_VENTA_ID IN HISTORIAL_PROMOCION.ORDEN_VENTA_ID%TYPE,
    P_PROMOCION_ID IN HISTORIAL_PROMOCION.PROMOCION_ID%TYPE,
    P_MONTO_DESCUENTO_SNAPSHOT IN HISTORIAL_PROMOCION.MONTO_DESCUENTO_SNAPSHOT%TYPE,
    P_HISTORIAL_PROMOCION_ID OUT HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO HISTORIAL_PROMOCION (
      ORDEN_VENTA_ID,
      PROMOCION_ID,
      MONTO_DESCUENTO_SNAPSHOT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_ORDEN_VENTA_ID,
      P_PROMOCION_ID,
      P_MONTO_DESCUENTO_SNAPSHOT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING HISTORIAL_PROMOCION_ID INTO P_HISTORIAL_PROMOCION_ID;
  END SP_INSERTAR_HISTORIAL_PROMOCION;

  PROCEDURE SP_ACTUALIZAR_HISTORIAL_PROMOCION(
    P_HISTORIAL_PROMOCION_ID IN HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE,
    P_ORDEN_VENTA_ID IN HISTORIAL_PROMOCION.ORDEN_VENTA_ID%TYPE,
    P_PROMOCION_ID IN HISTORIAL_PROMOCION.PROMOCION_ID%TYPE,
    P_MONTO_DESCUENTO_SNAPSHOT IN HISTORIAL_PROMOCION.MONTO_DESCUENTO_SNAPSHOT%TYPE
  ) AS
  BEGIN
    UPDATE HISTORIAL_PROMOCION
    SET         ORDEN_VENTA_ID = P_ORDEN_VENTA_ID,
        PROMOCION_ID = P_PROMOCION_ID,
        MONTO_DESCUENTO_SNAPSHOT = P_MONTO_DESCUENTO_SNAPSHOT,
        UPDATED_AT = SYSTIMESTAMP
    WHERE HISTORIAL_PROMOCION_ID = P_HISTORIAL_PROMOCION_ID;
  END SP_ACTUALIZAR_HISTORIAL_PROMOCION;

  PROCEDURE SP_ELIMINAR_HISTORIAL_PROMOCION(
    P_HISTORIAL_PROMOCION_ID IN HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE
  ) AS
  BEGIN
    UPDATE HISTORIAL_PROMOCION
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE HISTORIAL_PROMOCION_ID = P_HISTORIAL_PROMOCION_ID;
  END SP_ELIMINAR_HISTORIAL_PROMOCION;

  PROCEDURE SP_OBTENER_HISTORIAL_PROMOCION(
    P_HISTORIAL_PROMOCION_ID IN  HISTORIAL_PROMOCION.HISTORIAL_PROMOCION_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              HISTORIAL_PROMOCION_ID,
             ORDEN_VENTA_ID,
             PROMOCION_ID,
             MONTO_DESCUENTO_SNAPSHOT,
             ESTADO
      FROM HISTORIAL_PROMOCION
      WHERE HISTORIAL_PROMOCION_ID = P_HISTORIAL_PROMOCION_ID;
  END SP_OBTENER_HISTORIAL_PROMOCION;

  PROCEDURE SP_LISTAR_HISTORIAL_PROMOCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              HISTORIAL_PROMOCION_ID,
             ORDEN_VENTA_ID,
             PROMOCION_ID,
             MONTO_DESCUENTO_SNAPSHOT,
             ESTADO
      FROM HISTORIAL_PROMOCION
      WHERE ESTADO = 'ACTIVO'
      ORDER BY HISTORIAL_PROMOCION_ID DESC;
  END SP_LISTAR_HISTORIAL_PROMOCION;

  PROCEDURE SP_BUSCAR_HISTORIAL_PROMOCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              HISTORIAL_PROMOCION_ID,
             ORDEN_VENTA_ID,
             PROMOCION_ID,
             MONTO_DESCUENTO_SNAPSHOT,
             ESTADO
      FROM HISTORIAL_PROMOCION
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'ORDEN_VENTA_ID' AND UPPER(CAST(ORDEN_VENTA_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'PROMOCION_ID' AND UPPER(CAST(PROMOCION_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY HISTORIAL_PROMOCION_ID DESC;
  END SP_BUSCAR_HISTORIAL_PROMOCION;

END PKG_HISTORIAL_PROMOCION;
/
