CREATE OR REPLACE PACKAGE PKG_PRODUCTO AS

  PROCEDURE SP_INSERTAR_PRODUCTO(
    P_REFERENCIA       IN  PRODUCTO.REFERENCIA%TYPE,
    P_NOMBRE           IN  PRODUCTO.NOMBRE%TYPE,
    P_DESCRIPCION      IN  PRODUCTO.DESCRIPCION%TYPE,
    P_TIPO             IN  PRODUCTO.TIPO%TYPE,
    P_MATERIAL         IN  PRODUCTO.MATERIAL%TYPE,
    P_ALTO_CM          IN  PRODUCTO.ALTO_CM%TYPE,
    P_ANCHO_CM         IN  PRODUCTO.ANCHO_CM%TYPE,
    P_PROFUNDIDAD_CM   IN  PRODUCTO.PROFUNDIDAD_CM%TYPE,
    P_COLOR            IN  PRODUCTO.COLOR%TYPE,
    P_PESO_GRAMOS      IN  PRODUCTO.PESO_GRAMOS%TYPE,
    P_IMAGEN_URL       IN  PRODUCTO.IMAGEN_URL%TYPE,
    P_UNIDAD_MEDIDA_ID IN  PRODUCTO.UNIDAD_MEDIDA_ID%TYPE,
    P_CATEGORIA_ID     IN  PRODUCTO.CATEGORIA_ID%TYPE,
    P_LOTE_PRODUCTO    IN  PRODUCTO.LOTE_PRODUCTO%TYPE,
    P_PRODUCTO_ID      OUT PRODUCTO.PRODUCTO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PRODUCTO(
    P_PRODUCTO_ID      IN  PRODUCTO.PRODUCTO_ID%TYPE,
    P_REFERENCIA       IN  PRODUCTO.REFERENCIA%TYPE,
    P_NOMBRE           IN  PRODUCTO.NOMBRE%TYPE,
    P_DESCRIPCION      IN  PRODUCTO.DESCRIPCION%TYPE,
    P_TIPO             IN  PRODUCTO.TIPO%TYPE,
    P_MATERIAL         IN  PRODUCTO.MATERIAL%TYPE,
    P_ALTO_CM          IN  PRODUCTO.ALTO_CM%TYPE,
    P_ANCHO_CM         IN  PRODUCTO.ANCHO_CM%TYPE,
    P_PROFUNDIDAD_CM   IN  PRODUCTO.PROFUNDIDAD_CM%TYPE,
    P_COLOR            IN  PRODUCTO.COLOR%TYPE,
    P_PESO_GRAMOS      IN  PRODUCTO.PESO_GRAMOS%TYPE,
    P_IMAGEN_URL       IN  PRODUCTO.IMAGEN_URL%TYPE,
    P_UNIDAD_MEDIDA_ID IN  PRODUCTO.UNIDAD_MEDIDA_ID%TYPE,
    P_CATEGORIA_ID     IN  PRODUCTO.CATEGORIA_ID%TYPE,
    P_LOTE_PRODUCTO    IN  PRODUCTO.LOTE_PRODUCTO%TYPE
  );

  PROCEDURE SP_ELIMINAR_PRODUCTO(
    P_PRODUCTO_ID IN PRODUCTO.PRODUCTO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PRODUCTO(
    P_PRODUCTO_ID IN  PRODUCTO.PRODUCTO_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PRODUCTOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PRODUCTOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PRODUCTO;
/

CREATE OR REPLACE PACKAGE BODY PKG_PRODUCTO AS

  PROCEDURE SP_INSERTAR_PRODUCTO(
    P_REFERENCIA       IN  PRODUCTO.REFERENCIA%TYPE,
    P_NOMBRE           IN  PRODUCTO.NOMBRE%TYPE,
    P_DESCRIPCION      IN  PRODUCTO.DESCRIPCION%TYPE,
    P_TIPO             IN  PRODUCTO.TIPO%TYPE,
    P_MATERIAL         IN  PRODUCTO.MATERIAL%TYPE,
    P_ALTO_CM          IN  PRODUCTO.ALTO_CM%TYPE,
    P_ANCHO_CM         IN  PRODUCTO.ANCHO_CM%TYPE,
    P_PROFUNDIDAD_CM   IN  PRODUCTO.PROFUNDIDAD_CM%TYPE,
    P_COLOR            IN  PRODUCTO.COLOR%TYPE,
    P_PESO_GRAMOS      IN  PRODUCTO.PESO_GRAMOS%TYPE,
    P_IMAGEN_URL       IN  PRODUCTO.IMAGEN_URL%TYPE,
    P_UNIDAD_MEDIDA_ID IN  PRODUCTO.UNIDAD_MEDIDA_ID%TYPE,
    P_CATEGORIA_ID     IN  PRODUCTO.CATEGORIA_ID%TYPE,
    P_LOTE_PRODUCTO    IN  PRODUCTO.LOTE_PRODUCTO%TYPE,
    P_PRODUCTO_ID      OUT PRODUCTO.PRODUCTO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PRODUCTO (
      REFERENCIA,
      NOMBRE,
      DESCRIPCION,
      TIPO,
      MATERIAL,
      ALTO_CM,
      ANCHO_CM,
      PROFUNDIDAD_CM,
      COLOR,
      PESO_GRAMOS,
      IMAGEN_URL,
      UNIDAD_MEDIDA_ID,
      CATEGORIA_ID,
      LOTE_PRODUCTO,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_REFERENCIA,
      P_NOMBRE,
      P_DESCRIPCION,
      P_TIPO,
      P_MATERIAL,
      P_ALTO_CM,
      P_ANCHO_CM,
      P_PROFUNDIDAD_CM,
      P_COLOR,
      P_PESO_GRAMOS,
      P_IMAGEN_URL,
      P_UNIDAD_MEDIDA_ID,
      P_CATEGORIA_ID,
      P_LOTE_PRODUCTO,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING PRODUCTO_ID INTO P_PRODUCTO_ID;
  END SP_INSERTAR_PRODUCTO;

  PROCEDURE SP_ACTUALIZAR_PRODUCTO(
    P_PRODUCTO_ID      IN  PRODUCTO.PRODUCTO_ID%TYPE,
    P_REFERENCIA       IN  PRODUCTO.REFERENCIA%TYPE,
    P_NOMBRE           IN  PRODUCTO.NOMBRE%TYPE,
    P_DESCRIPCION      IN  PRODUCTO.DESCRIPCION%TYPE,
    P_TIPO             IN  PRODUCTO.TIPO%TYPE,
    P_MATERIAL         IN  PRODUCTO.MATERIAL%TYPE,
    P_ALTO_CM          IN  PRODUCTO.ALTO_CM%TYPE,
    P_ANCHO_CM         IN  PRODUCTO.ANCHO_CM%TYPE,
    P_PROFUNDIDAD_CM   IN  PRODUCTO.PROFUNDIDAD_CM%TYPE,
    P_COLOR            IN  PRODUCTO.COLOR%TYPE,
    P_PESO_GRAMOS      IN  PRODUCTO.PESO_GRAMOS%TYPE,
    P_IMAGEN_URL       IN  PRODUCTO.IMAGEN_URL%TYPE,
    P_UNIDAD_MEDIDA_ID IN  PRODUCTO.UNIDAD_MEDIDA_ID%TYPE,
    P_CATEGORIA_ID     IN  PRODUCTO.CATEGORIA_ID%TYPE,
    P_LOTE_PRODUCTO    IN  PRODUCTO.LOTE_PRODUCTO%TYPE
  ) AS
  BEGIN
    UPDATE PRODUCTO
    SET REFERENCIA       = P_REFERENCIA,
        NOMBRE           = P_NOMBRE,
        DESCRIPCION      = P_DESCRIPCION,
        TIPO             = P_TIPO,
        MATERIAL         = P_MATERIAL,
        ALTO_CM          = P_ALTO_CM,
        ANCHO_CM         = P_ANCHO_CM,
        PROFUNDIDAD_CM   = P_PROFUNDIDAD_CM,
        COLOR            = P_COLOR,
        PESO_GRAMOS      = P_PESO_GRAMOS,
        IMAGEN_URL       = P_IMAGEN_URL,
        UNIDAD_MEDIDA_ID = P_UNIDAD_MEDIDA_ID,
        CATEGORIA_ID     = P_CATEGORIA_ID,
        LOTE_PRODUCTO    = P_LOTE_PRODUCTO,
        UPDATED_AT       = SYSTIMESTAMP
    WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  END SP_ACTUALIZAR_PRODUCTO;

  PROCEDURE SP_ELIMINAR_PRODUCTO(
    P_PRODUCTO_ID IN PRODUCTO.PRODUCTO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM ORDEN_VENTA_DETALLE
    WHERE PRODUCTO_ID = P_PRODUCTO_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el producto porque tiene ordenes de venta asociadas.');
    END IF;

    UPDATE PRODUCTO
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  END SP_ELIMINAR_PRODUCTO;

  PROCEDURE SP_OBTENER_PRODUCTO(
    P_PRODUCTO_ID IN  PRODUCTO.PRODUCTO_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PRODUCTO_ID,
             REFERENCIA,
             NOMBRE,
             DESCRIPCION,
             TIPO,
             MATERIAL,
             ALTO_CM,
             ANCHO_CM,
             PROFUNDIDAD_CM,
             COLOR,
             PESO_GRAMOS,
             IMAGEN_URL,
             UNIDAD_MEDIDA_ID,
             CATEGORIA_ID,
             LOTE_PRODUCTO,
             ESTADO
      FROM PRODUCTO
      WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  END SP_OBTENER_PRODUCTO;

  PROCEDURE SP_LISTAR_PRODUCTOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PRODUCTO_ID,
             REFERENCIA,
             NOMBRE,
             TIPO,
             CATEGORIA_ID,
             ESTADO
      FROM PRODUCTO
      WHERE ESTADO = 'ACTIVO'
      ORDER BY NOMBRE;
  END SP_LISTAR_PRODUCTOS;

  PROCEDURE SP_BUSCAR_PRODUCTOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PRODUCTO_ID,
             REFERENCIA,
             NOMBRE,
             TIPO,
             CATEGORIA_ID,
             ESTADO
      FROM PRODUCTO
      WHERE ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'NOMBRE'     AND UPPER(NOMBRE)     LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'REFERENCIA' AND UPPER(REFERENCIA) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'TIPO'       AND UPPER(TIPO)       LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY NOMBRE;
  END SP_BUSCAR_PRODUCTOS;

END PKG_PRODUCTO;
/

