CREATE OR REPLACE PACKAGE PKG_INVENTARIO_PRODUCTO AS

  PROCEDURE SP_INSERTAR_INVENTARIO_PRODUCTO(
    P_PRODUCTO_ID      IN  INVENTARIO_PRODUCTO.PRODUCTO_ID%TYPE,
    P_STOCK            IN  INVENTARIO_PRODUCTO.STOCK%TYPE,
    P_STOCK_RESERVADO  IN  INVENTARIO_PRODUCTO.STOCK_RESERVADO%TYPE,
    P_STOCK_MINIMO     IN  INVENTARIO_PRODUCTO.STOCK_MINIMO%TYPE,
    P_INV_PROD_ID      OUT INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_INVENTARIO_PRODUCTO(
    P_INV_PROD_ID      IN  INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE,
    P_PRODUCTO_ID      IN  INVENTARIO_PRODUCTO.PRODUCTO_ID%TYPE,
    P_STOCK            IN  INVENTARIO_PRODUCTO.STOCK%TYPE,
    P_STOCK_RESERVADO  IN  INVENTARIO_PRODUCTO.STOCK_RESERVADO%TYPE,
    P_STOCK_MINIMO     IN  INVENTARIO_PRODUCTO.STOCK_MINIMO%TYPE
  );

  PROCEDURE SP_ELIMINAR_INVENTARIO_PRODUCTO(
    P_INV_PROD_ID IN INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE
  );

  PROCEDURE SP_OBTENER_INVENTARIO_PRODUCTO(
    P_INV_PROD_ID IN  INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_INVENTARIO_PRODUCTO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_INVENTARIO_PRODUCTO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_INVENTARIO_PRODUCTO;
/

CREATE OR REPLACE PACKAGE BODY PKG_INVENTARIO_PRODUCTO AS

  PROCEDURE SP_INSERTAR_INVENTARIO_PRODUCTO(
    P_PRODUCTO_ID      IN  INVENTARIO_PRODUCTO.PRODUCTO_ID%TYPE,
    P_STOCK            IN  INVENTARIO_PRODUCTO.STOCK%TYPE,
    P_STOCK_RESERVADO  IN  INVENTARIO_PRODUCTO.STOCK_RESERVADO%TYPE,
    P_STOCK_MINIMO     IN  INVENTARIO_PRODUCTO.STOCK_MINIMO%TYPE,
    P_INV_PROD_ID      OUT INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO INVENTARIO_PRODUCTO (
      PRODUCTO_ID,
      STOCK,
      STOCK_RESERVADO,
      STOCK_MINIMO,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_PRODUCTO_ID,
      P_STOCK,
      P_STOCK_RESERVADO,
      P_STOCK_MINIMO,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING INV_PROD_ID INTO P_INV_PROD_ID;
  END SP_INSERTAR_INVENTARIO_PRODUCTO;

  PROCEDURE SP_ACTUALIZAR_INVENTARIO_PRODUCTO(
    P_INV_PROD_ID      IN  INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE,
    P_PRODUCTO_ID      IN  INVENTARIO_PRODUCTO.PRODUCTO_ID%TYPE,
    P_STOCK            IN  INVENTARIO_PRODUCTO.STOCK%TYPE,
    P_STOCK_RESERVADO  IN  INVENTARIO_PRODUCTO.STOCK_RESERVADO%TYPE,
    P_STOCK_MINIMO     IN  INVENTARIO_PRODUCTO.STOCK_MINIMO%TYPE
  ) AS
  BEGIN
    UPDATE INVENTARIO_PRODUCTO
    SET PRODUCTO_ID     = P_PRODUCTO_ID,
        STOCK           = P_STOCK,
        STOCK_RESERVADO = P_STOCK_RESERVADO,
        STOCK_MINIMO    = P_STOCK_MINIMO,
        UPDATED_AT      = SYSTIMESTAMP
    WHERE INV_PROD_ID = P_INV_PROD_ID;
  END SP_ACTUALIZAR_INVENTARIO_PRODUCTO;

  PROCEDURE SP_ELIMINAR_INVENTARIO_PRODUCTO(
    P_INV_PROD_ID IN INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM MOVIMIENTO_INVENTARIO
    WHERE INV_PROD_ID = P_INV_PROD_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el inventario porque tiene movimientos registrados.');
    END IF;

    UPDATE INVENTARIO_PRODUCTO
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE INV_PROD_ID = P_INV_PROD_ID;
  END SP_ELIMINAR_INVENTARIO_PRODUCTO;

  PROCEDURE SP_OBTENER_INVENTARIO_PRODUCTO(
    P_INV_PROD_ID IN  INVENTARIO_PRODUCTO.INV_PROD_ID%TYPE,
    P_CURSOR      OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT INV_PROD_ID,
             PRODUCTO_ID,
             STOCK,
             STOCK_RESERVADO,
             STOCK_MINIMO,
             ESTADO
      FROM INVENTARIO_PRODUCTO
      WHERE INV_PROD_ID = P_INV_PROD_ID;
  END SP_OBTENER_INVENTARIO_PRODUCTO;

  PROCEDURE SP_LISTAR_INVENTARIO_PRODUCTO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT IP.INV_PROD_ID,
             IP.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             IP.STOCK,
             IP.STOCK_RESERVADO,
             IP.STOCK_MINIMO,
             IP.ESTADO
      FROM INVENTARIO_PRODUCTO IP
      JOIN PRODUCTO P ON P.PRODUCTO_ID = IP.PRODUCTO_ID
      WHERE IP.ESTADO = 'ACTIVO'
      ORDER BY P.NOMBRE;
  END SP_LISTAR_INVENTARIO_PRODUCTO;

  PROCEDURE SP_BUSCAR_INVENTARIO_PRODUCTO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT IP.INV_PROD_ID,
             IP.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             IP.STOCK,
             IP.STOCK_RESERVADO,
             IP.STOCK_MINIMO,
             IP.ESTADO
      FROM INVENTARIO_PRODUCTO IP
      JOIN PRODUCTO P ON P.PRODUCTO_ID = IP.PRODUCTO_ID
      WHERE IP.ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'PRODUCTO' AND UPPER(P.NOMBRE)     LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'STOCK'    AND TO_CHAR(IP.STOCK)   LIKE '%' || P_VALOR || '%')
      )
      ORDER BY P.NOMBRE;
  END SP_BUSCAR_INVENTARIO_PRODUCTO;

END PKG_INVENTARIO_PRODUCTO;
/
