/* ============================================
   PACKAGE SPEC
   ============================================ */

CREATE OR REPLACE PACKAGE PKG_DEPARTAMENTO AS

  PROCEDURE SP_INSERTAR_DEPARTAMENTO(
    P_NOMBRE       IN DEPARTAMENTO.NOMBRE%TYPE,
    P_DESCRIPCION  IN DEPARTAMENTO.DESCRIPCION%TYPE,
    P_DEPTO_ID     OUT DEPARTAMENTO.DEPTO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_DEPARTAMENTO(
    P_DEPTO_ID     IN DEPARTAMENTO.DEPTO_ID%TYPE,
    P_NOMBRE       IN DEPARTAMENTO.NOMBRE%TYPE,
    P_DESCRIPCION  IN DEPARTAMENTO.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_DEPARTAMENTO(
    P_DEPTO_ID IN DEPARTAMENTO.DEPTO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_DEPARTAMENTO(
    P_DEPTO_ID IN DEPARTAMENTO.DEPTO_ID%TYPE,
    P_CURSOR   OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_DEPARTAMENTOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_DEPARTAMENTO;
/

/* ============================================
   PACKAGE BODY
   ============================================ */

CREATE OR REPLACE PACKAGE BODY PKG_DEPARTAMENTO AS

  PROCEDURE SP_INSERTAR_DEPARTAMENTO(
    P_NOMBRE       IN DEPARTAMENTO.NOMBRE%TYPE,
    P_DESCRIPCION  IN DEPARTAMENTO.DESCRIPCION%TYPE,
    P_DEPTO_ID     OUT DEPARTAMENTO.DEPTO_ID%TYPE
  ) AS
  BEGIN

    INSERT INTO DEPARTAMENTO(
      NOMBRE,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    )
    VALUES(
      P_NOMBRE,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING DEPTO_ID INTO P_DEPTO_ID;

  END SP_INSERTAR_DEPARTAMENTO;


  PROCEDURE SP_ACTUALIZAR_DEPARTAMENTO(
    P_DEPTO_ID     IN DEPARTAMENTO.DEPTO_ID%TYPE,
    P_NOMBRE       IN DEPARTAMENTO.NOMBRE%TYPE,
    P_DESCRIPCION  IN DEPARTAMENTO.DESCRIPCION%TYPE
  ) AS
  BEGIN

    UPDATE DEPARTAMENTO
       SET NOMBRE = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT = SYSTIMESTAMP
     WHERE DEPTO_ID = P_DEPTO_ID;

  END SP_ACTUALIZAR_DEPARTAMENTO;


  PROCEDURE SP_ELIMINAR_DEPARTAMENTO(
    P_DEPTO_ID IN DEPARTAMENTO.DEPTO_ID%TYPE
  ) AS
  BEGIN

    UPDATE DEPARTAMENTO
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE DEPTO_ID = P_DEPTO_ID;

  END SP_ELIMINAR_DEPARTAMENTO;


  PROCEDURE SP_OBTENER_DEPARTAMENTO(
    P_DEPTO_ID IN DEPARTAMENTO.DEPTO_ID%TYPE,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT DEPTO_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM DEPARTAMENTO
       WHERE DEPTO_ID = P_DEPTO_ID;

  END SP_OBTENER_DEPARTAMENTO;


  PROCEDURE SP_LISTAR_DEPARTAMENTOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
      SELECT DEPTO_ID,
             NOMBRE,
             DESCRIPCION,
             ESTADO
        FROM DEPARTAMENTO
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;

  END SP_LISTAR_DEPARTAMENTOS;

END PKG_DEPARTAMENTO;
/