CREATE OR REPLACE PACKAGE PKG_LISTA_MATERIALES AS

  PROCEDURE SP_INSERTAR_LISTA_MATERIALES(
    P_CODIGO_LISTA      IN LISTA_MATERIALES.CODIGO_LISTA%TYPE,
    P_PRODUCTO_ID       IN LISTA_MATERIALES.PRODUCTO_ID%TYPE,
    P_VERSION           IN LISTA_MATERIALES.VERSION%TYPE,
    P_FECHA_VIGENCIA    IN LISTA_MATERIALES.FECHA_VIGENCIA%TYPE,
    P_ESTADO            IN LISTA_MATERIALES.ESTADO%TYPE,
    P_OBSERVACIONES     IN LISTA_MATERIALES.OBSERVACIONES%TYPE,
    P_LM_ID             OUT LISTA_MATERIALES.LM_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_LISTA_MATERIALES(
    P_LM_ID             IN LISTA_MATERIALES.LM_ID%TYPE,
    P_CODIGO_LISTA      IN LISTA_MATERIALES.CODIGO_LISTA%TYPE,
    P_PRODUCTO_ID       IN LISTA_MATERIALES.PRODUCTO_ID%TYPE,
    P_VERSION           IN LISTA_MATERIALES.VERSION%TYPE,
    P_FECHA_VIGENCIA    IN LISTA_MATERIALES.FECHA_VIGENCIA%TYPE,
    P_ESTADO            IN LISTA_MATERIALES.ESTADO%TYPE,
    P_OBSERVACIONES     IN LISTA_MATERIALES.OBSERVACIONES%TYPE
  );

  PROCEDURE SP_ELIMINAR_LISTA_MATERIALES(
    P_LM_ID IN LISTA_MATERIALES.LM_ID%TYPE
  );

  PROCEDURE SP_OBTENER_LISTA_MATERIALES(
    P_LM_ID   IN LISTA_MATERIALES.LM_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_LISTAS_MATERIALES(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_LISTAS_MATERIALES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_LISTA_MATERIALES;
/

CREATE OR REPLACE PACKAGE BODY PKG_LISTA_MATERIALES AS

  PROCEDURE SP_INSERTAR_LISTA_MATERIALES(
    P_CODIGO_LISTA      IN LISTA_MATERIALES.CODIGO_LISTA%TYPE,
    P_PRODUCTO_ID       IN LISTA_MATERIALES.PRODUCTO_ID%TYPE,
    P_VERSION           IN LISTA_MATERIALES.VERSION%TYPE,
    P_FECHA_VIGENCIA    IN LISTA_MATERIALES.FECHA_VIGENCIA%TYPE,
    P_ESTADO            IN LISTA_MATERIALES.ESTADO%TYPE,
    P_OBSERVACIONES     IN LISTA_MATERIALES.OBSERVACIONES%TYPE,
    P_LM_ID             OUT LISTA_MATERIALES.LM_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO LISTA_MATERIALES (
      CODIGO_LISTA,
      PRODUCTO_ID,
      VERSION,
      FECHA_VIGENCIA,
      ESTADO,
      OBSERVACIONES,
      CREATED_AT
    )
    VALUES (
      P_CODIGO_LISTA,
      P_PRODUCTO_ID,
      P_VERSION,
      P_FECHA_VIGENCIA,
      P_ESTADO,
      P_OBSERVACIONES,
      SYSTIMESTAMP
    )
    RETURNING LM_ID INTO P_LM_ID;
  END SP_INSERTAR_LISTA_MATERIALES;


  PROCEDURE SP_ACTUALIZAR_LISTA_MATERIALES(
    P_LM_ID             IN LISTA_MATERIALES.LM_ID%TYPE,
    P_CODIGO_LISTA      IN LISTA_MATERIALES.CODIGO_LISTA%TYPE,
    P_PRODUCTO_ID       IN LISTA_MATERIALES.PRODUCTO_ID%TYPE,
    P_VERSION           IN LISTA_MATERIALES.VERSION%TYPE,
    P_FECHA_VIGENCIA    IN LISTA_MATERIALES.FECHA_VIGENCIA%TYPE,
    P_ESTADO            IN LISTA_MATERIALES.ESTADO%TYPE,
    P_OBSERVACIONES     IN LISTA_MATERIALES.OBSERVACIONES%TYPE
  ) AS
  BEGIN
    UPDATE LISTA_MATERIALES
       SET CODIGO_LISTA   = P_CODIGO_LISTA,
           PRODUCTO_ID    = P_PRODUCTO_ID,
           VERSION        = P_VERSION,
           FECHA_VIGENCIA = P_FECHA_VIGENCIA,
           ESTADO         = P_ESTADO,
           OBSERVACIONES  = P_OBSERVACIONES,
           UPDATED_AT     = SYSTIMESTAMP
     WHERE LM_ID = P_LM_ID;
  END SP_ACTUALIZAR_LISTA_MATERIALES;


  PROCEDURE SP_ELIMINAR_LISTA_MATERIALES(
    P_LM_ID IN LISTA_MATERIALES.LM_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM LISTA_MATERIALES_DETALLE
     WHERE LM_ID = P_LM_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la lista de materiales porque tiene detalles asociados.');
    END IF;

    DELETE FROM LISTA_MATERIALES
     WHERE LM_ID = P_LM_ID;
  END SP_ELIMINAR_LISTA_MATERIALES;


  PROCEDURE SP_OBTENER_LISTA_MATERIALES(
    P_LM_ID   IN LISTA_MATERIALES.LM_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT LM_ID,
             CODIGO_LISTA,
             PRODUCTO_ID,
             VERSION,
             FECHA_VIGENCIA,
             ESTADO,
             OBSERVACIONES
        FROM LISTA_MATERIALES
       WHERE LM_ID = P_LM_ID;
  END SP_OBTENER_LISTA_MATERIALES;


  PROCEDURE SP_LISTAR_LISTAS_MATERIALES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT LM_ID,
             CODIGO_LISTA,
             PRODUCTO_ID,
             VERSION,
             FECHA_VIGENCIA,
             ESTADO,
             OBSERVACIONES
        FROM LISTA_MATERIALES
       ORDER BY LM_ID DESC;
  END SP_LISTAR_LISTAS_MATERIALES;


  PROCEDURE SP_BUSCAR_LISTAS_MATERIALES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT LM_ID,
             CODIGO_LISTA,
             PRODUCTO_ID,
             VERSION,
             FECHA_VIGENCIA,
             ESTADO,
             OBSERVACIONES
        FROM LISTA_MATERIALES
       WHERE (
             (UPPER(P_CRITERIO) = 'CODIGO' AND UPPER(CODIGO_LISTA) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'PRODUCTO_ID' AND TO_CHAR(PRODUCTO_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'VERSION' AND TO_CHAR(VERSION) LIKE '%' || P_VALOR || '%')
       )
       ORDER BY LM_ID DESC;
  END SP_BUSCAR_LISTAS_MATERIALES;

END PKG_LISTA_MATERIALES;
/