CREATE OR REPLACE PACKAGE PKG_MOVIMIENTO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_MOVIMIENTO_MATERIA_PRIMA(
    P_INV_MP_ID          IN MOVIMIENTO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_TIPO_MOVIMIENTO    IN MOVIMIENTO_MATERIA_PRIMA.TIPO_MOVIMIENTO%TYPE,
    P_CANTIDAD           IN MOVIMIENTO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_FECHA_MOVIMIENTO   IN MOVIMIENTO_MATERIA_PRIMA.FECHA_MOVIMIENTO%TYPE,
    P_OBSERVACIONES      IN MOVIMIENTO_MATERIA_PRIMA.OBSERVACIONES%TYPE,
    P_USUARIO_REGISTRO   IN MOVIMIENTO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE,
    P_MOV_MP_ID          OUT MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_MOVIMIENTO_MATERIA_PRIMA(
    P_MOV_MP_ID          IN MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE,
    P_INV_MP_ID          IN MOVIMIENTO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_TIPO_MOVIMIENTO    IN MOVIMIENTO_MATERIA_PRIMA.TIPO_MOVIMIENTO%TYPE,
    P_CANTIDAD           IN MOVIMIENTO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_FECHA_MOVIMIENTO   IN MOVIMIENTO_MATERIA_PRIMA.FECHA_MOVIMIENTO%TYPE,
    P_OBSERVACIONES      IN MOVIMIENTO_MATERIA_PRIMA.OBSERVACIONES%TYPE,
    P_USUARIO_REGISTRO   IN MOVIMIENTO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE
  );

  PROCEDURE SP_ELIMINAR_MOVIMIENTO_MATERIA_PRIMA(
    P_MOV_MP_ID IN MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE
  );

  PROCEDURE SP_OBTENER_MOVIMIENTO_MATERIA_PRIMA(
    P_MOV_MP_ID IN MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE,
    P_CURSOR    OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_MOVIMIENTOS_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_MOVIMIENTOS_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_MOVIMIENTO_MATERIA_PRIMA;
/

CREATE OR REPLACE PACKAGE BODY PKG_MOVIMIENTO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_MOVIMIENTO_MATERIA_PRIMA(
    P_INV_MP_ID          IN MOVIMIENTO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_TIPO_MOVIMIENTO    IN MOVIMIENTO_MATERIA_PRIMA.TIPO_MOVIMIENTO%TYPE,
    P_CANTIDAD           IN MOVIMIENTO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_FECHA_MOVIMIENTO   IN MOVIMIENTO_MATERIA_PRIMA.FECHA_MOVIMIENTO%TYPE,
    P_OBSERVACIONES      IN MOVIMIENTO_MATERIA_PRIMA.OBSERVACIONES%TYPE,
    P_USUARIO_REGISTRO   IN MOVIMIENTO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE,
    P_MOV_MP_ID          OUT MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO MOVIMIENTO_MATERIA_PRIMA (
      INV_MP_ID,
      TIPO_MOVIMIENTO,
      CANTIDAD,
      FECHA_MOVIMIENTO,
      OBSERVACIONES,
      USUARIO_REGISTRO,
      CREATED_AT
    )
    VALUES (
      P_INV_MP_ID,
      P_TIPO_MOVIMIENTO,
      P_CANTIDAD,
      P_FECHA_MOVIMIENTO,
      P_OBSERVACIONES,
      P_USUARIO_REGISTRO,
      SYSTIMESTAMP
    )
    RETURNING MOV_MP_ID INTO P_MOV_MP_ID;
  END SP_INSERTAR_MOVIMIENTO_MATERIA_PRIMA;


  PROCEDURE SP_ACTUALIZAR_MOVIMIENTO_MATERIA_PRIMA(
    P_MOV_MP_ID          IN MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE,
    P_INV_MP_ID          IN MOVIMIENTO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_TIPO_MOVIMIENTO    IN MOVIMIENTO_MATERIA_PRIMA.TIPO_MOVIMIENTO%TYPE,
    P_CANTIDAD           IN MOVIMIENTO_MATERIA_PRIMA.CANTIDAD%TYPE,
    P_FECHA_MOVIMIENTO   IN MOVIMIENTO_MATERIA_PRIMA.FECHA_MOVIMIENTO%TYPE,
    P_OBSERVACIONES      IN MOVIMIENTO_MATERIA_PRIMA.OBSERVACIONES%TYPE,
    P_USUARIO_REGISTRO   IN MOVIMIENTO_MATERIA_PRIMA.USUARIO_REGISTRO%TYPE
  ) AS
  BEGIN
    UPDATE MOVIMIENTO_MATERIA_PRIMA
       SET INV_MP_ID        = P_INV_MP_ID,
           TIPO_MOVIMIENTO  = P_TIPO_MOVIMIENTO,
           CANTIDAD         = P_CANTIDAD,
           FECHA_MOVIMIENTO = P_FECHA_MOVIMIENTO,
           OBSERVACIONES    = P_OBSERVACIONES,
           USUARIO_REGISTRO = P_USUARIO_REGISTRO,
           UPDATED_AT       = SYSTIMESTAMP
     WHERE MOV_MP_ID = P_MOV_MP_ID;
  END SP_ACTUALIZAR_MOVIMIENTO_MATERIA_PRIMA;


  PROCEDURE SP_ELIMINAR_MOVIMIENTO_MATERIA_PRIMA(
    P_MOV_MP_ID IN MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM MOVIMIENTO_MATERIA_PRIMA
     WHERE MOV_MP_ID = P_MOV_MP_ID;
  END SP_ELIMINAR_MOVIMIENTO_MATERIA_PRIMA;


  PROCEDURE SP_OBTENER_MOVIMIENTO_MATERIA_PRIMA(
    P_MOV_MP_ID IN MOVIMIENTO_MATERIA_PRIMA.MOV_MP_ID%TYPE,
    P_CURSOR    OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MOV_MP_ID,
             INV_MP_ID,
             TIPO_MOVIMIENTO,
             CANTIDAD,
             FECHA_MOVIMIENTO,
             OBSERVACIONES,
             USUARIO_REGISTRO
        FROM MOVIMIENTO_MATERIA_PRIMA
       WHERE MOV_MP_ID = P_MOV_MP_ID;
  END SP_OBTENER_MOVIMIENTO_MATERIA_PRIMA;


  PROCEDURE SP_LISTAR_MOVIMIENTOS_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MOV_MP_ID,
             INV_MP_ID,
             TIPO_MOVIMIENTO,
             CANTIDAD,
             FECHA_MOVIMIENTO,
             OBSERVACIONES,
             USUARIO_REGISTRO
        FROM MOVIMIENTO_MATERIA_PRIMA
       ORDER BY FECHA_MOVIMIENTO DESC, MOV_MP_ID DESC;
  END SP_LISTAR_MOVIMIENTOS_MATERIA_PRIMA;


  PROCEDURE SP_BUSCAR_MOVIMIENTOS_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT MOV_MP_ID,
             INV_MP_ID,
             TIPO_MOVIMIENTO,
             CANTIDAD,
             FECHA_MOVIMIENTO,
             OBSERVACIONES,
             USUARIO_REGISTRO
        FROM MOVIMIENTO_MATERIA_PRIMA
       WHERE (
             (UPPER(P_CRITERIO) = 'TIPO' AND UPPER(TIPO_MOVIMIENTO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'USUARIO' AND UPPER(USUARIO_REGISTRO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'INV_MP_ID' AND TO_CHAR(INV_MP_ID) LIKE '%' || P_VALOR || '%')
       )
       ORDER BY FECHA_MOVIMIENTO DESC, MOV_MP_ID DESC;
  END SP_BUSCAR_MOVIMIENTOS_MATERIA_PRIMA;

END PKG_MOVIMIENTO_MATERIA_PRIMA;
/