CREATE OR REPLACE PACKAGE PKG_RESENA_COMENTARIO AS
  PROCEDURE SP_INSERTAR_RESENA_COMENTARIO(
    P_CLI_ID IN RESENA_COMENTARIO.CLI_ID%TYPE,
    P_PRODUCTO_ID IN RESENA_COMENTARIO.PRODUCTO_ID%TYPE,
    P_CALIFICACION IN RESENA_COMENTARIO.CALIFICACION%TYPE,
    P_COMENTARIO IN RESENA_COMENTARIO.COMENTARIO%TYPE,
    P_RESENA_AT IN RESENA_COMENTARIO.RESENA_AT%TYPE,
    P_RESENA_ID OUT RESENA_COMENTARIO.RESENA_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_RESENA_COMENTARIO(
    P_RESENA_ID IN RESENA_COMENTARIO.RESENA_ID%TYPE,
    P_CLI_ID IN RESENA_COMENTARIO.CLI_ID%TYPE,
    P_PRODUCTO_ID IN RESENA_COMENTARIO.PRODUCTO_ID%TYPE,
    P_CALIFICACION IN RESENA_COMENTARIO.CALIFICACION%TYPE,
    P_COMENTARIO IN RESENA_COMENTARIO.COMENTARIO%TYPE,
    P_RESENA_AT IN RESENA_COMENTARIO.RESENA_AT%TYPE
  );

  PROCEDURE SP_ELIMINAR_RESENA_COMENTARIO(
    P_RESENA_ID IN RESENA_COMENTARIO.RESENA_ID%TYPE
  );

  PROCEDURE SP_OBTENER_RESENA_COMENTARIO(
    P_RESENA_ID IN  RESENA_COMENTARIO.RESENA_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_RESENA_COMENTARIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_RESENA_COMENTARIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_RESENA_COMENTARIO;
/


CREATE OR REPLACE PACKAGE BODY PKG_RESENA_COMENTARIO AS

  PROCEDURE SP_INSERTAR_RESENA_COMENTARIO(
    P_CLI_ID IN RESENA_COMENTARIO.CLI_ID%TYPE,
    P_PRODUCTO_ID IN RESENA_COMENTARIO.PRODUCTO_ID%TYPE,
    P_CALIFICACION IN RESENA_COMENTARIO.CALIFICACION%TYPE,
    P_COMENTARIO IN RESENA_COMENTARIO.COMENTARIO%TYPE,
    P_RESENA_AT IN RESENA_COMENTARIO.RESENA_AT%TYPE,
    P_RESENA_ID OUT RESENA_COMENTARIO.RESENA_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO RESENA_COMENTARIO (
      CLI_ID,
      PRODUCTO_ID,
      CALIFICACION,
      COMENTARIO,
      RESENA_AT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CLI_ID,
      P_PRODUCTO_ID,
      P_CALIFICACION,
      P_COMENTARIO,
      P_RESENA_AT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING RESENA_ID INTO P_RESENA_ID;
  END SP_INSERTAR_RESENA_COMENTARIO;

  PROCEDURE SP_ACTUALIZAR_RESENA_COMENTARIO(
    P_RESENA_ID IN RESENA_COMENTARIO.RESENA_ID%TYPE,
    P_CLI_ID IN RESENA_COMENTARIO.CLI_ID%TYPE,
    P_PRODUCTO_ID IN RESENA_COMENTARIO.PRODUCTO_ID%TYPE,
    P_CALIFICACION IN RESENA_COMENTARIO.CALIFICACION%TYPE,
    P_COMENTARIO IN RESENA_COMENTARIO.COMENTARIO%TYPE,
    P_RESENA_AT IN RESENA_COMENTARIO.RESENA_AT%TYPE
  ) AS
  BEGIN
    UPDATE RESENA_COMENTARIO
    SET         CLI_ID = P_CLI_ID,
        PRODUCTO_ID = P_PRODUCTO_ID,
        CALIFICACION = P_CALIFICACION,
        COMENTARIO = P_COMENTARIO,
        RESENA_AT = P_RESENA_AT,
        UPDATED_AT = SYSTIMESTAMP
    WHERE RESENA_ID = P_RESENA_ID;
  END SP_ACTUALIZAR_RESENA_COMENTARIO;

  PROCEDURE SP_ELIMINAR_RESENA_COMENTARIO(
    P_RESENA_ID IN RESENA_COMENTARIO.RESENA_ID%TYPE
  ) AS
  BEGIN
    UPDATE RESENA_COMENTARIO
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE RESENA_ID = P_RESENA_ID;
  END SP_ELIMINAR_RESENA_COMENTARIO;

  PROCEDURE SP_OBTENER_RESENA_COMENTARIO(
    P_RESENA_ID IN  RESENA_COMENTARIO.RESENA_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              RESENA_ID,
             CLI_ID,
             PRODUCTO_ID,
             CALIFICACION,
             RESENA_AT,
             ESTADO
      FROM RESENA_COMENTARIO
      WHERE RESENA_ID = P_RESENA_ID;
  END SP_OBTENER_RESENA_COMENTARIO;

  PROCEDURE SP_LISTAR_RESENA_COMENTARIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              RESENA_ID,
             CLI_ID,
             PRODUCTO_ID,
             CALIFICACION,
             RESENA_AT,
             ESTADO
      FROM RESENA_COMENTARIO
      WHERE ESTADO = 'ACTIVO'
      ORDER BY RESENA_AT DESC;
  END SP_LISTAR_RESENA_COMENTARIO;

  PROCEDURE SP_BUSCAR_RESENA_COMENTARIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              RESENA_ID,
             CLI_ID,
             PRODUCTO_ID,
             CALIFICACION,
             RESENA_AT,
             ESTADO
      FROM RESENA_COMENTARIO
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'CLI_ID' AND UPPER(CAST(CLI_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'PRODUCTO_ID' AND UPPER(CAST(PRODUCTO_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY RESENA_AT DESC;
  END SP_BUSCAR_RESENA_COMENTARIO;

END PKG_RESENA_COMENTARIO;
/
