CREATE OR REPLACE PACKAGE PKG_PROMOCION_PRODUCTO AS

  PROCEDURE SP_INSERTAR_PROMOCION_PRODUCTO(
    P_PROMOCION_ID          IN PROMOCION_PRODUCTO.PROMOCION_ID%TYPE,
    P_PRODUCTO_ID           IN PROMOCION_PRODUCTO.PRODUCTO_ID%TYPE,
    P_LIMITE_UNIDADES       IN PROMOCION_PRODUCTO.LIMITE_UNIDADES%TYPE,
    P_PROMOCION_PRODUCTO_ID OUT PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_PROMOCION_PRODUCTO(
    P_PROMOCION_PRODUCTO_ID IN PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE,
    P_PROMOCION_ID          IN PROMOCION_PRODUCTO.PROMOCION_ID%TYPE,
    P_PRODUCTO_ID           IN PROMOCION_PRODUCTO.PRODUCTO_ID%TYPE,
    P_LIMITE_UNIDADES       IN PROMOCION_PRODUCTO.LIMITE_UNIDADES%TYPE
  );

  PROCEDURE SP_ELIMINAR_PROMOCION_PRODUCTO(
    P_PROMOCION_PRODUCTO_ID IN PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_PROMOCION_PRODUCTO(
    P_PROMOCION_PRODUCTO_ID IN PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE,
    P_CURSOR                OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_PROMOCION_PRODUCTO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_PROMOCION_PRODUCTO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_PROMOCION_PRODUCTO;
/

CREATE OR REPLACE PACKAGE BODY PKG_PROMOCION_PRODUCTO AS

  PROCEDURE SP_INSERTAR_PROMOCION_PRODUCTO(
    P_PROMOCION_ID          IN PROMOCION_PRODUCTO.PROMOCION_ID%TYPE,
    P_PRODUCTO_ID           IN PROMOCION_PRODUCTO.PRODUCTO_ID%TYPE,
    P_LIMITE_UNIDADES       IN PROMOCION_PRODUCTO.LIMITE_UNIDADES%TYPE,
    P_PROMOCION_PRODUCTO_ID OUT PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO PROMOCION_PRODUCTO (
      PROMOCION_ID,
      PRODUCTO_ID,
      LIMITE_UNIDADES,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_PROMOCION_ID,
      P_PRODUCTO_ID,
      P_LIMITE_UNIDADES,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING PROMOCION_PRODUCTO_ID INTO P_PROMOCION_PRODUCTO_ID;
  END SP_INSERTAR_PROMOCION_PRODUCTO;

  PROCEDURE SP_ACTUALIZAR_PROMOCION_PRODUCTO(
    P_PROMOCION_PRODUCTO_ID IN PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE,
    P_PROMOCION_ID          IN PROMOCION_PRODUCTO.PROMOCION_ID%TYPE,
    P_PRODUCTO_ID           IN PROMOCION_PRODUCTO.PRODUCTO_ID%TYPE,
    P_LIMITE_UNIDADES       IN PROMOCION_PRODUCTO.LIMITE_UNIDADES%TYPE
  ) AS
  BEGIN
    UPDATE PROMOCION_PRODUCTO
       SET PROMOCION_ID    = P_PROMOCION_ID,
           PRODUCTO_ID     = P_PRODUCTO_ID,
           LIMITE_UNIDADES = P_LIMITE_UNIDADES,
           UPDATED_AT      = SYSTIMESTAMP
     WHERE PROMOCION_PRODUCTO_ID = P_PROMOCION_PRODUCTO_ID;
  END SP_ACTUALIZAR_PROMOCION_PRODUCTO;

  PROCEDURE SP_ELIMINAR_PROMOCION_PRODUCTO(
    P_PROMOCION_PRODUCTO_ID IN PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE
  ) AS
  BEGIN
    UPDATE PROMOCION_PRODUCTO
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE PROMOCION_PRODUCTO_ID = P_PROMOCION_PRODUCTO_ID;
  END SP_ELIMINAR_PROMOCION_PRODUCTO;

  PROCEDURE SP_OBTENER_PROMOCION_PRODUCTO(
    P_PROMOCION_PRODUCTO_ID IN PROMOCION_PRODUCTO.PROMOCION_PRODUCTO_ID%TYPE,
    P_CURSOR                OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PP.PROMOCION_PRODUCTO_ID,
             PP.PROMOCION_ID,
             PR.NOMBRE AS PROMOCION,
             PP.PRODUCTO_ID,
             PD.NOMBRE AS PRODUCTO,
             PP.LIMITE_UNIDADES,
             PP.ESTADO
        FROM PROMOCION_PRODUCTO PP
        JOIN PROMOCION PR
          ON PR.PROMOCION_ID = PP.PROMOCION_ID
        JOIN PRODUCTO PD
          ON PD.PRODUCTO_ID = PP.PRODUCTO_ID
       WHERE PP.PROMOCION_PRODUCTO_ID = P_PROMOCION_PRODUCTO_ID;
  END SP_OBTENER_PROMOCION_PRODUCTO;

  PROCEDURE SP_LISTAR_PROMOCION_PRODUCTO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PP.PROMOCION_PRODUCTO_ID,
             PR.NOMBRE AS PROMOCION,
             PD.REFERENCIA,
             PD.NOMBRE AS PRODUCTO,
             PP.LIMITE_UNIDADES,
             PP.ESTADO
        FROM PROMOCION_PRODUCTO PP
        JOIN PROMOCION PR
          ON PR.PROMOCION_ID = PP.PROMOCION_ID
        JOIN PRODUCTO PD
          ON PD.PRODUCTO_ID = PP.PRODUCTO_ID
       WHERE PP.ESTADO = 'ACTIVO'
       ORDER BY PR.NOMBRE, PD.NOMBRE;
  END SP_LISTAR_PROMOCION_PRODUCTO;

  PROCEDURE SP_BUSCAR_PROMOCION_PRODUCTO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT PP.PROMOCION_PRODUCTO_ID,
             PR.NOMBRE AS PROMOCION,
             PD.REFERENCIA,
             PD.NOMBRE AS PRODUCTO,
             PP.LIMITE_UNIDADES,
             PP.ESTADO
        FROM PROMOCION_PRODUCTO PP
        JOIN PROMOCION PR
          ON PR.PROMOCION_ID = PP.PROMOCION_ID
        JOIN PRODUCTO PD
          ON PD.PRODUCTO_ID = PP.PRODUCTO_ID
       WHERE PP.ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'PROMOCION' AND UPPER(PR.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'PRODUCTO' AND UPPER(PD.NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'REFERENCIA' AND UPPER(PD.REFERENCIA) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY PR.NOMBRE, PD.NOMBRE;
  END SP_BUSCAR_PROMOCION_PRODUCTO;

END PKG_PROMOCION_PRODUCTO;
/
