CREATE OR REPLACE PACKAGE PKG_ORDEN_PRODUCCION_TAREA AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION_TAREA(
    P_OP_ID              IN ORDEN_PRODUCCION_TAREA.OP_ID%TYPE,
    P_NOMBRE_TAREA       IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_DESCRIPCION        IN ORDEN_PRODUCCION_TAREA.DESCRIPCION%TYPE,
    P_RESPONSABLE        IN ORDEN_PRODUCCION_TAREA.RESPONSABLE%TYPE,
    P_FECHA_INICIO       IN ORDEN_PRODUCCION_TAREA.FECHA_INICIO%TYPE,
    P_FECHA_FIN          IN ORDEN_PRODUCCION_TAREA.FECHA_FIN%TYPE,
    P_ESTADO             IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE,
    P_OPT_ID             OUT ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION_TAREA(
    P_OPT_ID             IN ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE,
    P_OP_ID              IN ORDEN_PRODUCCION_TAREA.OP_ID%TYPE,
    P_NOMBRE_TAREA       IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_DESCRIPCION        IN ORDEN_PRODUCCION_TAREA.DESCRIPCION%TYPE,
    P_RESPONSABLE        IN ORDEN_PRODUCCION_TAREA.RESPONSABLE%TYPE,
    P_FECHA_INICIO       IN ORDEN_PRODUCCION_TAREA.FECHA_INICIO%TYPE,
    P_FECHA_FIN          IN ORDEN_PRODUCCION_TAREA.FECHA_FIN%TYPE,
    P_ESTADO             IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION_TAREA(
    P_OPT_ID IN ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION_TAREA(
    P_OPT_ID  IN ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ORDENES_PRODUCCION_TAREA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ORDENES_PRODUCCION_TAREA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ORDEN_PRODUCCION_TAREA;
/

CREATE OR REPLACE PACKAGE BODY PKG_ORDEN_PRODUCCION_TAREA AS

  PROCEDURE SP_INSERTAR_ORDEN_PRODUCCION_TAREA(
    P_OP_ID              IN ORDEN_PRODUCCION_TAREA.OP_ID%TYPE,
    P_NOMBRE_TAREA       IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_DESCRIPCION        IN ORDEN_PRODUCCION_TAREA.DESCRIPCION%TYPE,
    P_RESPONSABLE        IN ORDEN_PRODUCCION_TAREA.RESPONSABLE%TYPE,
    P_FECHA_INICIO       IN ORDEN_PRODUCCION_TAREA.FECHA_INICIO%TYPE,
    P_FECHA_FIN          IN ORDEN_PRODUCCION_TAREA.FECHA_FIN%TYPE,
    P_ESTADO             IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE,
    P_OPT_ID             OUT ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ORDEN_PRODUCCION_TAREA (
      OP_ID,
      NOMBRE_TAREA,
      DESCRIPCION,
      RESPONSABLE,
      FECHA_INICIO,
      FECHA_FIN,
      ESTADO,
      CREATED_AT
    )
    VALUES (
      P_OP_ID,
      P_NOMBRE_TAREA,
      P_DESCRIPCION,
      P_RESPONSABLE,
      P_FECHA_INICIO,
      P_FECHA_FIN,
      P_ESTADO,
      SYSTIMESTAMP
    )
    RETURNING OPT_ID INTO P_OPT_ID;
  END SP_INSERTAR_ORDEN_PRODUCCION_TAREA;


  PROCEDURE SP_ACTUALIZAR_ORDEN_PRODUCCION_TAREA(
    P_OPT_ID             IN ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE,
    P_OP_ID              IN ORDEN_PRODUCCION_TAREA.OP_ID%TYPE,
    P_NOMBRE_TAREA       IN ORDEN_PRODUCCION_TAREA.NOMBRE_TAREA%TYPE,
    P_DESCRIPCION        IN ORDEN_PRODUCCION_TAREA.DESCRIPCION%TYPE,
    P_RESPONSABLE        IN ORDEN_PRODUCCION_TAREA.RESPONSABLE%TYPE,
    P_FECHA_INICIO       IN ORDEN_PRODUCCION_TAREA.FECHA_INICIO%TYPE,
    P_FECHA_FIN          IN ORDEN_PRODUCCION_TAREA.FECHA_FIN%TYPE,
    P_ESTADO             IN ORDEN_PRODUCCION_TAREA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE ORDEN_PRODUCCION_TAREA
       SET OP_ID         = P_OP_ID,
           NOMBRE_TAREA  = P_NOMBRE_TAREA,
           DESCRIPCION   = P_DESCRIPCION,
           RESPONSABLE   = P_RESPONSABLE,
           FECHA_INICIO  = P_FECHA_INICIO,
           FECHA_FIN     = P_FECHA_FIN,
           ESTADO        = P_ESTADO,
           UPDATED_AT    = SYSTIMESTAMP
     WHERE OPT_ID = P_OPT_ID;
  END SP_ACTUALIZAR_ORDEN_PRODUCCION_TAREA;


  PROCEDURE SP_ELIMINAR_ORDEN_PRODUCCION_TAREA(
    P_OPT_ID IN ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM ORDEN_PRODUCCION_TAREA
     WHERE OPT_ID = P_OPT_ID;
  END SP_ELIMINAR_ORDEN_PRODUCCION_TAREA;


  PROCEDURE SP_OBTENER_ORDEN_PRODUCCION_TAREA(
    P_OPT_ID  IN ORDEN_PRODUCCION_TAREA.OPT_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OPT_ID,
             OP_ID,
             NOMBRE_TAREA,
             DESCRIPCION,
             RESPONSABLE,
             FECHA_INICIO,
             FECHA_FIN,
             ESTADO
        FROM ORDEN_PRODUCCION_TAREA
       WHERE OPT_ID = P_OPT_ID;
  END SP_OBTENER_ORDEN_PRODUCCION_TAREA;


  PROCEDURE SP_LISTAR_ORDENES_PRODUCCION_TAREA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OPT_ID,
             OP_ID,
             NOMBRE_TAREA,
             DESCRIPCION,
             RESPONSABLE,
             FECHA_INICIO,
             FECHA_FIN,
             ESTADO
        FROM ORDEN_PRODUCCION_TAREA
       ORDER BY OPT_ID DESC;
  END SP_LISTAR_ORDENES_PRODUCCION_TAREA;


  PROCEDURE SP_BUSCAR_ORDENES_PRODUCCION_TAREA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT OPT_ID,
             OP_ID,
             NOMBRE_TAREA,
             DESCRIPCION,
             RESPONSABLE,
             FECHA_INICIO,
             FECHA_FIN,
             ESTADO
        FROM ORDEN_PRODUCCION_TAREA
       WHERE (
             (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE_TAREA) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'RESPONSABLE' AND UPPER(RESPONSABLE) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'OP_ID' AND TO_CHAR(OP_ID) LIKE '%' || P_VALOR || '%')
       )
       ORDER BY OPT_ID DESC;
  END SP_BUSCAR_ORDENES_PRODUCCION_TAREA;

END PKG_ORDEN_PRODUCCION_TAREA;
/