CREATE OR REPLACE PACKAGE PKG_ZONA_ENVIO AS

  PROCEDURE SP_INSERTAR_ZONA_ENVIO(
    P_NOMBRE          IN ZONA_ENVIO.NOMBRE%TYPE,
    P_PAIS            IN ZONA_ENVIO.PAIS%TYPE,
    P_DEPARTAMENTO    IN ZONA_ENVIO.DEPARTAMENTO%TYPE,
    P_CIUDAD          IN ZONA_ENVIO.CIUDAD%TYPE,
    P_ZONA_ENVIO_ID   OUT ZONA_ENVIO.ZONA_ENVIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ZONA_ENVIO(
    P_ZONA_ENVIO_ID   IN ZONA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_NOMBRE          IN ZONA_ENVIO.NOMBRE%TYPE,
    P_PAIS            IN ZONA_ENVIO.PAIS%TYPE,
    P_DEPARTAMENTO    IN ZONA_ENVIO.DEPARTAMENTO%TYPE,
    P_CIUDAD          IN ZONA_ENVIO.CIUDAD%TYPE
  );

  PROCEDURE SP_ELIMINAR_ZONA_ENVIO(
    P_ZONA_ENVIO_ID IN ZONA_ENVIO.ZONA_ENVIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ZONA_ENVIO(
    P_ZONA_ENVIO_ID IN ZONA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_CURSOR        OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ZONAS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ZONAS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ZONA_ENVIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_ZONA_ENVIO AS

  PROCEDURE SP_INSERTAR_ZONA_ENVIO(
    P_NOMBRE          IN ZONA_ENVIO.NOMBRE%TYPE,
    P_PAIS            IN ZONA_ENVIO.PAIS%TYPE,
    P_DEPARTAMENTO    IN ZONA_ENVIO.DEPARTAMENTO%TYPE,
    P_CIUDAD          IN ZONA_ENVIO.CIUDAD%TYPE,
    P_ZONA_ENVIO_ID   OUT ZONA_ENVIO.ZONA_ENVIO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ZONA_ENVIO (
      NOMBRE,
      PAIS,
      DEPARTAMENTO,
      CIUDAD,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_NOMBRE,
      P_PAIS,
      P_DEPARTAMENTO,
      P_CIUDAD,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING ZONA_ENVIO_ID INTO P_ZONA_ENVIO_ID;
  END SP_INSERTAR_ZONA_ENVIO;

  PROCEDURE SP_ACTUALIZAR_ZONA_ENVIO(
    P_ZONA_ENVIO_ID   IN ZONA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_NOMBRE          IN ZONA_ENVIO.NOMBRE%TYPE,
    P_PAIS            IN ZONA_ENVIO.PAIS%TYPE,
    P_DEPARTAMENTO    IN ZONA_ENVIO.DEPARTAMENTO%TYPE,
    P_CIUDAD          IN ZONA_ENVIO.CIUDAD%TYPE
  ) AS
  BEGIN
    UPDATE ZONA_ENVIO
       SET NOMBRE       = P_NOMBRE,
           PAIS         = P_PAIS,
           DEPARTAMENTO = P_DEPARTAMENTO,
           CIUDAD       = P_CIUDAD,
           UPDATED_AT   = SYSTIMESTAMP
     WHERE ZONA_ENVIO_ID = P_ZONA_ENVIO_ID;
  END SP_ACTUALIZAR_ZONA_ENVIO;

  PROCEDURE SP_ELIMINAR_ZONA_ENVIO(
    P_ZONA_ENVIO_ID IN ZONA_ENVIO.ZONA_ENVIO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM (
        SELECT ZONA_ENVIO_ID FROM REGLA_ENVIO_GRATIS WHERE ZONA_ENVIO_ID = P_ZONA_ENVIO_ID
        UNION ALL
        SELECT ZONA_ENVIO_ID FROM TARIFA_ENVIO WHERE ZONA_ENVIO_ID = P_ZONA_ENVIO_ID
        UNION ALL
        SELECT ZONA_ENVIO_ID FROM ENVIO WHERE ZONA_ENVIO_ID = P_ZONA_ENVIO_ID
      );

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar la zona de envío porque tiene registros asociados.');
    END IF;

    UPDATE ZONA_ENVIO
       SET ESTADO     = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE ZONA_ENVIO_ID = P_ZONA_ENVIO_ID;
  END SP_ELIMINAR_ZONA_ENVIO;

  PROCEDURE SP_OBTENER_ZONA_ENVIO(
    P_ZONA_ENVIO_ID IN ZONA_ENVIO.ZONA_ENVIO_ID%TYPE,
    P_CURSOR        OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ZONA_ENVIO_ID,
             NOMBRE,
             PAIS,
             DEPARTAMENTO,
             CIUDAD,
             ESTADO
        FROM ZONA_ENVIO
       WHERE ZONA_ENVIO_ID = P_ZONA_ENVIO_ID;
  END SP_OBTENER_ZONA_ENVIO;

  PROCEDURE SP_LISTAR_ZONAS_ENVIO(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ZONA_ENVIO_ID,
             NOMBRE,
             PAIS,
             DEPARTAMENTO,
             CIUDAD,
             ESTADO
        FROM ZONA_ENVIO
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRE;
  END SP_LISTAR_ZONAS_ENVIO;

  PROCEDURE SP_BUSCAR_ZONAS_ENVIO(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ZONA_ENVIO_ID,
             NOMBRE,
             PAIS,
             DEPARTAMENTO,
             CIUDAD,
             ESTADO
        FROM ZONA_ENVIO
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRE) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'PAIS' AND UPPER(PAIS) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'DEPARTAMENTO' AND UPPER(DEPARTAMENTO) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'CIUDAD' AND UPPER(CIUDAD) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY NOMBRE;
  END SP_BUSCAR_ZONAS_ENVIO;

END PKG_ZONA_ENVIO;
/
