CREATE OR REPLACE PACKAGE PKG_LISTA_MATERIALES_DETALLE AS

  PROCEDURE SP_INSERTAR_LISTA_MATERIALES_DETALLE(
    P_LM_ID              IN LISTA_MATERIALES_DETALLE.LM_ID%TYPE,
    P_MP_ID              IN LISTA_MATERIALES_DETALLE.MP_ID%TYPE,
    P_CANTIDAD_REQUERIDA IN LISTA_MATERIALES_DETALLE.CANTIDAD_REQUERIDA%TYPE,
    P_UNIDAD_MEDIDA      IN LISTA_MATERIALES_DETALLE.UNIDAD_MEDIDA%TYPE,
    P_DESCRIPCION        IN LISTA_MATERIALES_DETALLE.DESCRIPCION%TYPE,
    P_LMD_ID             OUT LISTA_MATERIALES_DETALLE.LMD_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_LISTA_MATERIALES_DETALLE(
    P_LMD_ID             IN LISTA_MATERIALES_DETALLE.LMD_ID%TYPE,
    P_LM_ID              IN LISTA_MATERIALES_DETALLE.LM_ID%TYPE,
    P_MP_ID              IN LISTA_MATERIALES_DETALLE.MP_ID%TYPE,
    P_CANTIDAD_REQUERIDA IN LISTA_MATERIALES_DETALLE.CANTIDAD_REQUERIDA%TYPE,
    P_UNIDAD_MEDIDA      IN LISTA_MATERIALES_DETALLE.UNIDAD_MEDIDA%TYPE,
    P_DESCRIPCION        IN LISTA_MATERIALES_DETALLE.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_LISTA_MATERIALES_DETALLE(
    P_LMD_ID IN LISTA_MATERIALES_DETALLE.LMD_ID%TYPE
  );

  PROCEDURE SP_OBTENER_LISTA_MATERIALES_DETALLE(
    P_LMD_ID  IN LISTA_MATERIALES_DETALLE.LMD_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_LISTAS_MATERIALES_DETALLE(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_LISTAS_MATERIALES_DETALLE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_LISTA_MATERIALES_DETALLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_LISTA_MATERIALES_DETALLE AS

  PROCEDURE SP_INSERTAR_LISTA_MATERIALES_DETALLE(
    P_LM_ID              IN LISTA_MATERIALES_DETALLE.LM_ID%TYPE,
    P_MP_ID              IN LISTA_MATERIALES_DETALLE.MP_ID%TYPE,
    P_CANTIDAD_REQUERIDA IN LISTA_MATERIALES_DETALLE.CANTIDAD_REQUERIDA%TYPE,
    P_UNIDAD_MEDIDA      IN LISTA_MATERIALES_DETALLE.UNIDAD_MEDIDA%TYPE,
    P_DESCRIPCION        IN LISTA_MATERIALES_DETALLE.DESCRIPCION%TYPE,
    P_LMD_ID             OUT LISTA_MATERIALES_DETALLE.LMD_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO LISTA_MATERIALES_DETALLE (
      LM_ID,
      MP_ID,
      CANTIDAD_REQUERIDA,
      UNIDAD_MEDIDA,
      DESCRIPCION,
      CREATED_AT
    )
    VALUES (
      P_LM_ID,
      P_MP_ID,
      P_CANTIDAD_REQUERIDA,
      P_UNIDAD_MEDIDA,
      P_DESCRIPCION,
      SYSTIMESTAMP
    )
    RETURNING LMD_ID INTO P_LMD_ID;
  END SP_INSERTAR_LISTA_MATERIALES_DETALLE;


  PROCEDURE SP_ACTUALIZAR_LISTA_MATERIALES_DETALLE(
    P_LMD_ID             IN LISTA_MATERIALES_DETALLE.LMD_ID%TYPE,
    P_LM_ID              IN LISTA_MATERIALES_DETALLE.LM_ID%TYPE,
    P_MP_ID              IN LISTA_MATERIALES_DETALLE.MP_ID%TYPE,
    P_CANTIDAD_REQUERIDA IN LISTA_MATERIALES_DETALLE.CANTIDAD_REQUERIDA%TYPE,
    P_UNIDAD_MEDIDA      IN LISTA_MATERIALES_DETALLE.UNIDAD_MEDIDA%TYPE,
    P_DESCRIPCION        IN LISTA_MATERIALES_DETALLE.DESCRIPCION%TYPE
  ) AS
  BEGIN
    UPDATE LISTA_MATERIALES_DETALLE
       SET LM_ID              = P_LM_ID,
           MP_ID              = P_MP_ID,
           CANTIDAD_REQUERIDA = P_CANTIDAD_REQUERIDA,
           UNIDAD_MEDIDA      = P_UNIDAD_MEDIDA,
           DESCRIPCION        = P_DESCRIPCION,
           UPDATED_AT         = SYSTIMESTAMP
     WHERE LMD_ID = P_LMD_ID;
  END SP_ACTUALIZAR_LISTA_MATERIALES_DETALLE;


  PROCEDURE SP_ELIMINAR_LISTA_MATERIALES_DETALLE(
    P_LMD_ID IN LISTA_MATERIALES_DETALLE.LMD_ID%TYPE
  ) AS
  BEGIN
    DELETE FROM LISTA_MATERIALES_DETALLE
     WHERE LMD_ID = P_LMD_ID;
  END SP_ELIMINAR_LISTA_MATERIALES_DETALLE;


  PROCEDURE SP_OBTENER_LISTA_MATERIALES_DETALLE(
    P_LMD_ID  IN LISTA_MATERIALES_DETALLE.LMD_ID%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT LMD_ID,
             LM_ID,
             MP_ID,
             CANTIDAD_REQUERIDA,
             UNIDAD_MEDIDA,
             DESCRIPCION
        FROM LISTA_MATERIALES_DETALLE
       WHERE LMD_ID = P_LMD_ID;
  END SP_OBTENER_LISTA_MATERIALES_DETALLE;


  PROCEDURE SP_LISTAR_LISTAS_MATERIALES_DETALLE(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT LMD_ID,
             LM_ID,
             MP_ID,
             CANTIDAD_REQUERIDA,
             UNIDAD_MEDIDA,
             DESCRIPCION
        FROM LISTA_MATERIALES_DETALLE
       ORDER BY LMD_ID DESC;
  END SP_LISTAR_LISTAS_MATERIALES_DETALLE;


  PROCEDURE SP_BUSCAR_LISTAS_MATERIALES_DETALLE(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT LMD_ID,
             LM_ID,
             MP_ID,
             CANTIDAD_REQUERIDA,
             UNIDAD_MEDIDA,
             DESCRIPCION
        FROM LISTA_MATERIALES_DETALLE
       WHERE (
             (UPPER(P_CRITERIO) = 'LM_ID' AND TO_CHAR(LM_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'MP_ID' AND TO_CHAR(MP_ID) LIKE '%' || P_VALOR || '%')
          OR (UPPER(P_CRITERIO) = 'UNIDAD_MEDIDA' AND UPPER(UNIDAD_MEDIDA) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
       )
       ORDER BY LMD_ID DESC;
  END SP_BUSCAR_LISTAS_MATERIALES_DETALLE;

END PKG_LISTA_MATERIALES_DETALLE;
/