CREATE OR REPLACE PACKAGE PKG_DEVOLUCION AS
  PROCEDURE SP_INSERTAR_DEVOLUCION(
    P_ORDEN_VENTA_ID IN DEVOLUCION.ORDEN_VENTA_ID%TYPE,
    P_CLI_ID IN DEVOLUCION.CLI_ID%TYPE,
    P_MOTIVO IN DEVOLUCION.MOTIVO%TYPE,
    P_ESTADO_DEVOLUCION IN DEVOLUCION.ESTADO_DEVOLUCION%TYPE,
    P_SOLICITUD_AT IN DEVOLUCION.SOLICITUD_AT%TYPE,
    P_RESOLUCION_AT IN DEVOLUCION.RESOLUCION_AT%TYPE,
    P_DEVOLUCION_ID OUT DEVOLUCION.DEVOLUCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_DEVOLUCION(
    P_DEVOLUCION_ID IN DEVOLUCION.DEVOLUCION_ID%TYPE,
    P_ORDEN_VENTA_ID IN DEVOLUCION.ORDEN_VENTA_ID%TYPE,
    P_CLI_ID IN DEVOLUCION.CLI_ID%TYPE,
    P_MOTIVO IN DEVOLUCION.MOTIVO%TYPE,
    P_ESTADO_DEVOLUCION IN DEVOLUCION.ESTADO_DEVOLUCION%TYPE,
    P_SOLICITUD_AT IN DEVOLUCION.SOLICITUD_AT%TYPE,
    P_RESOLUCION_AT IN DEVOLUCION.RESOLUCION_AT%TYPE
  );

  PROCEDURE SP_ELIMINAR_DEVOLUCION(
    P_DEVOLUCION_ID IN DEVOLUCION.DEVOLUCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_DEVOLUCION(
    P_DEVOLUCION_ID IN  DEVOLUCION.DEVOLUCION_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_DEVOLUCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_DEVOLUCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_DEVOLUCION;
/


CREATE OR REPLACE PACKAGE BODY PKG_DEVOLUCION AS

  PROCEDURE SP_INSERTAR_DEVOLUCION(
    P_ORDEN_VENTA_ID IN DEVOLUCION.ORDEN_VENTA_ID%TYPE,
    P_CLI_ID IN DEVOLUCION.CLI_ID%TYPE,
    P_MOTIVO IN DEVOLUCION.MOTIVO%TYPE,
    P_ESTADO_DEVOLUCION IN DEVOLUCION.ESTADO_DEVOLUCION%TYPE,
    P_SOLICITUD_AT IN DEVOLUCION.SOLICITUD_AT%TYPE,
    P_RESOLUCION_AT IN DEVOLUCION.RESOLUCION_AT%TYPE,
    P_DEVOLUCION_ID OUT DEVOLUCION.DEVOLUCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO DEVOLUCION (
      ORDEN_VENTA_ID,
      CLI_ID,
      MOTIVO,
      ESTADO_DEVOLUCION,
      SOLICITUD_AT,
      RESOLUCION_AT,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_ORDEN_VENTA_ID,
      P_CLI_ID,
      P_MOTIVO,
      P_ESTADO_DEVOLUCION,
      P_SOLICITUD_AT,
      P_RESOLUCION_AT,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING DEVOLUCION_ID INTO P_DEVOLUCION_ID;
  END SP_INSERTAR_DEVOLUCION;

  PROCEDURE SP_ACTUALIZAR_DEVOLUCION(
    P_DEVOLUCION_ID IN DEVOLUCION.DEVOLUCION_ID%TYPE,
    P_ORDEN_VENTA_ID IN DEVOLUCION.ORDEN_VENTA_ID%TYPE,
    P_CLI_ID IN DEVOLUCION.CLI_ID%TYPE,
    P_MOTIVO IN DEVOLUCION.MOTIVO%TYPE,
    P_ESTADO_DEVOLUCION IN DEVOLUCION.ESTADO_DEVOLUCION%TYPE,
    P_SOLICITUD_AT IN DEVOLUCION.SOLICITUD_AT%TYPE,
    P_RESOLUCION_AT IN DEVOLUCION.RESOLUCION_AT%TYPE
  ) AS
  BEGIN
    UPDATE DEVOLUCION
    SET         ORDEN_VENTA_ID = P_ORDEN_VENTA_ID,
        CLI_ID = P_CLI_ID,
        MOTIVO = P_MOTIVO,
        ESTADO_DEVOLUCION = P_ESTADO_DEVOLUCION,
        SOLICITUD_AT = P_SOLICITUD_AT,
        RESOLUCION_AT = P_RESOLUCION_AT,
        UPDATED_AT = SYSTIMESTAMP
    WHERE DEVOLUCION_ID = P_DEVOLUCION_ID;
  END SP_ACTUALIZAR_DEVOLUCION;

  PROCEDURE SP_ELIMINAR_DEVOLUCION(
    P_DEVOLUCION_ID IN DEVOLUCION.DEVOLUCION_ID%TYPE
  ) AS
  BEGIN
    UPDATE DEVOLUCION
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE DEVOLUCION_ID = P_DEVOLUCION_ID;
  END SP_ELIMINAR_DEVOLUCION;

  PROCEDURE SP_OBTENER_DEVOLUCION(
    P_DEVOLUCION_ID IN  DEVOLUCION.DEVOLUCION_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              DEVOLUCION_ID,
             ORDEN_VENTA_ID,
             CLI_ID,
             ESTADO_DEVOLUCION,
             SOLICITUD_AT,
             ESTADO
      FROM DEVOLUCION
      WHERE DEVOLUCION_ID = P_DEVOLUCION_ID;
  END SP_OBTENER_DEVOLUCION;

  PROCEDURE SP_LISTAR_DEVOLUCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              DEVOLUCION_ID,
             ORDEN_VENTA_ID,
             CLI_ID,
             ESTADO_DEVOLUCION,
             SOLICITUD_AT,
             ESTADO
      FROM DEVOLUCION
      WHERE ESTADO = 'ACTIVO'
      ORDER BY SOLICITUD_AT DESC;
  END SP_LISTAR_DEVOLUCION;

  PROCEDURE SP_BUSCAR_DEVOLUCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              DEVOLUCION_ID,
             ORDEN_VENTA_ID,
             CLI_ID,
             ESTADO_DEVOLUCION,
             SOLICITUD_AT,
             ESTADO
      FROM DEVOLUCION
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'ESTADO_DEVOLUCION' AND UPPER(CAST(ESTADO_DEVOLUCION AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'CLI_ID' AND UPPER(CAST(CLI_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY SOLICITUD_AT DESC;
  END SP_BUSCAR_DEVOLUCION;

END PKG_DEVOLUCION;
/
