CREATE OR REPLACE PACKAGE PKG_LISTA_DESEOS AS
  PROCEDURE SP_INSERTAR_LISTA_DESEOS(
    P_CLI_ID IN LISTA_DESEOS.CLI_ID%TYPE,
    P_PRODUCTO_ID IN LISTA_DESEOS.PRODUCTO_ID%TYPE,
    P_NOTA IN LISTA_DESEOS.NOTA%TYPE,
    P_LISTA_DESEOS_ID OUT LISTA_DESEOS.LISTA_DESEOS_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_LISTA_DESEOS(
    P_LISTA_DESEOS_ID IN LISTA_DESEOS.LISTA_DESEOS_ID%TYPE,
    P_CLI_ID IN LISTA_DESEOS.CLI_ID%TYPE,
    P_PRODUCTO_ID IN LISTA_DESEOS.PRODUCTO_ID%TYPE,
    P_NOTA IN LISTA_DESEOS.NOTA%TYPE
  );

  PROCEDURE SP_ELIMINAR_LISTA_DESEOS(
    P_LISTA_DESEOS_ID IN LISTA_DESEOS.LISTA_DESEOS_ID%TYPE
  );

  PROCEDURE SP_OBTENER_LISTA_DESEOS(
    P_LISTA_DESEOS_ID IN  LISTA_DESEOS.LISTA_DESEOS_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_LISTA_DESEOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_LISTA_DESEOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_LISTA_DESEOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_LISTA_DESEOS AS

  PROCEDURE SP_INSERTAR_LISTA_DESEOS(
    P_CLI_ID IN LISTA_DESEOS.CLI_ID%TYPE,
    P_PRODUCTO_ID IN LISTA_DESEOS.PRODUCTO_ID%TYPE,
    P_NOTA IN LISTA_DESEOS.NOTA%TYPE,
    P_LISTA_DESEOS_ID OUT LISTA_DESEOS.LISTA_DESEOS_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO LISTA_DESEOS (
      CLI_ID,
      PRODUCTO_ID,
      NOTA,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CLI_ID,
      P_PRODUCTO_ID,
      P_NOTA,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING LISTA_DESEOS_ID INTO P_LISTA_DESEOS_ID;
  END SP_INSERTAR_LISTA_DESEOS;

  PROCEDURE SP_ACTUALIZAR_LISTA_DESEOS(
    P_LISTA_DESEOS_ID IN LISTA_DESEOS.LISTA_DESEOS_ID%TYPE,
    P_CLI_ID IN LISTA_DESEOS.CLI_ID%TYPE,
    P_PRODUCTO_ID IN LISTA_DESEOS.PRODUCTO_ID%TYPE,
    P_NOTA IN LISTA_DESEOS.NOTA%TYPE
  ) AS
  BEGIN
    UPDATE LISTA_DESEOS
    SET         CLI_ID = P_CLI_ID,
        PRODUCTO_ID = P_PRODUCTO_ID,
        NOTA = P_NOTA,
        UPDATED_AT = SYSTIMESTAMP
    WHERE LISTA_DESEOS_ID = P_LISTA_DESEOS_ID;
  END SP_ACTUALIZAR_LISTA_DESEOS;

  PROCEDURE SP_ELIMINAR_LISTA_DESEOS(
    P_LISTA_DESEOS_ID IN LISTA_DESEOS.LISTA_DESEOS_ID%TYPE
  ) AS
  BEGIN
    UPDATE LISTA_DESEOS
    SET ESTADO = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE LISTA_DESEOS_ID = P_LISTA_DESEOS_ID;
  END SP_ELIMINAR_LISTA_DESEOS;

  PROCEDURE SP_OBTENER_LISTA_DESEOS(
    P_LISTA_DESEOS_ID IN  LISTA_DESEOS.LISTA_DESEOS_ID%TYPE,
    P_CURSOR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              LISTA_DESEOS_ID,
             CLI_ID,
             PRODUCTO_ID,
             NOTA,
             ESTADO
      FROM LISTA_DESEOS
      WHERE LISTA_DESEOS_ID = P_LISTA_DESEOS_ID;
  END SP_OBTENER_LISTA_DESEOS;

  PROCEDURE SP_LISTAR_LISTA_DESEOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              LISTA_DESEOS_ID,
             CLI_ID,
             PRODUCTO_ID,
             NOTA,
             ESTADO
      FROM LISTA_DESEOS
      WHERE ESTADO = 'ACTIVO'
      ORDER BY LISTA_DESEOS_ID;
  END SP_LISTAR_LISTA_DESEOS;

  PROCEDURE SP_BUSCAR_LISTA_DESEOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT              LISTA_DESEOS_ID,
             CLI_ID,
             PRODUCTO_ID,
             NOTA,
             ESTADO
      FROM LISTA_DESEOS
      WHERE ESTADO = 'ACTIVO'
        AND (
          (UPPER(P_CRITERIO) = 'CLI_ID' AND UPPER(CAST(CLI_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
          OR
          (UPPER(P_CRITERIO) = 'PRODUCTO_ID' AND UPPER(CAST(PRODUCTO_ID AS VARCHAR2(200))) LIKE '%' || UPPER(P_VALOR) || '%')
        )
      ORDER BY LISTA_DESEOS_ID;
  END SP_BUSCAR_LISTA_DESEOS;

END PKG_LISTA_DESEOS;
/
