CREATE OR REPLACE PACKAGE PKG_ESTADO_PRODUCCION AS

  PROCEDURE SP_INSERTAR_ESTADO_PRODUCCION(
    P_CODIGO               IN  ESTADO_PRODUCCION.CODIGO%TYPE,
    P_DESCRIPCION          IN  ESTADO_PRODUCCION.DESCRIPCION%TYPE,
    P_ESTADO_PRODUCCION_ID OUT ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ESTADO_PRODUCCION(
    P_ESTADO_PRODUCCION_ID IN  ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_CODIGO               IN  ESTADO_PRODUCCION.CODIGO%TYPE,
    P_DESCRIPCION          IN  ESTADO_PRODUCCION.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_ESTADO_PRODUCCION(
    P_ESTADO_PRODUCCION_ID IN ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ESTADO_PRODUCCION(
    P_ESTADO_PRODUCCION_ID IN  ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_CURSOR               OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ESTADO_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ESTADO_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ESTADO_PRODUCCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_ESTADO_PRODUCCION AS

  PROCEDURE SP_INSERTAR_ESTADO_PRODUCCION(
    P_CODIGO               IN  ESTADO_PRODUCCION.CODIGO%TYPE,
    P_DESCRIPCION          IN  ESTADO_PRODUCCION.DESCRIPCION%TYPE,
    P_ESTADO_PRODUCCION_ID OUT ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ESTADO_PRODUCCION (
      CODIGO,
      DESCRIPCION,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_CODIGO,
      P_DESCRIPCION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING ESTADO_PRODUCCION_ID INTO P_ESTADO_PRODUCCION_ID;
  END SP_INSERTAR_ESTADO_PRODUCCION;

  PROCEDURE SP_ACTUALIZAR_ESTADO_PRODUCCION(
    P_ESTADO_PRODUCCION_ID IN  ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_CODIGO               IN  ESTADO_PRODUCCION.CODIGO%TYPE,
    P_DESCRIPCION          IN  ESTADO_PRODUCCION.DESCRIPCION%TYPE
  ) AS
  BEGIN
    UPDATE ESTADO_PRODUCCION
    SET CODIGO      = P_CODIGO,
        DESCRIPCION = P_DESCRIPCION,
        UPDATED_AT  = SYSTIMESTAMP
    WHERE ESTADO_PRODUCCION_ID = P_ESTADO_PRODUCCION_ID;
  END SP_ACTUALIZAR_ESTADO_PRODUCCION;

  PROCEDURE SP_ELIMINAR_ESTADO_PRODUCCION(
    P_ESTADO_PRODUCCION_ID IN ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM ORDEN_PRODUCCION
    WHERE ESTADO_PRODUCCION_ID = P_ESTADO_PRODUCCION_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el estado de produccion porque tiene ordenes asociadas.');
    END IF;

    UPDATE ESTADO_PRODUCCION
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE ESTADO_PRODUCCION_ID = P_ESTADO_PRODUCCION_ID;
  END SP_ELIMINAR_ESTADO_PRODUCCION;

  PROCEDURE SP_OBTENER_ESTADO_PRODUCCION(
    P_ESTADO_PRODUCCION_ID IN  ESTADO_PRODUCCION.ESTADO_PRODUCCION_ID%TYPE,
    P_CURSOR               OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ESTADO_PRODUCCION_ID,
             CODIGO,
             DESCRIPCION,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
      FROM ESTADO_PRODUCCION
      WHERE ESTADO_PRODUCCION_ID = P_ESTADO_PRODUCCION_ID;
  END SP_OBTENER_ESTADO_PRODUCCION;

  PROCEDURE SP_LISTAR_ESTADO_PRODUCCION(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ESTADO_PRODUCCION_ID,
             CODIGO,
             DESCRIPCION,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
      FROM ESTADO_PRODUCCION
      WHERE ESTADO = 'ACTIVO'
      ORDER BY CODIGO;
  END SP_LISTAR_ESTADO_PRODUCCION;

  PROCEDURE SP_BUSCAR_ESTADO_PRODUCCION(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ESTADO_PRODUCCION_ID,
             CODIGO,
             DESCRIPCION,
             CREATED_AT,
             UPDATED_AT,
             ESTADO
      FROM ESTADO_PRODUCCION
      WHERE ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'CODIGO'      AND UPPER(CODIGO)      LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'DESCRIPCION' AND UPPER(DESCRIPCION) LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY CODIGO;
  END SP_BUSCAR_ESTADO_PRODUCCION;

END PKG_ESTADO_PRODUCCION;
/

