CREATE OR REPLACE PACKAGE PKG_ROL AS

  PROCEDURE SP_INSERTAR_ROL(
    P_NOMBRE      IN ROL.NOMBRE%TYPE,
    P_DESCRIPCION IN ROL.DESCRIPCION%TYPE,
    P_ROL_ID      OUT ROL.ROL_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ROL(
    P_ROL_ID      IN ROL.ROL_ID%TYPE,
    P_NOMBRE      IN ROL.NOMBRE%TYPE,
    P_DESCRIPCION IN ROL.DESCRIPCION%TYPE
  );

  PROCEDURE SP_ELIMINAR_ROL(
    P_ROL_ID IN ROL.ROL_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ROL(
    P_ROL_ID IN ROL.ROL_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ROLES(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ROL(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_ROL;
/

CREATE OR REPLACE PACKAGE BODY PKG_ROL AS

  PROCEDURE SP_INSERTAR_ROL(
    P_NOMBRE      IN ROL.NOMBRE%TYPE,
    P_DESCRIPCION IN ROL.DESCRIPCION%TYPE,
    P_ROL_ID      OUT ROL.ROL_ID%TYPE
  ) AS
  BEGIN

    INSERT INTO ROL(
        NOMBRE,
        DESCRIPCION,
        CREATED_AT
    )
    VALUES(
        P_NOMBRE,
        P_DESCRIPCION,
        SYSTIMESTAMP
    )
    RETURNING ROL_ID INTO P_ROL_ID;

  END SP_INSERTAR_ROL;



  PROCEDURE SP_ACTUALIZAR_ROL(
    P_ROL_ID      IN ROL.ROL_ID%TYPE,
    P_NOMBRE      IN ROL.NOMBRE%TYPE,
    P_DESCRIPCION IN ROL.DESCRIPCION%TYPE
  ) AS
  BEGIN

    UPDATE ROL
       SET NOMBRE = P_NOMBRE,
           DESCRIPCION = P_DESCRIPCION,
           UPDATED_AT = SYSTIMESTAMP
     WHERE ROL_ID = P_ROL_ID;

  END SP_ACTUALIZAR_ROL;



  PROCEDURE SP_ELIMINAR_ROL(
    P_ROL_ID IN ROL.ROL_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM USUARIO
     WHERE ROL_ID = P_ROL_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(
        -20001,
        'No se puede eliminar el rol porque está asignado a usuarios.'
      );
    END IF;

    DELETE FROM ROL
     WHERE ROL_ID = P_ROL_ID;

  END SP_ELIMINAR_ROL;



  PROCEDURE SP_OBTENER_ROL(
    P_ROL_ID IN ROL.ROL_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ROL_ID,
            NOMBRE,
            DESCRIPCION
        FROM ROL
        WHERE ROL_ID = P_ROL_ID;

  END SP_OBTENER_ROL;



  PROCEDURE SP_LISTAR_ROLES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ROL_ID,
            NOMBRE,
            DESCRIPCION
        FROM ROL
        ORDER BY NOMBRE;

  END SP_LISTAR_ROLES;



  PROCEDURE SP_BUSCAR_ROL(
    P_NOMBRE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN

    OPEN P_CURSOR FOR
        SELECT
            ROL_ID,
            NOMBRE,
            DESCRIPCION
        FROM ROL
        WHERE UPPER(NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%'
        ORDER BY NOMBRE;

  END SP_BUSCAR_ROL;

END PKG_ROL;
/