CREATE OR REPLACE PACKAGE PKG_CLIENTE AS

  PROCEDURE SP_INSERTAR_CLIENTE(
    P_TIPO_DOCUMENTO IN CLIENTE.TIPO_DOCUMENTO%TYPE,
    P_NUM_DOCUMENTO  IN CLIENTE.NUM_DOCUMENTO%TYPE,
    P_NIT            IN CLIENTE.NIT%TYPE,
    P_NOMBRES        IN CLIENTE.NOMBRES%TYPE,
    P_APELLIDOS      IN CLIENTE.APELLIDOS%TYPE,
    P_EMAIL          IN CLIENTE.EMAIL%TYPE,
    P_TEL_RESIDENCIA IN CLIENTE.TEL_RESIDENCIA%TYPE,
    P_TEL_CELULAR    IN CLIENTE.TEL_CELULAR%TYPE,
    P_DIRECCION      IN CLIENTE.DIRECCION%TYPE,
    P_CIUDAD         IN CLIENTE.CIUDAD%TYPE,
    P_DEPARTAMENTO   IN CLIENTE.DEPARTAMENTO%TYPE,
    P_PAIS           IN CLIENTE.PAIS%TYPE,
    P_PROFESION      IN CLIENTE.PROFESION%TYPE,
    P_CLI_ID         OUT CLIENTE.CLI_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_CLIENTE(
    P_CLI_ID         IN CLIENTE.CLI_ID%TYPE,
    P_TIPO_DOCUMENTO IN CLIENTE.TIPO_DOCUMENTO%TYPE,
    P_NUM_DOCUMENTO  IN CLIENTE.NUM_DOCUMENTO%TYPE,
    P_NIT            IN CLIENTE.NIT%TYPE,
    P_NOMBRES        IN CLIENTE.NOMBRES%TYPE,
    P_APELLIDOS      IN CLIENTE.APELLIDOS%TYPE,
    P_EMAIL          IN CLIENTE.EMAIL%TYPE,
    P_TEL_RESIDENCIA IN CLIENTE.TEL_RESIDENCIA%TYPE,
    P_TEL_CELULAR    IN CLIENTE.TEL_CELULAR%TYPE,
    P_DIRECCION      IN CLIENTE.DIRECCION%TYPE,
    P_CIUDAD         IN CLIENTE.CIUDAD%TYPE,
    P_DEPARTAMENTO   IN CLIENTE.DEPARTAMENTO%TYPE,
    P_PAIS           IN CLIENTE.PAIS%TYPE,
    P_PROFESION      IN CLIENTE.PROFESION%TYPE
  );

  PROCEDURE SP_ELIMINAR_CLIENTE(
    P_CLI_ID IN CLIENTE.CLI_ID%TYPE
  );

  PROCEDURE SP_OBTENER_CLIENTE(
    P_CLI_ID IN CLIENTE.CLI_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_CLIENTES(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_CLIENTES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_CLIENTE;
/


CREATE OR REPLACE PACKAGE BODY PKG_CLIENTE AS

  PROCEDURE SP_INSERTAR_CLIENTE(
    P_TIPO_DOCUMENTO IN CLIENTE.TIPO_DOCUMENTO%TYPE,
    P_NUM_DOCUMENTO  IN CLIENTE.NUM_DOCUMENTO%TYPE,
    P_NIT            IN CLIENTE.NIT%TYPE,
    P_NOMBRES        IN CLIENTE.NOMBRES%TYPE,
    P_APELLIDOS      IN CLIENTE.APELLIDOS%TYPE,
    P_EMAIL          IN CLIENTE.EMAIL%TYPE,
    P_TEL_RESIDENCIA IN CLIENTE.TEL_RESIDENCIA%TYPE,
    P_TEL_CELULAR    IN CLIENTE.TEL_CELULAR%TYPE,
    P_DIRECCION      IN CLIENTE.DIRECCION%TYPE,
    P_CIUDAD         IN CLIENTE.CIUDAD%TYPE,
    P_DEPARTAMENTO   IN CLIENTE.DEPARTAMENTO%TYPE,
    P_PAIS           IN CLIENTE.PAIS%TYPE,
    P_PROFESION      IN CLIENTE.PROFESION%TYPE,
    P_CLI_ID         OUT CLIENTE.CLI_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO CLIENTE (
      TIPO_DOCUMENTO,
      NUM_DOCUMENTO,
      NIT,
      NOMBRES,
      APELLIDOS,
      EMAIL,
      TEL_RESIDENCIA,
      TEL_CELULAR,
      DIRECCION,
      CIUDAD,
      DEPARTAMENTO,
      PAIS,
      PROFESION,
      CREATED_AT,
      ESTADO
    )
    VALUES (
      P_TIPO_DOCUMENTO,
      P_NUM_DOCUMENTO,
      P_NIT,
      P_NOMBRES,
      P_APELLIDOS,
      P_EMAIL,
      P_TEL_RESIDENCIA,
      P_TEL_CELULAR,
      P_DIRECCION,
      P_CIUDAD,
      P_DEPARTAMENTO,
      P_PAIS,
      P_PROFESION,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING CLI_ID INTO P_CLI_ID;
  END SP_INSERTAR_CLIENTE;

  PROCEDURE SP_ACTUALIZAR_CLIENTE(
    P_CLI_ID         IN CLIENTE.CLI_ID%TYPE,
    P_TIPO_DOCUMENTO IN CLIENTE.TIPO_DOCUMENTO%TYPE,
    P_NUM_DOCUMENTO  IN CLIENTE.NUM_DOCUMENTO%TYPE,
    P_NIT            IN CLIENTE.NIT%TYPE,
    P_NOMBRES        IN CLIENTE.NOMBRES%TYPE,
    P_APELLIDOS      IN CLIENTE.APELLIDOS%TYPE,
    P_EMAIL          IN CLIENTE.EMAIL%TYPE,
    P_TEL_RESIDENCIA IN CLIENTE.TEL_RESIDENCIA%TYPE,
    P_TEL_CELULAR    IN CLIENTE.TEL_CELULAR%TYPE,
    P_DIRECCION      IN CLIENTE.DIRECCION%TYPE,
    P_CIUDAD         IN CLIENTE.CIUDAD%TYPE,
    P_DEPARTAMENTO   IN CLIENTE.DEPARTAMENTO%TYPE,
    P_PAIS           IN CLIENTE.PAIS%TYPE,
    P_PROFESION      IN CLIENTE.PROFESION%TYPE
  ) AS
  BEGIN
    UPDATE CLIENTE
       SET TIPO_DOCUMENTO = P_TIPO_DOCUMENTO,
           NUM_DOCUMENTO  = P_NUM_DOCUMENTO,
           NIT            = P_NIT,
           NOMBRES        = P_NOMBRES,
           APELLIDOS      = P_APELLIDOS,
           EMAIL          = P_EMAIL,
           TEL_RESIDENCIA = P_TEL_RESIDENCIA,
           TEL_CELULAR    = P_TEL_CELULAR,
           DIRECCION      = P_DIRECCION,
           CIUDAD         = P_CIUDAD,
           DEPARTAMENTO   = P_DEPARTAMENTO,
           PAIS           = P_PAIS,
           PROFESION      = P_PROFESION,
           UPDATED_AT     = SYSTIMESTAMP
     WHERE CLI_ID = P_CLI_ID;
  END SP_ACTUALIZAR_CLIENTE;

  PROCEDURE SP_ELIMINAR_CLIENTE(
    P_CLI_ID IN CLIENTE.CLI_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM ORDEN_VENTA
     WHERE CLI_ID = P_CLI_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el cliente porque ya tiene compras registradas.');
    END IF;

    UPDATE CLIENTE
       SET ESTADO = 'INACTIVO',
           UPDATED_AT = SYSTIMESTAMP
     WHERE CLI_ID = P_CLI_ID;
  END SP_ELIMINAR_CLIENTE;

  PROCEDURE SP_OBTENER_CLIENTE(
    P_CLI_ID IN CLIENTE.CLI_ID%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CLI_ID,
             TIPO_DOCUMENTO,
             NUM_DOCUMENTO,
             NIT,
             NOMBRES,
             APELLIDOS,
             EMAIL,
             TEL_RESIDENCIA,
             TEL_CELULAR,
             DIRECCION,
             CIUDAD,
             DEPARTAMENTO,
             PAIS,
             PROFESION,
             ESTADO
        FROM CLIENTE
       WHERE CLI_ID = P_CLI_ID;
  END SP_OBTENER_CLIENTE;

  PROCEDURE SP_LISTAR_CLIENTES(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CLI_ID,
             NUM_DOCUMENTO,
             NOMBRES || ' ' || APELLIDOS AS NOMBRE_COMPLETO,
             EMAIL,
             CIUDAD,
             ESTADO
        FROM CLIENTE
       WHERE ESTADO = 'ACTIVO'
       ORDER BY NOMBRES, APELLIDOS;
  END SP_LISTAR_CLIENTES;

  PROCEDURE SP_BUSCAR_CLIENTES(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT CLI_ID,
             NUM_DOCUMENTO,
             NOMBRES || ' ' || APELLIDOS AS NOMBRE_COMPLETO,
             EMAIL,
             CIUDAD,
             ESTADO
        FROM CLIENTE
       WHERE ESTADO = 'ACTIVO'
         AND (
           (UPPER(P_CRITERIO) = 'DOCUMENTO' AND UPPER(NUM_DOCUMENTO) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'NOMBRE' AND UPPER(NOMBRES || ' ' || APELLIDOS) LIKE '%' || UPPER(P_VALOR) || '%')
           OR
           (UPPER(P_CRITERIO) = 'EMAIL' AND UPPER(EMAIL) LIKE '%' || UPPER(P_VALOR) || '%')
         )
       ORDER BY NOMBRES, APELLIDOS;
  END SP_BUSCAR_CLIENTES;

END PKG_CLIENTE;
/