CREATE OR REPLACE PACKAGE PKG_ENVIO AS

  PROCEDURE SP_INSERTAR_ENVIO(
    P_ORDEN_VENTA_ID              IN  ENVIO.ORDEN_VENTA_ID%TYPE,
    P_ESTADO_ENVIO_ID             IN  ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID             IN  ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_ZONA_ENVIO_ID               IN  ENVIO.ZONA_ENVIO_ID%TYPE,
    P_RUTA_ENTREGA_ID             IN  ENVIO.RUTA_ENTREGA_ID%TYPE,
    P_DIRECCION_ENTREGA_SNAPSHOT  IN  ENVIO.DIRECCION_ENTREGA_SNAPSHOT%TYPE,
    P_COSTO_ENVIO_SNAPSHOT        IN  ENVIO.COSTO_ENVIO_SNAPSHOT%TYPE,
    P_FECHA_ENVIO                 IN  ENVIO.FECHA_ENVIO%TYPE,
    P_FECHA_ENTREGA_ESTIMADA      IN  ENVIO.FECHA_ENTREGA_ESTIMADA%TYPE,
    P_FECHA_ENTREGA_REAL          IN  ENVIO.FECHA_ENTREGA_REAL%TYPE,
    P_TRACKING_CODIGO             IN  ENVIO.TRACKING_CODIGO%TYPE,
    P_ENVIO_ID                    OUT ENVIO.ENVIO_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_ENVIO(
    P_ENVIO_ID                    IN  ENVIO.ENVIO_ID%TYPE,
    P_ORDEN_VENTA_ID              IN  ENVIO.ORDEN_VENTA_ID%TYPE,
    P_ESTADO_ENVIO_ID             IN  ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID             IN  ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_ZONA_ENVIO_ID               IN  ENVIO.ZONA_ENVIO_ID%TYPE,
    P_RUTA_ENTREGA_ID             IN  ENVIO.RUTA_ENTREGA_ID%TYPE,
    P_DIRECCION_ENTREGA_SNAPSHOT  IN  ENVIO.DIRECCION_ENTREGA_SNAPSHOT%TYPE,
    P_COSTO_ENVIO_SNAPSHOT        IN  ENVIO.COSTO_ENVIO_SNAPSHOT%TYPE,
    P_FECHA_ENVIO                 IN  ENVIO.FECHA_ENVIO%TYPE,
    P_FECHA_ENTREGA_ESTIMADA      IN  ENVIO.FECHA_ENTREGA_ESTIMADA%TYPE,
    P_FECHA_ENTREGA_REAL          IN  ENVIO.FECHA_ENTREGA_REAL%TYPE,
    P_TRACKING_CODIGO             IN  ENVIO.TRACKING_CODIGO%TYPE
  );

  PROCEDURE SP_ELIMINAR_ENVIO(
    P_ENVIO_ID IN ENVIO.ENVIO_ID%TYPE
  );

  PROCEDURE SP_OBTENER_ENVIO(
    P_ENVIO_ID IN  ENVIO.ENVIO_ID%TYPE,
    P_CURSOR   OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_ENVIOS(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_ENVIOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_ENVIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_ENVIO AS

  PROCEDURE SP_INSERTAR_ENVIO(
    P_ORDEN_VENTA_ID              IN  ENVIO.ORDEN_VENTA_ID%TYPE,
    P_ESTADO_ENVIO_ID             IN  ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID             IN  ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_ZONA_ENVIO_ID               IN  ENVIO.ZONA_ENVIO_ID%TYPE,
    P_RUTA_ENTREGA_ID             IN  ENVIO.RUTA_ENTREGA_ID%TYPE,
    P_DIRECCION_ENTREGA_SNAPSHOT  IN  ENVIO.DIRECCION_ENTREGA_SNAPSHOT%TYPE,
    P_COSTO_ENVIO_SNAPSHOT        IN  ENVIO.COSTO_ENVIO_SNAPSHOT%TYPE,
    P_FECHA_ENVIO                 IN  ENVIO.FECHA_ENVIO%TYPE,
    P_FECHA_ENTREGA_ESTIMADA      IN  ENVIO.FECHA_ENTREGA_ESTIMADA%TYPE,
    P_FECHA_ENTREGA_REAL          IN  ENVIO.FECHA_ENTREGA_REAL%TYPE,
    P_TRACKING_CODIGO             IN  ENVIO.TRACKING_CODIGO%TYPE,
    P_ENVIO_ID                    OUT ENVIO.ENVIO_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO ENVIO (
      ORDEN_VENTA_ID,
      ESTADO_ENVIO_ID,
      TIPO_ENTREGA_ID,
      ZONA_ENVIO_ID,
      RUTA_ENTREGA_ID,
      DIRECCION_ENTREGA_SNAPSHOT,
      COSTO_ENVIO_SNAPSHOT,
      FECHA_ENVIO,
      FECHA_ENTREGA_ESTIMADA,
      FECHA_ENTREGA_REAL,
      TRACKING_CODIGO,
      CREATED_AT,
      ESTADO
    ) VALUES (
      P_ORDEN_VENTA_ID,
      P_ESTADO_ENVIO_ID,
      P_TIPO_ENTREGA_ID,
      P_ZONA_ENVIO_ID,
      P_RUTA_ENTREGA_ID,
      P_DIRECCION_ENTREGA_SNAPSHOT,
      P_COSTO_ENVIO_SNAPSHOT,
      P_FECHA_ENVIO,
      P_FECHA_ENTREGA_ESTIMADA,
      P_FECHA_ENTREGA_REAL,
      P_TRACKING_CODIGO,
      SYSTIMESTAMP,
      'ACTIVO'
    )
    RETURNING ENVIO_ID INTO P_ENVIO_ID;
  END SP_INSERTAR_ENVIO;

  PROCEDURE SP_ACTUALIZAR_ENVIO(
    P_ENVIO_ID                    IN  ENVIO.ENVIO_ID%TYPE,
    P_ORDEN_VENTA_ID              IN  ENVIO.ORDEN_VENTA_ID%TYPE,
    P_ESTADO_ENVIO_ID             IN  ENVIO.ESTADO_ENVIO_ID%TYPE,
    P_TIPO_ENTREGA_ID             IN  ENVIO.TIPO_ENTREGA_ID%TYPE,
    P_ZONA_ENVIO_ID               IN  ENVIO.ZONA_ENVIO_ID%TYPE,
    P_RUTA_ENTREGA_ID             IN  ENVIO.RUTA_ENTREGA_ID%TYPE,
    P_DIRECCION_ENTREGA_SNAPSHOT  IN  ENVIO.DIRECCION_ENTREGA_SNAPSHOT%TYPE,
    P_COSTO_ENVIO_SNAPSHOT        IN  ENVIO.COSTO_ENVIO_SNAPSHOT%TYPE,
    P_FECHA_ENVIO                 IN  ENVIO.FECHA_ENVIO%TYPE,
    P_FECHA_ENTREGA_ESTIMADA      IN  ENVIO.FECHA_ENTREGA_ESTIMADA%TYPE,
    P_FECHA_ENTREGA_REAL          IN  ENVIO.FECHA_ENTREGA_REAL%TYPE,
    P_TRACKING_CODIGO             IN  ENVIO.TRACKING_CODIGO%TYPE
  ) AS
  BEGIN
    UPDATE ENVIO
    SET ORDEN_VENTA_ID             = P_ORDEN_VENTA_ID,
        ESTADO_ENVIO_ID            = P_ESTADO_ENVIO_ID,
        TIPO_ENTREGA_ID            = P_TIPO_ENTREGA_ID,
        ZONA_ENVIO_ID              = P_ZONA_ENVIO_ID,
        RUTA_ENTREGA_ID            = P_RUTA_ENTREGA_ID,
        DIRECCION_ENTREGA_SNAPSHOT = P_DIRECCION_ENTREGA_SNAPSHOT,
        COSTO_ENVIO_SNAPSHOT       = P_COSTO_ENVIO_SNAPSHOT,
        FECHA_ENVIO                = P_FECHA_ENVIO,
        FECHA_ENTREGA_ESTIMADA     = P_FECHA_ENTREGA_ESTIMADA,
        FECHA_ENTREGA_REAL         = P_FECHA_ENTREGA_REAL,
        TRACKING_CODIGO            = P_TRACKING_CODIGO,
        UPDATED_AT                 = SYSTIMESTAMP
    WHERE ENVIO_ID = P_ENVIO_ID;
  END SP_ACTUALIZAR_ENVIO;

  PROCEDURE SP_ELIMINAR_ENVIO(
    P_ENVIO_ID IN ENVIO.ENVIO_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM SEGUIMIENTO_ENVIO
    WHERE ENVIO_ID = P_ENVIO_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el envio porque tiene registros de seguimiento asociados.');
    END IF;

    UPDATE ENVIO
    SET ESTADO     = 'INACTIVO',
        UPDATED_AT = SYSTIMESTAMP
    WHERE ENVIO_ID = P_ENVIO_ID;
  END SP_ELIMINAR_ENVIO;

  PROCEDURE SP_OBTENER_ENVIO(
    P_ENVIO_ID IN  ENVIO.ENVIO_ID%TYPE,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT ENVIO_ID,
             ORDEN_VENTA_ID,
             ESTADO_ENVIO_ID,
             TIPO_ENTREGA_ID,
             ZONA_ENVIO_ID,
             RUTA_ENTREGA_ID,
             DIRECCION_ENTREGA_SNAPSHOT,
             COSTO_ENVIO_SNAPSHOT,
             FECHA_ENVIO,
             FECHA_ENTREGA_ESTIMADA,
             FECHA_ENTREGA_REAL,
             TRACKING_CODIGO,
             ESTADO
      FROM ENVIO
      WHERE ENVIO_ID = P_ENVIO_ID;
  END SP_OBTENER_ENVIO;

  PROCEDURE SP_LISTAR_ENVIOS(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT E.ENVIO_ID,
             E.ORDEN_VENTA_ID,
             E.TRACKING_CODIGO,
             EE.DESCRIPCION  AS ESTADO_ENVIO,
             TE.NOMBRE       AS TIPO_ENTREGA,
             ZE.NOMBRE       AS ZONA_ENVIO,
             E.FECHA_ENVIO,
             E.FECHA_ENTREGA_ESTIMADA,
             E.ESTADO
      FROM ENVIO E
      JOIN ESTADO_ENVIO   EE ON EE.ESTADO_ENVIO_ID   = E.ESTADO_ENVIO_ID
      JOIN TIPO_ENTREGA   TE ON TE.TIPO_ENTREGA_ID   = E.TIPO_ENTREGA_ID
      JOIN ZONA_ENVIO     ZE ON ZE.ZONA_ENVIO_ID     = E.ZONA_ENVIO_ID
      WHERE E.ESTADO = 'ACTIVO'
      ORDER BY E.FECHA_ENVIO DESC;
  END SP_LISTAR_ENVIOS;

  PROCEDURE SP_BUSCAR_ENVIOS(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT E.ENVIO_ID,
             E.ORDEN_VENTA_ID,
             E.TRACKING_CODIGO,
             EE.DESCRIPCION  AS ESTADO_ENVIO,
             TE.NOMBRE       AS TIPO_ENTREGA,
             ZE.NOMBRE       AS ZONA_ENVIO,
             E.FECHA_ENVIO,
             E.FECHA_ENTREGA_ESTIMADA,
             E.ESTADO
      FROM ENVIO E
      JOIN ESTADO_ENVIO   EE ON EE.ESTADO_ENVIO_ID   = E.ESTADO_ENVIO_ID
      JOIN TIPO_ENTREGA   TE ON TE.TIPO_ENTREGA_ID   = E.TIPO_ENTREGA_ID
      JOIN ZONA_ENVIO     ZE ON ZE.ZONA_ENVIO_ID     = E.ZONA_ENVIO_ID
      WHERE E.ESTADO = 'ACTIVO'
      AND (
        (UPPER(P_CRITERIO) = 'TRACKING'      AND UPPER(E.TRACKING_CODIGO) LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'ESTADO_ENVIO'  AND UPPER(EE.DESCRIPCION)   LIKE '%' || UPPER(P_VALOR) || '%')
        OR
        (UPPER(P_CRITERIO) = 'ZONA'          AND UPPER(ZE.NOMBRE)         LIKE '%' || UPPER(P_VALOR) || '%')
      )
      ORDER BY E.FECHA_ENVIO DESC;
  END SP_BUSCAR_ENVIOS;

END PKG_ENVIO;
/
