CREATE OR REPLACE PACKAGE PKG_INVENTARIO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_INVENTARIO_MATERIA_PRIMA(
    P_MP_ID             IN INVENTARIO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_ACTUAL   IN INVENTARIO_MATERIA_PRIMA.CANTIDAD_ACTUAL%TYPE,
    P_STOCK_MINIMO      IN INVENTARIO_MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_UBICACION         IN INVENTARIO_MATERIA_PRIMA.UBICACION%TYPE,
    P_FECHA_ULT_INGRESO IN INVENTARIO_MATERIA_PRIMA.FECHA_ULT_INGRESO%TYPE,
    P_ESTADO            IN INVENTARIO_MATERIA_PRIMA.ESTADO%TYPE,
    P_INV_MP_ID         OUT INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE
  );

  PROCEDURE SP_ACTUALIZAR_INVENTARIO_MATERIA_PRIMA(
    P_INV_MP_ID         IN INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_MP_ID             IN INVENTARIO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_ACTUAL   IN INVENTARIO_MATERIA_PRIMA.CANTIDAD_ACTUAL%TYPE,
    P_STOCK_MINIMO      IN INVENTARIO_MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_UBICACION         IN INVENTARIO_MATERIA_PRIMA.UBICACION%TYPE,
    P_FECHA_ULT_INGRESO IN INVENTARIO_MATERIA_PRIMA.FECHA_ULT_INGRESO%TYPE,
    P_ESTADO            IN INVENTARIO_MATERIA_PRIMA.ESTADO%TYPE
  );

  PROCEDURE SP_ELIMINAR_INVENTARIO_MATERIA_PRIMA(
    P_INV_MP_ID IN INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE
  );

  PROCEDURE SP_OBTENER_INVENTARIO_MATERIA_PRIMA(
    P_INV_MP_ID IN INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_CURSOR    OUT SYS_REFCURSOR
  );

  PROCEDURE SP_LISTAR_INVENTARIOS_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE SP_BUSCAR_INVENTARIOS_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  );

END PKG_INVENTARIO_MATERIA_PRIMA;
/

CREATE OR REPLACE PACKAGE BODY PKG_INVENTARIO_MATERIA_PRIMA AS

  PROCEDURE SP_INSERTAR_INVENTARIO_MATERIA_PRIMA(
    P_MP_ID             IN INVENTARIO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_ACTUAL   IN INVENTARIO_MATERIA_PRIMA.CANTIDAD_ACTUAL%TYPE,
    P_STOCK_MINIMO      IN INVENTARIO_MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_UBICACION         IN INVENTARIO_MATERIA_PRIMA.UBICACION%TYPE,
    P_FECHA_ULT_INGRESO IN INVENTARIO_MATERIA_PRIMA.FECHA_ULT_INGRESO%TYPE,
    P_ESTADO            IN INVENTARIO_MATERIA_PRIMA.ESTADO%TYPE,
    P_INV_MP_ID         OUT INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE
  ) AS
  BEGIN
    INSERT INTO INVENTARIO_MATERIA_PRIMA (
      MP_ID,
      CANTIDAD_ACTUAL,
      STOCK_MINIMO,
      UBICACION,
      FECHA_ULT_INGRESO,
      ESTADO,
      CREATED_AT
    )
    VALUES (
      P_MP_ID,
      P_CANTIDAD_ACTUAL,
      P_STOCK_MINIMO,
      P_UBICACION,
      P_FECHA_ULT_INGRESO,
      P_ESTADO,
      SYSTIMESTAMP
    )
    RETURNING INV_MP_ID INTO P_INV_MP_ID;
  END SP_INSERTAR_INVENTARIO_MATERIA_PRIMA;


  PROCEDURE SP_ACTUALIZAR_INVENTARIO_MATERIA_PRIMA(
    P_INV_MP_ID         IN INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_MP_ID             IN INVENTARIO_MATERIA_PRIMA.MP_ID%TYPE,
    P_CANTIDAD_ACTUAL   IN INVENTARIO_MATERIA_PRIMA.CANTIDAD_ACTUAL%TYPE,
    P_STOCK_MINIMO      IN INVENTARIO_MATERIA_PRIMA.STOCK_MINIMO%TYPE,
    P_UBICACION         IN INVENTARIO_MATERIA_PRIMA.UBICACION%TYPE,
    P_FECHA_ULT_INGRESO IN INVENTARIO_MATERIA_PRIMA.FECHA_ULT_INGRESO%TYPE,
    P_ESTADO            IN INVENTARIO_MATERIA_PRIMA.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE INVENTARIO_MATERIA_PRIMA
       SET MP_ID             = P_MP_ID,
           CANTIDAD_ACTUAL   = P_CANTIDAD_ACTUAL,
           STOCK_MINIMO      = P_STOCK_MINIMO,
           UBICACION         = P_UBICACION,
           FECHA_ULT_INGRESO = P_FECHA_ULT_INGRESO,
           ESTADO            = P_ESTADO,
           UPDATED_AT        = SYSTIMESTAMP
     WHERE INV_MP_ID = P_INV_MP_ID;
  END SP_ACTUALIZAR_INVENTARIO_MATERIA_PRIMA;


  PROCEDURE SP_ELIMINAR_INVENTARIO_MATERIA_PRIMA(
    P_INV_MP_ID IN INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE
  ) AS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM MOVIMIENTO_MATERIA_PRIMA
     WHERE INV_MP_ID = P_INV_MP_ID;

    IF V_EXISTE > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el inventario porque tiene movimientos registrados.');
    END IF;

    DELETE FROM INVENTARIO_MATERIA_PRIMA
     WHERE INV_MP_ID = P_INV_MP_ID;
  END SP_ELIMINAR_INVENTARIO_MATERIA_PRIMA;


  PROCEDURE SP_OBTENER_INVENTARIO_MATERIA_PRIMA(
    P_INV_MP_ID IN INVENTARIO_MATERIA_PRIMA.INV_MP_ID%TYPE,
    P_CURSOR    OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT INV_MP_ID,
             MP_ID,
             CANTIDAD_ACTUAL,
             STOCK_MINIMO,
             UBICACION,
             FECHA_ULT_INGRESO,
             ESTADO
        FROM INVENTARIO_MATERIA_PRIMA
       WHERE INV_MP_ID = P_INV_MP_ID;
  END SP_OBTENER_INVENTARIO_MATERIA_PRIMA;


  PROCEDURE SP_LISTAR_INVENTARIOS_MATERIA_PRIMA(
    P_CURSOR OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT INV_MP_ID,
             MP_ID,
             CANTIDAD_ACTUAL,
             STOCK_MINIMO,
             UBICACION,
             FECHA_ULT_INGRESO,
             ESTADO
        FROM INVENTARIO_MATERIA_PRIMA
       ORDER BY INV_MP_ID;
  END SP_LISTAR_INVENTARIOS_MATERIA_PRIMA;


  PROCEDURE SP_BUSCAR_INVENTARIOS_MATERIA_PRIMA(
    P_CRITERIO IN VARCHAR2,
    P_VALOR    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT INV_MP_ID,
             MP_ID,
             CANTIDAD_ACTUAL,
             STOCK_MINIMO,
             UBICACION,
             FECHA_ULT_INGRESO,
             ESTADO
        FROM INVENTARIO_MATERIA_PRIMA
       WHERE (
             (UPPER(P_CRITERIO) = 'UBICACION' AND UPPER(UBICACION) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'ESTADO' AND UPPER(ESTADO) LIKE '%' || UPPER(P_VALOR) || '%')
          OR (UPPER(P_CRITERIO) = 'MP_ID' AND TO_CHAR(MP_ID) LIKE '%' || P_VALOR || '%')
       )
       ORDER BY INV_MP_ID;
  END SP_BUSCAR_INVENTARIOS_MATERIA_PRIMA;

END PKG_INVENTARIO_MATERIA_PRIMA;
/